In [1]:
library(ggplot2)
library(dplyr)
# Load the required libraries
library(ggpubr)
# load dplyr and tidyr library

library(tidyr)
library(parallel)
library(future)
library(furrr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/genric_regions")

In [3]:
data <- read.csv(gzfile("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/IntronExonfeatureCount/pacBio/list2/all_feture_count_list2.tsv.gz"), header=FALSE,sep='\t')
data

          V1
1         exon:None_transcript:ENSMUST00200004126_144021_144931
2         exon:None_transcript:ENSMUST00200004126_147103_147234
3         exon:None_transcript:ENSMUST00200004126_147843_147930
4         exon:None_transcript:ENSMUST00200004126_148183_148402
5         exon:None_transcript:ENSMUST00200004126_150196_150622
6         exon:None_transcript:ENSMUST00200004126_150624_151067
7         exon:None_transcript:ENSMUST00200006521_144031_144556
8         exon:None_transcript:ENSMUST00200006521_150350_150623
9         exon:None_transcript:ENSMUST00200004330_191124_191277
10        exon:None_transcript:ENSMUST00200004330_207684_207776
11        exon:None_transcript:ENSMUST00200004330_208568_208665
12        exon:None_transcript:ENSMUST00200004330_212118_212173
13        exon:None_transcript:ENSMUST00200004330_214720_214786
14        exon:None_transcript:ENSMUST00200004330_214874_215121
15        exon:None_transcript:ENSMUST00200004337_206798_207776
16        exon:None_transcript:ENSMUST00200004337_208568_208665
17        exon:None_transcript:ENSMUST00200004337_212118_212173
18        exon:None_transcript:ENSMUST00200004337_214720_214786
19        exon:None_transcript:ENSMUST00200004337_214874_215126
20        exon:None_transcript:ENSMUST00200004347_211204_211251
21        exon:None_transcript:ENSMUST00200004347_212118_212173
22        exon:None_transcript:ENSMUST00200004347_212867_214786
23        exon:None_transcript:ENSMUST00200004347_214874_215119
24        exon:None_transcript:ENSMUST00200006083_542547_543406
25        exon:None_transcript:ENSMUST00200006083_543408_543616
26        exon:None_transcript:ENSMUST00200003782_665229_672813
27        exon:None_transcript:ENSMUST00200003782_678931_682465
28        exon:None_transcript:ENSMUST00200003782_884601_884800
29        exon:None_transcript:ENSMUST00200003782_1130584_1131803
30        exon:None_transcript:ENSMUST00200003787_679979_682465
⋮         ⋮
278715679 intron:None_transcript__WSB_EiJ#1#chr9_99993918_99993929
278715680 intron:None_transcript__WSB_EiJ#1#chr9_99993946_99994009
278715681 intron:None_transcript__WSB_EiJ#1#chr9_99994143_99994791
278715682 intron:None_transcript__WSB_EiJ#1#chr9_99994256_99994353
278715683 intron:None_transcript__WSB_EiJ#1#chr3_99994256_99994353
278715684 intron:None_transcript__WSB_EiJ#1#chr3_99994286_99994431
278715685 intron:None_transcript__WSB_EiJ#1#chr9_99994399_99994509
278715686 intron:None_transcript__WSB_EiJ#1#chr9_99994423_99994508
278715687 intron:None_transcript__WSB_EiJ#1#chr11_99994501_99994603
278715688 intron:None_transcript__WSB_EiJ#1#chr3_99994501_99994603
278715689 intron:None_transcript__WSB_EiJ#1#chr3_99994694_99994834
278715690 intron:None_transcript__WSB_EiJ#1#chr3_99996346_99996469
278715691 intron:None_transcript__WSB_EiJ#1#chr9_99996346_99996469
278715692 intron:None_transcript__WSB_EiJ#1#chr9_99996715_99996916
278715693 intron:None_transcript__WSB_EiJ#1#chr11_99996715_99996916
278715694 intron:None_transcript__WSB_EiJ#1#chr11_99996919_99996990
278715695 intron:None_transcript__WSB_EiJ#1#chr11_99997089_99997237
278715696 intron:None_transcript__WSB_EiJ#1#chr9_99997089_99997237
278715697 intron:None_transcript__WSB_EiJ#1#chr9_99997156_99997318
278715698 intron:None_transcript__WSB_EiJ#1#chr3_99997221_99997425
278715699 intron:None_transcript__WSB_EiJ#1#chr11_99997221_99997425
278715700 intron:None_transcript__WSB_EiJ#1#chr11_99997378_99997516
278715701 intron:None_transcript__WSB_EiJ#1#chr3_99997378_99997516
278715702 intron:None_transcript__WSB_EiJ#1#chr3_99997500_99998312
278715703 intron:None_transcript__WSB_EiJ#1#chr15_99999697_100000060
278715704 intron:None_transcript__WSB_EiJ#1#chr3_99999697_100000060
278715705 intron:None_transcript__WSB_EiJ#1#chr3_99999752_99999902
278715706 intron:None_transcript__WSB_EiJ#1#chr9_99999752_99999902
278715707 intron:None_transcript__WSB_EiJ#1#chr9_99999871_100000060
278715708 intron:None_transcript__WSB_EiJ#1#chr3_99999891_100004373
          V2
1         129S1_SvImJ#1#chr1
2         129S1_SvImJ#1#chr1
3         129S1_SvImJ#1#chr1
4         129S1_SvImJ#1#chr1
5         129S1_SvImJ#1#chr1
6         129S1_SvImJ#1#chr1
7         129S1_SvImJ#1#chr1
8         129S1_SvImJ#1#chr1
9         129S1_SvImJ#1#chr1
10        129S1_SvImJ#1#chr1
11        129S1_SvImJ#1#chr1
12        129S1_SvImJ#1#chr1
13        129S1_SvImJ#1#chr1
14        129S1_SvImJ#1#chr1
15        129S1_SvImJ#1#chr1
16        129S1_SvImJ#1#chr1
17        129S1_SvImJ#1#chr1
18        129S1_SvImJ#1#chr1
19        129S1_SvImJ#1#chr1
20        129S1_SvImJ#1#chr1
21        129S1_SvImJ#1#chr1
22        129S1_SvImJ#1#chr1
23        129S1_SvImJ#1#chr1
24        129S1_SvImJ#1#chr1
25        129S1_SvImJ#1#chr1
26        129S1_SvImJ#1#chr1
27        129S1_SvImJ#1#chr1
28        129S1_SvImJ#1#chr1
29        129S1_SvImJ#1#chr1
30        129S1_SvImJ#1#chr1
⋮         ⋮
278715679 WSB_EiJ#1#chr9
278715680 WSB_EiJ#1#chr9
278715681 WSB_EiJ#1#chr9
278715682 WSB_EiJ#1#chr9
278715683 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715684 WSB_EiJ#1#chr3
278715685 WSB_EiJ#1#chr9
278715686 WSB_EiJ#1#chr9
278715687 WSB_EiJ#1#chr11
278715688 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715689 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715690 WSB_EiJ#1#chr3
278715691 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715692 WSB_EiJ#1#chr9
278715693 WSB_EiJ#1#chr11
278715694 WSB_EiJ#1#chr11
278715695 WSB_EiJ#1#chr11
278715696 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715697 WSB_EiJ#1#chr9
278715698 WSB_EiJ#1#chr3
278715699 WSB_EiJ#1#chr11
278715700 WSB_EiJ#1#chr11
278715701 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715702 WSB_EiJ#1#chr3
278715703 WSB_EiJ#1#chr15
278715704 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715705 WSB_EiJ#1#chr3
278715706 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715707 WSB_EiJ#1#chr9
278715708 WSB_EiJ#1#chr3
          V3
1         144021
2         147103
3         147843
4         148183
5         150196
6         150624
7         144031
8         150350
9         191124
10        207684
11        208568
12        212118
13        214720
14        214874
15        206798
16        208568
17        212118
18        214720
19        214874
20        211204
21        212118
22        212867
23        214874
24        542547
25        543408
26        665229
27        678931
28        884601
29        1130584
30        679979
⋮         ⋮
278715679 99993918
278715680 99993946
278715681 99994143
278715682 99994256
278715683 99994256;99994256;99994256;99994256
278715684 99994286
278715685 99994399
278715686 99994423
278715687 99994501
278715688 99994501;99994501;99994501;99994501
278715689 99994694;99994694;99994694;99994694;99994694
278715690 99996346
278715691 99996346;99996346
278715692 99996715
278715693 99996715
278715694 99996919
278715695 99997089
278715696 99997089;99997089
278715697 99997156
278715698 99997221
278715699 99997221
278715700 99997378
278715701 99997378;99997378;99997378;99997378
278715702 99997500
278715703 99999697
278715704 99999697;99999697;99999697
278715705 99999752
278715706 99999752;99999752
278715707 99999871
278715708 99999891
          V4                                           V5        V6   V7
1         144931                                       +          911  6.37
2         147234                                       +          132  0.00
3         147930                                       +           88  0.00
4         148402                                       +          220  0.50
5         150622                                       +          427  2.33
6         151067                                       +          444  1.75
7         144556                                       -          526  4.62
8         150623                                       -          274  0.83
9         191277                                       -          154  9.08
10        207776                                       -           93  8.12
11        208665                                       -           98  0.90
12        212173                                       -           56  0.93
13        214786                                       -           67  2.14
14        215121                                       -          248  1.47
15        207776                                       -          979  8.38
16        208665                                       -           98  0.90
17        212173                                       -           56  0.93
18        214786                                       -           67  2.14
19        215126                                       -          253  1.47
20        211251                                       -           48  0.25
21        212173                                       -           56  0.93
22        214786                                       -         1920 27.03
23        215119                                       -          246  1.47
24        543406                                       +          860  0.00
25        543616                                       +          209  0.00
26        672813                                       -         7585  2.50
27        682465                                       -         3535  0.75
28        884800                                       -          200  0.20
29        1131803                                      -         1220  0.00
30        682465                                       -         2487  0.25
⋮         ⋮                                            ⋮         ⋮    ⋮
278715679 99993929                                     -           12 0.00
278715680 99994009                                     -           64 0.00
278715681 99994791                                     -          649 0.00
278715682 99994353                                     +           98 0.00
278715683 99994353;99994353;99994353;99994353          -;-;-;-     98 0.00
278715684 99994431                                     -          146 0.00
278715685 99994509                                     +          111 0.00
278715686 99994508                                     +           86 0.00
278715687 99994603                                     -          103 6.33
278715688 99994603;99994603;99994603;99994603          -;-;-;-    103 0.08
278715689 99994834;99994834;99994834;99994834;99994834 -;-;-;-;-  141 0.00
278715690 99996469                                     -          124 0.00
278715691 99996469;99996469                            +;+        124 0.14
278715692 99996916                                     +          202 0.00
278715693 99996916                                     -          202 6.80
278715694 99996990                                     -           72 0.00
278715695 99997237                                     -          149 0.00
278715696 99997237;99997237                            +;+        149 0.00
278715697 99997318                                     +          163 0.00
278715698 99997425                                     -          205 0.00
278715699 99997425                                     -          205 0.80
278715700 99997516                                     -          139 0.00
278715701 99997516;99997516;99997516;99997516          -;-;-;-    139 0.00
278715702 99998312                                     -          813 0.00
278715703 100000060                                    +          364 0.00
278715704 100000060;100000060;100000060                -;-;-      364 0.00
278715705 99999902                                     -          151 0.00
278715706 99999902;99999902                            +;+        151 0.00
278715707 100000060                                    +          190 0.00
278715708 100004373                                    -         4483 0.10
          V8
1         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
2         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
3         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
4         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
5         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
6         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
7         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
8         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
10        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
11        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
12        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
13        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
14        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
15        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
16        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
17        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
18        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
19        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
20        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
21        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
22        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
23        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
24        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
25        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
26        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
27        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
28        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
29        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
30        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
⋮         ⋮
278715679 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715680 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715681 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715682 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715683 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715684 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715685 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715686 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715687 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715688 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715689 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715690 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715691 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715692 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715693 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715694 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715695 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715696 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715697 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715698 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715699 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715700 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715701 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715702 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715703 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715704 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715705 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715706 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715707 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715708 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts

In [4]:
 # Split name column into 
data <- data %>% separate(V1, c('V9', 'V10','V11','V12'), sep =":")
data

Warning message:
“Expected 4 pieces. Missing pieces filled with `NA` in 196948602 rows [1, 2, 3,
4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].”

          V9     V10
1         exon   None_transcript
2         exon   None_transcript
3         exon   None_transcript
4         exon   None_transcript
5         exon   None_transcript
6         exon   None_transcript
7         exon   None_transcript
8         exon   None_transcript
9         exon   None_transcript
10        exon   None_transcript
11        exon   None_transcript
12        exon   None_transcript
13        exon   None_transcript
14        exon   None_transcript
15        exon   None_transcript
16        exon   None_transcript
17        exon   None_transcript
18        exon   None_transcript
19        exon   None_transcript
20        exon   None_transcript
21        exon   None_transcript
22        exon   None_transcript
23        exon   None_transcript
24        exon   None_transcript
25        exon   None_transcript
26        exon   None_transcript
27        exon   None_transcript
28        exon   None_transcript
29        exon   None_transcript
30        exon   None_transcript
⋮         ⋮      ⋮
278715679 intron None_transcript__WSB_EiJ#1#chr9_99993918_99993929
278715680 intron None_transcript__WSB_EiJ#1#chr9_99993946_99994009
278715681 intron None_transcript__WSB_EiJ#1#chr9_99994143_99994791
278715682 intron None_transcript__WSB_EiJ#1#chr9_99994256_99994353
278715683 intron None_transcript__WSB_EiJ#1#chr3_99994256_99994353
278715684 intron None_transcript__WSB_EiJ#1#chr3_99994286_99994431
278715685 intron None_transcript__WSB_EiJ#1#chr9_99994399_99994509
278715686 intron None_transcript__WSB_EiJ#1#chr9_99994423_99994508
278715687 intron None_transcript__WSB_EiJ#1#chr11_99994501_99994603
278715688 intron None_transcript__WSB_EiJ#1#chr3_99994501_99994603
278715689 intron None_transcript__WSB_EiJ#1#chr3_99994694_99994834
278715690 intron None_transcript__WSB_EiJ#1#chr3_99996346_99996469
278715691 intron None_transcript__WSB_EiJ#1#chr9_99996346_99996469
278715692 intron None_transcript__WSB_EiJ#1#chr9_99996715_99996916
278715693 intron None_transcript__WSB_EiJ#1#chr11_99996715_99996916
278715694 intron None_transcript__WSB_EiJ#1#chr11_99996919_99996990
278715695 intron None_transcript__WSB_EiJ#1#chr11_99997089_99997237
278715696 intron None_transcript__WSB_EiJ#1#chr9_99997089_99997237
278715697 intron None_transcript__WSB_EiJ#1#chr9_99997156_99997318
278715698 intron None_transcript__WSB_EiJ#1#chr3_99997221_99997425
278715699 intron None_transcript__WSB_EiJ#1#chr11_99997221_99997425
278715700 intron None_transcript__WSB_EiJ#1#chr11_99997378_99997516
278715701 intron None_transcript__WSB_EiJ#1#chr3_99997378_99997516
278715702 intron None_transcript__WSB_EiJ#1#chr3_99997500_99998312
278715703 intron None_transcript__WSB_EiJ#1#chr15_99999697_100000060
278715704 intron None_transcript__WSB_EiJ#1#chr3_99999697_100000060
278715705 intron None_transcript__WSB_EiJ#1#chr3_99999752_99999902
278715706 intron None_transcript__WSB_EiJ#1#chr9_99999752_99999902
278715707 intron None_transcript__WSB_EiJ#1#chr9_99999871_100000060
278715708 intron None_transcript__WSB_EiJ#1#chr3_99999891_100004373
          V11                                V12
1         ENSMUST00200004126_144021_144931   NA
2         ENSMUST00200004126_147103_147234   NA
3         ENSMUST00200004126_147843_147930   NA
4         ENSMUST00200004126_148183_148402   NA
5         ENSMUST00200004126_150196_150622   NA
6         ENSMUST00200004126_150624_151067   NA
7         ENSMUST00200006521_144031_144556   NA
8         ENSMUST00200006521_150350_150623   NA
9         ENSMUST00200004330_191124_191277   NA
10        ENSMUST00200004330_207684_207776   NA
11        ENSMUST00200004330_208568_208665   NA
12        ENSMUST00200004330_212118_212173   NA
13        ENSMUST00200004330_214720_214786   NA
14        ENSMUST00200004330_214874_215121   NA
15        ENSMUST00200004337_206798_207776   NA
16        ENSMUST00200004337_208568_208665   NA
17        ENSMUST00200004337_212118_212173   NA
18        ENSMUST00200004337_214720_214786   NA
19        ENSMUST00200004337_214874_215126   NA
20        ENSMUST00200004347_211204_211251   NA
21        ENSMUST00200004347_212118_212173   NA
22        ENSMUST00200004347_212867_214786   NA
23        ENSMUST00200004347_214874_215119   NA
24        ENSMUST00200006083_542547_543406   NA
25        ENSMUST00200006083_543408_543616   NA
26        ENSMUST00200003782_665229_672813   NA
27        ENSMUST00200003782_678931_682465   NA
28        ENSMUST00200003782_884601_884800   NA
29        ENSMUST00200003782_1130584_1131803 NA
30        ENSMUST00200003787_679979_682465   NA
⋮         ⋮                                  ⋮
278715679 NA                                 NA
278715680 NA                                 NA
278715681 NA                                 NA
278715682 NA                                 NA
278715683 NA                                 NA
278715684 NA                                 NA
278715685 NA                                 NA
278715686 NA                                 NA
278715687 NA                                 NA
278715688 NA                                 NA
278715689 NA                                 NA
278715690 NA                                 NA
278715691 NA                                 NA
278715692 NA                                 NA
278715693 NA                                 NA
278715694 NA                                 NA
278715695 NA                                 NA
278715696 NA                                 NA
278715697 NA                                 NA
278715698 NA                                 NA
278715699 NA                                 NA
278715700 NA                                 NA
278715701 NA                                 NA
278715702 NA                                 NA
278715703 NA                                 NA
278715704 NA                                 NA
278715705 NA                                 NA
278715706 NA                                 NA
278715707 NA                                 NA
278715708 NA                                 NA
          V2
1         129S1_SvImJ#1#chr1
2         129S1_SvImJ#1#chr1
3         129S1_SvImJ#1#chr1
4         129S1_SvImJ#1#chr1
5         129S1_SvImJ#1#chr1
6         129S1_SvImJ#1#chr1
7         129S1_SvImJ#1#chr1
8         129S1_SvImJ#1#chr1
9         129S1_SvImJ#1#chr1
10        129S1_SvImJ#1#chr1
11        129S1_SvImJ#1#chr1
12        129S1_SvImJ#1#chr1
13        129S1_SvImJ#1#chr1
14        129S1_SvImJ#1#chr1
15        129S1_SvImJ#1#chr1
16        129S1_SvImJ#1#chr1
17        129S1_SvImJ#1#chr1
18        129S1_SvImJ#1#chr1
19        129S1_SvImJ#1#chr1
20        129S1_SvImJ#1#chr1
21        129S1_SvImJ#1#chr1
22        129S1_SvImJ#1#chr1
23        129S1_SvImJ#1#chr1
24        129S1_SvImJ#1#chr1
25        129S1_SvImJ#1#chr1
26        129S1_SvImJ#1#chr1
27        129S1_SvImJ#1#chr1
28        129S1_SvImJ#1#chr1
29        129S1_SvImJ#1#chr1
30        129S1_SvImJ#1#chr1
⋮         ⋮
278715679 WSB_EiJ#1#chr9
278715680 WSB_EiJ#1#chr9
278715681 WSB_EiJ#1#chr9
278715682 WSB_EiJ#1#chr9
278715683 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715684 WSB_EiJ#1#chr3
278715685 WSB_EiJ#1#chr9
278715686 WSB_EiJ#1#chr9
278715687 WSB_EiJ#1#chr11
278715688 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715689 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715690 WSB_EiJ#1#chr3
278715691 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715692 WSB_EiJ#1#chr9
278715693 WSB_EiJ#1#chr11
278715694 WSB_EiJ#1#chr11
278715695 WSB_EiJ#1#chr11
278715696 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715697 WSB_EiJ#1#chr9
278715698 WSB_EiJ#1#chr3
278715699 WSB_EiJ#1#chr11
278715700 WSB_EiJ#1#chr11
278715701 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715702 WSB_EiJ#1#chr3
278715703 WSB_EiJ#1#chr15
278715704 WSB_EiJ#1#chr3;WSB_EiJ#1#chr3;WSB_EiJ#1#chr3
278715705 WSB_EiJ#1#chr3
278715706 WSB_EiJ#1#chr9;WSB_EiJ#1#chr9
278715707 WSB_EiJ#1#chr9
278715708 WSB_EiJ#1#chr3
          V3
1         144021
2         147103
3         147843
4         148183
5         150196
6         150624
7         144031
8         150350
9         191124
10        207684
11        208568
12        212118
13        214720
14        214874
15        206798
16        208568
17        212118
18        214720
19        214874
20        211204
21        212118
22        212867
23        214874
24        542547
25        543408
26        665229
27        678931
28        884601
29        1130584
30        679979
⋮         ⋮
278715679 99993918
278715680 99993946
278715681 99994143
278715682 99994256
278715683 99994256;99994256;99994256;99994256
278715684 99994286
278715685 99994399
278715686 99994423
278715687 99994501
278715688 99994501;99994501;99994501;99994501
278715689 99994694;99994694;99994694;99994694;99994694
278715690 99996346
278715691 99996346;99996346
278715692 99996715
278715693 99996715
278715694 99996919
278715695 99997089
278715696 99997089;99997089
278715697 99997156
278715698 99997221
278715699 99997221
278715700 99997378
278715701 99997378;99997378;99997378;99997378
278715702 99997500
278715703 99999697
278715704 99999697;99999697;99999697
278715705 99999752
278715706 99999752;99999752
278715707 99999871
278715708 99999891
          V4                                           V5        V6   V7
1         144931                                       +          911  6.37
2         147234                                       +          132  0.00
3         147930                                       +           88  0.00
4         148402                                       +          220  0.50
5         150622                                       +          427  2.33
6         151067                                       +          444  1.75
7         144556                                       -          526  4.62
8         150623                                       -          274  0.83
9         191277                                       -          154  9.08
10        207776                                       -           93  8.12
11        208665                                       -           98  0.90
12        212173                                       -           56  0.93
13        214786                                       -           67  2.14
14        215121                                       -          248  1.47
15        207776                                       -          979  8.38
16        208665                                       -           98  0.90
17        212173                                       -           56  0.93
18        214786                                       -           67  2.14
19        215126                                       -          253  1.47
20        211251                                       -           48  0.25
21        212173                                       -           56  0.93
22        214786                                       -         1920 27.03
23        215119                                       -          246  1.47
24        543406                                       +          860  0.00
25        543616                                       +          209  0.00
26        672813                                       -         7585  2.50
27        682465                                       -         3535  0.75
28        884800                                       -          200  0.20
29        1131803                                      -         1220  0.00
30        682465                                       -         2487  0.25
⋮         ⋮                                            ⋮         ⋮    ⋮
278715679 99993929                                     -           12 0.00
278715680 99994009                                     -           64 0.00
278715681 99994791                                     -          649 0.00
278715682 99994353                                     +           98 0.00
278715683 99994353;99994353;99994353;99994353          -;-;-;-     98 0.00
278715684 99994431                                     -          146 0.00
278715685 99994509                                     +          111 0.00
278715686 99994508                                     +           86 0.00
278715687 99994603                                     -          103 6.33
278715688 99994603;99994603;99994603;99994603          -;-;-;-    103 0.08
278715689 99994834;99994834;99994834;99994834;99994834 -;-;-;-;-  141 0.00
278715690 99996469                                     -          124 0.00
278715691 99996469;99996469                            +;+        124 0.14
278715692 99996916                                     +          202 0.00
278715693 99996916                                     -          202 6.80
278715694 99996990                                     -           72 0.00
278715695 99997237                                     -          149 0.00
278715696 99997237;99997237                            +;+        149 0.00
278715697 99997318                                     +          163 0.00
278715698 99997425                                     -          205 0.00
278715699 99997425                                     -          205 0.80
278715700 99997516                                     -          139 0.00
278715701 99997516;99997516;99997516;99997516          -;-;-;-    139 0.00
278715702 99998312                                     -          813 0.00
278715703 100000060                                    +          364 0.00
278715704 100000060;100000060;100000060                -;-;-      364 0.00
278715705 99999902                                     -          151 0.00
278715706 99999902;99999902                            +;+        151 0.00
278715707 100000060                                    +          190 0.00
278715708 100004373                                    -         4483 0.10
          V8
1         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
2         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
3         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
4         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
5         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
6         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
7         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
8         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9         129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
10        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
11        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
12        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
13        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
14        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
15        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
16        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
17        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
18        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
19        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
20        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
21        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
22        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
23        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
24        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
25        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
26        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
27        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
28        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
29        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
30        129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
⋮         ⋮
278715679 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715680 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715681 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715682 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715683 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715684 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715685 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715686 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715687 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715688 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715689 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715690 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715691 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715692 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715693 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715694 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715695 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715696 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715697 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715698 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715699 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715700 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715701 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715702 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715703 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715704 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715705 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715706 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715707 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts
278715708 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts

In [5]:
# Group by V8, V9, V10 and sum the V7 values
new_data <- data %>%
  group_by(V8, V9) %>%
  summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
  ungroup()
new_data

write.csv(new_data, "list2_count.csv", row.names=FALSE)

`summarise()` has grouped output by 'V8'. You can override using the `.groups`
argument.

    V8                                              V9              summed_V7
1   129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts CDS              1116561.5
2   129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts exon             7183952.8
3   129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts five_prime_UTR    229013.5
4   129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts intron           2753341.3
5   129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts three_prime_UTR  5085918.5
6   129S1_SvImJ/129S1_SvImJ-12.5dpp.2.featureCounts CDS              1704816.8
7   129S1_SvImJ/129S1_SvImJ-12.5dpp.2.featureCounts exon            11054526.7
8   129S1_SvImJ/129S1_SvImJ-12.5dpp.2.featureCounts five_prime_UTR    357834.0
9   129S1_SvImJ/129S1_SvImJ-12.5dpp.2.featureCounts intron           4260580.4
10  129S1_SvImJ/129S1_SvImJ-12.5dpp.2.featureCounts three_prime_UTR  7431344.4
11  129S1_SvImJ/129S1_SvImJ-12.5dpp.3.featureCounts CDS              1128943.3
12  129S1_SvImJ/129S1_SvImJ-12.5dpp.3.featureCounts exon             6858838.3
13  129S1_SvImJ/129S1_SvImJ-12.5dpp.3.featureCounts five_prime_UTR    246391.1
14  129S1_SvImJ/129S1_SvImJ-12.5dpp.3.featureCounts intron           2650955.1
15  129S1_SvImJ/129S1_SvImJ-12.5dpp.3.featureCounts three_prime_UTR  4664215.4
16  129S1_SvImJ/129S1_SvImJ-16.5dpc.1.featureCounts CDS               787245.7
17  129S1_SvImJ/129S1_SvImJ-16.5dpc.1.featureCounts exon             4062259.6
18  129S1_SvImJ/129S1_SvImJ-16.5dpc.1.featureCounts five_prime_UTR    271468.0
19  129S1_SvImJ/129S1_SvImJ-16.5dpc.1.featureCounts intron           1899150.9
20  129S1_SvImJ/129S1_SvImJ-16.5dpc.1.featureCounts three_prime_UTR  1583472.5
21  129S1_SvImJ/129S1_SvImJ-16.5dpc.2.featureCounts CDS               738007.5
22  129S1_SvImJ/129S1_SvImJ-16.5dpc.2.featureCounts exon             4181195.1
23  129S1_SvImJ/129S1_SvImJ-16.5dpc.2.featureCounts five_prime_UTR    292189.2
24  129S1_SvImJ/129S1_SvImJ-16.5dpc.2.featureCounts intron           1998334.3
25  129S1_SvImJ/129S1_SvImJ-16.5dpc.2.featureCounts three_prime_UTR  1525308.2
26  129S1_SvImJ/129S1_SvImJ-16.5dpc.3.featureCounts CDS               835123.4
27  129S1_SvImJ/129S1_SvImJ-16.5dpc.3.featureCounts exon             4514353.4
28  129S1_SvImJ/129S1_SvImJ-16.5dpc.3.featureCounts five_prime_UTR    291429.4
29  129S1_SvImJ/129S1_SvImJ-16.5dpc.3.featureCounts intron           2088013.5
30  129S1_SvImJ/129S1_SvImJ-16.5dpc.3.featureCounts three_prime_UTR  1698168.9
⋮   ⋮                                               ⋮               ⋮
691 WSB_EiJ/WSB_EiJ-16.5dpc.1.featureCounts         CDS              1034283.7
692 WSB_EiJ/WSB_EiJ-16.5dpc.1.featureCounts         exon             6963375.8
693 WSB_EiJ/WSB_EiJ-16.5dpc.1.featureCounts         five_prime_UTR    403762.8
694 WSB_EiJ/WSB_EiJ-16.5dpc.1.featureCounts         intron           3963796.6
695 WSB_EiJ/WSB_EiJ-16.5dpc.1.featureCounts         three_prime_UTR  1587809.1
696 WSB_EiJ/WSB_EiJ-16.5dpc.2.featureCounts         CDS               919369.3
697 WSB_EiJ/WSB_EiJ-16.5dpc.2.featureCounts         exon             7771208.4
698 WSB_EiJ/WSB_EiJ-16.5dpc.2.featureCounts         five_prime_UTR    453514.6
699 WSB_EiJ/WSB_EiJ-16.5dpc.2.featureCounts         intron           5207813.0
700 WSB_EiJ/WSB_EiJ-16.5dpc.2.featureCounts         three_prime_UTR  1421732.0
701 WSB_EiJ/WSB_EiJ-16.5dpc.3.featureCounts         CDS               916391.8
702 WSB_EiJ/WSB_EiJ-16.5dpc.3.featureCounts         exon             7823676.2
703 WSB_EiJ/WSB_EiJ-16.5dpc.3.featureCounts         five_prime_UTR    440521.0
704 WSB_EiJ/WSB_EiJ-16.5dpc.3.featureCounts         intron           4841917.0
705 WSB_EiJ/WSB_EiJ-16.5dpc.3.featureCounts         three_prime_UTR  1412776.3
706 WSB_EiJ/WSB_EiJ-20.5dpp.1.featureCounts         CDS               961693.0
707 WSB_EiJ/WSB_EiJ-20.5dpp.1.featureCounts         exon            15095475.6
708 WSB_EiJ/WSB_EiJ-20.5dpp.1.featureCounts         five_prime_UTR    240678.8
709 WSB_EiJ/WSB_EiJ-20.5dpp.1.featureCounts         intron           7713414.4
710 WSB_EiJ/WSB_EiJ-20.5dpp.1.featureCounts         three_prime_UTR  3009732.1
711 WSB_EiJ/WSB_EiJ-20.5dpp.2.featureCounts         CDS               863062.6
712 WSB_EiJ/WSB_EiJ-20.5dpp.2.featureCounts         exon            10606611.3
713 WSB_EiJ/WSB_EiJ-20.5dpp.2.featureCounts         five_prime_UTR    211552.7
714 WSB_EiJ/WSB_EiJ-20.5dpp.2.featureCounts         intron           5617975.8
715 WSB_EiJ/WSB_EiJ-20.5dpp.2.featureCounts         three_prime_UTR  2623044.9
716 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts         CDS               655434.4
717 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts         exon             8787322.8
718 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts         five_prime_UTR    160655.6
719 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts         intron           4702418.9
720 WSB_EiJ/WSB_EiJ-20.5dpp.3.featureCounts         three_prime_UTR  1998973.6