In [25]:
library(ggplot2)
library(dplyr)
# Load the required libraries
library(ggpubr)
# load dplyr and tidyr library

library(tidyr)
library(parallel)
library(future)
library(furrr)

In [26]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/genric_regions")

In [27]:
data <- read.csv(gzfile("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/STAR_uniqe_marker_strain_wise/fetureCountlist3/all_list3_uniq_piRNa.tab.gz"), header=FALSE,sep='\t')
data

        V1
1       exon:None_6972170_6972318
2       exon:None_7292335_7294445
3       exon:None_7292335_7294372
4       exon:None_7292335_7294447
5       exon:None_7292335_7293220
6       exon:None_7292335_7293610
7       exon:None_7292335_7293455
8       exon:None_13924083_13924230
9       exon:None_18403597_18408662
10      exon:None_18403597_18408063
11      exon:None_31372289_31383742
12      exon:None_32020575_32025596
13      exon:None_32389530_32393707
14      exon:None_32389537_32393707
15      exon:None_33891041_33892997
16      exon:None_37883099_37889635
17      exon:None_39738243_39738391
18      exon:None_40699361_40702005
19      exon:None_40699381_40702005
20      exon:None_42426301_42427851
21      exon:None_49676638_49679506
22      exon:None_55557651_55560981
23      exon:None_55557384_55560008
24      exon:None_60086362_60087813
25      exon:None_60091799_60091947
26      exon:None_60594452_60605795
27      exon:None_90508811_90517421
28      exon:None_90560494_90560632
29      exon:None_90963020_90966837
30      exon:None_90963020_90966843
⋮       ⋮
1386935 intron:ENSIUOT00005048946__WSB_EiJ#1#chr9_79642568_79643696
1386936 intron:ENSIUOT00005050035__WSB_EiJ#1#chr9_80066316_80070434
1386937 intron:ENSIUOT00005007032__WSB_EiJ#1#chr9_85099451_85100880
1386938 intron:ENSIUOT00005050530__WSB_EiJ#1#chr9_92565407_92568578
1386939 intron:ENSIUOT00005046445__WSB_EiJ#1#chr9_98132693_98132808
1386940 intron:ENSIUOT00005045865__WSB_EiJ#1#chr9_98529836_98530022
1386941 intron:ENSIUOT00005045865__WSB_EiJ#1#chr9_98534410_98538765
1386942 intron:ENSIUOT00005095527__WSB_EiJ#1#chr9_102736672_102742271
1386943 intron:ENSIUOT00005093563__WSB_EiJ#1#chr9_110513201_110520143
1386944 intron:ENSIUOT00005091698__WSB_EiJ#1#chr9_110754886_110758264
1386945 intron:ENSIUOT00005091688__WSB_EiJ#1#chr9_110754886_110757786
1386946 intron:ENSIUOT00005040162__WSB_EiJ#1#chr9_115445802_115447533
1386947 intron:ENSIUOT00005040238__WSB_EiJ#1#chr9_115462314_115462388
1386948 intron:ENSIUOT00005040190__WSB_EiJ#1#chr9_115462314_115462388
1386949 intron:ENSIUOT00005040206__WSB_EiJ#1#chr9_115462314_115462388
1386950 intron:ENSIUOT00005040218__WSB_EiJ#1#chr9_115462314_115462388
1386951 intron:ENSIUOT00005040238__WSB_EiJ#1#chr9_115464930_115465042
1386952 intron:ENSIUOT00005040190__WSB_EiJ#1#chr9_115464930_115465042
1386953 intron:ENSIUOT00005040206__WSB_EiJ#1#chr9_115464930_115465042
1386954 intron:ENSIUOT00005040218__WSB_EiJ#1#chr9_115464930_115465042
1386955 intron:ENSIUOT00005043016__WSB_EiJ#1#chr9_116063623_116067213
1386956 intron:ENSIUOT00005041077__WSB_EiJ#1#chr9_119034495_119038947
1386957 intron:ENSIUOT00005041112__WSB_EiJ#1#chr9_119034495_119038947
1386958 intron:ENSIUOT00005041077__WSB_EiJ#1#chr9_119040642_119046682
1386959 intron:ENSIUOT00005081955__WSB_EiJ#1#chrX_25869619_25871797
1386960 intron:ENSIUOT00005087114__WSB_EiJ#1#chrX_62990762_62992210
1386961 intron:ENSIUOT00005088660__WSB_EiJ#1#chrX_83476938_83482053
1386962 intron:ENSIUOT00005087377__WSB_EiJ#1#chrX_128552262_128555309
1386963 intron:ENSIUOT00005080868__WSB_EiJ#1#chrX_128552262_128555309
1386964 intron:ENSIUOT00005052101__WSB_EiJ#1#chrX_136760928_136761034
        V2
1       129S1_SvImJ#1#chr1
2       129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
3       129S1_SvImJ#1#chr1
4       129S1_SvImJ#1#chr1
5       129S1_SvImJ#1#chr1
6       129S1_SvImJ#1#chr1
7       129S1_SvImJ#1#chr1
8       129S1_SvImJ#1#chr1
9       129S1_SvImJ#1#chr1
10      129S1_SvImJ#1#chr1
11      129S1_SvImJ#1#chr1
12      129S1_SvImJ#1#chr1
13      129S1_SvImJ#1#chr1
14      129S1_SvImJ#1#chr1
15      129S1_SvImJ#1#chr1
16      129S1_SvImJ#1#chr1
17      129S1_SvImJ#1#chr1
18      129S1_SvImJ#1#chr1
19      129S1_SvImJ#1#chr1
20      129S1_SvImJ#1#chr1
21      129S1_SvImJ#1#chr1
22      129S1_SvImJ#1#chr1
23      129S1_SvImJ#1#chr1
24      129S1_SvImJ#1#chr1
25      129S1_SvImJ#1#chr1
26      129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
27      129S1_SvImJ#1#chr1
28      129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
29      129S1_SvImJ#1#chr1
30      129S1_SvImJ#1#chr1
⋮       ⋮
1386935 WSB_EiJ#1#chr9
1386936 WSB_EiJ#1#chr9
1386937 WSB_EiJ#1#chr9
1386938 WSB_EiJ#1#chr9
1386939 WSB_EiJ#1#chr9
1386940 WSB_EiJ#1#chr9
1386941 WSB_EiJ#1#chr9
1386942 WSB_EiJ#1#chr9
1386943 WSB_EiJ#1#chr9
1386944 WSB_EiJ#1#chr9
1386945 WSB_EiJ#1#chr9
1386946 WSB_EiJ#1#chr9
1386947 WSB_EiJ#1#chr9
1386948 WSB_EiJ#1#chr9
1386949 WSB_EiJ#1#chr9
1386950 WSB_EiJ#1#chr9
1386951 WSB_EiJ#1#chr9
1386952 WSB_EiJ#1#chr9
1386953 WSB_EiJ#1#chr9
1386954 WSB_EiJ#1#chr9
1386955 WSB_EiJ#1#chr9
1386956 WSB_EiJ#1#chr9
1386957 WSB_EiJ#1#chr9
1386958 WSB_EiJ#1#chr9
1386959 WSB_EiJ#1#chrX
1386960 WSB_EiJ#1#chrX
1386961 WSB_EiJ#1#chrX
1386962 WSB_EiJ#1#chrX
1386963 WSB_EiJ#1#chrX
1386964 WSB_EiJ#1#chrX
        V3                         V4                         V5    V6    V7
1       6972170                    6972318                    +       149  0.16
2       7292335;7292335            7294445;7294445            +;+    2111  0.05
3       7292335                    7294372                    +      2038  0.05
4       7292335                    7294447                    +      2113  0.05
5       7292335                    7293220                    +       886  0.05
6       7292335                    7293610                    +      1276  0.05
7       7292335                    7293455                    +      1121  0.05
8       13924083                   13924230                   +       148 12.16
9       18403597                   18408662                   +      5066  0.33
10      18403597                   18408063                   +      4467  0.33
11      31372289                   31383742                   -     11454 12.33
12      32020575                   32025596                   +      5022 14.67
13      32389530                   32393707                   -      4178  1.33
14      32389537                   32393707                   -      4171  1.33
15      33891041                   33892997                   -      1957  2.00
16      37883099                   37889635                   +      6537  0.53
17      39738243                   39738391                   -       149  0.16
18      40699361                   40702005                   -      2645  0.50
19      40699381                   40702005                   -      2625  0.50
20      42426301                   42427851                   +      1551  0.06
21      49676638                   49679506                   -      2869  1.33
22      55557651                   55560981                   -      3331  0.80
23      55557384                   55560008                   +      2625  0.80
24      60086362                   60087813                   -      1452  0.04
25      60091799                   60091947                   +       149  0.16
26      60594452;60594452;60594452 60605795;60605795;60605795 -;-;- 11344  2.80
27      90508811                   90517421                   +      8611  4.00
28      90560494;90560494;90560494 90560632;90560632;90560632 -;-;-   139  0.25
29      90963020                   90966837                   +      3818  2.17
30      90963020                   90966843                   +      3824  2.17
⋮       ⋮                          ⋮                          ⋮     ⋮     ⋮
1386935 79642568                   79643696                   -     1129   0.70
1386936 80066316                   80070434                   +     4119   8.33
1386937 85099451                   85100880                   +     1430   0.11
1386938 92565407                   92568578                   +     3172   1.33
1386939 98132693                   98132808                   -      116   4.10
1386940 98529836                   98530022                   +      187   1.00
1386941 98534410                   98538765                   +     4356   7.33
1386942 102736672                  102742271                  -     5600   4.00
1386943 110513201                  110520143                  -     6943  26.33
1386944 110754886                  110758264                  +     3379  11.00
1386945 110754886                  110757786                  +     2901  11.00
1386946 115445802                  115447533                  +     1732   4.33
1386947 115462314                  115462388                  +       75   1.43
1386948 115462314                  115462388                  +       75   1.43
1386949 115462314                  115462388                  +       75   1.43
1386950 115462314                  115462388                  +       75   1.43
1386951 115464930                  115465042                  +      113   0.50
1386952 115464930                  115465042                  +      113   0.50
1386953 115464930                  115465042                  +      113   0.50
1386954 115464930                  115465042                  +      113   0.50
1386955 116063623                  116067213                  -     3591  20.50
1386956 119034495                  119038947                  +     4453   1.00
1386957 119034495                  119038947                  -     4453   1.00
1386958 119040642                  119046682                  +     6041   3.33
1386959 25869619                   25871797                   +     2179   0.47
1386960 62990762                   62992210                   -     1449   0.06
1386961 83476938                   83482053                   +     5116   0.01
1386962 128552262                  128555309                  -     3048   1.50
1386963 128552262                  128555309                  -     3048   1.50
1386964 136760928                  136761034                  +      107  58.50
        V8
1       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
2       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
3       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
4       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
5       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
6       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
7       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
8       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
9       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
10      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
11      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
12      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
13      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
14      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
15      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
16      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
17      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
18      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
19      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
20      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
21      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
22      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
23      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
24      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
25      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
26      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
27      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
28      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
29      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
30      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
⋮       ⋮
1386935 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386936 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386937 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386938 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386939 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386940 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386941 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386942 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386943 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386944 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386945 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386946 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386947 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386948 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386949 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386950 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386951 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386952 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386953 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386954 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386955 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386956 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386957 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386958 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386959 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386960 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386961 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386962 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386963 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386964 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts

In [28]:
data <- data %>% filter(V7 != 0) 
data <- data %>% separate(V1, c('V9', 'V10','V11','V12'), sep =" ") 
data

Warning message:
“Expected 4 pieces. Missing pieces filled with `NA` in 1386964 rows [1, 2, 3, 4,
5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].”

        V9                                                            V10 V11
1       exon:None_6972170_6972318                                     NA  NA
2       exon:None_7292335_7294445                                     NA  NA
3       exon:None_7292335_7294372                                     NA  NA
4       exon:None_7292335_7294447                                     NA  NA
5       exon:None_7292335_7293220                                     NA  NA
6       exon:None_7292335_7293610                                     NA  NA
7       exon:None_7292335_7293455                                     NA  NA
8       exon:None_13924083_13924230                                   NA  NA
9       exon:None_18403597_18408662                                   NA  NA
10      exon:None_18403597_18408063                                   NA  NA
11      exon:None_31372289_31383742                                   NA  NA
12      exon:None_32020575_32025596                                   NA  NA
13      exon:None_32389530_32393707                                   NA  NA
14      exon:None_32389537_32393707                                   NA  NA
15      exon:None_33891041_33892997                                   NA  NA
16      exon:None_37883099_37889635                                   NA  NA
17      exon:None_39738243_39738391                                   NA  NA
18      exon:None_40699361_40702005                                   NA  NA
19      exon:None_40699381_40702005                                   NA  NA
20      exon:None_42426301_42427851                                   NA  NA
21      exon:None_49676638_49679506                                   NA  NA
22      exon:None_55557651_55560981                                   NA  NA
23      exon:None_55557384_55560008                                   NA  NA
24      exon:None_60086362_60087813                                   NA  NA
25      exon:None_60091799_60091947                                   NA  NA
26      exon:None_60594452_60605795                                   NA  NA
27      exon:None_90508811_90517421                                   NA  NA
28      exon:None_90560494_90560632                                   NA  NA
29      exon:None_90963020_90966837                                   NA  NA
30      exon:None_90963020_90966843                                   NA  NA
⋮       ⋮                                                             ⋮   ⋮
1386935 intron:ENSIUOT00005048946__WSB_EiJ#1#chr9_79642568_79643696   NA  NA
1386936 intron:ENSIUOT00005050035__WSB_EiJ#1#chr9_80066316_80070434   NA  NA
1386937 intron:ENSIUOT00005007032__WSB_EiJ#1#chr9_85099451_85100880   NA  NA
1386938 intron:ENSIUOT00005050530__WSB_EiJ#1#chr9_92565407_92568578   NA  NA
1386939 intron:ENSIUOT00005046445__WSB_EiJ#1#chr9_98132693_98132808   NA  NA
1386940 intron:ENSIUOT00005045865__WSB_EiJ#1#chr9_98529836_98530022   NA  NA
1386941 intron:ENSIUOT00005045865__WSB_EiJ#1#chr9_98534410_98538765   NA  NA
1386942 intron:ENSIUOT00005095527__WSB_EiJ#1#chr9_102736672_102742271 NA  NA
1386943 intron:ENSIUOT00005093563__WSB_EiJ#1#chr9_110513201_110520143 NA  NA
1386944 intron:ENSIUOT00005091698__WSB_EiJ#1#chr9_110754886_110758264 NA  NA
1386945 intron:ENSIUOT00005091688__WSB_EiJ#1#chr9_110754886_110757786 NA  NA
1386946 intron:ENSIUOT00005040162__WSB_EiJ#1#chr9_115445802_115447533 NA  NA
1386947 intron:ENSIUOT00005040238__WSB_EiJ#1#chr9_115462314_115462388 NA  NA
1386948 intron:ENSIUOT00005040190__WSB_EiJ#1#chr9_115462314_115462388 NA  NA
1386949 intron:ENSIUOT00005040206__WSB_EiJ#1#chr9_115462314_115462388 NA  NA
1386950 intron:ENSIUOT00005040218__WSB_EiJ#1#chr9_115462314_115462388 NA  NA
1386951 intron:ENSIUOT00005040238__WSB_EiJ#1#chr9_115464930_115465042 NA  NA
1386952 intron:ENSIUOT00005040190__WSB_EiJ#1#chr9_115464930_115465042 NA  NA
1386953 intron:ENSIUOT00005040206__WSB_EiJ#1#chr9_115464930_115465042 NA  NA
1386954 intron:ENSIUOT00005040218__WSB_EiJ#1#chr9_115464930_115465042 NA  NA
1386955 intron:ENSIUOT00005043016__WSB_EiJ#1#chr9_116063623_116067213 NA  NA
1386956 intron:ENSIUOT00005041077__WSB_EiJ#1#chr9_119034495_119038947 NA  NA
1386957 intron:ENSIUOT00005041112__WSB_EiJ#1#chr9_119034495_119038947 NA  NA
1386958 intron:ENSIUOT00005041077__WSB_EiJ#1#chr9_119040642_119046682 NA  NA
1386959 intron:ENSIUOT00005081955__WSB_EiJ#1#chrX_25869619_25871797   NA  NA
1386960 intron:ENSIUOT00005087114__WSB_EiJ#1#chrX_62990762_62992210   NA  NA
1386961 intron:ENSIUOT00005088660__WSB_EiJ#1#chrX_83476938_83482053   NA  NA
1386962 intron:ENSIUOT00005087377__WSB_EiJ#1#chrX_128552262_128555309 NA  NA
1386963 intron:ENSIUOT00005080868__WSB_EiJ#1#chrX_128552262_128555309 NA  NA
1386964 intron:ENSIUOT00005052101__WSB_EiJ#1#chrX_136760928_136761034 NA  NA
        V12 V2
1       NA  129S1_SvImJ#1#chr1
2       NA  129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
3       NA  129S1_SvImJ#1#chr1
4       NA  129S1_SvImJ#1#chr1
5       NA  129S1_SvImJ#1#chr1
6       NA  129S1_SvImJ#1#chr1
7       NA  129S1_SvImJ#1#chr1
8       NA  129S1_SvImJ#1#chr1
9       NA  129S1_SvImJ#1#chr1
10      NA  129S1_SvImJ#1#chr1
11      NA  129S1_SvImJ#1#chr1
12      NA  129S1_SvImJ#1#chr1
13      NA  129S1_SvImJ#1#chr1
14      NA  129S1_SvImJ#1#chr1
15      NA  129S1_SvImJ#1#chr1
16      NA  129S1_SvImJ#1#chr1
17      NA  129S1_SvImJ#1#chr1
18      NA  129S1_SvImJ#1#chr1
19      NA  129S1_SvImJ#1#chr1
20      NA  129S1_SvImJ#1#chr1
21      NA  129S1_SvImJ#1#chr1
22      NA  129S1_SvImJ#1#chr1
23      NA  129S1_SvImJ#1#chr1
24      NA  129S1_SvImJ#1#chr1
25      NA  129S1_SvImJ#1#chr1
26      NA  129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
27      NA  129S1_SvImJ#1#chr1
28      NA  129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1;129S1_SvImJ#1#chr1
29      NA  129S1_SvImJ#1#chr1
30      NA  129S1_SvImJ#1#chr1
⋮       ⋮   ⋮
1386935 NA  WSB_EiJ#1#chr9
1386936 NA  WSB_EiJ#1#chr9
1386937 NA  WSB_EiJ#1#chr9
1386938 NA  WSB_EiJ#1#chr9
1386939 NA  WSB_EiJ#1#chr9
1386940 NA  WSB_EiJ#1#chr9
1386941 NA  WSB_EiJ#1#chr9
1386942 NA  WSB_EiJ#1#chr9
1386943 NA  WSB_EiJ#1#chr9
1386944 NA  WSB_EiJ#1#chr9
1386945 NA  WSB_EiJ#1#chr9
1386946 NA  WSB_EiJ#1#chr9
1386947 NA  WSB_EiJ#1#chr9
1386948 NA  WSB_EiJ#1#chr9
1386949 NA  WSB_EiJ#1#chr9
1386950 NA  WSB_EiJ#1#chr9
1386951 NA  WSB_EiJ#1#chr9
1386952 NA  WSB_EiJ#1#chr9
1386953 NA  WSB_EiJ#1#chr9
1386954 NA  WSB_EiJ#1#chr9
1386955 NA  WSB_EiJ#1#chr9
1386956 NA  WSB_EiJ#1#chr9
1386957 NA  WSB_EiJ#1#chr9
1386958 NA  WSB_EiJ#1#chr9
1386959 NA  WSB_EiJ#1#chrX
1386960 NA  WSB_EiJ#1#chrX
1386961 NA  WSB_EiJ#1#chrX
1386962 NA  WSB_EiJ#1#chrX
1386963 NA  WSB_EiJ#1#chrX
1386964 NA  WSB_EiJ#1#chrX
        V3                         V4                         V5    V6    V7
1       6972170                    6972318                    +       149  0.16
2       7292335;7292335            7294445;7294445            +;+    2111  0.05
3       7292335                    7294372                    +      2038  0.05
4       7292335                    7294447                    +      2113  0.05
5       7292335                    7293220                    +       886  0.05
6       7292335                    7293610                    +      1276  0.05
7       7292335                    7293455                    +      1121  0.05
8       13924083                   13924230                   +       148 12.16
9       18403597                   18408662                   +      5066  0.33
10      18403597                   18408063                   +      4467  0.33
11      31372289                   31383742                   -     11454 12.33
12      32020575                   32025596                   +      5022 14.67
13      32389530                   32393707                   -      4178  1.33
14      32389537                   32393707                   -      4171  1.33
15      33891041                   33892997                   -      1957  2.00
16      37883099                   37889635                   +      6537  0.53
17      39738243                   39738391                   -       149  0.16
18      40699361                   40702005                   -      2645  0.50
19      40699381                   40702005                   -      2625  0.50
20      42426301                   42427851                   +      1551  0.06
21      49676638                   49679506                   -      2869  1.33
22      55557651                   55560981                   -      3331  0.80
23      55557384                   55560008                   +      2625  0.80
24      60086362                   60087813                   -      1452  0.04
25      60091799                   60091947                   +       149  0.16
26      60594452;60594452;60594452 60605795;60605795;60605795 -;-;- 11344  2.80
27      90508811                   90517421                   +      8611  4.00
28      90560494;90560494;90560494 90560632;90560632;90560632 -;-;-   139  0.25
29      90963020                   90966837                   +      3818  2.17
30      90963020                   90966843                   +      3824  2.17
⋮       ⋮                          ⋮                          ⋮     ⋮     ⋮
1386935 79642568                   79643696                   -     1129   0.70
1386936 80066316                   80070434                   +     4119   8.33
1386937 85099451                   85100880                   +     1430   0.11
1386938 92565407                   92568578                   +     3172   1.33
1386939 98132693                   98132808                   -      116   4.10
1386940 98529836                   98530022                   +      187   1.00
1386941 98534410                   98538765                   +     4356   7.33
1386942 102736672                  102742271                  -     5600   4.00
1386943 110513201                  110520143                  -     6943  26.33
1386944 110754886                  110758264                  +     3379  11.00
1386945 110754886                  110757786                  +     2901  11.00
1386946 115445802                  115447533                  +     1732   4.33
1386947 115462314                  115462388                  +       75   1.43
1386948 115462314                  115462388                  +       75   1.43
1386949 115462314                  115462388                  +       75   1.43
1386950 115462314                  115462388                  +       75   1.43
1386951 115464930                  115465042                  +      113   0.50
1386952 115464930                  115465042                  +      113   0.50
1386953 115464930                  115465042                  +      113   0.50
1386954 115464930                  115465042                  +      113   0.50
1386955 116063623                  116067213                  -     3591  20.50
1386956 119034495                  119038947                  +     4453   1.00
1386957 119034495                  119038947                  -     4453   1.00
1386958 119040642                  119046682                  +     6041   3.33
1386959 25869619                   25871797                   +     2179   0.47
1386960 62990762                   62992210                   -     1449   0.06
1386961 83476938                   83482053                   +     5116   0.01
1386962 128552262                  128555309                  -     3048   1.50
1386963 128552262                  128555309                  -     3048   1.50
1386964 136760928                  136761034                  +      107  58.50
        V8
1       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
2       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
3       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
4       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
5       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
6       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
7       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
8       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
9       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
10      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
11      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
12      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
13      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
14      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
15      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
16      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
17      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
18      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
19      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
20      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
21      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
22      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
23      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
24      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
25      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
26      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
27      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
28      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
29      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
30      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
⋮       ⋮
1386935 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386936 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386937 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386938 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386939 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386940 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386941 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386942 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386943 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386944 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386945 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386946 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386947 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386948 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386949 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386950 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386951 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386952 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386953 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386954 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386955 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386956 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386957 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386958 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386959 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386960 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386961 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386962 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386963 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386964 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts

In [29]:
# Group by V8, V9, V10 and sum the V7 values
new_data <- data %>%
  group_by(V8, V9) %>%
  summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
  ungroup()
new_data

write.csv(new_data, "uniq_piRNA_list3_count.csv", row.names=FALSE)

`summarise()` has grouped output by 'V8'. You can override using the `.groups`
argument.

        V8
1       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
2       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
3       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
4       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
5       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
6       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
7       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
8       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
9       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
10      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
11      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
12      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
13      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
14      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
15      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
16      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
17      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
18      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
19      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
20      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
21      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
22      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
23      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
24      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
25      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
26      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
27      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
28      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
29      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
30      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
⋮       ⋮
1386935 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386936 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386937 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386938 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386939 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386940 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386941 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386942 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386943 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386944 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386945 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386946 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386947 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386948 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386949 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386950 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386951 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386952 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386953 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386954 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386955 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386956 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386957 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386958 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386959 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386960 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386961 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386962 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386963 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
1386964 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
        V9                                     summed_V7
1       exon:None_100123244_100127936          0.33
2       exon:None_100525456_100525926          2.00
3       exon:None_100554702_100559377          0.17
4       exon:None_101134435_101137259          0.40
5       exon:None_101407742_101411557          0.17
6       exon:None_10189444_10192446            1.05
7       exon:None_10189444_10192610            1.05
8       exon:None_102018622_102020510          2.67
9       exon:None_102018622_102027055          2.67
10      exon:None_102053859_102056696          0.92
11      exon:None_102053865_102054838          0.92
12      exon:None_102054087_102054838          0.92
13      exon:None_102054379_102054753          0.92
14      exon:None_10211410_10214313            0.33
15      exon:None_10211410_10216779            0.33
16      exon:None_102456606_102457288          0.03
17      exon:None_102459344_102463402          0.23
18      exon:None_102461410_102464041          0.23
19      exon:None_102462006_102463722          0.23
20      exon:None_102462372_102465291          0.23
21      exon:None_102462513_102464845          0.23
22      exon:None_103006158_103011813          0.11
23      exon:None_103006158_103011817          0.11
24      exon:None_103006158_103011822          0.11
25      exon:None_103237216_103240495          3.33
26      exon:None_103237228_103240495          3.33
27      exon:None_103252698_103257339          6.33
28      exon:None_103372871_103374483          0.06
29      exon:None_103568024_103570870          0.14
30      exon:None_103639602_103641411          0.18
⋮       ⋮                                      ⋮
1386935 three_prime_UTR:None_92719059_92726458  0.01
1386936 three_prime_UTR:None_92730450_92738717  8.33
1386937 three_prime_UTR:None_92736542_92738717  8.33
1386938 three_prime_UTR:None_92814710_92816994 10.00
1386939 three_prime_UTR:None_93028776_93030066 24.00
1386940 three_prime_UTR:None_93029957_93030066 23.00
1386941 three_prime_UTR:None_93082659_93085672  1.33
1386942 three_prime_UTR:None_94104398_94105773  0.33
1386943 three_prime_UTR:None_94104400_94105773  0.33
1386944 three_prime_UTR:None_94104404_94105773  0.33
1386945 three_prime_UTR:None_94127973_94130939  1.40
1386946 three_prime_UTR:None_94358987_94364140  3.25
1386947 three_prime_UTR:None_94615511_94616667  0.10
1386948 three_prime_UTR:None_94717005_94717627  3.15
1386949 three_prime_UTR:None_94717005_94717629  3.15
1386950 three_prime_UTR:None_95751405_95752521  6.33
1386951 three_prime_UTR:None_95879449_95884796 25.00
1386952 three_prime_UTR:None_9617901_9621504    2.67
1386953 three_prime_UTR:None_96940714_96949426  3.33
1386954 three_prime_UTR:None_97670505_97672882 22.67
1386955 three_prime_UTR:None_97673931_97677538  0.67
1386956 three_prime_UTR:None_97892227_97900563  7.83
1386957 three_prime_UTR:None_97925920_97929122 23.00
1386958 three_prime_UTR:None_98306966_98307967  0.83
1386959 three_prime_UTR:None_98306968_98307967  0.83
1386960 three_prime_UTR:None_98535305_98538766  7.33
1386961 three_prime_UTR:None_98705782_98710143  2.67
1386962 three_prime_UTR:None_98965440_98969017  4.00
1386963 three_prime_UTR:None_99514215_99515873  1.17
1386964 three_prime_UTR:None_99514215_99519598 17.50