In [1]:
library(ggplot2)
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/sRNA_STAR_testing")

In [3]:
data <- read.csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/data/sRNA_STAR_testing.csv", header=TRUE,sep=';')
data

    Strains   TimePoint Mismatch Multimap AnchorMultimap Replicate
1   C57BL_6NJ E16.5     0         50      100            3
2   C57BL_6NJ E16.5     0         50      100            2
3   C57BL_6NJ E16.5     0         50      100            1
4   C57BL_6NJ E16.5     0         50      100            3
5   C57BL_6NJ E16.5     0         50      100            2
6   C57BL_6NJ E16.5     0         50      100            1
7   C57BL_6NJ E16.5     0         50      100            3
8   C57BL_6NJ E16.5     0         50      100            2
9   C57BL_6NJ E16.5     0         50      100            1
10  C57BL_6NJ E16.5     0        100      200            2
11  C57BL_6NJ E16.5     0        100      200            1
12  C57BL_6NJ E16.5     0        100      200            2
13  C57BL_6NJ E16.5     0        100      200            1
14  C57BL_6NJ E16.5     0        100      200            2
15  C57BL_6NJ E16.5     0        100      200            1
16  C57BL_6NJ E16.5     0        200      400            3
17  C57BL_6NJ E16.5     0        200      400            2
18  C57BL_6NJ E16.5     0        200      400            1
19  C57BL_6NJ E16.5     0        200      400            3
20  C57BL_6NJ E16.5     0        200      400            2
21  C57BL_6NJ E16.5     0        200      400            1
22  C57BL_6NJ E16.5     0        200      400            3
23  C57BL_6NJ E16.5     0        200      400            2
24  C57BL_6NJ E16.5     0        200      400            1
25  C57BL_6NJ E16.5     0        400      800            3
26  C57BL_6NJ E16.5     0        400      800            2
27  C57BL_6NJ E16.5     0        400      800            1
28  C57BL_6NJ E16.5     0        400      800            3
29  C57BL_6NJ E16.5     0        400      800            2
30  C57BL_6NJ E16.5     0        400      800            1
⋮   ⋮         ⋮         ⋮        ⋮        ⋮              ⋮
130 C57BL_6NJ E16.5     10        200      400           3
131 C57BL_6NJ E16.5     10        200      400           2
132 C57BL_6NJ E16.5     10        200      400           1
133 C57BL_6NJ E16.5     10        400      800           3
134 C57BL_6NJ E16.5     10        400      800           2
135 C57BL_6NJ E16.5     10        400      800           1
136 C57BL_6NJ E16.5     10        400      800           3
137 C57BL_6NJ E16.5     10        400      800           2
138 C57BL_6NJ E16.5     10        400      800           1
139 C57BL_6NJ E16.5     10        400      800           3
140 C57BL_6NJ E16.5     10        400      800           2
141 C57BL_6NJ E16.5     10        400      800           1
142 C57BL_6NJ E16.5     10        800     1600           3
143 C57BL_6NJ E16.5     10        800     1600           2
144 C57BL_6NJ E16.5     10        800     1600           1
145 C57BL_6NJ E16.5     10        800     1600           3
146 C57BL_6NJ E16.5     10        800     1600           2
147 C57BL_6NJ E16.5     10        800     1600           1
148 C57BL_6NJ E16.5     10        800     1600           3
149 C57BL_6NJ E16.5     10        800     1600           2
150 C57BL_6NJ E16.5     10        800     1600           1
151 C57BL_6NJ E16.5     10       1500     3000           3
152 C57BL_6NJ E16.5     10       1500     3000           2
153 C57BL_6NJ E16.5     10       1500     3000           1
154 C57BL_6NJ E16.5     10       1500     3000           3
155 C57BL_6NJ E16.5     10       1500     3000           2
156 C57BL_6NJ E16.5     10       1500     3000           1
157 C57BL_6NJ E16.5     10       1500     3000           3
158 C57BL_6NJ E16.5     10       1500     3000           2
159 C57BL_6NJ E16.5     10       1500     3000           1
    Measure.Names                 Measure.Values
1   Uniquely mapped reads         35.70
2   Uniquely mapped reads         34.61
3   Uniquely mapped reads         38.43
4   Reads Mapped To Multiple Loci 26.99
5   Reads Mapped To Multiple Loci 25.89
6   Reads Mapped To Multiple Loci 25.11
7   Reads Mapped To Too Many Loci  3.43
8   Reads Mapped To Too Many Loci  3.47
9   Reads Mapped To Too Many Loci  3.52
10  Uniquely mapped reads         34.61
11  Uniquely mapped reads         38.43
12  Reads Mapped To Multiple Loci 29.35
13  Reads Mapped To Multiple Loci 28.63
14  Reads Mapped To Too Many Loci  2.43
15  Reads Mapped To Too Many Loci  2.40
16  Uniquely mapped reads         35.70
17  Uniquely mapped reads         34.61
18  Uniquely mapped reads         38.43
19  Reads Mapped To Multiple Loci 32.61
20  Reads Mapped To Multiple Loci 31.78
21  Reads Mapped To Multiple Loci 31.02
22  Reads Mapped To Too Many Loci  1.80
23  Reads Mapped To Too Many Loci  1.87
24  Reads Mapped To Too Many Loci  1.94
25  Uniquely mapped reads         35.69
26  Uniquely mapped reads         34.60
27  Uniquely mapped reads         38.43
28  Reads Mapped To Multiple Loci 34.41
29  Reads Mapped To Multiple Loci 33.64
30  Reads Mapped To Multiple Loci 32.96
⋮   ⋮                             ⋮
130 Reads Mapped To Too Many Loci  1.88
131 Reads Mapped To Too Many Loci  1.96
132 Reads Mapped To Too Many Loci  2.02
133 Uniquely mapped reads         41.09
134 Uniquely mapped reads         41.41
135 Uniquely mapped reads         43.43
136 Reads Mapped To Multiple Loci 41.73
137 Reads Mapped To Multiple Loci 43.35
138 Reads Mapped To Multiple Loci 39.03
139 Reads Mapped To Too Many Loci  2.82
140 Reads Mapped To Too Many Loci  2.95
141 Reads Mapped To Too Many Loci  3.01
142 Uniquely mapped reads         40.99
143 Uniquely mapped reads         41.31
144 Uniquely mapped reads         43.36
145 Reads Mapped To Multiple Loci 44.64
146 Reads Mapped To Multiple Loci 46.42
147 Reads Mapped To Multiple Loci 42.10
148 Reads Mapped To Too Many Loci  3.16
149 Reads Mapped To Too Many Loci  3.41
150 Reads Mapped To Too Many Loci  3.36
151 Uniquely mapped reads         40.95
152 Uniquely mapped reads         41.25
153 Uniquely mapped reads         43.30
154 Reads Mapped To Multiple Loci 47.68
155 Reads Mapped To Multiple Loci 49.74
156 Reads Mapped To Multiple Loci 45.33
157 Reads Mapped To Too Many Loci  1.79
158 Reads Mapped To Too Many Loci  1.51
159 Reads Mapped To Too Many Loci  1.78

In [4]:
summary_data <- data %>%
  group_by(Mismatch, Multimap, AnchorMultimap, Measure.Names) %>%
  summarise(Mean = mean(Measure.Values),
            SE = sd(Measure.Values)/sqrt(n()))

`summarise()` has grouped output by 'Mismatch', 'Multimap', 'AnchorMultimap'.
You can override using the `.groups` argument.

In [5]:
summary_data <- summary_data %>%
  arrange(Mismatch, Multimap, AnchorMultimap, Measure.Names) %>% # Ensuring data is in correct order
  group_by(Mismatch, Multimap, AnchorMultimap) %>%
  mutate(cumulativeMean = cumsum(Mean))

In [6]:
# Define custom colors for stacked bars and error bars
stacked_bar_colors <- c( "#1f77b4","#2ca02c","#ff7f0e", "#d62728" )  # Replace with your colors
error_bar_color <- "#000000"   # Replace with your color


plot <- ggplot(summary_data, aes(x=Measure.Names, y=Mean, fill=Measure.Names)) +
  geom_errorbar(aes(ymax = cumulativeMean + SE, ymin = cumulativeMean - SE ), position="stack", width=4) +
  geom_bar(stat="identity", position="stack",width=10) +
  labs(x=NULL, y="Value") +  # You can also set the x label to NULL
  facet_grid(Measure.Names ~  Mismatch + Multimap + AnchorMultimap  ) +
  scale_fill_manual(values = stacked_bar_colors) +  # Set custom fill colors  
  theme_minimal() +
  theme(strip.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x=element_blank(), 
        axis.text.x=element_blank())

ggsave(filename = "sRNA_STAR_testing.pdf", plot = plot, width = 7, height = 7)

Warning message:
“Stacking not well defined when not anchored on the axis”

In [1]:
run_data <- read.csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/data/sRNA_testing_runTime.csv", header=TRUE,sep=';')
run_data

   Finished        Started         Mismatch Multimap Replicate TimePoint
1  Apr 09 13:18:44 Apr 09 12:22:52  1         50     1         E16.5
2  Apr 09 13:29:36 Apr 09 12:34:07  1         50     2         E16.5
3  Apr 09 13:50:19 Apr 09 12:35:01  1         50     3         E16.5
4  Apr 09 16:13:49 Apr 09 14:55:25 10        200     1         E16.5
5  Apr 09 16:15:35 Apr 09 14:57:32 10        200     2         E16.5
6  Apr 09 18:01:16 Apr 09 15:04:10 10        200     3         E16.5
7  Apr 09 21:04:25 Apr 09 19:49:24  0        200     2         E16.5
8  Apr 09 21:09:54 Apr 09 19:44:00  0        200     1         E16.5
9  Apr 09 22:05:56 Apr 09 20:01:19  0        200     3         E16.5
10 Apr 10 04:42:27 Apr 10 03:52:23 10         50     1         E16.5
11 Apr 10 04:56:39 Apr 10 03:59:36 10         50     2         E16.5
12 Apr 10 05:35:18 Apr 10 04:24:35 10         50     3         E16.5
13 Apr 10 09:48:18 Apr 10 08:58:59  0         50     1         E16.5
14 Apr 10 10:41:20 Apr 10 09:44:30  0         50     2         E16.5
15 Apr 10 11:31:03 Apr 10 10:22:28  0         50     3         E16.5
16 Apr 10 13:23:26 Apr 10 11:57:53  1        200     1         E16.5
17 Apr 10 14:00:25 Apr 10 12:34:30  1        200     2         E16.5
18 Apr 10 21:26:14 Apr 10 19:44:09 10        100     2         E16.5
19 Apr 10 21:40:57 Apr 10 20:15:21 10        100     3         E16.5
20 Apr 11 01:44:42 Apr 10 23:44:22  1        400     1         E16.5
21 Apr 11 02:01:15 Apr 11 00:00:21  1        400     2         E16.5
22 Apr 11 03:00:31 Apr 11 00:05:09  1        400     3         E16.5
23 Apr 11 10:04:21 Apr 11 08:51:38  1        100     1         E16.5
24 Apr 11 10:17:41 Apr 11 09:07:42  1        100     2         E16.5
25 Apr 11 11:33:32 Apr 11 09:12:24  1        100     3         E16.5
26 Apr 11 13:10:46 Apr 11 11:09:34 10        400     1         E16.5
27 Apr 11 20:09:20 Apr 11 18:10:14  0        400     1         E16.5
28 Apr 11 20:19:30 Apr 11 18:22:26  0        400     2         E16.5
29 Apr 11 21:23:38 Apr 11 20:22:48 10        100     1         E16.5
30 Apr 12 21:50:51 Apr 12 19:50:52 10        400     2         E16.5
31 Apr 13 03:03:27 Apr 13 01:00:42  0        100     2         E16.5
32 Apr 24 18:52:39 Apr 24 16:06:36  0        400     3         E16.5
33 Aug 01 13:22:39 Aug 01 09:41:04  0        800     2         E16.5
34 Jul 01 06:06:51 Jun 30 21:57:53  1       1500     2         E16.5
35 Jul 01 17:02:40 Jul 01 13:16:30  0        800     1         E16.5
36 Jul 02 12:31:45 Jul 02 08:42:05 10        800     1         E16.5
37 Jul 04 09:56:29 Jul 03 23:03:54  1       1500     3         E16.5
38 Jul 04 20:47:06 Jul 04 16:55:08  1        800     2         E16.5
39 Jul 05 01:15:33 Jul 04 17:03:50  0       1500     1         E16.5
40 Jul 05 02:11:32 Jul 04 20:51:42  0        800     3         E16.5
41 Jul 08 17:24:31 Jul 08 08:48:55 10       1500     2         E16.5
42 Jul 12 20:21:19 Jul 12 14:58:57 10        800     3         E16.5
43 Jul 16 09:14:28 Jul 15 22:18:42  0       1500     3         E16.5
44 Jul 18 05:46:10 Jul 17 21:15:44 10       1500     1         E16.5
45 Jul 18 19:23:04 Jul 18 11:42:57  0       1500     2         E16.5
46 Jul 25 10:55:14 Jul 25 09:59:59  0        100     1         E16.5
47 Jul 27 14:26:09 Jul 27 12:48:46  1        200     3         E16.5
48 Jun 29 18:40:48 Jun 29 10:19:23  1       1500     1         E16.5
49 Jun 30 10:34:32 Jun 30 05:05:21  1        800     3         E16.5
50 May 06 20:20:34 May 06 16:00:54  1        800     1         E16.5
51 May 09 11:41:11 May 09 07:19:15 10        800     2         E16.5
52 May 18 21:34:42 May 18 18:41:04 10        400     3         E16.5
53 May 29 05:33:25 May 28 16:36:11 10       1500     3         E16.5
   AnchorMultimap
1   100
2   100
3   100
4   400
5   400
6   400
7   400
8   400
9   400
10  100
11  100
12  100
13  100
14  100
15  100
16  400
17  400
18  200
19  200
20  800
21  800
22  800
23  200
24  200
25  200
26  800
27  800
28  800
29  200
30  800
31  200
32  800
33 1600
34 3000
35 1600
36 1600
37 3000
38 1600
39 3000
40 1600
41 3000
42 1600
43 3000
44 3000
45 3000
46  200
47  400
48 3000
49 1600
50 1600
51 1600
52  800
53 3000

In [3]:
library(ggplot2)
library(dplyr)



# Calculate time difference in minutes
run_data$Runtime <- as.numeric(difftime(as.POSIXct(run_data$Finished, format="%b %d %H:%M:%S"), 
                                    as.POSIXct(run_data$Started, format="%b %d %H:%M:%S"), units = "mins"))

                                    
# Summarize data
summary_data <- run_data %>% 
  group_by(Mismatch, Multimap, AnchorMultimap) %>% 
  summarize(Mean_Runtime = mean(Runtime), SD_Runtime = sd(Runtime))

# Plotting
plot <- ggplot(summary_data, aes(x=interaction(Mismatch, Multimap,  AnchorMultimap), y=Mean_Runtime)) +
  geom_errorbar(aes(ymin=Mean_Runtime-SD_Runtime, ymax=Mean_Runtime+SD_Runtime), width=.2) +
  geom_bar(stat="identity",width=10) +  theme_minimal()  +
  theme(axis.text.x = NULL) +
   # You can also set the x label to NULL
  facet_grid( ~  Mismatch + Multimap + AnchorMultimap  ) + 
  labs(x= NULL, y='Runtime (minutes)', title='Runtime with Error Bars') 
# Save plot with specific dimensions
ggsave(filename = "sRNA_STAR_testing_runtime.pdf",  plot, width=7, height=3)

`summarise()` has grouped output by 'Mismatch', 'Multimap'. You can override
using the `.groups` argument.