In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import random
p = 0.01  # 1% of the lines
df = pd.read_csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/TEtranscriptCount/pacBio/all_TEtrascript_data.featureCounts.gz",sep="\t", header=None,compression='gzip')

In [4]:
df = df.loc[df[6] > 0]

df.head()

,0,1,2,3,4,5,6,7
9161,tRNA-Gln-CAA_v tRNA 129S1_SvImJ#1#MT 3772-3842,129S1_SvImJ#1#MT,3772,3842,-,71,781.50,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9163,GSAT_MM Satellite 129S1_SvImJ#1#chr1 1-2510,129S1_SvImJ#1#chr1,1,2510,-,2510,1.30,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9166,RLTR13A1 LTR/ERVK 129S1_SvImJ#1#chr1 8694-9546,129S1_SvImJ#1#chr1,8694,9546,-,853,3.34,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9167,IAPEY3_LTR LTR/ERVK 129S1_SvImJ#1#chr1 11649-...,129S1_SvImJ#1#chr1,11649,11978,+,330,0.05,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts
9168,IAPEY3-int LTR/ERVK 129S1_SvImJ#1#chr1 11979-...,129S1_SvImJ#1#chr1,11979,15253,+,3275,5.73,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts

In [5]:
strains = df[7].str.split("/", expand = True)
df['strains'] = strains[0]

In [6]:

replicates = df[7].str.split("-", expand = True)

In [7]:
rep1 = replicates[1].str.split(".f", expand = True)

In [8]:
rep2 = rep1[0].str.split(".", expand = True)
df['replicates'] = rep2[2]

In [9]:
df['timepoint'] = rep2[0] + '.' + rep2[1]

In [10]:
df['sampleName'] = strains[1].str.split(".f", expand = True)[0]

df.head()

,0,1,2,3,4,5,6,7,strains,replicates,timepoint,sampleName
9161,tRNA-Gln-CAA_v tRNA 129S1_SvImJ#1#MT 3772-3842,129S1_SvImJ#1#MT,3772,3842,-,71,781.50,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1
9163,GSAT_MM Satellite 129S1_SvImJ#1#chr1 1-2510,129S1_SvImJ#1#chr1,1,2510,-,2510,1.30,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1
9166,RLTR13A1 LTR/ERVK 129S1_SvImJ#1#chr1 8694-9546,129S1_SvImJ#1#chr1,8694,9546,-,853,3.34,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1
9167,IAPEY3_LTR LTR/ERVK 129S1_SvImJ#1#chr1 11649-...,129S1_SvImJ#1#chr1,11649,11978,+,330,0.05,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1
9168,IAPEY3-int LTR/ERVK 129S1_SvImJ#1#chr1 11979-...,129S1_SvImJ#1#chr1,11979,15253,+,3275,5.73,129S1_SvImJ/129S1_SvImJ-12.5dpp.1.featureCounts,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1

In [11]:
subfamily = df[0].str.split(" ", expand = True)
df['subFamily'] = subfamily[0]

In [12]:
df['Family'] = subfamily[1]

In [13]:
family = df['Family'].str.split("/", expand = True)
df['Family1'] = family[0]

In [14]:
df['Family2'] = family[1]

In [15]:
df['count'] = df[6]

In [16]:
df.head()
list(df.columns.values)
df[['strains',	'replicates'	,'timepoint',	'sampleName',	'subFamily',	'Family',	'Family1',	'Family2',	'count']].to_csv('all_TEtrascript_count.tab', sep='\t', index=False)

In [17]:
df[['strains',	'replicates'	,'timepoint',	'sampleName',	'subFamily',	'Family',	'Family1',	'Family2',	'count']].head()

,strains,replicates,timepoint,sampleName,subFamily,Family,Family1,Family2,count
9161,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1,tRNA-Gln-CAA_v,tRNA,tRNA,None,781.50
9163,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1,GSAT_MM,Satellite,Satellite,None,1.30
9166,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1,RLTR13A1,LTR/ERVK,LTR,ERVK,3.34
9167,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1,IAPEY3_LTR,LTR/ERVK,LTR,ERVK,0.05
9168,129S1_SvImJ,1,12.5dpp,129S1_SvImJ-12.5dpp.1,IAPEY3-int,LTR/ERVK,LTR,ERVK,5.73