In [1]:
###testing R in jyupter 
system("type R")

In [2]:
#package installation 
#install.packages("purrr")
#install.packages("tidyverse")
#conda install r-tidyverse r-purrr bioconductor-edger bioconductor-busparse bioconductor-rtracklayer r-dplyr -y 
#conda install -c conda-forge r-purrr -y
#conda install -c bioconda bioconductor-edger -y
#conda install -c bioconda bioconductor-busparse -y
#conda install -c bioconda bioconductor-rtracklayer -y
#conda install -c conda-forge r-dplyr -y

In [3]:
library(purrr)
library(tidyverse)
library(edgeR)
library(rtracklayer)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: limma

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:limma’:

    plotMA


The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:lubridate’:

    second, second<-


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:tidyr’:

    expand


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:lubridate’:

    %within%


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:purrr’:

    reduce


Loading required package: GenomeInfoDb

In [4]:
library(purrr)
library(tidyverse)
f_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/TPMCount_rna/strains/", pattern = ".featureCounts$", full.names = T,recursive = T)

f_files

  [1] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts"
  [2] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts"
  [3] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts"
  [4] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts"
  [5] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts"
  [6] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts"
  [7] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts"
  [8] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts"
  [9] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts"
 [10] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts"
 [11] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts"
 [12] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts"
 [13] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts"
 [14] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts"
 [15] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts"
 [16] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts"
 [17] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts"
 [18] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts"
 [19] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts"
 [20] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts"
 [21] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts"
 [22] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts"
 [23] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts"
 [24] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts"
 [25] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts"
 [26] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts"
 [27] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts"
 [28] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts"
 [29] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts"
 [30] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts"
 [31] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts"
 [32] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts"
 [33] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts"
 [34] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts"
 [35] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts"
 [36] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts"
 [37] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts"
 [38] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts"
 [39] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts"
 [40] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts"
 [41] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts"
 [42] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts"
 [43] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts"
 [44] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts"
 [45] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts"
 [46] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts"
 [47] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts"
 [48] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts"
 [49] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts"
 [50] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts"
 [51] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts"
 [52] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts"
 [53] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts"
 [54] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts"
 [55] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts"
 [56] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts"
 [57] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts"
 [58] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts"
 [59] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts"
 [60] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts"
 [61] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts"
 [62] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts"
 [63] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts"
 [64] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts"
 [65] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts"
 [66] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts"
 [67] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts"
 [68] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts"
 [69] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts"
 [70] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts"
 [71] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts"
 [72] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts"
 [73] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts"
 [74] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts"
 [75] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts"
 [76] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts"
 [77] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts"
 [78] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts"
 [79] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts"
 [80] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts"
 [81] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts"
 [82] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts"
 [83] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts"
 [84] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts"
 [85] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts"
 [86] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts"
 [87] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts"
 [88] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts"
 [89] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts"
 [90] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts"
 [91] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.1.featureCounts"
 [92] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.2.featureCounts"
 [93] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.3.featureCounts"
 [94] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.1.featureCounts"
 [95] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.2.featureCounts"
 [96] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.3.featureCounts"
 [97] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.1.featureCounts"
 [98] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.2.featureCounts"
 [99] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.3.featureCounts"
[100] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts"
[101] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts"
[102] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts"
[103] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts"
[104] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts"
[105] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts"
[106] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts"
[107] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts"
[108] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts"
[109] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.1.featureCounts"
[110] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.2.featureCounts"
[111] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.3.featureCounts"
[112] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.1.featureCounts"
[113] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.2.featureCounts"
[114] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.3.featureCounts"
[115] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.1.featureCounts"
[116] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.2.featureCounts"
[117] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.3.featureCounts"
[118] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts"
[119] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts"
[120] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts"
[121] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts"
[122] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts"
[123] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts"
[124] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts"
[125] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts"
[126] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts"
[127] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts"
[128] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts"
[129] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts"
[130] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts"
[131] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts"
[132] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts"
[133] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts"
[134] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts"
[135] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts"
[136] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts"
[137] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts"
[138] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts"
[139] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts"
[140] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts"
[141] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts"
[142] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts"
[143] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts"
[144] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts"

In [5]:
#samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames = c('C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'A_J-E16.5','A_J-E16.5','A_J-E16.5','A_J-P12.5','A_J-P12.5','A_J-P12.5','A_J-P20.5','A_J-P20.5','A_J-P20.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'LP_J-E16.5','LP_J-E16.5','LP_J-E16.5','LP_J-P12.5','LP_J-P12.5','LP_J-P12.5','LP_J-P20.5','LP_J-P20.5','LP_J-P20.5',
'129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-E16.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-E16.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')

In [6]:
#list of sample names with replicates 
#lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))
lables  = c('C57BL_6NJ-16.5dpc.1','C57BL_6NJ-16.5dpc.2','C57BL_6NJ-16.5dpc.3','C57BL_6NJ-12.5dpp.1','C57BL_6NJ-12.5dpp.2','C57BL_6NJ-12.5dpp.3','C57BL_6NJ-20.5dpp.1','C57BL_6NJ-20.5dpp.2','C57BL_6NJ-20.5dpp.3',
'BALB_cJ-16.5dpc.1','BALB_cJ-16.5dpc.2','BALB_cJ-16.5dpc.3','BALB_cJ-12.5dpp.1','BALB_cJ-12.5dpp.2','BALB_cJ-12.5dp.3','BALB_cJ-20.5dpp.1','BALB_cJ-20.5dp.2','BALB_cJ-20.5dpp.3',
'A_J-16.5dpc.1','A_J-16.5dpc.2','A_J-16.5dpc.3','A_J-12.5dpp.1','A_J-12.5dpp.2','A_J-12.5dpp.3','A_J-20.5dpp.1','A_J-20.5dpp.2','A_J-20.5dpp.3',
'FVB_NJ-16.5dpc.1','FVB_NJ-16.5dpc.2','FVB_NJ-16.5dpc.3','FVB_NJ-12.5dpp.1','FVB_NJ-12.5dpp.2','FVB_NJ-12.5dpp.3','FVB_NJ-20.5dpp.1','FVB_NJ-20.5dpp.2','FVB_NJ-20.5dpp.3',
'C3H_HeJ-16.5dpc.1','C3H_HeJ-16.5dpc.2','C3H_HeJ-16.5dpc.3','C3H_HeJ-12.5dpp.1','C3H_HeJ-12.5dp.2','C3H_HeJ-12.5dpp.3','C3H_HeJ-20.5dpp.1','C3H_HeJ-20.5dp.2','C3H_HeJ-20.5dpp.3',
'LP_J-16.5dpc.1','LP_J-16.5dpc.2','LP_J-16.5dpc.3','LP_J-12.5dpp.1','LP_J-12.5dpp.2','LP_J-12.5dpp.3','LP_J-20.5dpp.1','LP_J-20.5dpp.2','LP_J-20.5dpp.3',
'129S1_SvImJ-16.5dp.1','129S1_SvImJ-16.5dpc.2','129S1_SvImJ-16.5dpc.3','129S1_SvImJ-12.5dpp.1','129S1_SvImJ-12.5dpp.2','129S1_SvImJ-12.5dpp.3','129S1_SvImJ-20.5dpp.1','129S1_SvImJ-20.5dp.2','129S1_SvImJ-20.5dpp.3',
'DBA_2J-16.5dpc.1','DBA_2J-16.5dpc.2','DBA_2J-16.5dpc.3','DBA_2J-12.5dpp.1','DBA_2J-12.5dpp.2','DBA_2J-12.5dpp.3','DBA_2J-20.5dpp.1','DBA_2J-20.5dpp.2','DBA_2J-20.5dpp.3',
'AKR_J-16.5dpc.1','AKR_J-16.5dpc.2','AKR_J-16.5dpc.3','AKR_J-12.5dpp.1','AKR_J-12.5dpp.2','AKR_J-12.5dpp.3','AKR_J-20.5dpp.1','AKR_J-20.5dpp.2','AKR_J-20.5dpp.3',
'CBA_J-16.5dpc.1','CBA_J-16.5dp.2','CBA_J-16.5dpc.3','CBA_J-12.5dpp.1','CBA_J-12.5dpp.2','CBA_J-12.5dpp.3','CBA_J-20.5dpp.1','CBA_J-20.5dpp.2','CBA_J-20.5dpp.3',
'NZO_HlLtJ-16.5dpc.1','NZO_HlLtJ-16.5dpc.2','NZO_HlLtJ-16.5dpc.3','NZO_HlLtJ-12.5dpp.1','NZO_HlLtJ-12.5dpp.2','NZO_HlLtJ-12.5dpp.3','NZO_HlLtJ-20.5dpp.1','NZO_HlLtJ-20.5dpp.2','NZO_HlLtJ-20.5dpp.3',
'NOD_ShiLtJ-16.5dpc.1','NOD_ShiLtJ-16.5dpc.2','NOD_ShiLtJ-16.5dpc.3','NOD_ShiLtJ-12.5dpp.1','NOD_ShiLtJ-12.5dpp.2','NOD_ShiLtJ-12.5dpp.3','NOD_ShiLtJ-20.5dpp.1','NOD_ShiLtJ-20.5dpp.2','NOD_ShiLtJ-20.5dpp.3',
'WSB_EiJ-16.5dpc.1','WSB_EiJ-16.5dpc.2','WSB_EiJ-16.5dpc.3','WSB_EiJ-12.5dpp.1','WSB_EiJ-12.5dpp.2','WSB_EiJ-12.5dpp.3','WSB_EiJ-20.5dpp.1','WSB_EiJ-20.5dpp.2','WSB_EiJ-20.5dpp.3',
'CAST_EiJ-16.5dpc.1','CAST_EiJ-16.5dpc.2','CAST_EiJ-16.5dpc.3','CAST_EiJ-12.5dpp.1','CAST_EiJ-12.5dpp.2','CAST_EiJ-12.5dpp.3','CAST_EiJ-20.5dpp.1','CAST_EiJ-20.5dpp.2','CAST_EiJ-20.5dpp.3',
'PWK_PhJ-16.5dpc.1','PWK_PhJ-16.5dpc.2','PWK_PhJ-16.5dpc.3','PWK_PhJ-12.5dpp.1','PWK_PhJ-12.5dpp.2','PWK_PhJ-12.5dpp.3','PWK_PhJ-20.5dpp.1','PWK_PhJ-20.5dp.2','PWK_PhJ-20.5dpp.3',
'SPRET_EiJ-16.5dpc.1','SPRET_EiJ-16.5dpc.2','SPRET_EiJ-16.5dpc.3','SPRET_EiJ-12.5dpp.1','SPRET_EiJ-12.5dpp.2','SPRET_EiJ-12.5dpp.3','SPRET_EiJ-20.5dpp.1','SPRET_EiJ-20.5dpp.2','SPRET_EiJ-20.5dpp,3')

In [7]:
raw <- readDGE(f_files, columns = c(1, 7), comment.char = "#", sep="\t", group= samplenames, labels = lables,)

In [8]:
rawdata <- raw
rawdata

An object of class "DGEList"
$samples
                                                                                                                                             files
C57BL_6NJ-16.5dpc.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
C57BL_6NJ-16.5dpc.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
C57BL_6NJ-16.5dpc.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
C57BL_6NJ-12.5dpp.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
C57BL_6NJ-12.5dpp.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
                              group lib.size norm.factors
C57BL_6NJ-16.5dpc.1 C57BL_6NJ-E16.5 31878714            1
C57BL_6NJ-16.5dpc.2 C57BL_6NJ-E16.5 31993372            1
C57BL_6NJ-16.5dpc.3 C57BL_6NJ-E16.5 32262165            1
C57BL_6NJ-12.5dpp.1 C57BL_6NJ-P12.5 30879948            1
C57BL_6NJ-12.5dpp.2 C57BL_6NJ-P12.5 35864325            1
139 more rows ...

$counts
                    Samples
Tags                 C57BL_6NJ-16.5dpc.1 C57BL_6NJ-16.5dpc.2
  ENSMUSG00200053149               24.50               20.50
  ENSMUSG00200032800                0.00                0.00
  ENSMUSG00200032797             1679.95             1636.63
  ENSMUSG00200032798                6.50                8.00
  ENSMUSG00200032795                5.50               10.00
                    Samples
Tags                 C57BL_6NJ-16.5dpc.3 C57BL_6NJ-12.5dpp.1
  ENSMUSG00200053149               32.00                5.00
  ENSMUSG00200032800                0.00                0.00
  ENSMUSG00200032797             1454.33             5649.27
  ENSMUSG00200032798               10.50               30.00
  ENSMUSG00200032795                8.00               29.50
                    Samples
Tags                 C57BL_6NJ-12.5dpp.2 C57BL_6NJ-12.5dpp.3
  ENSMUSG00200053149                9.50                6.50
  ENSMUSG00200032800                0.00                0.00
  ENSMUSG00200032797             6939.42             7462.89
  ENSMUSG00200032798               41.50               46.50
  ENSMUSG00200032795               31.00               35.00
                    Samples
Tags                 C57BL_6NJ-20.5dpp.1 C57BL_6NJ-20.5dpp.2
  ENSMUSG00200053149               21.00               29.00
  ENSMUSG00200032800                0.00                0.00
  ENSMUSG00200032797              220.16              166.69
  ENSMUSG00200032798                1.00                1.00
  ENSMUSG00200032795                1.00                0.00
                    Samples
Tags                 C57BL_6NJ-20.5dpp.3 BALB_cJ-16.5dpc.1 BALB_cJ-16.5dpc.2
  ENSMUSG00200053149               27.50                 0                 0
  ENSMUSG00200032800                0.00                 0                 0
  ENSMUSG00200032797              252.17                 0                 0
  ENSMUSG00200032798                1.00                 0                 0
  ENSMUSG00200032795                1.00                 0                 0
                    Samples
Tags                 BALB_cJ-16.5dpc.3 BALB_cJ-12.5dpp.1 BALB_cJ-12.5dpp.2
  ENSMUSG00200053149                 0                 0                 0
  ENSMUSG00200032800                 0                 0                 0
  ENSMUSG00200032797                 0                 0                 0
  ENSMUSG00200032798                 0                 0                 0
  ENSMUSG00200032795                 0                 0                 0
                    Samples
Tags                 BALB_cJ-12.5dp.3 BALB_cJ-20.5dpp.1 BALB_cJ-20.5dp.2
  ENSMUSG00200053149                0                 0                0
  ENSMUSG00200032800                0                 0                0
  ENSMUSG00200032797                0                 0                0
  ENSMUSG00200032798                0                 0                0
  ENSMUSG00200032795                0                 0                0
                    Samples
Tags                 BALB_cJ-20.5dpp.3 A_J-16.5dpc.1 A_J-16.5dpc.2
  ENSMUSG00200053149                 0             0             0
  ENSMUSG00200032800                 0             0             0
  ENSMUSG00200032797                 0             0             0
  ENSMUSG00200032798                 0             0             0
  ENSMUSG00200032795                 0             0             0
                    Samples
Tags                 A_J-16.5dpc.3 A_J-12.5dpp.1 A_J-12.5dpp.2 A_J-12.5dpp.3
  ENSMUSG00200053149             0             0             0             0
  ENSMUSG00200032800             0             0             0             0
  ENSMUSG00200032797             0             0             0             0
  ENSMUSG00200032798             0             0             0             0
  ENSMUSG00200032795             0             0             0             0
                    Samples
Tags                 A_J-20.5dpp.1 A_J-20.5dpp.2 A_J-20.5dpp.3 FVB_NJ-16.5dpc.1
  ENSMUSG00200053149             0             0             0                0
  ENSMUSG00200032800             0             0             0                0
  ENSMUSG00200032797             0             0             0                0
  ENSMUSG00200032798             0             0             0                0
  ENSMUSG00200032795             0             0             0                0
                    Samples
Tags                 FVB_NJ-16.5dpc.2 FVB_NJ-16.5dpc.3 FVB_NJ-12.5dpp.1
  ENSMUSG00200053149                0                0                0
  ENSMUSG00200032800                0                0                0
  ENSMUSG00200032797                0                0                0
  ENSMUSG00200032798                0                0                0
  ENSMUSG00200032795                0                0                0
                    Samples
Tags                 FVB_NJ-12.5dpp.2 FVB_NJ-12.5dpp.3 FVB_NJ-20.5dpp.1
  ENSMUSG00200053149                0                0                0
  ENSMUSG00200032800                0                0                0
  ENSMUSG00200032797                0                0                0
  ENSMUSG00200032798                0                0                0
  ENSMUSG00200032795                0                0                0
                    Samples
Tags                 FVB_NJ-20.5dpp.2 FVB_NJ-20.5dpp.3 C3H_HeJ-16.5dpc.1
  ENSMUSG00200053149                0                0                 0
  ENSMUSG00200032800                0                0                 0
  ENSMUSG00200032797                0                0                 0
  ENSMUSG00200032798                0                0                 0
  ENSMUSG00200032795                0                0                 0
                    Samples
Tags                 C3H_HeJ-16.5dpc.2 C3H_HeJ-16.5dpc.3 C3H_HeJ-12.5dpp.1
  ENSMUSG00200053149                 0                 0                 0
  ENSMUSG00200032800                 0                 0                 0
  ENSMUSG00200032797                 0                 0                 0
  ENSMUSG00200032798                 0                 0                 0
  ENSMUSG00200032795                 0                 0                 0
                    Samples
Tags                 C3H_HeJ-12.5dp.2 C3H_HeJ-12.5dpp.3 C3H_HeJ-20.5dpp.1
  ENSMUSG00200053149                0                 0                 0
  ENSMUSG00200032800                0                 0                 0
  ENSMUSG00200032797                0                 0                 0
  ENSMUSG00200032798                0                 0                 0
  ENSMUSG00200032795                0                 0                 0
                    Samples
Tags                 C3H_HeJ-20.5dp.2 C3H_HeJ-20.5dpp.3 LP_J-16.5dpc.1
  ENSMUSG00200053149                0                 0              0
  ENSMUSG00200032800                0                 0              0
  ENSMUSG00200032797                0                 0              0
  ENSMUSG00200032798                0                 0              0
  ENSMUSG00200032795                0                 0              0
                    Samples
Tags                 LP_J-16.5dpc.2 LP_J-16.5dpc.3 LP_J-12.5dpp.1
  ENSMUSG00200053149              0              0              0
  ENSMUSG00200032800              0              0              0
  ENSMUSG00200032797              0              0              0
  ENSMUSG00200032798              0              0              0
  ENSMUSG00200032795              0              0              0
                    Samples
Tags                 LP_J-12.5dpp.2 LP_J-12.5dpp.3 LP_J-20.5dpp.1
  ENSMUSG00200053149              0              0              0
  ENSMUSG00200032800              0              0              0
  ENSMUSG00200032797              0              0              0
  ENSMUSG00200032798              0              0              0
  ENSMUSG00200032795              0              0              0
                    Samples
Tags                 LP_J-20.5dpp.2 LP_J-20.5dpp.3 129S1_SvImJ-16.5dp.1
  ENSMUSG00200053149              0              0                    0
  ENSMUSG00200032800              0              0                    0
  ENSMUSG00200032797              0              0                    0
  ENSMUSG00200032798              0              0                    0
  ENSMUSG00200032795              0              0                    0
                    Samples
Tags                 129S1_SvImJ-16.5dpc.2 129S1_SvImJ-16.5dpc.3
  ENSMUSG00200053149                     0                     0
  ENSMUSG00200032800                     0                     0
  ENSMUSG00200032797                     0                     0
  ENSMUSG00200032798                     0                     0
  ENSMUSG00200032795                     0                     0
                    Samples
Tags                 129S1_SvImJ-12.5dpp.1 129S1_SvImJ-12.5dpp.2
  ENSMUSG00200053149                     0                     0
  ENSMUSG00200032800                     0                     0
  ENSMUSG00200032797                     0                     0
  ENSMUSG00200032798                     0                     0
  ENSMUSG00200032795                     0                     0
                    Samples
Tags                 129S1_SvImJ-12.5dpp.3 129S1_SvImJ-20.5dpp.1
  ENSMUSG00200053149                     0                     0
  ENSMUSG00200032800                     0                     0
  ENSMUSG00200032797                     0                     0
  ENSMUSG00200032798                     0                     0
  ENSMUSG00200032795                     0                     0
                    Samples
Tags                 129S1_SvImJ-20.5dp.2 129S1_SvImJ-20.5dpp.3
  ENSMUSG00200053149                    0                     0
  ENSMUSG00200032800                    0                     0
  ENSMUSG00200032797                    0                     0
  ENSMUSG00200032798                    0                     0
  ENSMUSG00200032795                    0                     0
                    Samples
Tags                 DBA_2J-16.5dpc.1 DBA_2J-16.5dpc.2 DBA_2J-16.5dpc.3
  ENSMUSG00200053149                0                0                0
  ENSMUSG00200032800                0                0                0
  ENSMUSG00200032797                0                0                0
  ENSMUSG00200032798                0                0                0
  ENSMUSG00200032795                0                0                0
                    Samples
Tags                 DBA_2J-12.5dpp.1 DBA_2J-12.5dpp.2 DBA_2J-12.5dpp.3
  ENSMUSG00200053149                0                0                0
  ENSMUSG00200032800                0                0                0
  ENSMUSG00200032797                0                0                0
  ENSMUSG00200032798                0                0                0
  ENSMUSG00200032795                0                0                0
                    Samples
Tags                 DBA_2J-20.5dpp.1 DBA_2J-20.5dpp.2 DBA_2J-20.5dpp.3
  ENSMUSG00200053149                0                0                0
  ENSMUSG00200032800                0                0                0
  ENSMUSG00200032797                0                0                0
  ENSMUSG00200032798                0                0                0
  ENSMUSG00200032795                0                0                0
                    Samples
Tags                 AKR_J-16.5dpc.1 AKR_J-16.5dpc.2 AKR_J-16.5dpc.3
  ENSMUSG00200053149               0               0               0
  ENSMUSG00200032800               0               0               0
  ENSMUSG00200032797               0               0               0
  ENSMUSG00200032798               0               0               0
  ENSMUSG00200032795               0               0               0
                    Samples
Tags                 AKR_J-12.5dpp.1 AKR_J-12.5dpp.2 AKR_J-12.5dpp.3
  ENSMUSG00200053149               0               0               0
  ENSMUSG00200032800               0               0               0
  ENSMUSG00200032797               0               0               0
  ENSMUSG00200032798               0               0               0
  ENSMUSG00200032795               0               0               0
                    Samples
Tags                 AKR_J-20.5dpp.1 AKR_J-20.5dpp.2 AKR_J-20.5dpp.3
  ENSMUSG00200053149               0               0               0
  ENSMUSG00200032800               0               0               0
  ENSMUSG00200032797               0               0               0
  ENSMUSG00200032798               0               0               0
  ENSMUSG00200032795               0               0               0
                    Samples
Tags                 CBA_J-16.5dpc.1 CBA_J-16.5dp.2 CBA_J-16.5dpc.3
  ENSMUSG00200053149               0              0               0
  ENSMUSG00200032800               0              0               0
  ENSMUSG00200032797               0              0               0
  ENSMUSG00200032798               0              0               0
  ENSMUSG00200032795               0              0               0
                    Samples
Tags                 CBA_J-12.5dpp.1 CBA_J-12.5dpp.2 CBA_J-12.5dpp.3
  ENSMUSG00200053149               0               0               0
  ENSMUSG00200032800               0               0               0
  ENSMUSG00200032797               0               0               0
  ENSMUSG00200032798               0               0               0
  ENSMUSG00200032795               0               0               0
                    Samples
Tags                 CBA_J-20.5dpp.1 CBA_J-20.5dpp.2 CBA_J-20.5dpp.3
  ENSMUSG00200053149               0               0               0
  ENSMUSG00200032800               0               0               0
  ENSMUSG00200032797               0               0               0
  ENSMUSG00200032798               0               0               0
  ENSMUSG00200032795               0               0               0
                    Samples
Tags                 NZO_HlLtJ-16.5dpc.1 NZO_HlLtJ-16.5dpc.2
  ENSMUSG00200053149                   0                   0
  ENSMUSG00200032800                   0                   0
  ENSMUSG00200032797                   0                   0
  ENSMUSG00200032798                   0                   0
  ENSMUSG00200032795                   0                   0
                    Samples
Tags                 NZO_HlLtJ-16.5dpc.3 NZO_HlLtJ-12.5dpp.1
  ENSMUSG00200053149                   0                   0
  ENSMUSG00200032800                   0                   0
  ENSMUSG00200032797                   0                   0
  ENSMUSG00200032798                   0                   0
  ENSMUSG00200032795                   0                   0
                    Samples
Tags                 NZO_HlLtJ-12.5dpp.2 NZO_HlLtJ-12.5dpp.3
  ENSMUSG00200053149                   0                   0
  ENSMUSG00200032800                   0                   0
  ENSMUSG00200032797                   0                   0
  ENSMUSG00200032798                   0                   0
  ENSMUSG00200032795                   0                   0
                    Samples
Tags                 NZO_HlLtJ-20.5dpp.1 NZO_HlLtJ-20.5dpp.2
  ENSMUSG00200053149                   0                   0
  ENSMUSG00200032800                   0                   0
  ENSMUSG00200032797                   0                   0
  ENSMUSG00200032798                   0                   0
  ENSMUSG00200032795                   0                   0
                    Samples
Tags                 NZO_HlLtJ-20.5dpp.3 NOD_ShiLtJ-16.5dpc.1
  ENSMUSG00200053149                   0                    0
  ENSMUSG00200032800                   0                    0
  ENSMUSG00200032797                   0                    0
  ENSMUSG00200032798                   0                    0
  ENSMUSG00200032795                   0                    0
                    Samples
Tags                 NOD_ShiLtJ-16.5dpc.2 NOD_ShiLtJ-16.5dpc.3
  ENSMUSG00200053149                    0                    0
  ENSMUSG00200032800                    0                    0
  ENSMUSG00200032797                    0                    0
  ENSMUSG00200032798                    0                    0
  ENSMUSG00200032795                    0                    0
                    Samples
Tags                 NOD_ShiLtJ-12.5dpp.1 NOD_ShiLtJ-12.5dpp.2
  ENSMUSG00200053149                    0                    0
  ENSMUSG00200032800                    0                    0
  ENSMUSG00200032797                    0                    0
  ENSMUSG00200032798                    0                    0
  ENSMUSG00200032795                    0                    0
                    Samples
Tags                 NOD_ShiLtJ-12.5dpp.3 NOD_ShiLtJ-20.5dpp.1
  ENSMUSG00200053149                    0                    0
  ENSMUSG00200032800                    0                    0
  ENSMUSG00200032797                    0                    0
  ENSMUSG00200032798                    0                    0
  ENSMUSG00200032795                    0                    0
                    Samples
Tags                 NOD_ShiLtJ-20.5dpp.2 NOD_ShiLtJ-20.5dpp.3
  ENSMUSG00200053149                    0                    0
  ENSMUSG00200032800                    0                    0
  ENSMUSG00200032797                    0                    0
  ENSMUSG00200032798                    0                    0
  ENSMUSG00200032795                    0                    0
                    Samples
Tags                 WSB_EiJ-16.5dpc.1 WSB_EiJ-16.5dpc.2 WSB_EiJ-16.5dpc.3
  ENSMUSG00200053149                 0                 0                 0
  ENSMUSG00200032800                 0                 0                 0
  ENSMUSG00200032797                 0                 0                 0
  ENSMUSG00200032798                 0                 0                 0
  ENSMUSG00200032795                 0                 0                 0
                    Samples
Tags                 WSB_EiJ-12.5dpp.1 WSB_EiJ-12.5dpp.2 WSB_EiJ-12.5dpp.3
  ENSMUSG00200053149                 0                 0                 0
  ENSMUSG00200032800                 0                 0                 0
  ENSMUSG00200032797                 0                 0                 0

In [9]:
A129S1_SvImJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/129S1_SvImJ_v3.2.gff3") #import gff3 file 
A129S1_SvImJ_geneName = na.omit(mcols(A129S1_SvImJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

A_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/A_J_v3.2.gff3") #import gff3 file 
A_J_geneName = na.omit(mcols(A_J )[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

AKR_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/AKR_J_v3.2.gff3") #import gff3 file 
AKR_J_geneName = na.omit(mcols(AKR_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

BALB_cJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/BALB_cJ_v3.2.gff3") #import gff3 file 
BALB_cJ_geneName = na.omit(mcols(BALB_cJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C3H_HeJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C3H_HeJ_v3.2.gff3") #import gff3 file 
C3H_HeJ_geneName = na.omit(mcols(C3H_HeJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C57BL_6NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C57BL_6NJ_v3.2.gff3") #import gff3 file 
C57BL_6NJ_geneName = na.omit(mcols(C57BL_6NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CAST_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CAST_EiJ_v3.2.gff3") #import gff3 file 
CAST_EiJ_geneName = na.omit(mcols(CAST_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CBA_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CBA_J_v3.2.gff3") #import gff3 file 
CBA_J_geneName = na.omit(mcols(CBA_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

DBA_2J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/DBA_2J_v3.2.gff3") #import gff3 file 
DBA_2J_geneName = na.omit(mcols(DBA_2J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

FVB_NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/FVB_NJ_v3.2.gff3") #import gff3 file 
FVB_NJ_geneName = na.omit(mcols(FVB_NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

LP_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/LP_J_v3.2.gff3") #import gff3 file 
LP_J_geneName = na.omit(mcols(LP_J)[,c("gene_id","Name")]) #get gene symbloes for respective gene id 



NOD_ShiLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NOD_ShiLtJ_v3.2.gff3") #import gff3 file 
NOD_ShiLtJ_geneName = na.omit(mcols(NOD_ShiLtJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

NZO_HlLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NZO_HlLtJ_v3.2.gff3") #import gff3 file 
NZO_HlLtJ_geneName = na.omit(mcols(NZO_HlLtJ)[,c("gene_id","Name")]) #get gene symbloes for respective gene id 



PWK_PhJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/PWK_PhJ_v3.2.gff3") #import gff3 file 
PWK_PhJ_geneName = na.omit(mcols(PWK_PhJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

SPRET_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/SPRET_EiJ_v3.2.gff3") #import gff3 file 
SPRET_EiJ_geneName = na.omit(mcols(SPRET_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 


WSB_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/WSB_EiJ_v3.2.gff3") #import gff3 file 
WSB_EiJ_geneName = na.omit(mcols(WSB_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id

In [10]:
colnames(LP_J_geneName)[which(names(LP_J_geneName) == "Name")] <- "parent_gene_display_xref" #change columns name
colnames(NZO_HlLtJ_geneName)[which(names(NZO_HlLtJ_geneName) == "Name")] <- "parent_gene_display_xref" # change column name

In [11]:

geneName <- do.call("rbind", list(A129S1_SvImJ_geneName, A_J_geneName, AKR_J_geneName, BALB_cJ_geneName, C3H_HeJ_geneName, C57BL_6NJ_geneName, CAST_EiJ_geneName, CBA_J_geneName, DBA_2J_geneName , FVB_NJ_geneName,  LP_J_geneName, NOD_ShiLtJ_geneName ,    NZO_HlLtJ_geneName, PWK_PhJ_geneName, SPRET_EiJ_geneName,WSB_EiJ_geneName ))
geneName

DataFrame with 780454 rows and 2 columns
                  gene_id parent_gene_display_xref
              <character>              <character>
1      ENSMUSG00200053149                   Ugt1a1
2      ENSMUSG00200053174                  Gm20528
3      ENSMUSG00200032800            4933401J01Rik
4      ENSMUSG00200032799                  Gm26206
5      ENSMUSG00200032797                     Xkr4
...                   ...                      ...
780450 ENSMUSG00010031589                 BC022960
780451 ENSMUSG00010023776                  Gm15245
780452 ENSMUSG00010023781                     Mid1
780453 ENSMUSG00010023777                  Gm25651
780454 ENSMUSG00010023774            4933400A11Rik

In [12]:
rownames(geneName) <- geneName$gene_id
geneName$gene_id <- NULL
geneName

DataFrame with 780454 rows and 1 column
                   parent_gene_display_xref
                                <character>
ENSMUSG00200053149                   Ugt1a1
ENSMUSG00200053174                  Gm20528
ENSMUSG00200032800            4933401J01Rik
ENSMUSG00200032799                  Gm26206
ENSMUSG00200032797                     Xkr4
...                                     ...
ENSMUSG00010031589                 BC022960
ENSMUSG00010023776                  Gm15245
ENSMUSG00010023781                     Mid1
ENSMUSG00010023777                  Gm25651
ENSMUSG00010023774            4933400A11Rik

In [13]:
library(dplyr)
rawdata$counts <- merge(x=raw$counts, y=geneName, by = 0,all.x=TRUE ) #left merge

In [14]:
rawdata

An object of class "DGEList"
$samples
                                                                                                                                             files
C57BL_6NJ-16.5dpc.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
C57BL_6NJ-16.5dpc.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
C57BL_6NJ-16.5dpc.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
C57BL_6NJ-12.5dpp.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
C57BL_6NJ-12.5dpp.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
                              group lib.size norm.factors
C57BL_6NJ-16.5dpc.1 C57BL_6NJ-E16.5 31878714            1
C57BL_6NJ-16.5dpc.2 C57BL_6NJ-E16.5 31993372            1
C57BL_6NJ-16.5dpc.3 C57BL_6NJ-E16.5 32262165            1
C57BL_6NJ-12.5dpp.1 C57BL_6NJ-P12.5 30879948            1
C57BL_6NJ-12.5dpp.2 C57BL_6NJ-P12.5 35864325            1
139 more rows ...

$counts
           Row.names C57BL_6NJ-16.5dpc.1 C57BL_6NJ-16.5dpc.2
1 ENSMSPG00010000002                   0                   0
2 ENSMSPG00010000009                   0                   0
3 ENSMSPG00010000011                   0                   0
4 ENSMSPG00010000021                   0                   0
5 ENSMSPG00010000029                   0                   0
  C57BL_6NJ-16.5dpc.3 C57BL_6NJ-12.5dpp.1 C57BL_6NJ-12.5dpp.2
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  C57BL_6NJ-12.5dpp.3 C57BL_6NJ-20.5dpp.1 C57BL_6NJ-20.5dpp.2
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  C57BL_6NJ-20.5dpp.3 BALB_cJ-16.5dpc.1 BALB_cJ-16.5dpc.2 BALB_cJ-16.5dpc.3
1                   0                 0                 0                 0
2                   0                 0                 0                 0
3                   0                 0                 0                 0
4                   0                 0                 0                 0
5                   0                 0                 0                 0
  BALB_cJ-12.5dpp.1 BALB_cJ-12.5dpp.2 BALB_cJ-12.5dp.3 BALB_cJ-20.5dpp.1
1                 0                 0                0                 0
2                 0                 0                0                 0
3                 0                 0                0                 0
4                 0                 0                0                 0
5                 0                 0                0                 0
  BALB_cJ-20.5dp.2 BALB_cJ-20.5dpp.3 A_J-16.5dpc.1 A_J-16.5dpc.2 A_J-16.5dpc.3
1                0                 0             0             0             0
2                0                 0             0             0             0
3                0                 0             0             0             0
4                0                 0             0             0             0
5                0                 0             0             0             0
  A_J-12.5dpp.1 A_J-12.5dpp.2 A_J-12.5dpp.3 A_J-20.5dpp.1 A_J-20.5dpp.2
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0
5             0             0             0             0             0
  A_J-20.5dpp.3 FVB_NJ-16.5dpc.1 FVB_NJ-16.5dpc.2 FVB_NJ-16.5dpc.3
1             0                0                0                0
2             0                0                0                0
3             0                0                0                0
4             0                0                0                0
5             0                0                0                0
  FVB_NJ-12.5dpp.1 FVB_NJ-12.5dpp.2 FVB_NJ-12.5dpp.3 FVB_NJ-20.5dpp.1
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                0                0
5                0                0                0                0
  FVB_NJ-20.5dpp.2 FVB_NJ-20.5dpp.3 C3H_HeJ-16.5dpc.1 C3H_HeJ-16.5dpc.2
1                0                0                 0                 0
2                0                0                 0                 0
3                0                0                 0                 0
4                0                0                 0                 0
5                0                0                 0                 0
  C3H_HeJ-16.5dpc.3 C3H_HeJ-12.5dpp.1 C3H_HeJ-12.5dp.2 C3H_HeJ-12.5dpp.3
1                 0                 0                0                 0
2                 0                 0                0                 0
3                 0                 0                0                 0
4                 0                 0                0                 0
5                 0                 0                0                 0
  C3H_HeJ-20.5dpp.1 C3H_HeJ-20.5dp.2 C3H_HeJ-20.5dpp.3 LP_J-16.5dpc.1
1                 0                0                 0              0
2                 0                0                 0              0
3                 0                0                 0              0
4                 0                0                 0              0
5                 0                0                 0              0
  LP_J-16.5dpc.2 LP_J-16.5dpc.3 LP_J-12.5dpp.1 LP_J-12.5dpp.2 LP_J-12.5dpp.3
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0
5              0              0              0              0              0
  LP_J-20.5dpp.1 LP_J-20.5dpp.2 LP_J-20.5dpp.3 129S1_SvImJ-16.5dp.1
1              0              0              0                    0
2              0              0              0                    0
3              0              0              0                    0
4              0              0              0                    0
5              0              0              0                    0
  129S1_SvImJ-16.5dpc.2 129S1_SvImJ-16.5dpc.3 129S1_SvImJ-12.5dpp.1
1                     0                     0                     0
2                     0                     0                     0
3                     0                     0                     0
4                     0                     0                     0
5                     0                     0                     0
  129S1_SvImJ-12.5dpp.2 129S1_SvImJ-12.5dpp.3 129S1_SvImJ-20.5dpp.1
1                     0                     0                     0
2                     0                     0                     0
3                     0                     0                     0
4                     0                     0                     0
5                     0                     0                     0
  129S1_SvImJ-20.5dp.2 129S1_SvImJ-20.5dpp.3 DBA_2J-16.5dpc.1 DBA_2J-16.5dpc.2
1                    0                     0                0                0
2                    0                     0                0                0
3                    0                     0                0                0
4                    0                     0                0                0
5                    0                     0                0                0
  DBA_2J-16.5dpc.3 DBA_2J-12.5dpp.1 DBA_2J-12.5dpp.2 DBA_2J-12.5dpp.3
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                0                0
5                0                0                0                0
  DBA_2J-20.5dpp.1 DBA_2J-20.5dpp.2 DBA_2J-20.5dpp.3 AKR_J-16.5dpc.1
1                0                0                0               0
2                0                0                0               0
3                0                0                0               0
4                0                0                0               0
5                0                0                0               0
  AKR_J-16.5dpc.2 AKR_J-16.5dpc.3 AKR_J-12.5dpp.1 AKR_J-12.5dpp.2
1               0               0               0               0
2               0               0               0               0
3               0               0               0               0
4               0               0               0               0
5               0               0               0               0
  AKR_J-12.5dpp.3 AKR_J-20.5dpp.1 AKR_J-20.5dpp.2 AKR_J-20.5dpp.3
1               0               0               0               0
2               0               0               0               0
3               0               0               0               0
4               0               0               0               0
5               0               0               0               0
  CBA_J-16.5dpc.1 CBA_J-16.5dp.2 CBA_J-16.5dpc.3 CBA_J-12.5dpp.1
1               0              0               0               0
2               0              0               0               0
3               0              0               0               0
4               0              0               0               0
5               0              0               0               0
  CBA_J-12.5dpp.2 CBA_J-12.5dpp.3 CBA_J-20.5dpp.1 CBA_J-20.5dpp.2
1               0               0               0               0
2               0               0               0               0
3               0               0               0               0
4               0               0               0               0
5               0               0               0               0
  CBA_J-20.5dpp.3 NZO_HlLtJ-16.5dpc.1 NZO_HlLtJ-16.5dpc.2 NZO_HlLtJ-16.5dpc.3
1               0                   0                   0                   0
2               0                   0                   0                   0
3               0                   0                   0                   0
4               0                   0                   0                   0
5               0                   0                   0                   0
  NZO_HlLtJ-12.5dpp.1 NZO_HlLtJ-12.5dpp.2 NZO_HlLtJ-12.5dpp.3
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  NZO_HlLtJ-20.5dpp.1 NZO_HlLtJ-20.5dpp.2 NZO_HlLtJ-20.5dpp.3
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  NOD_ShiLtJ-16.5dpc.1 NOD_ShiLtJ-16.5dpc.2 NOD_ShiLtJ-16.5dpc.3
1                    0                    0                    0
2                    0                    0                    0
3                    0                    0                    0
4                    0                    0                    0
5                    0                    0                    0
  NOD_ShiLtJ-12.5dpp.1 NOD_ShiLtJ-12.5dpp.2 NOD_ShiLtJ-12.5dpp.3
1                    0                    0                    0
2                    0                    0                    0
3                    0                    0                    0
4                    0                    0                    0
5                    0                    0                    0
  NOD_ShiLtJ-20.5dpp.1 NOD_ShiLtJ-20.5dpp.2 NOD_ShiLtJ-20.5dpp.3
1                    0                    0                    0
2                    0                    0                    0
3                    0                    0                    0
4                    0                    0                    0
5                    0                    0                    0
  WSB_EiJ-16.5dpc.1 WSB_EiJ-16.5dpc.2 WSB_EiJ-16.5dpc.3 WSB_EiJ-12.5dpp.1
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0
5                 0                 0                 0                 0
  WSB_EiJ-12.5dpp.2 WSB_EiJ-12.5dpp.3 WSB_EiJ-20.5dpp.1 WSB_EiJ-20.5dpp.2
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0
5                 0                 0                 0                 0
  WSB_EiJ-20.5dpp.3 CAST_EiJ-16.5dpc.1 CAST_EiJ-16.5dpc.2 CAST_EiJ-16.5dpc.3
1                 0                  0                  0                  0
2                 0                  0                  0                  0
3                 0                  0                  0                  0
4                 0                  0                  0                  0
5                 0                  0                  0                  0
  CAST_EiJ-12.5dpp.1 CAST_EiJ-12.5dpp.2 CAST_EiJ-12.5dpp.3 CAST_EiJ-20.5dpp.1
1                  0                  0                  0                  0
2                  0                  0                  0                  0
3                  0                  0                  0                  0
4                  0                  0                  0                  0
5                  0                  0                  0                  0
  CAST_EiJ-20.5dpp.2 CAST_EiJ-20.5dpp.3 PWK_PhJ-16.5dpc.1 PWK_PhJ-16.5dpc.2
1                  0                  0              0.00              0.00
2                  0                  0              0.00              0.00
3                  0                  0              0.00              1.00
4                  0                  0            225.83            251.68
5                  0                  0              0.00              0.00
  PWK_PhJ-16.5dpc.3 PWK_PhJ-12.5dpp.1 PWK_PhJ-12.5dpp.2 PWK_PhJ-12.5dpp.3
1              0.00              0.00              0.00              0.00
2              0.00              0.00              0.00              0.00
3              0.00             11.50              0.50              0.50
4            253.94            166.83            144.83            119.33
5              0.00              0.00              0.00              0.00
  PWK_PhJ-20.5dpp.1 PWK_PhJ-20.5dp.2 PWK_PhJ-20.5dpp.3 SPRET_EiJ-16.5dpc.1
1              0.00             0.00               0.0                   0
2              0.00             0.00               0.0                   0
3              2.00             6.00               5.5                   0
4            135.83            92.67              71.0                   0
5              0.00             0.00               0.0                   0
  SPRET_EiJ-16.5dpc.2 SPRET_EiJ-16.5dpc.3 SPRET_EiJ-12.5dpp.1
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  SPRET_EiJ-12.5dpp.2 SPRET_EiJ-12.5dpp.3 SPRET_EiJ-20.5dpp.1
1                   0                   0                   0
2                   0                   0                   0
3                   0                   0                   0
4                   0                   0                   0
5                   0                   0                   0
  SPRET_EiJ-20.5dpp.2 SPRET_EiJ-20.5dpp,3 parent_gene_display_xref
1                   0                   0                     <NA>
2                   0                   0                     <NA>
3                   0                   0                     <NA>
4                   0                   0                  Gm37340
5                   0                   0                     <NA>
369026 more rows ...

In [15]:
rawdata_copy <- rawdata
rawdata_copy$counts['Row.names'] <- NULL #remove the columns name Row.names

In [16]:
rawdata_copy$counts <- rawdata_copy$counts[!is.na(rawdata_copy$counts$parent_gene_display_xref),] #remove NA 
rawdata_copy$counts

       C57BL_6NJ-16.5dpc.1 C57BL_6NJ-16.5dpc.2 C57BL_6NJ-16.5dpc.3
4      0                   0                   0
10     0                   0                   0
11     0                   0                   0
12     0                   0                   0
13     0                   0                   0
14     0                   0                   0
15     0                   0                   0
16     0                   0                   0
17     0                   0                   0
18     0                   0                   0
19     0                   0                   0
20     0                   0                   0
21     0                   0                   0
22     0                   0                   0
23     0                   0                   0
24     0                   0                   0
25     0                   0                   0
26     0                   0                   0
27     0                   0                   0
28     0                   0                   0
29     0                   0                   0
30     0                   0                   0
31     0                   0                   0
32     0                   0                   0
33     0                   0                   0
34     0                   0                   0
35     0                   0                   0
36     0                   0                   0
37     0                   0                   0
38     0                   0                   0
⋮      ⋮                   ⋮                   ⋮
369002 0                   0                   0
369003 0                   0                   0
369004 0                   0                   0
369005 0                   0                   0
369006 0                   0                   0
369007 0                   0                   0
369008 0                   0                   0
369009 0                   0                   0
369010 0                   0                   0
369011 0                   0                   0
369012 0                   0                   0
369013 0                   0                   0
369014 0                   0                   0
369015 0                   0                   0
369016 0                   0                   0
369017 0                   0                   0
369018 0                   0                   0
369019 0                   0                   0
369020 0                   0                   0
369021 0                   0                   0
369022 0                   0                   0
369023 0                   0                   0
369024 0                   0                   0
369025 0                   0                   0
369026 0                   0                   0
369027 0                   0                   0
369028 0                   0                   0
369029 0                   0                   0
369030 0                   0                   0
369031 0                   0                   0
       C57BL_6NJ-12.5dpp.1 C57BL_6NJ-12.5dpp.2 C57BL_6NJ-12.5dpp.3
4      0                   0                   0
10     0                   0                   0
11     0                   0                   0
12     0                   0                   0
13     0                   0                   0
14     0                   0                   0
15     0                   0                   0
16     0                   0                   0
17     0                   0                   0
18     0                   0                   0
19     0                   0                   0
20     0                   0                   0
21     0                   0                   0
22     0                   0                   0
23     0                   0                   0
24     0                   0                   0
25     0                   0                   0
26     0                   0                   0
27     0                   0                   0
28     0                   0                   0
29     0                   0                   0
30     0                   0                   0
31     0                   0                   0
32     0                   0                   0
33     0                   0                   0
34     0                   0                   0
35     0                   0                   0
36     0                   0                   0
37     0                   0                   0
38     0                   0                   0
⋮      ⋮                   ⋮                   ⋮
369002 0                   0                   0
369003 0                   0                   0
369004 0                   0                   0
369005 0                   0                   0
369006 0                   0                   0
369007 0                   0                   0
369008 0                   0                   0
369009 0                   0                   0
369010 0                   0                   0
369011 0                   0                   0
369012 0                   0                   0
369013 0                   0                   0
369014 0                   0                   0
369015 0                   0                   0
369016 0                   0                   0
369017 0                   0                   0
369018 0                   0                   0
369019 0                   0                   0
369020 0                   0                   0
369021 0                   0                   0
369022 0                   0                   0
369023 0                   0                   0
369024 0                   0                   0
369025 0                   0                   0
369026 0                   0                   0
369027 0                   0                   0
369028 0                   0                   0
369029 0                   0                   0
369030 0                   0                   0
369031 0                   0                   0
       C57BL_6NJ-20.5dpp.1 C57BL_6NJ-20.5dpp.2 C57BL_6NJ-20.5dpp.3
4      0                   0                   0
10     0                   0                   0
11     0                   0                   0
12     0                   0                   0
13     0                   0                   0
14     0                   0                   0
15     0                   0                   0
16     0                   0                   0
17     0                   0                   0
18     0                   0                   0
19     0                   0                   0
20     0                   0                   0
21     0                   0                   0
22     0                   0                   0
23     0                   0                   0
24     0                   0                   0
25     0                   0                   0
26     0                   0                   0
27     0                   0                   0
28     0                   0                   0
29     0                   0                   0
30     0                   0                   0
31     0                   0                   0
32     0                   0                   0
33     0                   0                   0
34     0                   0                   0
35     0                   0                   0
36     0                   0                   0
37     0                   0                   0
38     0                   0                   0
⋮      ⋮                   ⋮                   ⋮
369002 0                   0                   0
369003 0                   0                   0
369004 0                   0                   0
369005 0                   0                   0
369006 0                   0                   0
369007 0                   0                   0
369008 0                   0                   0
369009 0                   0                   0
369010 0                   0                   0
369011 0                   0                   0
369012 0                   0                   0
369013 0                   0                   0
369014 0                   0                   0
369015 0                   0                   0
369016 0                   0                   0
369017 0                   0                   0
369018 0                   0                   0
369019 0                   0                   0
369020 0                   0                   0
369021 0                   0                   0
369022 0                   0                   0
369023 0                   0                   0
369024 0                   0                   0
369025 0                   0                   0
369026 0                   0                   0
369027 0                   0                   0
369028 0                   0                   0
369029 0                   0                   0
369030 0                   0                   0
369031 0                   0                   0
       BALB_cJ-16.5dpc.1 ⋯ SPRET_EiJ-16.5dpc.1 SPRET_EiJ-16.5dpc.2
4      0                 ⋯ 0                   0
10     0                 ⋯ 0                   0
11     0                 ⋯ 0                   0
12     0                 ⋯ 0                   0
13     0                 ⋯ 0                   0
14     0                 ⋯ 0                   0
15     0                 ⋯ 0                   0
16     0                 ⋯ 0                   0
17     0                 ⋯ 0                   0
18     0                 ⋯ 0                   0
19     0                 ⋯ 0                   0
20     0                 ⋯ 0                   0
21     0                 ⋯ 0                   0
22     0                 ⋯ 0                   0
23     0                 ⋯ 0                   0
24     0                 ⋯ 0                   0
25     0                 ⋯ 0                   0
26     0                 ⋯ 0                   0
27     0                 ⋯ 0                   0
28     0                 ⋯ 0                   0
29     0                 ⋯ 0                   0
30     0                 ⋯ 0                   0
31     0                 ⋯ 0                   0
32     0                 ⋯ 0                   0
33     0                 ⋯ 0                   0
34     0                 ⋯ 0                   0
35     0                 ⋯ 0                   0
36     0                 ⋯ 0                   0
37     0                 ⋯ 0                   0
38     0                 ⋯ 0                   0
⋮      ⋮                 ⋱ ⋮                   ⋮
369002 0                 ⋯ 0                   0
369003 0                 ⋯ 0                   0
369004 0                 ⋯ 0                   0
369005 0                 ⋯ 0                   0
369006 0                 ⋯ 0                   0
369007 0                 ⋯ 0                   0
369008 0                 ⋯ 0                   0
369009 0                 ⋯ 0                   0
369010 0                 ⋯ 0                   0
369011 0                 ⋯ 0                   0
369012 0                 ⋯ 0                   0
369013 0                 ⋯ 0                   0
369014 0                 ⋯ 0                   0
369015 0                 ⋯ 0                   0
369016 0                 ⋯ 0                   0
369017 0                 ⋯ 0                   0
369018 0                 ⋯ 0                   0
369019 0                 ⋯ 0                   0
369020 0                 ⋯ 0                   0
369021 0                 ⋯ 0                   0
369022 0                 ⋯ 0                   0
369023 0                 ⋯ 0                   0
369024 0                 ⋯ 0                   0
369025 0                 ⋯ 0                   0
369026 0                 ⋯ 0                   0
369027 0                 ⋯ 0                   0
369028 0                 ⋯ 0                   0
369029 0                 ⋯ 0                   0
369030 0                 ⋯ 0                   0
369031 0                 ⋯ 0                   0
       SPRET_EiJ-16.5dpc.3 SPRET_EiJ-12.5dpp.1 SPRET_EiJ-12.5dpp.2
4      0                   0                   0
10     0                   0                   0
11     0                   0                   0
12     0                   0                   0
13     0                   0                   0
14     0                   0                   0
15     0                   0                   0
16     0                   0                   0
17     0                   0                   0
18     0                   0                   0
19     0                   0                   0
20     0                   0                   0
21     0                   0                   0
22     0                   0                   0
23     0                   0                   0
24     0                   0                   0
25     0                   0                   0
26     0                   0                   0
27     0                   0                   0
28     0                   0                   0
29     0                   0                   0
30     0                   0                   0
31     0                   0                   0
32     0                   0                   0
33     0                   0                   0
34     0                   0                   0
35     0                   0                   0
36     0                   0                   0
37     0                   0                   0
38     0                   0                   0
⋮      ⋮                   ⋮                   ⋮
369002 0                   0                   0
369003 0                   0                   0
369004 0                   0                   0
369005 0                   0                   0
369006 0                   0                   0
369007 0                   0                   0
369008 0                   0                   0
369009 0                   0                   0
369010 0                   0                   0
369011 0                   0                   0
369012 0                   0                   0
369013 0                   0                   0
369014 0                   0                   0
369015 0                   0                   0
369016 0                   0                   0
369017 0                   0                   0
369018 0                   0                   0
369019 0                   0                   0
369020 0                   0                   0
369021 0                   0                   0
369022 0                   0                   0
369023 0                   0                   0
369024 0                   0                   0
369025 0                   0                   0
369026 0                   0                   0
369027 0                   0                   0
369028 0                   0                   0
369029 0                   0                   0
369030 0                   0                   0
369031 0                   0                   0
       SPRET_EiJ-12.5dpp.3 SPRET_EiJ-20.5dpp.1 SPRET_EiJ-20.5dpp.2
4      0                   0                   0
10     0                   0                   0
11     0                   0                   0
12     0                   0                   0
13     0                   0                   0
14     0                   0                   0
15     0                   0                   0
16     0                   0                   0
17     0                   0                   0
18     0                   0                   0
19     0                   0                   0
20     0                   0                   0
21     0                   0                   0
22     0                   0                   0
23     0                   0                   0
24     0                   0                   0
25     0                   0                   0
26     0                   0                   0
27     0                   0                   0
28     0                   0                   0
29     0                   0                   0
30     0                   0                   0
31     0                   0                   0
32     0                   0                   0
33     0                   0                   0
34     0                   0                   0
35     0                   0                   0
36     0                   0                   0
37     0                   0                   0
38     0                   0                   0
⋮      ⋮                   ⋮                   ⋮
369002 0                   0                   0
369003 0                   0                   0
369004 0                   0                   0
369005 0                   0                   0
369006 0                   0                   0
369007 0                   0                   0
369008 0                   0                   0
369009 0                   0                   0
369010 0                   0                   0
369011 0                   0                   0
369012 0                   0                   0
369013 0                   0                   0
369014 0                   0                   0
369015 0                   0                   0
369016 0                   0                   0
369017 0                   0                   0
369018 0                   0                   0
369019 0                   0                   0
369020 0                   0                   0
369021 0                   0                   0
369022 0                   0                   0
369023 0                   0                   0
369024 0                   0                   0
369025 0                   0                   0
369026 0                   0                   0
369027 0                   0                   0
369028 0                   0                   0
369029 0                   0                   0
369030 0                   0                   0
369031 0                   0                   0
       SPRET_EiJ-20.5dpp,3 parent_gene_display_xref
4      0                   Gm37340
10     0                   Ptf1a
11     0                   Msrb2
12     0                   4921504E06Rik
13     0                   Upf2
14     0                   Proser2
15     0                   Dhtkd1
16     0                   Echdc3
17     0                   C1ql3
18     0                   Pter
19     0                   Gm37811
20     0                   Gm37824
21     0                   Gm37255
22     0                   Gm38014
23     0                   Fam107b
24     0                   Cdnf
25     0                   Brd3
26     0                   Lcn4
27     0                   Abo
28     0                   Rxra
29     0                   Rpl7a
30     0                   Surf6
31     0                   Wdr5
32     0                   Med22
33     0                   Ajm1
34     0                   Phpt1
35     0                   Mamdc4
36     0                   Edf1
37     0                   Rabl6
38     0                   Kin
⋮      ⋮                   ⋮
369002 0                   Ace2
369003 0                   Bmx
369004 0                   Pir
369005 0                   Vegfd
369006 0                   Piga
369007 0                   Asb11
369008 0                   Asb9
369009 0                   Mospd2
369010 0                   Fancb
369011 0                   Gm17604
369012 0                   Glra2
369013 0                   Gemin8
369014 0                   Gpm6b
369015 0                   Ofd1
369016 0                   Trappc2
369017 0                   Rab9
369018 0                   Tceanc

In [17]:

rawdata_copy$counts <- rawdata_copy$counts %>% 
  group_by(parent_gene_display_xref) %>% 
  summarise(across(everything(), sum))

In [18]:
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                             files
C57BL_6NJ-16.5dpc.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
C57BL_6NJ-16.5dpc.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
C57BL_6NJ-16.5dpc.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
C57BL_6NJ-12.5dpp.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
C57BL_6NJ-12.5dpp.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
                              group lib.size norm.factors
C57BL_6NJ-16.5dpc.1 C57BL_6NJ-E16.5 31878714            1
C57BL_6NJ-16.5dpc.2 C57BL_6NJ-E16.5 31993372            1
C57BL_6NJ-16.5dpc.3 C57BL_6NJ-E16.5 32262165            1
C57BL_6NJ-12.5dpp.1 C57BL_6NJ-P12.5 30879948            1
C57BL_6NJ-12.5dpp.2 C57BL_6NJ-P12.5 35864325            1
139 more rows ...

$counts
# A tibble: 5 × 145
  parent_gene_display_xref `C57BL_6NJ-16.5dpc.1` `C57BL_6NJ-16.5dpc.2`
  <chr>                                    <dbl>                 <dbl>
1 0610006L08Rik                                0                     0
2 0610007P14Rik                                0                     0
3 0610009B22Rik                              395                   390
4 0610009E02Rik                                0                     0
5 0610009L18Rik                                0                     0
# ℹ 142 more variables: `C57BL_6NJ-16.5dpc.3` <dbl>,
#   `C57BL_6NJ-12.5dpp.1` <dbl>, `C57BL_6NJ-12.5dpp.2` <dbl>,
#   `C57BL_6NJ-12.5dpp.3` <dbl>, `C57BL_6NJ-20.5dpp.1` <dbl>,
#   `C57BL_6NJ-20.5dpp.2` <dbl>, `C57BL_6NJ-20.5dpp.3` <dbl>,
#   `BALB_cJ-16.5dpc.1` <dbl>, `BALB_cJ-16.5dpc.2` <dbl>,
#   `BALB_cJ-16.5dpc.3` <dbl>, `BALB_cJ-12.5dpp.1` <dbl>,
#   `BALB_cJ-12.5dpp.2` <dbl>, `BALB_cJ-12.5dp.3` <dbl>, …
43883 more rows ...

In [19]:


rawdata_copy$counts <- as.data.frame(rawdata_copy$counts[!duplicated(rawdata_copy$counts$parent_gene_display_xref), ])  #remove dulicate values

In [20]:
rownames(rawdata_copy$counts) <- rawdata_copy$counts$parent_gene_display_xref #set rawname to gene symbloes

In [21]:
rawdata_copy$counts$parent_gene_display_xref <- NULL #remove genesybloe columns

In [22]:
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                             files
C57BL_6NJ-16.5dpc.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
C57BL_6NJ-16.5dpc.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
C57BL_6NJ-16.5dpc.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
C57BL_6NJ-12.5dpp.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
C57BL_6NJ-12.5dpp.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
                              group lib.size norm.factors
C57BL_6NJ-16.5dpc.1 C57BL_6NJ-E16.5 31878714            1
C57BL_6NJ-16.5dpc.2 C57BL_6NJ-E16.5 31993372            1
C57BL_6NJ-16.5dpc.3 C57BL_6NJ-E16.5 32262165            1
C57BL_6NJ-12.5dpp.1 C57BL_6NJ-P12.5 30879948            1
C57BL_6NJ-12.5dpp.2 C57BL_6NJ-P12.5 35864325            1
139 more rows ...

$counts
              C57BL_6NJ-16.5dpc.1 C57BL_6NJ-16.5dpc.2 C57BL_6NJ-16.5dpc.3
0610006L08Rik                   0                   0                   0
0610007P14Rik                   0                   0                   0
0610009B22Rik                 395                 390                 408
0610009E02Rik                   0                   0                   0
0610009L18Rik                   0                   0                   0
              C57BL_6NJ-12.5dpp.1 C57BL_6NJ-12.5dpp.2 C57BL_6NJ-12.5dpp.3
0610006L08Rik                0.00                   0                0.00
0610007P14Rik                0.00                   0                0.00
0610009B22Rik              467.25                 547              460.25
0610009E02Rik                0.00                   0                0.00
0610009L18Rik                0.00                   0                0.00
              C57BL_6NJ-20.5dpp.1 C57BL_6NJ-20.5dpp.2 C57BL_6NJ-20.5dpp.3
0610006L08Rik                   0                   0                   0
0610007P14Rik                   0                   0                   0
0610009B22Rik                 918                1021                 710
0610009E02Rik                   0                   0                   0
0610009L18Rik                   0                   0                   0
              BALB_cJ-16.5dpc.1 BALB_cJ-16.5dpc.2 BALB_cJ-16.5dpc.3
0610006L08Rik                 0                 0                 0
0610007P14Rik                 0                 0                 0
0610009B22Rik               362               439               430
0610009E02Rik                 0                 0                 0
0610009L18Rik                 0                 0                 0
              BALB_cJ-12.5dpp.1 BALB_cJ-12.5dpp.2 BALB_cJ-12.5dp.3
0610006L08Rik                 0                 0                0
0610007P14Rik                 0                 0                0
0610009B22Rik               504               473              440
0610009E02Rik                 0                 0                0
0610009L18Rik                 0                 0                0
              BALB_cJ-20.5dpp.1 BALB_cJ-20.5dp.2 BALB_cJ-20.5dpp.3
0610006L08Rik                 0                0                 0
0610007P14Rik                 0                0                 0
0610009B22Rik               809              660               630
0610009E02Rik                 0                0                 0
0610009L18Rik                 0                0                 0
              A_J-16.5dpc.1 A_J-16.5dpc.2 A_J-16.5dpc.3 A_J-12.5dpp.1
0610006L08Rik             0             0             0             0
0610007P14Rik             0             0             0             0
0610009B22Rik           471           464           394           457
0610009E02Rik             0             0             0             0
0610009L18Rik             0             0             0             0
              A_J-12.5dpp.2 A_J-12.5dpp.3 A_J-20.5dpp.1 A_J-20.5dpp.2
0610006L08Rik             0             0             0             0
0610007P14Rik             0             0             0             0
0610009B22Rik           539           512           879           872
0610009E02Rik             0             0             0             0
0610009L18Rik             0             0             0             0
              A_J-20.5dpp.3 FVB_NJ-16.5dpc.1 FVB_NJ-16.5dpc.2 FVB_NJ-16.5dpc.3
0610006L08Rik           0.0                0                0             0.00
0610007P14Rik           0.0                0                0             0.00
0610009B22Rik         785.5              327              369           436.17
0610009E02Rik           0.0                0                0             0.00
0610009L18Rik           0.0                0                0             0.00
              FVB_NJ-12.5dpp.1 FVB_NJ-12.5dpp.2 FVB_NJ-12.5dpp.3
0610006L08Rik                0                0                0
0610007P14Rik                0                0                0
0610009B22Rik              472              459              539
0610009E02Rik                0                0                0
0610009L18Rik                0                0                0
              FVB_NJ-20.5dpp.1 FVB_NJ-20.5dpp.2 FVB_NJ-20.5dpp.3
0610006L08Rik                0                0                0
0610007P14Rik                0                0                0
0610009B22Rik              599              530              724
0610009E02Rik                0                0                0
0610009L18Rik                0                0                0
              C3H_HeJ-16.5dpc.1 C3H_HeJ-16.5dpc.2 C3H_HeJ-16.5dpc.3
0610006L08Rik                 0                 0                 0
0610007P14Rik                 0                 0                 0
0610009B22Rik               397               343               393
0610009E02Rik                 0                 0                 0
0610009L18Rik                 0                 0                 0
              C3H_HeJ-12.5dpp.1 C3H_HeJ-12.5dp.2 C3H_HeJ-12.5dpp.3
0610006L08Rik                 0                0                 0
0610007P14Rik                 0                0                 0
0610009B22Rik               514              532               503
0610009E02Rik                 0                0                 0
0610009L18Rik                 0                0                 0
              C3H_HeJ-20.5dpp.1 C3H_HeJ-20.5dp.2 C3H_HeJ-20.5dpp.3
0610006L08Rik                 0                0                 0
0610007P14Rik                 0                0                 0
0610009B22Rik               792              816               718
0610009E02Rik                 0                0                 0
0610009L18Rik                 0                0                 0
              LP_J-16.5dpc.1 LP_J-16.5dpc.2 LP_J-16.5dpc.3 LP_J-12.5dpp.1
0610006L08Rik              0              0              0              0
0610007P14Rik              0              0              0              0
0610009B22Rik            403            368            531            525
0610009E02Rik              0              0              0              0
0610009L18Rik              0              0              0              0
              LP_J-12.5dpp.2 LP_J-12.5dpp.3 LP_J-20.5dpp.1 LP_J-20.5dpp.2
0610006L08Rik              0              0              0              0
0610007P14Rik              0              0              0              0
0610009B22Rik            545            576            610            790
0610009E02Rik              0              0              0              0
0610009L18Rik              0              0              0              0
              LP_J-20.5dpp.3 129S1_SvImJ-16.5dp.1 129S1_SvImJ-16.5dpc.2
0610006L08Rik              0                    0                     0
0610007P14Rik              0                    0                     0
0610009B22Rik            812                  324                   331
0610009E02Rik              0                    0                     0
0610009L18Rik              0                    0                     0
              129S1_SvImJ-16.5dpc.3 129S1_SvImJ-12.5dpp.1 129S1_SvImJ-12.5dpp.2
0610006L08Rik                     0                     0                     0
0610007P14Rik                     0                     0                     0
0610009B22Rik                   317                   432                   516
0610009E02Rik                     0                     0                     0
0610009L18Rik                     0                     0                     0
              129S1_SvImJ-12.5dpp.3 129S1_SvImJ-20.5dpp.1 129S1_SvImJ-20.5dp.2
0610006L08Rik                     0                     0                    0
0610007P14Rik                     0                     0                    0
0610009B22Rik                   470                   530                  469
0610009E02Rik                     0                     0                    0
0610009L18Rik                     0                     0                    0
              129S1_SvImJ-20.5dpp.3 DBA_2J-16.5dpc.1 DBA_2J-16.5dpc.2
0610006L08Rik                     0                0                0
0610007P14Rik                     0                0                0
0610009B22Rik                   404              382              446
0610009E02Rik                     0                0                0
0610009L18Rik                     0                0                0
              DBA_2J-16.5dpc.3 DBA_2J-12.5dpp.1 DBA_2J-12.5dpp.2
0610006L08Rik                0                0              0.0
0610007P14Rik                0                0              0.0
0610009B22Rik              392              545            429.5
0610009E02Rik                0                0              0.0
0610009L18Rik                0                0              0.0
              DBA_2J-12.5dpp.3 DBA_2J-20.5dpp.1 DBA_2J-20.5dpp.2
0610006L08Rik                0                0                0
0610007P14Rik                0                0                0
0610009B22Rik              625              712              699
0610009E02Rik                0                0                0
0610009L18Rik                0                0                0
              DBA_2J-20.5dpp.3 AKR_J-16.5dpc.1 AKR_J-16.5dpc.2 AKR_J-16.5dpc.3
0610006L08Rik                0               0               0               0
0610007P14Rik                0               0               0               0
0610009B22Rik              615             454             357             396
0610009E02Rik                0               0               0               0
0610009L18Rik                0               0               0               0
              AKR_J-12.5dpp.1 AKR_J-12.5dpp.2 AKR_J-12.5dpp.3 AKR_J-20.5dpp.1
0610006L08Rik               0               0               0               0
0610007P14Rik               0               0               0               0
0610009B22Rik             446             379             423             724
0610009E02Rik               0               0               0               0
0610009L18Rik               0               0               0               0
              AKR_J-20.5dpp.2 AKR_J-20.5dpp.3 CBA_J-16.5dpc.1 CBA_J-16.5dp.2
0610006L08Rik               0               0               0              0
0610007P14Rik               0               0               0              0
0610009B22Rik             836             859             357            448
0610009E02Rik               0               0               0              0
0610009L18Rik               0               0               0              0
              CBA_J-16.5dpc.3 CBA_J-12.5dpp.1 CBA_J-12.5dpp.2 CBA_J-12.5dpp.3
0610006L08Rik               0               0               0               0
0610007P14Rik               0               0               0               0
0610009B22Rik             437             542             486             512
0610009E02Rik               0               0               0               0
0610009L18Rik               0               0               0               0
              CBA_J-20.5dpp.1 CBA_J-20.5dpp.2 CBA_J-20.5dpp.3
0610006L08Rik               0               0               0
0610007P14Rik               0               0               0
0610009B22Rik             690             701             623
0610009E02Rik               0               0               0
0610009L18Rik               0               0               0
              NZO_HlLtJ-16.5dpc.1 NZO_HlLtJ-16.5dpc.2 NZO_HlLtJ-16.5dpc.3
0610006L08Rik                0.00                 0.0                 0.0
0610007P14Rik             1111.50              1227.0              1188.5
0610009B22Rik              389.00               383.0               341.0
0610009E02Rik                0.00                 0.0                 0.0
0610009L18Rik              197.62               172.5               175.5
              NZO_HlLtJ-12.5dpp.1 NZO_HlLtJ-12.5dpp.2 NZO_HlLtJ-12.5dpp.3
0610006L08Rik                   0                0.00                 0.0
0610007P14Rik                1474             1334.00              1446.5
0610009B22Rik                 460              406.75               410.0
0610009E02Rik                   0                0.00                 0.0
0610009L18Rik                 139              146.17               155.0
              NZO_HlLtJ-20.5dpp.1 NZO_HlLtJ-20.5dpp.2 NZO_HlLtJ-20.5dpp.3
0610006L08Rik                   0                 0.0                 0.0
0610007P14Rik                 752               676.5               772.5
0610009B22Rik                 709               754.0               593.0
0610009E02Rik                   0                 0.0                 0.0
0610009L18Rik                 993              1116.5               692.5
              NOD_ShiLtJ-16.5dpc.1 NOD_ShiLtJ-16.5dpc.2 NOD_ShiLtJ-16.5dpc.3
0610006L08Rik                    0                    0                    0
0610007P14Rik                    0                    0                    0
0610009B22Rik                  297                  295                  466
0610009E02Rik                    0                    0                    0
0610009L18Rik                    0                    0                    0
              NOD_ShiLtJ-12.5dpp.1 NOD_ShiLtJ-12.5dpp.2 NOD_ShiLtJ-12.5dpp.3
0610006L08Rik                    0                    0                    0
0610007P14Rik                    0                    0                    0
0610009B22Rik                  435                  449                  419
0610009E02Rik                    0                    0                    0
0610009L18Rik                    0                    0                    0
              NOD_ShiLtJ-20.5dpp.1 NOD_ShiLtJ-20.5dpp.2 NOD_ShiLtJ-20.5dpp.3
0610006L08Rik                    0                    0                    0
0610007P14Rik                    0                    0                    0
0610009B22Rik                  553                  609                 1051
0610009E02Rik                    0                    0                    0
0610009L18Rik                    0                    0                    0
              WSB_EiJ-16.5dpc.1 WSB_EiJ-16.5dpc.2 WSB_EiJ-16.5dpc.3
0610006L08Rik              0.00               0.0              0.00
0610007P14Rik           1361.50            1343.5           1447.50
0610009B22Rik            562.50             533.0            642.00
0610009E02Rik              0.00               0.0              0.00
0610009L18Rik            183.75             172.5            181.67
              WSB_EiJ-12.5dpp.1 WSB_EiJ-12.5dpp.2 WSB_EiJ-12.5dpp.3
0610006L08Rik               0.0                 0              0.00
0610007P14Rik            1989.5               222           1984.00
0610009B22Rik             813.0                83            760.00
0610009E02Rik               0.0                 0              0.00
0610009L18Rik             135.0                14            102.25
              WSB_EiJ-20.5dpp.1 WSB_EiJ-20.5dpp.2 WSB_EiJ-20.5dpp.3
0610006L08Rik               0.0               0.0                 0
0610007P14Rik             973.5             982.5              1055
0610009B22Rik            1062.0            1072.0               924
0610009E02Rik               0.0               0.0                 0
0610009L18Rik             804.0             843.5               609
              CAST_EiJ-16.5dpc.1 CAST_EiJ-16.5dpc.2 CAST_EiJ-16.5dpc.3
0610006L08Rik                  0                  0                  0
0610007P14Rik                  0                  0                  0
0610009B22Rik                  4                 19                  7
0610009E02Rik                  0                  0                  0
0610009L18Rik                  0                  0                  0
              CAST_EiJ-12.5dpp.1 CAST_EiJ-12.5dpp.2 CAST_EiJ-12.5dpp.3
0610006L08Rik                  0                  0                  0
0610007P14Rik                  0                  0                  0
0610009B22Rik                  5                 10                  5
0610009E02Rik                  0                  0                  0
0610009L18Rik                  0                  0                  0
              CAST_EiJ-20.5dpp.1 CAST_EiJ-20.5dpp.2 CAST_EiJ-20.5dpp.3
0610006L08Rik                  0                  0                  0
0610007P14Rik                  0                  0                  0
0610009B22Rik                  4                  2                  1
0610009E02Rik                  0                  0                  0
0610009L18Rik                  0                  0                  0
              PWK_PhJ-16.5dpc.1 PWK_PhJ-16.5dpc.2 PWK_PhJ-16.5dpc.3
0610006L08Rik                 0                 0               0.0
0610007P14Rik                 0                 0               0.0
0610009B22Rik               392               538             542.5
0610009E02Rik                 0                 0               0.0
0610009L18Rik                 0                 0               0.0
              PWK_PhJ-12.5dpp.1 PWK_PhJ-12.5dpp.2 PWK_PhJ-12.5dpp.3
0610006L08Rik               0.0                 0                 0
0610007P14Rik               0.0                 0                 0
0610009B22Rik             716.5               552               586
0610009E02Rik               0.0                 0                 0
0610009L18Rik               0.0                 0                 0
              PWK_PhJ-20.5dpp.1 PWK_PhJ-20.5dp.2 PWK_PhJ-20.5dpp.3
0610006L08Rik                 0                0                 0
0610007P14Rik                 0                0                 0
0610009B22Rik               476              496               462
0610009E02Rik                 0                0                 0
0610009L18Rik                 0                0                 0
              SPRET_EiJ-16.5dpc.1 SPRET_EiJ-16.5dpc.2 SPRET_EiJ-16.5dpc.3
0610006L08Rik                57.5                  70                  80
0610007P14Rik                 0.0                   0                   0
0610009B22Rik                 0.0                   0                   0
0610009E02Rik               667.6                 738                 719
0610009L18Rik                 0.0                   0                   0
              SPRET_EiJ-12.5dpp.1 SPRET_EiJ-12.5dpp.2 SPRET_EiJ-12.5dpp.3
0610006L08Rik                  75                  57               67.42
0610007P14Rik                   0                   0                0.00

In [23]:
#DESeq and PCA and Dandogram 

#conda install -c bioconda bioconductor-deseq2 r-gplots r-rcolorbrewer r-ggplot2 r-tidyr r-ggrepel r-dplyr -y 
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘gplots’


The following object is masked from ‘package:rtracklayer’:

    space


The following object is masked from ‘package:IRanges’:

    space


The following object is masked from ‘package:S4Vectors’:

    space


The following object is masked from ‘package:stats’:

    lowess

In [24]:

#save results in this folder 
#mkdir -p  /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/AKR_J
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/all_timepoints")

In [25]:
# Make a color scheme for heatmaps
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)
# First we tell DESeq which samples correspond to which tissues.

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"

In [26]:
# Now we build a DESeq2 Count dataset and normalize it.
mircounts <- rawdata_copy$counts

cds <- DESeqDataSetFromMatrix(countData = round(mircounts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates, fitting model and testing: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [27]:
#rlog normalisations
rl=vst(cds)
pdf("all_timepoint_BarGraphBeforeAfter.pdf",paper="a4")
par(mfrow=c(2,1))

par(mar=c(10,4,0,2)) # increase y-axis margin.
prenorm=apply(mircounts,2,sum)
barplot(prenorm,col=as.factor(samplenames),las=2,names=samplenames,cex.names = 0.6 )
postnorm=apply(counts(cds,normalized=TRUE),2,sum)
barplot(postnorm,col=as.factor(samplenames),las=2,names=samplenames,cex.names = 0.6 )
dev.off()

png
  2

In [49]:

# Define the custom color assignments
custom_colors <- c(
  'C57BL_6NJ-E16.5' = 'blue',
  'C57BL_6NJ-P12.5' = 'green',
  'C57BL_6NJ-P20.5' = 'red',
  'BALB_cJ-E16.5' = 'purple',
  'BALB_cJ-P12.5' = 'orange',
  'BALB_cJ-P12.5' = 'cyan',
  'BALB_cJ-P20.5' = 'magenta',
  'BALB_cJ-P20.5' = 'yellow',
  'A_J-E16.5' = 'brown',
  'A_J-P12.5' = 'pink',
  'A_J-P20.5' = 'darkgray',
  'FVB_NJ-E16.5' = 'lightblue',
  'FVB_NJ-P12.5' = 'lightgreen',
  'FVB_NJ-P20.5' = 'lightred',
  'C3H_HeJ-E16.5' = 'darkpurple',
  'C3H_HeJ-P12.5' = 'darkorange',
  'C3H_HeJ-P12.5' = 'darkcyan',
  'C3H_HeJ-P20.5' = 'darkmagenta',
  'C3H_HeJ-P20.5' = 'darkyellow',
  'LP_J-E16.5' = 'darkbrown',
  'LP_J-P12.5' = 'darkpink',
  'LP_J-P20.5' = 'gray',
  '129S1_SvImJ-E16.5' = 'lightpurple',
  '129S1_SvImJ-E16.5' = 'lightorange',
  '129S1_SvImJ-P12.5' = 'lightcyan',
  '129S1_SvImJ-P20.5' = 'lightmagenta',
  '129S1_SvImJ-P20.5' = 'lightyellow',
  'DBA_2J-E16.5' = 'lightbrown',
  'DBA_2J-P12.5' = 'lightpink',
  'DBA_2J-P20.5' = 'darkgray',
  'AKR_J-E16.5' = 'lightblue',
  'AKR_J-P12.5' = 'lightgreen',
  'AKR_J-P20.5' = 'lightred',
  'CBA_J-E16.5' = 'darkpurple',
  'CBA_J-E16.5' = 'darkorange',
  'CBA_J-P12.5' = 'darkcyan',
  'CBA_J-P20.5' = 'darkmagenta',
  'NZO_HlLtJ-E16.5' = 'darkyellow',
  'NZO_HlLtJ-E16.5' = 'darkbrown',
  'NZO_HlLtJ-P12.5' = 'darkpink',
  'NZO_HlLtJ-P20.5' = 'gray',
  'NOD_ShiLtJ-E16.5' = 'lightpurple',
  'NOD_ShiLtJ-P12.5' = 'lightorange',
  'NOD_ShiLtJ-P20.5' = 'lightcyan',
  'WSB_EiJ-E16.5' = 'lightmagenta',
  'WSB_EiJ-P12.5' = 'lightyellow',
  'WSB_EiJ-P20.5' = 'lightbrown',
  'CAST_EiJ-E16.5' = 'lightpink',
  'CAST_EiJ-P12.5' = 'darkgray',
  'CAST_EiJ-P20.5' = 'lightblue',
  'PWK_PhJ-E16.5' = 'lightgreen',
  'PWK_PhJ-P12.5' = 'lightred',
  'PWK_PhJ-P20.5' = 'darkpurple',
  'SPRET_EiJ-E16.5' = 'darkorange',
  'SPRET_EiJ-P12.5' = 'darkcyan',
  'SPRET_EiJ-P20.5' = 'darkmagenta'
)

# Extract strain names
strain_names <- sub("-(E|P)[0-9\\.]+", "", names(custom_colors))

# Generate a unique set of strain names
unique_strain_names <- unique(strain_names)
unique_strain_names
# Define a set of bright colors from ggplot2 palette

bright_colors <-  c('#0000FF', '#008000', '#FF0000', '#800080', '#FFA500', '#00FFFF', '#FF00FF', '#FFFF00', '#A52A2A', '#FFC0CB', '#6B8E23', '#ADD8E6', '#90EE90', '#FFB6C1', '#E6E6FA', '#FFD700', '#E0FFFF', '#90EE90', '#FFFFE0')

# Create a color mapping for each unique strain name
color_mapping <- setNames(bright_colors, unique_strain_names)
color_mapping 
# Apply color mapping to the original custom_colors
reassigned_colors <- color_mapping[strain_names]

# Combine with the original labels to create the final color assignments
final_colors <- setNames(reassigned_colors, names(custom_colors))
final_colors

##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

 [1] "C57BL_6NJ"   "BALB_cJ"     "A_J"         "FVB_NJ"      "C3H_HeJ"
 [6] "LP_J"        "129S1_SvImJ" "DBA_2J"      "AKR_J"       "CBA_J"
[11] "NZO_HlLtJ"   "NOD_ShiLtJ"  "WSB_EiJ"     "CAST_EiJ"    "PWK_PhJ"
[16] "SPRET_EiJ"

  C57BL_6NJ     BALB_cJ         A_J      FVB_NJ     C3H_HeJ        LP_J
  "#0000FF"   "#008000"   "#FF0000"   "#800080"   "#FFA500"   "#00FFFF"
129S1_SvImJ      DBA_2J       AKR_J       CBA_J   NZO_HlLtJ  NOD_ShiLtJ
  "#FF00FF"   "#FFFF00"   "#A52A2A"   "#FFC0CB"   "#6B8E23"   "#ADD8E6"
    WSB_EiJ    CAST_EiJ     PWK_PhJ   SPRET_EiJ        <NA>        <NA>
  "#90EE90"   "#FFB6C1"   "#E6E6FA"   "#FFD700"   "#E0FFFF"   "#90EE90"
       <NA>
  "#FFFFE0"

  C57BL_6NJ-E16.5   C57BL_6NJ-P12.5   C57BL_6NJ-P20.5     BALB_cJ-E16.5
        "#0000FF"         "#0000FF"         "#0000FF"         "#008000"
    BALB_cJ-P12.5     BALB_cJ-P12.5     BALB_cJ-P20.5     BALB_cJ-P20.5
        "#008000"         "#008000"         "#008000"         "#008000"
        A_J-E16.5         A_J-P12.5         A_J-P20.5      FVB_NJ-E16.5
        "#FF0000"         "#FF0000"         "#FF0000"         "#800080"
     FVB_NJ-P12.5      FVB_NJ-P20.5     C3H_HeJ-E16.5     C3H_HeJ-P12.5
        "#800080"         "#800080"         "#FFA500"         "#FFA500"
    C3H_HeJ-P12.5     C3H_HeJ-P20.5     C3H_HeJ-P20.5        LP_J-E16.5
        "#FFA500"         "#FFA500"         "#FFA500"         "#00FFFF"
       LP_J-P12.5        LP_J-P20.5 129S1_SvImJ-E16.5 129S1_SvImJ-E16.5
        "#00FFFF"         "#00FFFF"         "#FF00FF"         "#FF00FF"
129S1_SvImJ-P12.5 129S1_SvImJ-P20.5 129S1_SvImJ-P20.5      DBA_2J-E16.5
        "#FF00FF"         "#FF00FF"         "#FF00FF"         "#FFFF00"
     DBA_2J-P12.5      DBA_2J-P20.5       AKR_J-E16.5       AKR_J-P12.5
        "#FFFF00"         "#FFFF00"         "#A52A2A"         "#A52A2A"
      AKR_J-P20.5       CBA_J-E16.5       CBA_J-E16.5       CBA_J-P12.5
        "#A52A2A"         "#FFC0CB"         "#FFC0CB"         "#FFC0CB"
      CBA_J-P20.5   NZO_HlLtJ-E16.5   NZO_HlLtJ-E16.5   NZO_HlLtJ-P12.5
        "#FFC0CB"         "#6B8E23"         "#6B8E23"         "#6B8E23"
  NZO_HlLtJ-P20.5  NOD_ShiLtJ-E16.5  NOD_ShiLtJ-P12.5  NOD_ShiLtJ-P20.5
        "#6B8E23"         "#ADD8E6"         "#ADD8E6"         "#ADD8E6"
    WSB_EiJ-E16.5     WSB_EiJ-P12.5     WSB_EiJ-P20.5    CAST_EiJ-E16.5
        "#90EE90"         "#90EE90"         "#90EE90"         "#FFB6C1"
   CAST_EiJ-P12.5    CAST_EiJ-P20.5     PWK_PhJ-E16.5     PWK_PhJ-P12.5
        "#FFB6C1"         "#FFB6C1"         "#E6E6FA"         "#E6E6FA"
    PWK_PhJ-P20.5   SPRET_EiJ-E16.5   SPRET_EiJ-P12.5   SPRET_EiJ-P20.5
        "#E6E6FA"         "#FFD700"         "#FFD700"         "#FFD700"

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [51]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_500_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = 3000))
dev.off()
}

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [52]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_2vs3_Beginning_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [53]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_2vs3_Beginning_500_",timePoint,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = 3000))
dev.off()
}

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [54]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs3_Beginning_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [55]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P12.5","E16.5","P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs3_Beginning_500_",timePoint,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = 3000))
dev.off()
}

[1] "P12.5"
[1] "E16.5"
[1] "P20.5"

In [57]:

##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }

  # Create a new column 'Shape' based on the sample names
  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
}

pdf("all_timepoint_PCA_After_1vs2_Beginning_all_genes.pdf",width = 10, height = 6)
plotPCA.san(rl, intgroup = "sample", ntop = nrow(counts(cds)))
dev.off()

png
  2

In [61]:
# Define the custom color assignments
custom_colors <- c(
  'C57BL_6NJ-E16.5' = 'blue',
  'C57BL_6NJ-P12.5' = 'green',
  'C57BL_6NJ-P20.5' = 'red',
  'BALB_cJ-E16.5' = 'purple',
  'BALB_cJ-P12.5' = 'orange',
  'BALB_cJ-P12.5' = 'cyan',
  'BALB_cJ-P20.5' = 'magenta',
  'BALB_cJ-P20.5' = 'yellow',
  'A_J-E16.5' = 'brown',
  'A_J-P12.5' = 'pink',
  'A_J-P20.5' = 'darkgray',
  'FVB_NJ-E16.5' = 'lightblue',
  'FVB_NJ-P12.5' = 'lightgreen',
  'FVB_NJ-P20.5' = 'lightred',
  'C3H_HeJ-E16.5' = 'darkpurple',
  'C3H_HeJ-P12.5' = 'darkorange',
  'C3H_HeJ-P12.5' = 'darkcyan',
  'C3H_HeJ-P20.5' = 'darkmagenta',
  'C3H_HeJ-P20.5' = 'darkyellow',
  'LP_J-E16.5' = 'darkbrown',
  'LP_J-P12.5' = 'darkpink',
  'LP_J-P20.5' = 'gray',
  '129S1_SvImJ-E16.5' = 'lightpurple',
  '129S1_SvImJ-E16.5' = 'lightorange',
  '129S1_SvImJ-P12.5' = 'lightcyan',
  '129S1_SvImJ-P20.5' = 'lightmagenta',
  '129S1_SvImJ-P20.5' = 'lightyellow',
  'DBA_2J-E16.5' = 'lightbrown',
  'DBA_2J-P12.5' = 'lightpink',
  'DBA_2J-P20.5' = 'darkgray',
  'AKR_J-E16.5' = 'lightblue',
  'AKR_J-P12.5' = 'lightgreen',
  'AKR_J-P20.5' = 'lightred',
  'CBA_J-E16.5' = 'darkpurple',
  'CBA_J-E16.5' = 'darkorange',
  'CBA_J-P12.5' = 'darkcyan',
  'CBA_J-P20.5' = 'darkmagenta',
  'NZO_HlLtJ-E16.5' = 'darkyellow',
  'NZO_HlLtJ-E16.5' = 'darkbrown',
  'NZO_HlLtJ-P12.5' = 'darkpink',
  'NZO_HlLtJ-P20.5' = 'gray',
  'NOD_ShiLtJ-E16.5' = 'lightpurple',
  'NOD_ShiLtJ-P12.5' = 'lightorange',
  'NOD_ShiLtJ-P20.5' = 'lightcyan',
  'WSB_EiJ-E16.5' = 'lightmagenta',
  'WSB_EiJ-P12.5' = 'lightyellow',
  'WSB_EiJ-P20.5' = 'lightbrown',
  'CAST_EiJ-E16.5' = 'lightpink',
  'CAST_EiJ-P12.5' = 'darkgray',
  'CAST_EiJ-P20.5' = 'lightblue',
  'PWK_PhJ-E16.5' = 'lightgreen',
  'PWK_PhJ-P12.5' = 'lightred',
  'PWK_PhJ-P20.5' = 'darkpurple',
  'SPRET_EiJ-E16.5' = 'darkorange',
  'SPRET_EiJ-P12.5' = 'darkcyan',
  'SPRET_EiJ-P20.5' = 'darkmagenta'
)

# Extract strain names
strain_names <- sub("-(E|P)[0-9\\.]+", "", names(custom_colors))

# Generate a unique set of strain names
unique_strain_names <- unique(strain_names)
unique_strain_names
# Define a set of bright colors from ggplot2 palette

bright_colors <-  c('#0000FF', '#008000', '#FF0000', '#800080', '#FFA500', '#00FFFF', '#FF00FF', '#FFFF00', '#A52A2A', '#FFC0CB', '#6B8E23', '#ADD8E6', '#90EE90', '#FFB6C1', '#E6E6FA', '#FFD700', '#E0FFFF', '#90EE90', '#FFFFE0')

# Create a color mapping for each unique strain name
color_mapping <- setNames(bright_colors, unique_strain_names)
color_mapping 
# Apply color mapping to the original custom_colors
reassigned_colors <- color_mapping[strain_names]

# Combine with the original labels to create the final color assignments
final_colors <- setNames(reassigned_colors, names(custom_colors))
final_colors
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }

  # Create a new column 'Shape' based on the sample names
  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
}

pdf("all_timepoint_PCA_After_1vs2_Beginning_500.pdf",,width = 10, height = 6)
plotPCA.san(rl, intgroup = "sample", ntop = 300)
dev.off()

 [1] "C57BL_6NJ"   "BALB_cJ"     "A_J"         "FVB_NJ"      "C3H_HeJ"
 [6] "LP_J"        "129S1_SvImJ" "DBA_2J"      "AKR_J"       "CBA_J"
[11] "NZO_HlLtJ"   "NOD_ShiLtJ"  "WSB_EiJ"     "CAST_EiJ"    "PWK_PhJ"
[16] "SPRET_EiJ"

  C57BL_6NJ     BALB_cJ         A_J      FVB_NJ     C3H_HeJ        LP_J
  "#0000FF"   "#008000"   "#FF0000"   "#800080"   "#FFA500"   "#00FFFF"
129S1_SvImJ      DBA_2J       AKR_J       CBA_J   NZO_HlLtJ  NOD_ShiLtJ
  "#FF00FF"   "#FFFF00"   "#A52A2A"   "#FFC0CB"   "#6B8E23"   "#ADD8E6"
    WSB_EiJ    CAST_EiJ     PWK_PhJ   SPRET_EiJ        <NA>        <NA>
  "#90EE90"   "#FFB6C1"   "#E6E6FA"   "#FFD700"   "#E0FFFF"   "#90EE90"
       <NA>
  "#FFFFE0"

  C57BL_6NJ-E16.5   C57BL_6NJ-P12.5   C57BL_6NJ-P20.5     BALB_cJ-E16.5
        "#0000FF"         "#0000FF"         "#0000FF"         "#008000"
    BALB_cJ-P12.5     BALB_cJ-P12.5     BALB_cJ-P20.5     BALB_cJ-P20.5
        "#008000"         "#008000"         "#008000"         "#008000"
        A_J-E16.5         A_J-P12.5         A_J-P20.5      FVB_NJ-E16.5
        "#FF0000"         "#FF0000"         "#FF0000"         "#800080"
     FVB_NJ-P12.5      FVB_NJ-P20.5     C3H_HeJ-E16.5     C3H_HeJ-P12.5
        "#800080"         "#800080"         "#FFA500"         "#FFA500"
    C3H_HeJ-P12.5     C3H_HeJ-P20.5     C3H_HeJ-P20.5        LP_J-E16.5
        "#FFA500"         "#FFA500"         "#FFA500"         "#00FFFF"
       LP_J-P12.5        LP_J-P20.5 129S1_SvImJ-E16.5 129S1_SvImJ-E16.5
        "#00FFFF"         "#00FFFF"         "#FF00FF"         "#FF00FF"
129S1_SvImJ-P12.5 129S1_SvImJ-P20.5 129S1_SvImJ-P20.5      DBA_2J-E16.5
        "#FF00FF"         "#FF00FF"         "#FF00FF"         "#FFFF00"
     DBA_2J-P12.5      DBA_2J-P20.5       AKR_J-E16.5       AKR_J-P12.5
        "#FFFF00"         "#FFFF00"         "#A52A2A"         "#A52A2A"
      AKR_J-P20.5       CBA_J-E16.5       CBA_J-E16.5       CBA_J-P12.5
        "#A52A2A"         "#FFC0CB"         "#FFC0CB"         "#FFC0CB"
      CBA_J-P20.5   NZO_HlLtJ-E16.5   NZO_HlLtJ-E16.5   NZO_HlLtJ-P12.5
        "#FFC0CB"         "#6B8E23"         "#6B8E23"         "#6B8E23"
  NZO_HlLtJ-P20.5  NOD_ShiLtJ-E16.5  NOD_ShiLtJ-P12.5  NOD_ShiLtJ-P20.5
        "#6B8E23"         "#ADD8E6"         "#ADD8E6"         "#ADD8E6"
    WSB_EiJ-E16.5     WSB_EiJ-P12.5     WSB_EiJ-P20.5    CAST_EiJ-E16.5
        "#90EE90"         "#90EE90"         "#90EE90"         "#FFB6C1"
   CAST_EiJ-P12.5    CAST_EiJ-P20.5     PWK_PhJ-E16.5     PWK_PhJ-P12.5
        "#FFB6C1"         "#FFB6C1"         "#E6E6FA"         "#E6E6FA"
    PWK_PhJ-P20.5   SPRET_EiJ-E16.5   SPRET_EiJ-P12.5   SPRET_EiJ-P20.5
        "#E6E6FA"         "#FFD700"         "#FFD700"         "#FFD700"

png
  2

In [62]:

##To plot PC2 versus 3
library(genefilter)
library(ggplot2)
library(ggrepel)

plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[2:3]
    return(d)
  }
#  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group",label = "name")) + geom_point(size = 1) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() +
#    theme_bw()+  theme(legend.text=element_text(size=1))
  # Create a new column 'Shape' based on the sample names
  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
}

pdf("all_timepoints_PCA_After_2vs3_all_genes.pdf",width = 10, height = 6)
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

png
  2

In [64]:

##To plot PC2 versus 3
library(genefilter)
library(ggplot2)
library(ggrepel)

plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[2:3]
    return(d)
  }
#  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group",label = "name")) + geom_point(size = 1) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() +
#    theme_bw()+  theme(legend.text=element_text(size=1))
  # Create a new column 'Shape' based on the sample names
  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
}

pdf("all_timepoints_PCA_After_2vs3_500.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = 300)
dev.off()

png
  2

In [66]:
##To plot PC1 versus 3
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
# ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "group", label = "name")) +
#   geom_point(size = 3) +
#   geom_text(size = 10, nudge_y = 0.1) +  # Adjust the label size here
#    xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) +
#    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) +
#    scale_color_manual(values = custom_colors) +  # Use custom colors
#    coord_fixed()

  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
  
}

pdf("all_timepoint_PCA_After_1vs3_all_genes.pdf",width = 10, height = 6)
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

png
  2

In [67]:
##To plot PC1 versus 3
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
# ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "group", label = "name")) +
#   geom_point(size = 3) +
#   geom_text(size = 10, nudge_y = 0.1) +  # Adjust the label size here
#    xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) +
#    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) +
#    scale_color_manual(values = custom_colors) +  # Use custom colors
#    coord_fixed()

  d$Shape <- ifelse(grepl("12.5", d$name), "P12.5",
            ifelse(grepl("16.5", d$name), "E16.5",
                   ifelse(grepl("20.5", d$name), "P20.5", "D")))
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "Samples", label = "name",shape = "Shape")) + geom_point(size = 1.5,, position = position_jitter(width = 1, height = 1)) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() + scale_color_manual(values = final_colors ) +
    scale_shape_manual(values = c("E16.5" = 16, "P12.5" = 17, "P20.5" = 18, "D" = 19)) +  # Assign shape codes to labels
     theme(legend.text=element_text(size=5)) + labs(shape = "Timepoint") + guides(color = guide_legend(title = "Strains"))
  # Replace the shape labels with timepoint labels
  
  
  
}

pdf("all_timepoint_PCA_After_1vs3_500.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = 500)
dev.off()

png
  2

In [68]:
###
# Margins area


pdf("all_timepoint_InitialHeatMap.pdf",paper="special",width=25000, height=25000,title="Trinity Assemblies",fillOddEven=T)
heatmap.2(cor(mircounts),trace="none",col=hmcol,main="Sample Correlation",cexRow=1000,cexCol=1000, 
    margins=c(12000,12000),na.rm=T,key=T,offsetRow=300,offsetCol=300,keysize=0.2,density.info='histogram')
dev.off()

png
  2

In [69]:
##And the Spearman Dendogram
foo_sub_1 = counts(cds, normalized = TRUE)

foo_cor_1 = cor(foo_sub_1, method = "spearman") #builds matrix of Spearman corrn and euclidean distances

foo_cor_dist_1 = dist(foo_cor_1, method = "euclidean")
pdf(file="all_timepoint_dendrogram.pdf", height=10, width=30)
plot(hclust(foo_cor_dist_1))
dev.off()

png
  2

In [ ]:
# Now we build a DESeq2 Count dataset and normalize it.
mircounts <- rawdata_copy$counts

cds <- DESeqDataSetFromMatrix(countData = round(mircounts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates, fitting model and testing: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [90]:

library(EnhancedVolcano)

In [ ]:
samplenames = c('C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'A_J-E16.5','A_J-E16.5','A_J-E16.5','A_J-P12.5','A_J-P12.5','A_J-P12.5','A_J-P20.5','A_J-P20.5','A_J-P20.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'LP_J-E16.5','LP_J-E16.5','LP_J-E16.5','LP_J-P12.5','LP_J-P12.5','LP_J-P12.5','LP_J-P20.5','LP_J-P20.5','LP_J-P20.5',
'129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-E16.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-E16.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')

In [105]:
library(foreach)
library(doParallel)


# Create a directory to save the plots
if (!dir.exists("volcano_plots")) {
    dir.create("volcano_plots")
}


# Set up parallel processing
num_cores <- 144 # Set the number of CPU cores to use
registerDoParallel(cores = num_cores)

# Define a function for generating a volcano plot
generate_volcano_plot <- function(col1, col2, cds) {
    contrast <- c('sample',col1, col2)
    res <- results(cds, contrast = contrast)

    # Create a color vector based on log2FoldChange and p-value
    colors <- ifelse(res$pvalue <= 0.05 & abs(res$log2FoldChange) >= 2, "red",
                             ifelse(res$pvalue <= 0.05, "blue", "gray"))
    
    volcano_plot <- EnhancedVolcano(res,
                                        lab = rownames(res),
                                        x = 'log2FoldChange',
                                        y = 'pvalue',
                                        title = paste(col1, "vs", col2, "Volcano Plot"),
                                        pCutoff = 0.05,
                                        FCcutoff = 2,
                                        col=colors,  #c('blue', 'blue', 'blue', 'red3'),
                                        colAlpha = 1,    cutoffLineType = 'blank',
                                        cutoffLineCol = 'black',
                                        cutoffLineWidth = 0.8,
                                        hline = c(10e-12, 10e-36, 10e-60, 10e-84),
                                        hlineCol = c('grey0', 'grey25','grey50','grey75'),
                                        hlineType = 'longdash',
                                        hlineWidth = 0.8,
                                        gridlines.major = FALSE,
                                        gridlines.minor = FALSE,
                                        xlim = c(-10, 10))

    # Add text labels for upregulated, downregulated, and nonsignificant genes
    textLabels <- ifelse(res$pvalue <= 0.05 & abs(res$log2FoldChange) >= 2,
                                 ifelse(res$log2FoldChange > 0, "Up", "Down"), "NS")
            
    text(x = res$log2FoldChange, y = -log10(res$pvalue), labels = textLabels, cex = 0.7, col = "black")
            
    
    plot_filename <- paste("volcano_plots/", col1, "_vs_", col2, "_volcano_plot.png", sep = "")
    png(plot_filename, width = 1000, height = 1200)
    print(volcano_plot)
    dev.off()
}


# Parallelize volcano plot generation using foreach
foreach(i = 1:(length(column_names) - 1),
        .combine = 'c') %dopar% {
    for (j in (i + 1):length(column_names)) {
        col1 <- column_names[i]
        col2 <- column_names[j]
        
        # Check if col1 and col2 have the same name
        if (col1 != col2) {
            generate_volcano_plot(col1, col2, cds)
        }
    }
}

# Stop parallel processing
stopImplicitCluster()