In [1]:
###testing R in jyupter 
system("type R")

In [2]:
#package installation 
#install.packages("purrr")
#install.packages("tidyverse")
#conda install r-tidyverse r-purrr bioconductor-edger bioconductor-busparse bioconductor-rtracklayer r-dplyr -y 
#conda install -c conda-forge r-purrr -y
#conda install -c bioconda bioconductor-edger -y
#conda install -c bioconda bioconductor-busparse -y
#conda install -c bioconda bioconductor-rtracklayer -y
#conda install -c conda-forge r-dplyr -y

In [3]:
library(purrr)
library(tidyverse)
library(edgeR)
library(rtracklayer)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: limma

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:limma’:

    plotMA


The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:lubridate’:

    second, second<-


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:tidyr’:

    expand


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:lubridate’:

    %within%


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:purrr’:

    reduce


Loading required package: GenomeInfoDb

In [4]:
library(purrr)
library(tidyverse)
f_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "12.5.+featureCounts$", full.names = T)

f_files

 [1] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts"
 [2] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts"
 [3] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts"
 [4] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts"
 [5] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts"
 [6] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts"
 [7] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts"
 [8] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts"
 [9] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts"
[10] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts"
[11] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts"
[12] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts"
[13] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts"
[14] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts"
[15] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts"
[16] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts"
[17] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts"
[18] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts"
[19] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts"
[20] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts"
[21] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts"
[22] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts"
[23] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts"
[24] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts"
[25] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts"
[26] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts"
[27] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts"
[28] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts"
[29] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts"
[30] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts"
[31] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts"
[32] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts"
[33] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts"
[34] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts"
[35] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts"
[36] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts"
[37] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts"
[38] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts"
[39] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts"
[40] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts"
[41] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts"
[42] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts"

In [5]:
samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames

 [1] "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp"
 [4] "A_J-12.5dpp"         "A_J-12.5dpp"         "A_J-12.5dpp"
 [7] "AKR_J-12.5dpp"       "AKR_J-12.5dpp"       "AKR_J-12.5dpp"
[10] "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"
[13] "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"
[16] "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"
[19] "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"
[22] "CBA_J-12.5dpp"       "CBA_J-12.5dpp"       "CBA_J-12.5dpp"
[25] "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"
[28] "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"
[31] "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"
[34] "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"
[37] "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"
[40] "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"

In [6]:
samplenames <- c('Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Wild','Wild','Wild',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Inbred','Inbred','Inbred',
'Wild','Wild','Wild',
'Wild','Wild','Wild',
'Wild','Wild','Wild')

In [7]:
#list of sample names with replicates 
lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))

lables

 [1] "129S1_SvImJ-12.5dpp.1" "129S1_SvImJ-12.5dpp.2" "129S1_SvImJ-12.5dpp.3"
 [4] "A_J-12.5dpp.1"         "A_J-12.5dpp.2"         "A_J-12.5dpp.3"
 [7] "AKR_J-12.5dpp.1"       "AKR_J-12.5dpp.2"       "AKR_J-12.5dpp.3"
[10] "BALB_cJ-12.5dpp.1"     "BALB_cJ-12.5dpp.2"     "BALB_cJ-12.5dpp.3"
[13] "C3H_HeJ-12.5dpp.1"     "C3H_HeJ-12.5dpp.2"     "C3H_HeJ-12.5dpp.3"
[16] "C57BL_6NJ-12.5dpp.1"   "C57BL_6NJ-12.5dpp.2"   "C57BL_6NJ-12.5dpp.3"
[19] "CAST_EiJ-12.5dpp.1"    "CAST_EiJ-12.5dpp.2"    "CAST_EiJ-12.5dpp.3"
[22] "CBA_J-12.5dpp.1"       "CBA_J-12.5dpp.2"       "CBA_J-12.5dpp.3"
[25] "DBA_2J-12.5dpp.1"      "DBA_2J-12.5dpp.2"      "DBA_2J-12.5dpp.3"
[28] "FVB_NJ-12.5dpp.1"      "FVB_NJ-12.5dpp.2"      "FVB_NJ-12.5dpp.3"
[31] "NOD_ShiLtJ-12.5dpp.1"  "NOD_ShiLtJ-12.5dpp.2"  "NOD_ShiLtJ-12.5dpp.3"
[34] "PWK_PhJ-12.5dpp.1"     "PWK_PhJ-12.5dpp.2"     "PWK_PhJ-12.5dpp.3"
[37] "SPRET_EiJ-12.5dpp.1"   "SPRET_EiJ-12.5dpp.2"   "SPRET_EiJ-12.5dpp.3"
[40] "WSB_EiJ-12.5dpp.1"     "WSB_EiJ-12.5dpp.2"     "WSB_EiJ-12.5dpp.3"

In [8]:
labels <- c('Inbred.1','Inbred.2','Inbred.3',
            'Inbred.4','Inbred.5','Inbred.6',
            'Inbred.7','Inbred.8','Inbred.9',
            'Inbred.10','Inbred.11','Inbred.12',
            'Inbred.13','Inbred.14','Inbred.15',
            'Inbred.16','Inbred.17','Inbred.18',
            'Wild.1','Wild.2','Wild.3',
            'Inbred.19','Inbred.20','Inbred.21',
            'Inbred.22','Inbred.23','Inbred.24',
            'Inbred.25','Inbred.26','Inbred.27',
            'Inbred.28','Inbred.29','Inbred.30',
            'Wild.4','Wild.5','Wild.6',
            'Wild.7','Wild.8','Wild.9',
            'Wild.10','Wild.11','Wild.12')
labels

 [1] "Inbred.1"  "Inbred.2"  "Inbred.3"  "Inbred.4"  "Inbred.5"  "Inbred.6"
 [7] "Inbred.7"  "Inbred.8"  "Inbred.9"  "Inbred.10" "Inbred.11" "Inbred.12"
[13] "Inbred.13" "Inbred.14" "Inbred.15" "Inbred.16" "Inbred.17" "Inbred.18"
[19] "Wild.1"    "Wild.2"    "Wild.3"    "Inbred.19" "Inbred.20" "Inbred.21"
[25] "Inbred.22" "Inbred.23" "Inbred.24" "Inbred.25" "Inbred.26" "Inbred.27"
[31] "Inbred.28" "Inbred.29" "Inbred.30" "Wild.4"    "Wild.5"    "Wild.6"
[37] "Wild.7"    "Wild.8"    "Wild.9"    "Wild.10"   "Wild.11"   "Wild.12"

In [9]:
raw <- readDGE(f_files, columns = c(1, 7), comment.char = "#", sep="\t", group= samplenames, labels = labels,)

In [10]:
rawdata <- raw
rawdata

An object of class "DGEList"
$samples
                                                                                                                                  files
Inbred.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
Inbred.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
Inbred.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
Inbred.4         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts
Inbred.5         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts
          group lib.size norm.factors
Inbred.1 Inbred 31878714            1
Inbred.2 Inbred 31993372            1
Inbred.3 Inbred 32262165            1
Inbred.4 Inbred 29667123            1
Inbred.5 Inbred 33838073            1
37 more rows ...

$counts
                    Samples
Tags                 Inbred.1 Inbred.2 Inbred.3 Inbred.4 Inbred.5 Inbred.6
  ENSMUSG00200053149    24.50    20.50    32.00        0        0        0
  ENSMUSG00200032800     0.00     0.00     0.00        0        0        0
  ENSMUSG00200032797  1679.95  1636.63  1454.33        0        0        0
  ENSMUSG00200032798     6.50     8.00    10.50        0        0        0
  ENSMUSG00200032795     5.50    10.00     8.00        0        0        0
                    Samples
Tags                 Inbred.7 Inbred.8 Inbred.9 Inbred.10 Inbred.11 Inbred.12
  ENSMUSG00200053149        0        0        0         0         0         0
  ENSMUSG00200032800        0        0        0         0         0         0
  ENSMUSG00200032797        0        0        0         0         0         0
  ENSMUSG00200032798        0        0        0         0         0         0
  ENSMUSG00200032795        0        0        0         0         0         0
                    Samples
Tags                 Inbred.13 Inbred.14 Inbred.15 Inbred.16 Inbred.17
  ENSMUSG00200053149         0         0         0         0         0
  ENSMUSG00200032800         0         0         0         0         0
  ENSMUSG00200032797         0         0         0         0         0
  ENSMUSG00200032798         0         0         0         0         0
  ENSMUSG00200032795         0         0         0         0         0
                    Samples
Tags                 Inbred.18 Wild.1 Wild.2 Wild.3 Inbred.19 Inbred.20
  ENSMUSG00200053149         0      0      0      0         0         0
  ENSMUSG00200032800         0      0      0      0         0         0
  ENSMUSG00200032797         0      0      0      0         0         0
  ENSMUSG00200032798         0      0      0      0         0         0
  ENSMUSG00200032795         0      0      0      0         0         0
                    Samples
Tags                 Inbred.21 Inbred.22 Inbred.23 Inbred.24 Inbred.25
  ENSMUSG00200053149         0         0         0         0         0
  ENSMUSG00200032800         0         0         0         0         0
  ENSMUSG00200032797         0         0         0         0         0
  ENSMUSG00200032798         0         0         0         0         0
  ENSMUSG00200032795         0         0         0         0         0
                    Samples
Tags                 Inbred.26 Inbred.27 Inbred.28 Inbred.29 Inbred.30 Wild.4
  ENSMUSG00200053149         0         0         0         0         0      0
  ENSMUSG00200032800         0         0         0         0         0      0
  ENSMUSG00200032797         0         0         0         0         0      0
  ENSMUSG00200032798         0         0         0         0         0      0
  ENSMUSG00200032795         0         0         0         0         0      0
                    Samples
Tags                 Wild.5 Wild.6 Wild.7 Wild.8 Wild.9 Wild.10 Wild.11 Wild.12
  ENSMUSG00200053149      0      0      0      0      0       0       0       0
  ENSMUSG00200032800      0      0      0      0      0       0       0       0
  ENSMUSG00200032797      0      0      0      0      0       0       0       0
  ENSMUSG00200032798      0      0      0      0      0       0       0       0
  ENSMUSG00200032795      0      0      0      0      0       0       0       0
323242 more rows ...

In [11]:
A129S1_SvImJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/129S1_SvImJ_v3.2.gff3") #import gff3 file 
A129S1_SvImJ_geneName = na.omit(mcols(A129S1_SvImJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

A_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/A_J_v3.2.gff3") #import gff3 file 
A_J_geneName = na.omit(mcols(A_J )[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

AKR_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/AKR_J_v3.2.gff3") #import gff3 file 
AKR_J_geneName = na.omit(mcols(AKR_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

BALB_cJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/BALB_cJ_v3.2.gff3") #import gff3 file 
BALB_cJ_geneName = na.omit(mcols(BALB_cJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C3H_HeJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C3H_HeJ_v3.2.gff3") #import gff3 file 
C3H_HeJ_geneName = na.omit(mcols(C3H_HeJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C57BL_6NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C57BL_6NJ_v3.2.gff3") #import gff3 file 
C57BL_6NJ_geneName = na.omit(mcols(C57BL_6NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CAST_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CAST_EiJ_v3.2.gff3") #import gff3 file 
CAST_EiJ_geneName = na.omit(mcols(CAST_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CBA_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CBA_J_v3.2.gff3") #import gff3 file 
CBA_J_geneName = na.omit(mcols(CBA_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

DBA_2J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/DBA_2J_v3.2.gff3") #import gff3 file 
DBA_2J_geneName = na.omit(mcols(DBA_2J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

FVB_NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/FVB_NJ_v3.2.gff3") #import gff3 file 
FVB_NJ_geneName = na.omit(mcols(FVB_NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

LP_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/LP_J_v3.2.gff3") #import gff3 file 
LP_J_geneName = na.omit(mcols(LP_J)[,c("gene_id","Name")]) #get gene symbloes for respective gene id 

NOD_ShiLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NOD_ShiLtJ_v3.2.gff3") #import gff3 file 
NOD_ShiLtJ_geneName = na.omit(mcols(NOD_ShiLtJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

NZO_HlLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NZO_HlLtJ_v3.2.gff3") #import gff3 file 
NZO_HlLtJ_geneName = na.omit(mcols(NZO_HlLtJ)[,c("gene_id","Name")]) #get gene symbloes for respective gene id 

PWK_PhJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/PWK_PhJ_v3.2.gff3") #import gff3 file 
PWK_PhJ_geneName = na.omit(mcols(PWK_PhJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

SPRET_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/SPRET_EiJ_v3.2.gff3") #import gff3 file 
SPRET_EiJ_geneName = na.omit(mcols(SPRET_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 


WSB_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/WSB_EiJ_v3.2.gff3") #import gff3 file 
WSB_EiJ_geneName = na.omit(mcols(WSB_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id

In [ ]:
colnames(LP_J_geneName)[which(names(LP_J_geneName) == "Name")] <- "parent_gene_display_xref" #change columns name
colnames(NZO_HlLtJ_geneName)[which(names(NZO_HlLtJ_geneName) == "Name")] <- "parent_gene_display_xref" # change column name

In [ ]:
geneName <- do.call("rbind", list(A129S1_SvImJ_geneName, A_J_geneName, AKR_J_geneName, BALB_cJ_geneName, C3H_HeJ_geneName, C57BL_6NJ_geneName, CAST_EiJ_geneName, CBA_J_geneName, DBA_2J_geneName , FVB_NJ_geneName,  LP_J_geneName, NOD_ShiLtJ_geneName ,    NZO_HlLtJ_geneName, PWK_PhJ_geneName, SPRET_EiJ_geneName,WSB_EiJ_geneName ))
geneName

DataFrame with 780454 rows and 2 columns
                  gene_id parent_gene_display_xref
              <character>              <character>
1      ENSMUSG00200053149                   Ugt1a1
2      ENSMUSG00200053174                  Gm20528
3      ENSMUSG00200032800            4933401J01Rik
4      ENSMUSG00200032799                  Gm26206
5      ENSMUSG00200032797                     Xkr4
...                   ...                      ...
780450 ENSMUSG00010031589                 BC022960
780451 ENSMUSG00010023776                  Gm15245
780452 ENSMUSG00010023781                     Mid1
780453 ENSMUSG00010023777                  Gm25651
780454 ENSMUSG00010023774            4933400A11Rik

In [ ]:
rownames(geneName) <- geneName$gene_id
geneName$gene_id <- NULL
geneName

DataFrame with 780454 rows and 1 column
                   parent_gene_display_xref
                                <character>
ENSMUSG00200053149                   Ugt1a1
ENSMUSG00200053174                  Gm20528
ENSMUSG00200032800            4933401J01Rik
ENSMUSG00200032799                  Gm26206
ENSMUSG00200032797                     Xkr4
...                                     ...
ENSMUSG00010031589                 BC022960
ENSMUSG00010023776                  Gm15245
ENSMUSG00010023781                     Mid1
ENSMUSG00010023777                  Gm25651
ENSMUSG00010023774            4933400A11Rik

In [ ]:
library(dplyr)
rawdata$counts <- merge(x=raw$counts, y=geneName,by = 0,all.x=TRUE ) #left merge

In [17]:
rawdata_copy <- rawdata
rawdata_copy$counts['Row.names'] <- NULL #remove the columns name Row.names

In [ ]:
rawdata_copy$counts <- rawdata_copy$counts[!is.na(rawdata_copy$counts$parent_gene_display_xref),] #remove NA 
rawdata_copy$counts

       Inbred.1 Inbred.2 Inbred.3 Inbred.4 Inbred.5 Inbred.6 Inbred.7 Inbred.8
4      0        0        0        0        0        0        0        0
10     0        0        0        0        0        0        0        0
11     0        0        0        0        0        0        0        0
12     0        0        0        0        0        0        0        0
13     0        0        0        0        0        0        0        0
14     0        0        0        0        0        0        0        0
15     0        0        0        0        0        0        0        0
16     0        0        0        0        0        0        0        0
17     0        0        0        0        0        0        0        0
18     0        0        0        0        0        0        0        0
19     0        0        0        0        0        0        0        0
20     0        0        0        0        0        0        0        0
21     0        0        0        0        0        0        0        0
22     0        0        0        0        0        0        0        0
23     0        0        0        0        0        0        0        0
24     0        0        0        0        0        0        0        0
25     0        0        0        0        0        0        0        0
26     0        0        0        0        0        0        0        0
27     0        0        0        0        0        0        0        0
28     0        0        0        0        0        0        0        0
29     0        0        0        0        0        0        0        0
30     0        0        0        0        0        0        0        0
31     0        0        0        0        0        0        0        0
32     0        0        0        0        0        0        0        0
33     0        0        0        0        0        0        0        0
34     0        0        0        0        0        0        0        0
35     0        0        0        0        0        0        0        0
36     0        0        0        0        0        0        0        0
37     0        0        0        0        0        0        0        0
38     0        0        0        0        0        0        0        0
⋮      ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮
323218 0        0        0        0        0        0        765.21    843.99
323219 0        0        0        0        0        0        993.21   1006.24
323220 0        0        0        0        0        0          2.50      4.92
323221 0        0        0        0        0        0          1.37      2.47
323222 0        0        0        0        0        0          4.78      9.25
323223 0        0        0        0        0        0          6.72      9.43
323224 0        0        0        0        0        0          6.71      5.04
323225 0        0        0        0        0        0          1.06      0.63
323226 0        0        0        0        0        0          3.81      2.41
323227 0        0        0        0        0        0        604.00    666.00
323228 0        0        0        0        0        0          6.02      6.00
323229 0        0        0        0        0        0          3.03      6.41
323230 0        0        0        0        0        0          1.04      1.58
323231 0        0        0        0        0        0          3.70      3.23
323232 0        0        0        0        0        0          3.31      3.45
323233 0        0        0        0        0        0          3.25      3.70
323234 0        0        0        0        0        0          3.25      3.70
323235 0        0        0        0        0        0          0.75      0.67
323236 0        0        0        0        0        0         22.27     35.16
323237 0        0        0        0        0        0          0.00      1.00
323238 0        0        0        0        0        0          4.98      9.71
323239 0        0        0        0        0        0          9.75     17.76
323240 0        0        0        0        0        0          9.31      7.27
323241 0        0        0        0        0        0          4.73      7.68
323242 0        0        0        0        0        0          1.07      3.04
323243 0        0        0        0        0        0          0.00      0.00
323244 0        0        0        0        0        0          0.00      0.00
323245 0        0        0        0        0        0          0.00      0.00
323246 0        0        0        0        0        0          0.00      0.00
323247 0        0        0        0        0        0          0.00      0.00
       Inbred.9 Inbred.10 ⋯ Wild.4 Wild.5 Wild.6 Wild.7  Wild.8  Wild.9
4      0        0         ⋯ 0      0      0       166.83  144.83  119.33
10     0        0         ⋯ 0      0      0         0.00    0.00    0.00
11     0        0         ⋯ 0      0      0       273.00  211.59  200.50
12     0        0         ⋯ 0      0      0       131.60  121.89  111.50
13     0        0         ⋯ 0      0      0      3666.79 3803.57 3392.70
14     0        0         ⋯ 0      0      0       543.33  492.00  533.00
15     0        0         ⋯ 0      0      0       450.50  496.53  519.50
16     0        0         ⋯ 0      0      0       276.00  243.00  287.00
17     0        0         ⋯ 0      0      0        43.17   49.33   33.83
18     0        0         ⋯ 0      0      0      1071.00 1020.50  928.33
19     0        0         ⋯ 0      0      0        10.17    8.33   10.33
20     0        0         ⋯ 0      0      0        14.67   12.83    8.83
21     0        0         ⋯ 0      0      0        11.00   13.50    9.50
22     0        0         ⋯ 0      0      0        12.00   14.50    9.50
23     0        0         ⋯ 0      0      0      1363.34 1450.09 1460.85
24     0        0         ⋯ 0      0      0        72.00   74.75   74.00
25     0        0         ⋯ 0      0      0      3659.50 3522.52 3423.33
26     0        0         ⋯ 0      0      0         1.00    1.00    0.00
27     0        0         ⋯ 0      0      0        12.00   11.00   11.00
28     0        0         ⋯ 0      0      0      3906.17 4182.50 4700.25
29     0        0         ⋯ 0      0      0      2931.77 2818.72 3388.96
30     0        0         ⋯ 0      0      0      1838.50 1525.00 1953.50
31     0        0         ⋯ 0      0      0      2768.00 2835.50 3285.75
32     0        0         ⋯ 0      0      0      1758.50 1549.00 1726.00
33     0        0         ⋯ 0      0      0        66.00   56.50   91.00
34     0        0         ⋯ 0      0      0       455.00  312.00  405.50
35     0        0         ⋯ 0      0      0       803.50  647.00  752.00
36     0        0         ⋯ 0      0      0       975.50  580.00  660.50
37     0        0         ⋯ 0      0      0      3840.83 3411.04 3801.20
38     0        0         ⋯ 0      0      0       844.00  777.00  768.00
⋮      ⋮        ⋮         ⋱ ⋮      ⋮      ⋮      ⋮       ⋮       ⋮
323218  833.63  0         ⋯ 0      0      0      0       0       0
323219 1133.63  0         ⋯ 0      0      0      0       0       0
323220    5.27  0         ⋯ 0      0      0      0       0       0
323221    2.69  0         ⋯ 0      0      0      0       0       0
323222    7.67  0         ⋯ 0      0      0      0       0       0
323223    6.64  0         ⋯ 0      0      0      0       0       0
323224    5.72  0         ⋯ 0      0      0      0       0       0
323225    0.52  0         ⋯ 0      0      0      0       0       0
323226    2.30  0         ⋯ 0      0      0      0       0       0
323227  670.00  0         ⋯ 0      0      0      0       0       0
323228    6.91  0         ⋯ 0      0      0      0       0       0
323229    3.67  0         ⋯ 0      0      0      0       0       0
323230    0.72  0         ⋯ 0      0      0      0       0       0
323231    4.51  0         ⋯ 0      0      0      0       0       0
323232    1.29  0         ⋯ 0      0      0      0       0       0
323233    4.08  0         ⋯ 0      0      0      0       0       0
323234    4.08  0         ⋯ 0      0      0      0       0       0
323235    0.25  0         ⋯ 0      0      0      0       0       0
323236   23.71  0         ⋯ 0      0      0      0       0       0
323237    0.50  0         ⋯ 0      0      0      0       0       0
323238    6.29  0         ⋯ 0      0      0      0       0       0
323239   14.16  0         ⋯ 0      0      0      0       0       0
323240    6.82  0         ⋯ 0      0      0      0       0       0
323241    7.95  0         ⋯ 0      0      0      0       0       0
323242    2.92  0         ⋯ 0      0      0      0       0       0
323243    0.00  0         ⋯ 0      0      0      0       0       0
323244    0.00  0         ⋯ 0      0      0      0       0       0
323245    0.00  0         ⋯ 0      0      0      0       0       0
323246    0.00  0         ⋯ 0      0      0      0       0       0
323247    0.00  0         ⋯ 0      0      0      0       0       0
       Wild.10 Wild.11 Wild.12 parent_gene_display_xref
4      0       0       0       Gm37340
10     0       0       0       Ptf1a
11     0       0       0       Msrb2
12     0       0       0       4921504E06Rik
13     0       0       0       Upf2
14     0       0       0       Proser2
15     0       0       0       Dhtkd1
16     0       0       0       Echdc3
17     0       0       0       C1ql3
18     0       0       0       Pter
19     0       0       0       Gm37811
20     0       0       0       Gm37824
21     0       0       0       Gm37255
22     0       0       0       Gm38014
23     0       0       0       Fam107b
24     0       0       0       Cdnf
25     0       0       0       Brd3
26     0       0       0       Lcn4
27     0       0       0       Abo
28     0       0       0       Rxra
29     0       0       0       Rpl7a
30     0       0       0       Surf6
31     0       0       0       Wdr5
32     0       0       0       Med22
33     0       0       0       Ajm1
34     0       0       0       Phpt1
35     0       0       0       Mamdc4
36     0       0       0       Edf1
37     0       0       0       Rabl6
38     0       0       0       Kin
⋮      ⋮       ⋮       ⋮       ⋮
323218 0       0       0       Gm10184
323219 0       0       0       Rpl7a
323220 0       0       0       Gm37665
323221 0       0       0       Gm37665
323222 0       0       0       Gm42687
323223 0       0       0       Gm38046
323224 0       0       0       Gm45663
323225 0       0       0       Gm21897
323226 0       0       0       Gm21897
323227 0       0       0       Bud31
323228 0       0       0       Gm45663
323229 0       0       0       Gm37665
323230 0       0       0       Gm21897
323231 0       0       0       Gm48377
323232 0       0       0       Gm44078
323233 0       0       0       Gm37110
323234 0       0       0       Gm44792
323235 0       0       0       Gm48377
323236 0       0       0       Gm43520
323237 0       0       0       Gm43198
323238 0       0       0       Gm37665
323239 0       0       0       Gm37665
323240 0       0       0       Magea6
323241 0       0       0       Gm43520
323242 0       0       0       Gm37665
323243 0       0       0       Gm42959
323244 0       0       0       Gm3424
323245 0       0       0       Gm5849
323246 0       0       0       Speer4e
323247 0       0       0       Gm47571

In [ ]:

rawdata_copy$counts <- rawdata_copy$counts %>% 
  group_by(parent_gene_display_xref) %>% 
  summarise(across(everything(), sum))

#rawdata_copy$counts <- aggregate(. ~ parent_gene_display_xref, rawdata_copy, sum, na.rm = TRUE)

In [ ]:

rawdata_copy$counts <- as.data.frame(rawdata_copy$counts[!duplicated(rawdata_copy$counts$parent_gene_display_xref), ])  #remove dulicate values 
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                  files
Inbred.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
Inbred.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
Inbred.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts
Inbred.4         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts
Inbred.5         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts
          group lib.size norm.factors
Inbred.1 Inbred 30879948            1
Inbred.2 Inbred 35864325            1
Inbred.3 Inbred 35755630            1
Inbred.4 Inbred 34342021            1
Inbred.5 Inbred 33488399            1
37 more rows ...

$counts
  parent_gene_display_xref Inbred.1 Inbred.2 Inbred.3 Inbred.4 Inbred.5
1            0610006L08Rik     0.00        0     0.00        0        0
2            0610009B22Rik   467.25      547   460.25      504      473
3            0610009E02Rik     0.00        0     0.00        0        0
4            0610009L18Rik     0.00        0     0.00        0        0
5            0610010K14Rik   996.50      995   945.00     1219     1063
  Inbred.6 Inbred.7 Inbred.8 Inbred.9 Inbred.10 Inbred.11 Inbred.12 Inbred.13
1        0        0        0        0         0       0.0         0         0
2      440      457      539      512       472     459.0       539       514
3        0        0        0        0         0       0.0         0         0
4        0        0        0        0         0       0.0         0         0
5      964      865      949     1038       666     779.5       837       858
  Inbred.14 Inbred.15 Inbred.16 Inbred.17 Inbred.18 Wild.1 Wild.2 Wild.3
1         0         0       0.0         0         0    0.0      0    0.0
2       532       503     525.0       545       576  432.0    516  470.0
3         0         0       0.0         0         0    0.0      0    0.0
4         0         0       0.0         0         0    0.0      0    0.0
5       899       717     807.5       950       886  693.5    755  789.5
  Inbred.19 Inbred.20 Inbred.21 Inbred.22 Inbred.23 Inbred.24 Inbred.25
1         0       0.0       0.0       0.0       0.0       0.0         0
2       545     429.5     625.0     446.0     379.0     423.0       542
3         0       0.0       0.0       0.0       0.0       0.0         0
4         0       0.0       0.0       0.0       0.0       0.0         0
5       757     878.5     867.5     852.5     799.5     910.5       829
  Inbred.26 Inbred.27 Inbred.28 Inbred.29 Inbred.30  Wild.4  Wild.5  Wild.6
1       0.0         0         0         0       0.0    0.00    0.00    0.00
2     486.0       512       435       449     419.0    5.00   10.00    5.00
3       0.0         0         0         0       0.0    0.00    0.00    0.00
4       0.0         0         0         0       0.0    0.00    0.00    0.00
5     710.5       709       672       766     714.5 2968.25 3098.17 2820.25
  Wild.7 Wild.8 Wild.9 Wild.10 Wild.11 Wild.12
1    0.0    0.0      0      75      57   67.42
2  716.5  552.0    586       0       0    0.00
3    0.0    0.0      0     454     420  415.00
4    0.0    0.0      0       0       0    0.00
5  906.5  892.5   1082       0       0    0.00
42807 more rows ...

In [ ]:
rownames(rawdata_copy$counts) <- rawdata_copy$counts$parent_gene_display_xref #set rawname to gene symbloes 
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                  files
Inbred.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
Inbred.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
Inbred.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts
Inbred.4         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts
Inbred.5         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts
          group lib.size norm.factors
Inbred.1 Inbred 30879948            1
Inbred.2 Inbred 35864325            1
Inbred.3 Inbred 35755630            1
Inbred.4 Inbred 34342021            1
Inbred.5 Inbred 33488399            1
37 more rows ...

$counts
              parent_gene_display_xref Inbred.1 Inbred.2 Inbred.3 Inbred.4
0610006L08Rik            0610006L08Rik     0.00        0     0.00        0
0610009B22Rik            0610009B22Rik   467.25      547   460.25      504
0610009E02Rik            0610009E02Rik     0.00        0     0.00        0
0610009L18Rik            0610009L18Rik     0.00        0     0.00        0
0610010K14Rik            0610010K14Rik   996.50      995   945.00     1219
              Inbred.5 Inbred.6 Inbred.7 Inbred.8 Inbred.9 Inbred.10 Inbred.11
0610006L08Rik        0        0        0        0        0         0       0.0
0610009B22Rik      473      440      457      539      512       472     459.0
0610009E02Rik        0        0        0        0        0         0       0.0
0610009L18Rik        0        0        0        0        0         0       0.0
0610010K14Rik     1063      964      865      949     1038       666     779.5
              Inbred.12 Inbred.13 Inbred.14 Inbred.15 Inbred.16 Inbred.17
0610006L08Rik         0         0         0         0       0.0         0
0610009B22Rik       539       514       532       503     525.0       545
0610009E02Rik         0         0         0         0       0.0         0
0610009L18Rik         0         0         0         0       0.0         0
0610010K14Rik       837       858       899       717     807.5       950
              Inbred.18 Wild.1 Wild.2 Wild.3 Inbred.19 Inbred.20 Inbred.21
0610006L08Rik         0    0.0      0    0.0         0       0.0       0.0
0610009B22Rik       576  432.0    516  470.0       545     429.5     625.0
0610009E02Rik         0    0.0      0    0.0         0       0.0       0.0
0610009L18Rik         0    0.0      0    0.0         0       0.0       0.0
0610010K14Rik       886  693.5    755  789.5       757     878.5     867.5
              Inbred.22 Inbred.23 Inbred.24 Inbred.25 Inbred.26 Inbred.27
0610006L08Rik       0.0       0.0       0.0         0       0.0         0
0610009B22Rik     446.0     379.0     423.0       542     486.0       512
0610009E02Rik       0.0       0.0       0.0         0       0.0         0
0610009L18Rik       0.0       0.0       0.0         0       0.0         0
0610010K14Rik     852.5     799.5     910.5       829     710.5       709
              Inbred.28 Inbred.29 Inbred.30  Wild.4  Wild.5  Wild.6 Wild.7
0610006L08Rik         0         0       0.0    0.00    0.00    0.00    0.0
0610009B22Rik       435       449     419.0    5.00   10.00    5.00  716.5
0610009E02Rik         0         0       0.0    0.00    0.00    0.00    0.0
0610009L18Rik         0         0       0.0    0.00    0.00    0.00    0.0
0610010K14Rik       672       766     714.5 2968.25 3098.17 2820.25  906.5
              Wild.8 Wild.9 Wild.10 Wild.11 Wild.12
0610006L08Rik    0.0      0      75      57   67.42
0610009B22Rik  552.0    586       0       0    0.00
0610009E02Rik    0.0      0     454     420  415.00
0610009L18Rik    0.0      0       0       0    0.00
0610010K14Rik  892.5   1082       0       0    0.00
42807 more rows ...

In [ ]:
rawdata_copy$counts$parent_gene_display_xref <- NULL #remove gene symbole columns

In [ ]:
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                  files
Inbred.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
Inbred.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
Inbred.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts
Inbred.4         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts
Inbred.5         /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts
          group lib.size norm.factors
Inbred.1 Inbred 30879948            1
Inbred.2 Inbred 35864325            1
Inbred.3 Inbred 35755630            1
Inbred.4 Inbred 34342021            1
Inbred.5 Inbred 33488399            1
37 more rows ...

$counts
              Inbred.1 Inbred.2 Inbred.3 Inbred.4 Inbred.5 Inbred.6 Inbred.7
0610006L08Rik     0.00        0     0.00        0        0        0        0
0610009B22Rik   467.25      547   460.25      504      473      440      457
0610009E02Rik     0.00        0     0.00        0        0        0        0
0610009L18Rik     0.00        0     0.00        0        0        0        0
0610010K14Rik   996.50      995   945.00     1219     1063      964      865
              Inbred.8 Inbred.9 Inbred.10 Inbred.11 Inbred.12 Inbred.13
0610006L08Rik        0        0         0       0.0         0         0
0610009B22Rik      539      512       472     459.0       539       514
0610009E02Rik        0        0         0       0.0         0         0
0610009L18Rik        0        0         0       0.0         0         0
0610010K14Rik      949     1038       666     779.5       837       858
              Inbred.14 Inbred.15 Inbred.16 Inbred.17 Inbred.18 Wild.1 Wild.2
0610006L08Rik         0         0       0.0         0         0    0.0      0
0610009B22Rik       532       503     525.0       545       576  432.0    516
0610009E02Rik         0         0       0.0         0         0    0.0      0
0610009L18Rik         0         0       0.0         0         0    0.0      0
0610010K14Rik       899       717     807.5       950       886  693.5    755
              Wild.3 Inbred.19 Inbred.20 Inbred.21 Inbred.22 Inbred.23
0610006L08Rik    0.0         0       0.0       0.0       0.0       0.0
0610009B22Rik  470.0       545     429.5     625.0     446.0     379.0
0610009E02Rik    0.0         0       0.0       0.0       0.0       0.0
0610009L18Rik    0.0         0       0.0       0.0       0.0       0.0
0610010K14Rik  789.5       757     878.5     867.5     852.5     799.5
              Inbred.24 Inbred.25 Inbred.26 Inbred.27 Inbred.28 Inbred.29
0610006L08Rik       0.0         0       0.0         0         0         0
0610009B22Rik     423.0       542     486.0       512       435       449
0610009E02Rik       0.0         0       0.0         0         0         0
0610009L18Rik       0.0         0       0.0         0         0         0
0610010K14Rik     910.5       829     710.5       709       672       766
              Inbred.30  Wild.4  Wild.5  Wild.6 Wild.7 Wild.8 Wild.9 Wild.10
0610006L08Rik       0.0    0.00    0.00    0.00    0.0    0.0      0      75
0610009B22Rik     419.0    5.00   10.00    5.00  716.5  552.0    586       0
0610009E02Rik       0.0    0.00    0.00    0.00    0.0    0.0      0     454
0610009L18Rik       0.0    0.00    0.00    0.00    0.0    0.0      0       0
0610010K14Rik     714.5 2968.25 3098.17 2820.25  906.5  892.5   1082       0
              Wild.11 Wild.12
0610006L08Rik      57   67.42
0610009B22Rik       0    0.00
0610009E02Rik     420  415.00
0610009L18Rik       0    0.00
0610010K14Rik       0    0.00
42807 more rows ...

In [ ]:
#DESeq and PCA and Dandogram 

#conda install -c bioconda bioconductor-deseq2 r-gplots r-rcolorbrewer r-ggplot2 r-tidyr r-ggrepel r-dplyr -y 
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

In [ ]:

#save results in this folder 
#mkdir -p  /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/AKR_J
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/inbredWild/P12.5")

In [ ]:
# Make a color scheme for heatmaps
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)
# First we tell DESeq which samples correspond to which tissues.

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"
conds

   sample
1  Inbred
2  Inbred
3  Inbred
4  Inbred
5  Inbred
6  Inbred
7  Inbred
8  Inbred
9  Inbred
10 Inbred
11 Inbred
12 Inbred
13 Inbred
14 Inbred
15 Inbred
16 Inbred
17 Inbred
18 Inbred
19 Wild
20 Wild
21 Wild
22 Inbred
23 Inbred
24 Inbred
25 Inbred
26 Inbred
27 Inbred
28 Inbred
29 Inbred
30 Inbred
31 Inbred
32 Inbred
33 Inbred
34 Wild
35 Wild
36 Wild
37 Wild
38 Wild
39 Wild
40 Wild
41 Wild
42 Wild

In [ ]:
# Now we build a DESeq2 Count dataset and normalize it.
mircounts <- rawdata_copy$counts
# Reorder columns
#mircounts = mircounts[lables_order]
cds <- DESeqDataSetFromMatrix(countData = round(mircounts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
estimating size factors

estimating dispersions

gene-wise dispersion estimates: 124 workers

mean-dispersion relationship

final dispersion estimates, fitting model and testing: 124 workers

-- replacing outliers and refitting for 13455 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

In [ ]:
colnames(mircounts)

 [1] "Inbred.1"  "Inbred.2"  "Inbred.3"  "Inbred.4"  "Inbred.5"  "Inbred.6"
 [7] "Inbred.7"  "Inbred.8"  "Inbred.9"  "Inbred.10" "Inbred.11" "Inbred.12"
[13] "Inbred.13" "Inbred.14" "Inbred.15" "Inbred.16" "Inbred.17" "Inbred.18"
[19] "Wild.1"    "Wild.2"    "Wild.3"    "Inbred.19" "Inbred.20" "Inbred.21"
[25] "Inbred.22" "Inbred.23" "Inbred.24" "Inbred.25" "Inbred.26" "Inbred.27"
[31] "Inbred.28" "Inbred.29" "Inbred.30" "Wild.4"    "Wild.5"    "Wild.6"
[37] "Wild.7"    "Wild.8"    "Wild.9"    "Wild.10"   "Wild.11"   "Wild.12"

In [ ]:
lables

 [1] "129S1_SvImJ-16.5dpc.1" "129S1_SvImJ-16.5dpc.2" "129S1_SvImJ-16.5dpc.3"
 [4] "A_J-16.5dpc.1"         "A_J-16.5dpc.2"         "A_J-16.5dpc.3"
 [7] "AKR_J-16.5dpc.1"       "AKR_J-16.5dpc.2"       "AKR_J-16.5dpc.3"
[10] "BALB_cJ-16.5dpc.1"     "BALB_cJ-16.5dpc.2"     "BALB_cJ-16.5dpc.3"
[13] "C3H_HeJ-16.5dpc.1"     "C3H_HeJ-16.5dpc.2"     "C3H_HeJ-16.5dpc.3"
[16] "C57BL_6NJ-16.5dpc.1"   "C57BL_6NJ-16.5dpc.2"   "C57BL_6NJ-16.5dpc.3"
[19] "CAST_EiJ-16.5dpc.1"    "CAST_EiJ-16.5dpc.2"    "CAST_EiJ-16.5dpc.3"
[22] "CBA_J-16.5dpc.1"       "CBA_J-16.5dpc.2"       "CBA_J-16.5dpc.3"
[25] "DBA_2J-16.5dpc.1"      "DBA_2J-16.5dpc.2"      "DBA_2J-16.5dpc.3"
[28] "FVB_NJ-16.5dpc.1"      "FVB_NJ-16.5dpc.2"      "FVB_NJ-16.5dpc.3"
[31] "NOD_ShiLtJ-16.5dpc.1"  "NOD_ShiLtJ-16.5dpc.2"  "NOD_ShiLtJ-16.5dpc.3"
[34] "PWK_PhJ-16.5dpc.1"     "PWK_PhJ-16.5dpc.2"     "PWK_PhJ-16.5dpc.3"
[37] "SPRET_EiJ-16.5dpc.1"   "SPRET_EiJ-16.5dpc.2"   "SPRET_EiJ-16.5dpc.3"
[40] "WSB_EiJ-16.5dpc.1"     "WSB_EiJ-16.5dpc.2"     "WSB_EiJ-16.5dpc.3"

In [ ]:
samplenames

 [1] "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred"
 [9] "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred"
[17] "Inbred" "Inbred" "Wild"   "Wild"   "Wild"   "Inbred" "Inbred" "Inbred"
[25] "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred" "Inbred"
[33] "Inbred" "Wild"   "Wild"   "Wild"   "Wild"   "Wild"   "Wild"   "Wild"
[41] "Wild"   "Wild"

In [ ]:
#rlog normalisations
rl=vst(cds)
pdf("P12.5_inbred_wild+BarGraphBeforeAfter.pdf",paper="a4")
par(mfrow=c(2,1))

par(mar=c(10,4,0,2)) # increase y-axis margin.
prenorm=apply(mircounts,2,sum)
barplot(prenorm,col=as.factor(samplenames),las=2,names=samplenames)
postnorm=apply(counts(cds,normalized=TRUE),2,sum)
barplot(postnorm,col=as.factor(samplenames),las=2,names=samplenames)
dev.off()

png
  2

In [ ]:
###
# Margins area


pdf("P12.5_inbred_wild_InitialHeatMap.pdf",paper="special",width=15000, height=15000,title="E16,5",fillOddEven=T)
heatmap.2(cor(mircounts),trace="none",col=hmcol,main="Sample Correlation",cexRow=800,cexCol=800,
    margins=c(9000,9000),na.rm=T,key=T,offsetRow=300,offsetCol=300,keysize=1,density.info='histogram')
dev.off()

png
  2

In [ ]:
##And the Spearman Dendogram
foo_sub_1 = counts(cds, normalized = TRUE)

foo_cor_1 = cor(foo_sub_1, method = "spearman") #builds matrix of Spearman corrn and euclidean distances

foo_cor_dist_1 = dist(foo_cor_1, method = "euclidean")
pdf(file="E12.5_inbred_wild_dendrogram.pdf", height=8, width=15)
plot(hclust(foo_cor_dist_1))
dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

contrast_list <- list(
  c('sample', 'Inbred', 'Wild')
  # Add more contrasts here if needed
)

# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)

go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enriched_terms <- enrichGO(gene = DEGs,
                             OrgDb = org.Mm.eg.db,
                             keyType = "SYMBOL",
                             ont = "BP",
                             pAdjustMethod = "BH",
                             pvalueCutoff = 0.05)
  
  # Order the enriched terms by p-value in decreasing order
  top_terms <- enriched_terms[order(enriched_terms$`pvalue`), ]
  
  # Return both the top terms and the DEGs for downstream use
  list(top_terms = top_terms, DEGs = DEGs)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

In [ ]:
# Create the directory if it doesn't exist
if (!file.exists("go-ontology-plots")) {
  dir.create("go-ontology-plots")
}

# Now let's create and save separate bar plots using the stored top terms and DEGs
for (i in 1:length(contrast_list)) {
  top_term <- go_enrichment_list[[i]]$top_term
  DEGs <- go_enrichment_list[[i]]$DEGs
  contrast_name <- paste(contrast_list[[i]], collapse = "_vs_")
  
  barplot_data <- data.frame(Term = top_term$Description,
                             PValue = as.numeric(top_term$`pvalue`))  # Convert to numeric
  
  barplot_data <- barplot_data[order(barplot_data$PValue, decreasing = TRUE), ]
  
  # Determine upregulated (positive log2FC) and downregulated (negative log2FC) genes
  res <- results(cds, contrast = contrast_list[[i]])
  upregulated_genes <- DEGs[res[DEGs, "log2FoldChange"] > 0]
  downregulated_genes <- DEGs[res[DEGs, "log2FoldChange"] < 0]
  
  # Assign colors based on upregulation and downregulation
  colors <- rep("skyblue", nrow(barplot_data))
  colors[barplot_data$Term %in% upregulated_genes] <- "red"
  colors[barplot_data$Term %in% downregulated_genes] <- "green"

  # Remove "sample-vs_" from contrast_name
  contrast_name <- gsub("sample_vs_", "", contrast_name)
  
   # Subset to include only the top 20 terms
  barplot_data <- barplot_data[1:20, ]
  
  pdf(file.path("go-ontology-plots", paste(contrast_name, ".pdf", sep = "")), width = 15, height = 8)
  # Adjust the margins and orientation of the bar plot
  par(mar = c(8, 40, 2, 2))  # Set margins (bottom, left, top, right)
  barplot(barplot_data$PValue, names.arg = barplot_data$Term, horiz = TRUE,
          main = paste(contrast_name),las = 2,
          col = colors)
  dev.off()
}

In [ ]:


contrast_list <- list(
  c('sample', 'Inbred', 'Wild')
  # Add more contrasts here if needed
)
# Load required libraries
library(foreach)
library(doParallel)
library(EnhancedVolcano)  # Make sure you have this package installed

# Create a directory to save the plots
if (!dir.exists("volcano_plots")) {
    dir.create("volcano_plots")
}

# Set up parallel processing
num_cores <- 50  # Set the number of CPU cores to use
registerDoParallel(cores = num_cores)

# Define a function for generating a volcano plot
generate_volcano_plot <- function(contrast, cds) {
    col1 <- contrast[2]
    col2 <- contrast[3]
    
    res <- results(cds, contrast = contrast)

    volcano_plot <- EnhancedVolcano(res,
                                        lab = rownames(res),
                                        x = 'log2FoldChange',
                                        y = 'pvalue',
                                        title = paste(col1, "vs", col2, "Volcano Plot"),
                                        pCutoff = 0.05,
                                        FCcutoff = 2,
                                        col=  c('green', 'black', 'blue', 'red3'),
                                        colAlpha = 1,    cutoffLineType = 'blank',
                                        cutoffLineCol = 'black',
                                        cutoffLineWidth = 0.8,
                                        hline = c(10e-12, 10e-36, 10e-60, 10e-84),
                                        hlineCol = c('grey0', 'grey25','grey50','grey75'),
                                        hlineType = 'longdash',
                                        hlineWidth = 0.8,
                                        gridlines.major = FALSE,
                                        gridlines.minor = FALSE,
                                        xlim = c(-10, 10))
    # Add text labels for upregulated, downregulated, and nonsignificant genes            
    
            
    
    plot_filename <- paste("volcano_plots/", col1, "_vs_", col2, "_volcano_plot.png", sep = "")
    png(plot_filename, width = 1000, height = 1200)
    print(volcano_plot)
    dev.off()

}


# Run volcano plots in parallel for each contrast
foreach(contrast = contrast_list, .packages = c("EnhancedVolcano")) %dopar% {
    generate_volcano_plot(contrast, cds)
}

# Stop parallel processing
stopImplicitCluster()

[[1]]
png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-E16.5', 'BALB_cJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'A_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'FVB_NJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'C3H_HeJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'LP_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', '129S1_SvImJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'DBA_2J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'AKR_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CBA_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NZO_HlLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NOD_ShiLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'WSB_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CAST_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'PWK_PhJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'CAST_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'WSB_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'WSB_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'WSB_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'NZO_HlLtJ-E16.5', 'SPRET_EiJ-E16.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "MF", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`Count`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}


# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_E16.5_gene_ontology_MF.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "E16.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-E16.5', 'BALB_cJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'A_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'FVB_NJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'C3H_HeJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'LP_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', '129S1_SvImJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'DBA_2J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'AKR_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CBA_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NZO_HlLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NOD_ShiLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'WSB_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CAST_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'PWK_PhJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'CAST_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
    c('sample', 'WSB_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'WSB_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'WSB_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'NZO_HlLtJ-E16.5', 'SPRET_EiJ-E16.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "CC", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`Count`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}


# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_E16.5_gene_ontology_CC.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "E16.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:



# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-E16.5', 'BALB_cJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'A_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'FVB_NJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'C3H_HeJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'LP_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', '129S1_SvImJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'DBA_2J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'AKR_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CBA_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NZO_HlLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NOD_ShiLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'WSB_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CAST_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'PWK_PhJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'CAST_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
    c('sample', 'WSB_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'WSB_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'WSB_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'NZO_HlLtJ-E16.5', 'SPRET_EiJ-E16.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "BP", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}


# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_E16.5_gene_ontology_p_value_BP.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "E16.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-E16.5', 'BALB_cJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'A_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'FVB_NJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'C3H_HeJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'LP_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', '129S1_SvImJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'DBA_2J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'AKR_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CBA_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NZO_HlLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NOD_ShiLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'WSB_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CAST_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'PWK_PhJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'CAST_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
    c('sample', 'WSB_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'WSB_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'WSB_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'NZO_HlLtJ-E16.5', 'SPRET_EiJ-E16.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "MF", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}


# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_E16.5_gene_ontology_p_value_MF.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "E16.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-E16.5', 'BALB_cJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'A_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'FVB_NJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'C3H_HeJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'LP_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', '129S1_SvImJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'DBA_2J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'AKR_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CBA_J-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NZO_HlLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'NOD_ShiLtJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'WSB_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'CAST_EiJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'PWK_PhJ-E16.5'),
  c('sample', 'C57BL_6NJ-E16.5', 'SPRET_EiJ-E16.5'),
  c('sample', 'CAST_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
    c('sample', 'WSB_EiJ-E16.5', 'SPRET_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'WSB_EiJ-E16.5'),
   c('sample', 'CAST_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'WSB_EiJ-E16.5', 'NZO_HlLtJ-E16.5'),
   c('sample', 'NZO_HlLtJ-E16.5', 'SPRET_EiJ-E16.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "CC", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}


# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_E16.5_gene_ontology_P_value_CC.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "E16.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2