In [1]:
###testing R in jyupter 
system("type R")

In [2]:
#package installation 
#install.packages("purrr")
#install.packages("tidyverse")
#conda install r-tidyverse r-purrr bioconductor-edger bioconductor-busparse bioconductor-rtracklayer r-dplyr -y 
#conda install -c conda-forge r-purrr -y
#conda install -c bioconda bioconductor-edger -y
#conda install -c bioconda bioconductor-busparse -y
#conda install -c bioconda bioconductor-rtracklayer -y
#conda install -c conda-forge r-dplyr -y

In [3]:
library(purrr)
library(tidyverse)
library(edgeR)
library(rtracklayer)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: limma

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:limma’:

    plotMA


The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:lubridate’:

    second, second<-


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:tidyr’:

    expand


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:lubridate’:

    %within%


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:purrr’:

    reduce


Loading required package: GenomeInfoDb

In [4]:
library(purrr)
library(tidyverse)
f_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "20.5.+featureCounts$", full.names = T)

f_files

 [1] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts"
 [2] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts"
 [3] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts"
 [4] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts"
 [5] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts"
 [6] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts"
 [7] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts"
 [8] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts"
 [9] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts"
[10] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts"
[11] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts"
[12] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts"
[13] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts"
[14] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts"
[15] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts"
[16] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts"
[17] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts"
[18] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts"
[19] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts"
[20] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts"
[21] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts"
[22] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts"
[23] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts"
[24] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts"
[25] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts"
[26] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts"
[27] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts"
[28] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts"
[29] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts"
[30] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts"
[31] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts"
[32] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts"
[33] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts"
[34] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts"
[35] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts"
[36] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts"
[37] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts"
[38] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts"
[39] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts"
[40] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts"
[41] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts"
[42] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts"

In [5]:
samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames

 [1] "129S1_SvImJ-20.5dpp" "129S1_SvImJ-20.5dpp" "129S1_SvImJ-20.5dpp"
 [4] "A_J-20.5dpp"         "A_J-20.5dpp"         "A_J-20.5dpp"
 [7] "AKR_J-20.5dpp"       "AKR_J-20.5dpp"       "AKR_J-20.5dpp"
[10] "BALB_cJ-20.5dpp"     "BALB_cJ-20.5dpp"     "BALB_cJ-20.5dpp"
[13] "C3H_HeJ-20.5dpp"     "C3H_HeJ-20.5dpp"     "C3H_HeJ-20.5dpp"
[16] "C57BL_6NJ-20.5dpp"   "C57BL_6NJ-20.5dpp"   "C57BL_6NJ-20.5dpp"
[19] "CAST_EiJ-20.5dpp"    "CAST_EiJ-20.5dpp"    "CAST_EiJ-20.5dpp"
[22] "CBA_J-20.5dpp"       "CBA_J-20.5dpp"       "CBA_J-20.5dpp"
[25] "DBA_2J-20.5dpp"      "DBA_2J-20.5dpp"      "DBA_2J-20.5dpp"
[28] "FVB_NJ-20.5dpp"      "FVB_NJ-20.5dpp"      "FVB_NJ-20.5dpp"
[31] "NOD_ShiLtJ-20.5dpp"  "NOD_ShiLtJ-20.5dpp"  "NOD_ShiLtJ-20.5dpp"
[34] "PWK_PhJ-20.5dpp"     "PWK_PhJ-20.5dpp"     "PWK_PhJ-20.5dpp"
[37] "SPRET_EiJ-20.5dpp"   "SPRET_EiJ-20.5dpp"   "SPRET_EiJ-20.5dpp"
[40] "WSB_EiJ-20.5dpp"     "WSB_EiJ-20.5dpp"     "WSB_EiJ-20.5dpp"

In [6]:
samplenames <- c('129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','A_J-P20.5','A_J-P20.5',
'A_J-P20.5','AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5','CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5','DBA_2J-P20.5',
'DBA_2J-P20.5','DBA_2J-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5')

In [7]:
#list of sample names with replicates 
lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))

lables

 [1] "129S1_SvImJ-20.5dpp.1" "129S1_SvImJ-20.5dpp.2" "129S1_SvImJ-20.5dpp.3"
 [4] "A_J-20.5dpp.1"         "A_J-20.5dpp.2"         "A_J-20.5dpp.3"
 [7] "AKR_J-20.5dpp.1"       "AKR_J-20.5dpp.2"       "AKR_J-20.5dpp.3"
[10] "BALB_cJ-20.5dpp.1"     "BALB_cJ-20.5dpp.2"     "BALB_cJ-20.5dpp.3"
[13] "C3H_HeJ-20.5dpp.1"     "C3H_HeJ-20.5dpp.2"     "C3H_HeJ-20.5dpp.3"
[16] "C57BL_6NJ-20.5dpp.1"   "C57BL_6NJ-20.5dpp.2"   "C57BL_6NJ-20.5dpp.3"
[19] "CAST_EiJ-20.5dpp.1"    "CAST_EiJ-20.5dpp.2"    "CAST_EiJ-20.5dpp.3"
[22] "CBA_J-20.5dpp.1"       "CBA_J-20.5dpp.2"       "CBA_J-20.5dpp.3"
[25] "DBA_2J-20.5dpp.1"      "DBA_2J-20.5dpp.2"      "DBA_2J-20.5dpp.3"
[28] "FVB_NJ-20.5dpp.1"      "FVB_NJ-20.5dpp.2"      "FVB_NJ-20.5dpp.3"
[31] "NOD_ShiLtJ-20.5dpp.1"  "NOD_ShiLtJ-20.5dpp.2"  "NOD_ShiLtJ-20.5dpp.3"
[34] "PWK_PhJ-20.5dpp.1"     "PWK_PhJ-20.5dpp.2"     "PWK_PhJ-20.5dpp.3"
[37] "SPRET_EiJ-20.5dpp.1"   "SPRET_EiJ-20.5dpp.2"   "SPRET_EiJ-20.5dpp.3"
[40] "WSB_EiJ-20.5dpp.1"     "WSB_EiJ-20.5dpp.2"     "WSB_EiJ-20.5dpp.3"

In [8]:
lables <- c('129S1_SvImJ-P20.5.1','129S1_SvImJ-P20.5.2','129S1_SvImJ-P20.5.3','A_J-P20.5.1',
'A_J-P20.5.2','A_J-P20.5.3','AKR_J-P20.5.1','AKR_J-P20.5.2','AKR_J-P20.5.3','BALB_cJ-P20.5.1',
'BALB_cJ-P20.5.2','BALB_cJ-P20.5.3','C3H_HeJ-P20.5.1','C3H_HeJ-P20.5.2','C3H_HeJ-P20.5.3',
'C57BL_6NJ-P20.5.1','C57BL_6NJ-P20.5.2','C57BL_6NJ-P20.5.3','CAST_EiJ-P20.5.1','CAST_EiJ-P20.5.2',
'CAST_EiJ-P20.5.3','CBA_J-P20.5.1','CBA_J-P20.5.2','CBA_J-P20.5.3','DBA_2J-P20.5.1','DBA_2J-P20.5.2',
'DBA_2J-P20.5.3','FVB_NJ-P20.5.1','FVB_NJ-P20.5.2','FVB_NJ-P20.5.3',
'NOD_ShiLtJ-P20.5.1',
'NOD_ShiLtJ-P20.5.2','NOD_ShiLtJ-P20.5.3','PWK_PhJ-P20.5.1','PWK_PhJ-P20.5.2','PWK_PhJ-P20.5.3',
'SPRET_EiJ-P20.5.1','SPRET_EiJ-P20.5.2','SPRET_EiJ-P20.5.3','WSB_EiJ-P20.5.1','WSB_EiJ-P20.5.2','WSB_EiJ-P20.5.3')

In [9]:
#samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames_order = c('C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'A_J-P20.5','A_J-P20.5','A_J-P20.5',
'FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5',
'CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')

In [10]:
#list of sample names with replicates 
#lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))
lables_order = c('C57BL_6NJ-P20.5.1','C57BL_6NJ-P20.5.2','C57BL_6NJ-P20.5.3',
'BALB_cJ-P20.5.1','BALB_cJ-P20.5.2','BALB_cJ-P20.5.3',
'A_J-P20.5.1','A_J-P20.5.2','A_J-P20.5.3',
'FVB_NJ-P20.5.1','FVB_NJ-P20.5.2','FVB_NJ-P20.5.3',
'C3H_HeJ-P20.5.1','C3H_HeJ-P20.5.2','C3H_HeJ-P20.5.3',
'129S1_SvImJ-P20.5.1','129S1_SvImJ-P20.5.2','129S1_SvImJ-P20.5.3',
'DBA_2J-P20.5.1','DBA_2J-P20.5.2','DBA_2J-P20.5.3',
'AKR_J-P20.5.1','AKR_J-P20.5.2','AKR_J-P20.5.3',
'CBA_J-P20.5.1','CBA_J-P20.5.2','CBA_J-P20.5.3',
'NOD_ShiLtJ-P20.5.1','NOD_ShiLtJ-P20.5.2','NOD_ShiLtJ-P20.5.3',
'WSB_EiJ-P20.5.1','WSB_EiJ-P20.5.2','WSB_EiJ-P20.5.3',
'CAST_EiJ-P20.5.1','CAST_EiJ-P20.5.2','CAST_EiJ-P20.5.3',
'PWK_PhJ-P20.5.1','PWK_PhJ-P20.5.2','PWK_PhJ-P20.5.3',
'SPRET_EiJ-P20.5.1','SPRET_EiJ-P20.5.2','SPRET_EiJ-P20.5.3')

In [11]:
raw <- readDGE(f_files, columns = c(1, 7), comment.char = "#", sep="\t", group= samplenames, labels = lables,)

In [12]:
rawdata <- raw

In [13]:
A129S1_SvImJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/129S1_SvImJ_v3.2.gff3") #import gff3 file 
A129S1_SvImJ_geneName = na.omit(mcols(A129S1_SvImJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

A_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/A_J_v3.2.gff3") #import gff3 file 
A_J_geneName = na.omit(mcols(A_J )[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

AKR_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/AKR_J_v3.2.gff3") #import gff3 file 
AKR_J_geneName = na.omit(mcols(AKR_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

BALB_cJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/BALB_cJ_v3.2.gff3") #import gff3 file 
BALB_cJ_geneName = na.omit(mcols(BALB_cJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C3H_HeJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C3H_HeJ_v3.2.gff3") #import gff3 file 
C3H_HeJ_geneName = na.omit(mcols(C3H_HeJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

C57BL_6NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C57BL_6NJ_v3.2.gff3") #import gff3 file 
C57BL_6NJ_geneName = na.omit(mcols(C57BL_6NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CAST_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CAST_EiJ_v3.2.gff3") #import gff3 file 
CAST_EiJ_geneName = na.omit(mcols(CAST_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

CBA_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CBA_J_v3.2.gff3") #import gff3 file 
CBA_J_geneName = na.omit(mcols(CBA_J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

DBA_2J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/DBA_2J_v3.2.gff3") #import gff3 file 
DBA_2J_geneName = na.omit(mcols(DBA_2J)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

FVB_NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/FVB_NJ_v3.2.gff3") #import gff3 file 
FVB_NJ_geneName = na.omit(mcols(FVB_NJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 


NOD_ShiLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NOD_ShiLtJ_v3.2.gff3") #import gff3 file 
NOD_ShiLtJ_geneName = na.omit(mcols(NOD_ShiLtJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

PWK_PhJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/PWK_PhJ_v3.2.gff3") #import gff3 file 
PWK_PhJ_geneName = na.omit(mcols(PWK_PhJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 

SPRET_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/SPRET_EiJ_v3.2.gff3") #import gff3 file 
SPRET_EiJ_geneName = na.omit(mcols(SPRET_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id 


WSB_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/WSB_EiJ_v3.2.gff3") #import gff3 file 
WSB_EiJ_geneName = na.omit(mcols(WSB_EiJ)[,c("gene_id","parent_gene_display_xref")]) #get gene symbloes for respective gene id

In [14]:
geneName <- do.call("rbind", list(A129S1_SvImJ_geneName, A_J_geneName, AKR_J_geneName, BALB_cJ_geneName, C3H_HeJ_geneName, C57BL_6NJ_geneName, CAST_EiJ_geneName, CBA_J_geneName, DBA_2J_geneName , FVB_NJ_geneName,   NOD_ShiLtJ_geneName ,    PWK_PhJ_geneName, SPRET_EiJ_geneName,WSB_EiJ_geneName ))
geneName

DataFrame with 720152 rows and 2 columns
                  gene_id parent_gene_display_xref
              <character>              <character>
1      ENSMUSG00200053149                   Ugt1a1
2      ENSMUSG00200053174                  Gm20528
3      ENSMUSG00200032800            4933401J01Rik
4      ENSMUSG00200032799                  Gm26206
5      ENSMUSG00200032797                     Xkr4
...                   ...                      ...
720148 ENSMUSG00010031589                 BC022960
720149 ENSMUSG00010023776                  Gm15245
720150 ENSMUSG00010023781                     Mid1
720151 ENSMUSG00010023777                  Gm25651
720152 ENSMUSG00010023774            4933400A11Rik

In [15]:
rownames(geneName) <- geneName$gene_id
geneName$gene_id <- NULL
geneName

DataFrame with 720152 rows and 1 column
                   parent_gene_display_xref
                                <character>
ENSMUSG00200053149                   Ugt1a1
ENSMUSG00200053174                  Gm20528
ENSMUSG00200032800            4933401J01Rik
ENSMUSG00200032799                  Gm26206
ENSMUSG00200032797                     Xkr4
...                                     ...
ENSMUSG00010031589                 BC022960
ENSMUSG00010023776                  Gm15245
ENSMUSG00010023781                     Mid1
ENSMUSG00010023777                  Gm25651
ENSMUSG00010023774            4933400A11Rik

In [16]:
library(dplyr)
rawdata$counts <- merge(x=raw$counts, y=geneName,by = 0,all.x=TRUE ) #left merge

In [17]:
rawdata_copy <- rawdata
rawdata_copy$counts['Row.names'] <- NULL #remove the columns name Row.names

In [18]:
rawdata_copy$counts <- rawdata_copy$counts[!is.na(rawdata_copy$counts$parent_gene_display_xref),] #remove NA 
rawdata_copy$counts

       129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P20.5.1
4      0                   0                   0                   0
10     0                   0                   0                   0
11     0                   0                   0                   0
12     0                   0                   0                   0
13     0                   0                   0                   0
14     0                   0                   0                   0
15     0                   0                   0                   0
16     0                   0                   0                   0
17     0                   0                   0                   0
18     0                   0                   0                   0
19     0                   0                   0                   0
20     0                   0                   0                   0
21     0                   0                   0                   0
22     0                   0                   0                   0
23     0                   0                   0                   0
24     0                   0                   0                   0
25     0                   0                   0                   0
26     0                   0                   0                   0
27     0                   0                   0                   0
28     0                   0                   0                   0
29     0                   0                   0                   0
30     0                   0                   0                   0
31     0                   0                   0                   0
32     0                   0                   0                   0
33     0                   0                   0                   0
34     0                   0                   0                   0
35     0                   0                   0                   0
36     0                   0                   0                   0
37     0                   0                   0                   0
38     0                   0                   0                   0
⋮      ⋮                   ⋮                   ⋮                   ⋮
323218 0                   0                   0                   0
323219 0                   0                   0                   0
323220 0                   0                   0                   0
323221 0                   0                   0                   0
323222 0                   0                   0                   0
323223 0                   0                   0                   0
323224 0                   0                   0                   0
323225 0                   0                   0                   0
323226 0                   0                   0                   0
323227 0                   0                   0                   0
323228 0                   0                   0                   0
323229 0                   0                   0                   0
323230 0                   0                   0                   0
323231 0                   0                   0                   0
323232 0                   0                   0                   0
323233 0                   0                   0                   0
323234 0                   0                   0                   0
323235 0                   0                   0                   0
323236 0                   0                   0                   0
323237 0                   0                   0                   0
323238 0                   0                   0                   0
323239 0                   0                   0                   0
323240 0                   0                   0                   0
323241 0                   0                   0                   0
323242 0                   0                   0                   0
323243 0                   0                   0                   0
323244 0                   0                   0                   0
323245 0                   0                   0                   0
323246 0                   0                   0                   0
323247 0                   0                   0                   0
       A_J-P20.5.2 A_J-P20.5.3 AKR_J-P20.5.1 AKR_J-P20.5.2 AKR_J-P20.5.3
4      0           0           0             0             0
10     0           0           0             0             0
11     0           0           0             0             0
12     0           0           0             0             0
13     0           0           0             0             0
14     0           0           0             0             0
15     0           0           0             0             0
16     0           0           0             0             0
17     0           0           0             0             0
18     0           0           0             0             0
19     0           0           0             0             0
20     0           0           0             0             0
21     0           0           0             0             0
22     0           0           0             0             0
23     0           0           0             0             0
24     0           0           0             0             0
25     0           0           0             0             0
26     0           0           0             0             0
27     0           0           0             0             0
28     0           0           0             0             0
29     0           0           0             0             0
30     0           0           0             0             0
31     0           0           0             0             0
32     0           0           0             0             0
33     0           0           0             0             0
34     0           0           0             0             0
35     0           0           0             0             0
36     0           0           0             0             0
37     0           0           0             0             0
38     0           0           0             0             0
⋮      ⋮           ⋮           ⋮             ⋮             ⋮
323218 0           0           1753.43       1751.92       1525.10
323219 0           0            235.92        247.39        204.36
323220 0           0              0.83          0.43          0.43
323221 0           0              0.38          0.33          0.40
323222 0           0              1.45          0.33          1.04
323223 0           0              6.80          6.56          6.69
323224 0           0              2.47          4.55          2.58
323225 0           0              1.27          0.75          0.62
323226 0           0              1.20          3.09          1.80
323227 0           0            584.00        596.50        563.50
323228 0           0              3.30          3.67          2.65
323229 0           0              1.13          0.87          0.66
323230 0           0              1.40          1.34          0.64
323231 0           0              3.27          3.63          2.86
323232 0           0              0.68          0.88          1.59
323233 0           0              2.52          3.14          1.92
323234 0           0              2.52          3.14          1.92
323235 0           0              3.33          0.67          1.33
323236 0           0              3.92          2.12          4.49
323237 0           0              0.50          0.00          0.00
323238 0           0              0.28          1.05          0.39
323239 0           0              1.05          0.41          1.68
323240 0           0             15.80         19.69         15.87
323241 0           0              1.32          0.71          0.41
323242 0           0              0.69          0.09          0.69
323243 0           0              0.00          0.00          0.00
323244 0           0              0.00          0.00          0.00
323245 0           0              0.00          0.00          0.00
323246 0           0              0.00          0.00          0.00
323247 0           0              0.00          0.00          0.00
       BALB_cJ-P20.5.1 ⋯ PWK_PhJ-P20.5.1 PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3
4      0               ⋯ 0               0               0
10     0               ⋯ 0               0               0
11     0               ⋯ 0               0               0
12     0               ⋯ 0               0               0
13     0               ⋯ 0               0               0
14     0               ⋯ 0               0               0
15     0               ⋯ 0               0               0
16     0               ⋯ 0               0               0
17     0               ⋯ 0               0               0
18     0               ⋯ 0               0               0
19     0               ⋯ 0               0               0
20     0               ⋯ 0               0               0
21     0               ⋯ 0               0               0
22     0               ⋯ 0               0               0
23     0               ⋯ 0               0               0
24     0               ⋯ 0               0               0
25     0               ⋯ 0               0               0
26     0               ⋯ 0               0               0
27     0               ⋯ 0               0               0
28     0               ⋯ 0               0               0
29     0               ⋯ 0               0               0
30     0               ⋯ 0               0               0
31     0               ⋯ 0               0               0
32     0               ⋯ 0               0               0
33     0               ⋯ 0               0               0
34     0               ⋯ 0               0               0
35     0               ⋯ 0               0               0
36     0               ⋯ 0               0               0
37     0               ⋯ 0               0               0
38     0               ⋯ 0               0               0
⋮      ⋮               ⋱ ⋮               ⋮               ⋮
323218 0               ⋯ 0               0               0
323219 0               ⋯ 0               0               0
323220 0               ⋯ 0               0               0
323221 0               ⋯ 0               0               0
323222 0               ⋯ 0               0               0
323223 0               ⋯ 0               0               0
323224 0               ⋯ 0               0               0
323225 0               ⋯ 0               0               0
323226 0               ⋯ 0               0               0
323227 0               ⋯ 0               0               0
323228 0               ⋯ 0               0               0
323229 0               ⋯ 0               0               0
323230 0               ⋯ 0               0               0
323231 0               ⋯ 0               0               0
323232 0               ⋯ 0               0               0
323233 0               ⋯ 0               0               0
323234 0               ⋯ 0               0               0
323235 0               ⋯ 0               0               0
323236 0               ⋯ 0               0               0
323237 0               ⋯ 0               0               0
323238 0               ⋯ 0               0               0
323239 0               ⋯ 0               0               0
323240 0               ⋯ 0               0               0
323241 0               ⋯ 0               0               0
323242 0               ⋯ 0               0               0
323243 0               ⋯ 0               0               0
323244 0               ⋯ 0               0               0
323245 0               ⋯ 0               0               0
323246 0               ⋯ 0               0               0
323247 0               ⋯ 0               0               0
       SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3 WSB_EiJ-P20.5.1
4       135.83             92.67             71.00           0
10        0.00              0.00              0.00           0
11      133.00            218.00            215.00           0
12       15.73             45.64             55.05           0
13     5279.29           4784.79           3860.91           0
14      441.00            418.00            337.00           0
15      538.62            598.00            554.68           0
16      250.00            220.00            171.75           0
17        7.33              7.00              9.50           0
18      148.50            101.00            107.00           0
19        0.33              0.50              1.50           0
20        2.83              3.50              2.50           0
21       41.50             26.50             27.00           0
22       32.00             18.00             21.00           0
23     1232.10           1619.30           1691.11           0
24      218.00            223.00            206.00           0
25     3057.00           3116.67           2567.98           0
26        1.00              0.00              0.00           0
27      137.00            178.50            167.00           0
28     1663.75           1323.00           1185.75           0
29     1244.72           1240.98           1206.27           0
30     1604.50           1580.86           1393.25           0
31     4129.75           4087.00           3787.00           0
32     1479.50           1512.50           1466.75           0
33       72.00             65.17             67.00           0
34      166.50            235.00            243.50           0
35      512.00            555.50            566.00           0
36      774.50            828.00            904.00           0
37     3215.33           3036.83           2835.00           0
38      777.00            760.00            706.00           0
⋮      ⋮                 ⋮                 ⋮                 ⋮
323218 0                 0                 0                 0
323219 0                 0                 0                 0
323220 0                 0                 0                 0
323221 0                 0                 0                 0
323222 0                 0                 0                 0
323223 0                 0                 0                 0
323224 0                 0                 0                 0
323225 0                 0                 0                 0
323226 0                 0                 0                 0
323227 0                 0                 0                 0
323228 0                 0                 0                 0
323229 0                 0                 0                 0
323230 0                 0                 0                 0
323231 0                 0                 0                 0
323232 0                 0                 0                 0
323233 0                 0                 0                 0
323234 0                 0                 0                 0
323235 0                 0                 0                 0
323236 0                 0                 0                 0
323237 0                 0                 0                 0
323238 0                 0                 0                 0
323239 0                 0                 0                 0
323240 0                 0                 0                 0
323241 0                 0                 0                 0
323242 0                 0                 0                 0
323243 0                 0                 0                 0
323244 0                 0                 0                 0
323245 0                 0                 0                 0
323246 0                 0                 0                 0
323247 0                 0                 0                 0
       WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3 parent_gene_display_xref
4      0               0               Gm37340
10     0               0               Ptf1a
11     0               0               Msrb2
12     0               0               4921504E06Rik
13     0               0               Upf2
14     0               0               Proser2
15     0               0               Dhtkd1
16     0               0               Echdc3
17     0               0               C1ql3
18     0               0               Pter
19     0               0               Gm37811
20     0               0               Gm37824
21     0               0               Gm37255
22     0               0               Gm38014
23     0               0               Fam107b
24     0               0               Cdnf
25     0               0               Brd3
26     0               0               Lcn4
27     0               0               Abo
28     0               0               Rxra
29     0               0               Rpl7a
30     0               0               Surf6
31     0               0               Wdr5
32     0               0               Med22
33     0               0               Ajm1
34     0               0               Phpt1
35     0               0               Mamdc4
36     0               0               Edf1
37     0               0               Rabl6
38     0               0               Kin
⋮      ⋮               ⋮               ⋮
323218 0               0               Gm10184
323219 0               0               Rpl7a
323220 0               0               Gm37665
323221 0               0               Gm37665
323222 0               0               Gm42687
323223 0               0               Gm38046
323224 0               0               Gm45663
323225 0               0               Gm21897
323226 0               0               Gm21897
323227 0               0               Bud31
323228 0               0               Gm45663
323229 0               0               Gm37665
323230 0               0               Gm21897
323231 0               0               Gm48377
323232 0               0               Gm44078
323233 0               0               Gm37110
323234 0               0               Gm44792
323235 0               0               Gm48377
323236 0               0               Gm43520
323237 0               0               Gm43198
323238 0               0               Gm37665
323239 0               0               Gm37665
323240 0               0               Magea6
323241 0               0               Gm43520
323242 0               0               Gm37665
323243 0               0               Gm42959
323244 0               0               Gm3424
323245 0               0               Gm5849
323246 0               0               Speer4e
323247 0               0               Gm47571

In [19]:

rawdata_copy$counts <- rawdata_copy$counts %>% 
  group_by(parent_gene_display_xref) %>% 
  summarise(across(everything(), sum))

#rawdata_copy$counts <- aggregate(. ~ parent_gene_display_xref, rawdata_copy, sum, na.rm = TRUE)

In [20]:

rawdata_copy$counts <- as.data.frame(rawdata_copy$counts[!duplicated(rawdata_copy$counts$parent_gene_display_xref), ])  #remove dulicate values 
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                             files
129S1_SvImJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts
129S1_SvImJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts
129S1_SvImJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts
A_J-P20.5.1                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts
A_J-P20.5.2                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts
                                group lib.size norm.factors
129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5 31695878            1
129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5 34592855            1
129S1_SvImJ-P20.5.3 129S1_SvImJ-P20.5 31849719            1
A_J-P20.5.1                 A_J-P20.5 31363174            1
A_J-P20.5.2                 A_J-P20.5 30304673            1
37 more rows ...

$counts
  parent_gene_display_xref 129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2
1            0610006L08Rik                   0                   0
2            0610009B22Rik                 918                1021
3            0610009E02Rik                   0                   0
4            0610009L18Rik                   0                   0
5            0610010K14Rik                 435                 423
  129S1_SvImJ-P20.5.3 A_J-P20.5.1 A_J-P20.5.2 A_J-P20.5.3 AKR_J-P20.5.1
1                   0         0.0         0.0           0             0
2                 710       809.0       660.0         630           879
3                   0         0.0         0.0           0             0
4                   0         0.0         0.0           0             0
5                 394       470.5       462.5         451           466
  AKR_J-P20.5.2 AKR_J-P20.5.3 BALB_cJ-P20.5.1 BALB_cJ-P20.5.2 BALB_cJ-P20.5.3
1           0.0           0.0             0.0               0               0
2         872.0         785.5           599.0             530             724
3           0.0           0.0             0.0               0               0
4           0.0           0.0             0.0               0               0
5         492.5         435.0           616.5             646             634
  C3H_HeJ-P20.5.1 C3H_HeJ-P20.5.2 C3H_HeJ-P20.5.3 C57BL_6NJ-P20.5.1
1               0             0.0               0                 0
2             792           816.0             718               610
3               0             0.0               0                 0
4               0             0.0               0                 0
5             369           407.5             392               437
  C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5.3 CAST_EiJ-P20.5.1 CAST_EiJ-P20.5.2
1                 0               0.0                0                0
2               790             812.0              530              469
3                 0               0.0                0                0
4                 0               0.0                0                0
5               466             412.5              454              493
  CAST_EiJ-P20.5.3 CBA_J-P20.5.1 CBA_J-P20.5.2 CBA_J-P20.5.3 DBA_2J-P20.5.1
1                0           0.0           0.0             0            0.0
2              404         712.0         699.0           615          724.0
3                0           0.0           0.0             0            0.0
4                0           0.0           0.0             0            0.0
5              641         602.5         495.5           519          518.5
  DBA_2J-P20.5.2 DBA_2J-P20.5.3 FVB_NJ-P20.5.1 FVB_NJ-P20.5.2 FVB_NJ-P20.5.3
1              0            0.0            0.0              0            0.0
2            836          859.0          690.0            701          623.0
3              0            0.0            0.0              0            0.0
4              0            0.0            0.0              0            0.0
5            470          501.5          491.5            513          494.5
  NOD_ShiLtJ-P20.5.1 NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5.3 PWK_PhJ-P20.5.1
1                  0                  0                  0            0.00
2                553                609               1051            4.00
3                  0                  0                  0            0.00
4                  0                  0                  0            0.00
5                555                615                415         4127.17
  PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3 SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5.2
1               0               0                 0               0.0
2               2               1               476             496.0
3               0               0                 0               0.0
4               0               0                 0               0.0
5            4369            3784               761             793.5
  SPRET_EiJ-P20.5.3 WSB_EiJ-P20.5.1 WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
1               0.0              42           29.33              36
2             462.0               0            0.00               0
3               0.0             847          684.00             707
4               0.0               0            0.00               0
5             763.5               0            0.00               0
42807 more rows ...

In [21]:
rownames(rawdata_copy$counts) <- rawdata_copy$counts$parent_gene_display_xref #set rawname to gene symbloes 
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                             files
129S1_SvImJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts
129S1_SvImJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts
129S1_SvImJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts
A_J-P20.5.1                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts
A_J-P20.5.2                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts
                                group lib.size norm.factors
129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5 31695878            1
129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5 34592855            1
129S1_SvImJ-P20.5.3 129S1_SvImJ-P20.5 31849719            1
A_J-P20.5.1                 A_J-P20.5 31363174            1
A_J-P20.5.2                 A_J-P20.5 30304673            1
37 more rows ...

$counts
              parent_gene_display_xref 129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2
0610006L08Rik            0610006L08Rik                   0                   0
0610009B22Rik            0610009B22Rik                 918                1021
0610009E02Rik            0610009E02Rik                   0                   0
0610009L18Rik            0610009L18Rik                   0                   0
0610010K14Rik            0610010K14Rik                 435                 423
              129S1_SvImJ-P20.5.3 A_J-P20.5.1 A_J-P20.5.2 A_J-P20.5.3
0610006L08Rik                   0         0.0         0.0           0
0610009B22Rik                 710       809.0       660.0         630
0610009E02Rik                   0         0.0         0.0           0
0610009L18Rik                   0         0.0         0.0           0
0610010K14Rik                 394       470.5       462.5         451
              AKR_J-P20.5.1 AKR_J-P20.5.2 AKR_J-P20.5.3 BALB_cJ-P20.5.1
0610006L08Rik             0           0.0           0.0             0.0
0610009B22Rik           879         872.0         785.5           599.0
0610009E02Rik             0           0.0           0.0             0.0
0610009L18Rik             0           0.0           0.0             0.0
0610010K14Rik           466         492.5         435.0           616.5
              BALB_cJ-P20.5.2 BALB_cJ-P20.5.3 C3H_HeJ-P20.5.1 C3H_HeJ-P20.5.2
0610006L08Rik               0               0               0             0.0
0610009B22Rik             530             724             792           816.0
0610009E02Rik               0               0               0             0.0
0610009L18Rik               0               0               0             0.0
0610010K14Rik             646             634             369           407.5
              C3H_HeJ-P20.5.3 C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5.2
0610006L08Rik               0                 0                 0
0610009B22Rik             718               610               790
0610009E02Rik               0                 0                 0
0610009L18Rik               0                 0                 0
0610010K14Rik             392               437               466
              C57BL_6NJ-P20.5.3 CAST_EiJ-P20.5.1 CAST_EiJ-P20.5.2
0610006L08Rik               0.0                0                0
0610009B22Rik             812.0              530              469
0610009E02Rik               0.0                0                0
0610009L18Rik               0.0                0                0
0610010K14Rik             412.5              454              493
              CAST_EiJ-P20.5.3 CBA_J-P20.5.1 CBA_J-P20.5.2 CBA_J-P20.5.3
0610006L08Rik                0           0.0           0.0             0
0610009B22Rik              404         712.0         699.0           615
0610009E02Rik                0           0.0           0.0             0
0610009L18Rik                0           0.0           0.0             0
0610010K14Rik              641         602.5         495.5           519
              DBA_2J-P20.5.1 DBA_2J-P20.5.2 DBA_2J-P20.5.3 FVB_NJ-P20.5.1
0610006L08Rik            0.0              0            0.0            0.0
0610009B22Rik          724.0            836          859.0          690.0
0610009E02Rik            0.0              0            0.0            0.0
0610009L18Rik            0.0              0            0.0            0.0
0610010K14Rik          518.5            470          501.5          491.5
              FVB_NJ-P20.5.2 FVB_NJ-P20.5.3 NOD_ShiLtJ-P20.5.1
0610006L08Rik              0            0.0                  0
0610009B22Rik            701          623.0                553
0610009E02Rik              0            0.0                  0
0610009L18Rik              0            0.0                  0
0610010K14Rik            513          494.5                555
              NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5.3 PWK_PhJ-P20.5.1
0610006L08Rik                  0                  0            0.00
0610009B22Rik                609               1051            4.00
0610009E02Rik                  0                  0            0.00
0610009L18Rik                  0                  0            0.00
0610010K14Rik                615                415         4127.17
              PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3 SPRET_EiJ-P20.5.1
0610006L08Rik               0               0                 0
0610009B22Rik               2               1               476
0610009E02Rik               0               0                 0
0610009L18Rik               0               0                 0
0610010K14Rik            4369            3784               761
              SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3 WSB_EiJ-P20.5.1
0610006L08Rik               0.0               0.0              42
0610009B22Rik             496.0             462.0               0
0610009E02Rik               0.0               0.0             847
0610009L18Rik               0.0               0.0               0
0610010K14Rik             793.5             763.5               0
              WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
0610006L08Rik           29.33              36
0610009B22Rik            0.00               0
0610009E02Rik          684.00             707
0610009L18Rik            0.00               0
0610010K14Rik            0.00               0
42807 more rows ...

In [22]:
rawdata_copy$counts$parent_gene_display_xref <- NULL #remove gene symbole columns

In [23]:
rawdata_copy

An object of class "DGEList"
$samples
                                                                                                                                             files
129S1_SvImJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts
129S1_SvImJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts
129S1_SvImJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts
A_J-P20.5.1                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts
A_J-P20.5.2                 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts
                                group lib.size norm.factors
129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5 31695878            1
129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5 34592855            1
129S1_SvImJ-P20.5.3 129S1_SvImJ-P20.5 31849719            1
A_J-P20.5.1                 A_J-P20.5 31363174            1
A_J-P20.5.2                 A_J-P20.5 30304673            1
37 more rows ...

$counts
              129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3
0610006L08Rik                   0                   0                   0
0610009B22Rik                 918                1021                 710
0610009E02Rik                   0                   0                   0
0610009L18Rik                   0                   0                   0
0610010K14Rik                 435                 423                 394
              A_J-P20.5.1 A_J-P20.5.2 A_J-P20.5.3 AKR_J-P20.5.1 AKR_J-P20.5.2
0610006L08Rik         0.0         0.0           0             0           0.0
0610009B22Rik       809.0       660.0         630           879         872.0
0610009E02Rik         0.0         0.0           0             0           0.0
0610009L18Rik         0.0         0.0           0             0           0.0
0610010K14Rik       470.5       462.5         451           466         492.5
              AKR_J-P20.5.3 BALB_cJ-P20.5.1 BALB_cJ-P20.5.2 BALB_cJ-P20.5.3
0610006L08Rik           0.0             0.0               0               0
0610009B22Rik         785.5           599.0             530             724
0610009E02Rik           0.0             0.0               0               0
0610009L18Rik           0.0             0.0               0               0
0610010K14Rik         435.0           616.5             646             634
              C3H_HeJ-P20.5.1 C3H_HeJ-P20.5.2 C3H_HeJ-P20.5.3 C57BL_6NJ-P20.5.1
0610006L08Rik               0             0.0               0                 0
0610009B22Rik             792           816.0             718               610
0610009E02Rik               0             0.0               0                 0
0610009L18Rik               0             0.0               0                 0
0610010K14Rik             369           407.5             392               437
              C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5.3 CAST_EiJ-P20.5.1
0610006L08Rik                 0               0.0                0
0610009B22Rik               790             812.0              530
0610009E02Rik                 0               0.0                0
0610009L18Rik                 0               0.0                0
0610010K14Rik               466             412.5              454
              CAST_EiJ-P20.5.2 CAST_EiJ-P20.5.3 CBA_J-P20.5.1 CBA_J-P20.5.2
0610006L08Rik                0                0           0.0           0.0
0610009B22Rik              469              404         712.0         699.0
0610009E02Rik                0                0           0.0           0.0
0610009L18Rik                0                0           0.0           0.0
0610010K14Rik              493              641         602.5         495.5
              CBA_J-P20.5.3 DBA_2J-P20.5.1 DBA_2J-P20.5.2 DBA_2J-P20.5.3
0610006L08Rik             0            0.0              0            0.0
0610009B22Rik           615          724.0            836          859.0
0610009E02Rik             0            0.0              0            0.0
0610009L18Rik             0            0.0              0            0.0
0610010K14Rik           519          518.5            470          501.5
              FVB_NJ-P20.5.1 FVB_NJ-P20.5.2 FVB_NJ-P20.5.3 NOD_ShiLtJ-P20.5.1
0610006L08Rik            0.0              0            0.0                  0
0610009B22Rik          690.0            701          623.0                553
0610009E02Rik            0.0              0            0.0                  0
0610009L18Rik            0.0              0            0.0                  0
0610010K14Rik          491.5            513          494.5                555
              NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5.3 PWK_PhJ-P20.5.1
0610006L08Rik                  0                  0            0.00
0610009B22Rik                609               1051            4.00
0610009E02Rik                  0                  0            0.00
0610009L18Rik                  0                  0            0.00
0610010K14Rik                615                415         4127.17
              PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3 SPRET_EiJ-P20.5.1
0610006L08Rik               0               0                 0
0610009B22Rik               2               1               476
0610009E02Rik               0               0                 0
0610009L18Rik               0               0                 0
0610010K14Rik            4369            3784               761
              SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3 WSB_EiJ-P20.5.1
0610006L08Rik               0.0               0.0              42
0610009B22Rik             496.0             462.0               0
0610009E02Rik               0.0               0.0             847
0610009L18Rik               0.0               0.0               0
0610010K14Rik             793.5             763.5               0
              WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
0610006L08Rik           29.33              36
0610009B22Rik            0.00               0
0610009E02Rik          684.00             707
0610009L18Rik            0.00               0
0610010K14Rik            0.00               0
42807 more rows ...

In [24]:
#DESeq and PCA and Dandogram 

#conda install -c bioconda bioconductor-deseq2 r-gplots r-rcolorbrewer r-ggplot2 r-tidyr r-ggrepel r-dplyr -y 
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘gplots’


The following object is masked from ‘package:rtracklayer’:

    space


The following object is masked from ‘package:IRanges’:

    space


The following object is masked from ‘package:S4Vectors’:

    space


The following object is masked from ‘package:stats’:

    lowess

In [25]:

#save results in this folder 
#mkdir -p  /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/AKR_J
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/P20.5")

In [26]:
# Make a color scheme for heatmaps
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)
# First we tell DESeq which samples correspond to which tissues.

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"

In [27]:
mircounts <- rawdata_copy$counts
# Reorder columns
mircounts = mircounts[lables_order]
mircounts

              C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5.3
0610006L08Rik    0.00              0.00              0.00
0610009B22Rik  610.00            790.00            812.00
0610009E02Rik    0.00              0.00              0.00
0610009L18Rik    0.00              0.00              0.00
0610010K14Rik  437.00            466.00            412.50
0610012D04Rik    0.00              0.00              0.00
0610012G03Rik  520.50            605.50            625.50
0610025J13Rik    0.00              0.00              0.00
0610030E20Rik 1602.00           1762.00           1541.00
0610031O16Rik    0.00              0.00              0.00
0610033M10Rik    0.00              0.00              0.00
0610038B21Rik    0.00              0.00              0.00
0610039K10Rik    0.00              0.00              0.00
0610040B10Rik    0.00              0.00              0.00
0610040F04Rik    0.00              0.00              0.00
0610040J01Rik   43.40             61.77             34.06
0610043K17Rik    0.00              0.00              0.00
0710001A04Rik    0.00              0.00              0.00
1010001B22Rik    0.00              0.00              0.00
1100001I12Rik    0.00              0.00              0.00
1110002E22Rik    2.54              4.00              3.00
1110002J07Rik    0.00              0.00              0.00
1110003F10Rik   16.00              8.50              7.50
1110004F10Rik 4700.17           5030.99           4748.56
1110006O24Rik    0.00              0.00              0.00
1110008E08Rik    0.00              0.00              0.00
1110013H19Rik    0.00              0.00              0.00
1110015O18Rik    0.00              0.00              0.00
1110017D15Rik  265.25            385.00            402.50
1110018N20Rik    0.00              0.00              0.00
⋮             ⋮                 ⋮                 ⋮
n-R5s130      0                 0                 0
n-R5s133      0                 0                 0
n-R5s134      0                 0                 0
n-R5s136      0                 0                 0
n-R5s139      0                 0                 0
n-R5s141      0                 0                 0
n-R5s142      0                 0                 0
n-R5s143      0                 0                 0
n-R5s149      0                 0                 0
n-R5s151      0                 0                 0
n-R5s173      0                 0                 0
n-R5s185      0                 0                 0
n-R5s194      0                 0                 0
n-R5s195      0                 0                 0
n-R5s197      0                 0                 0
n-R5s2        0                 0                 0
n-R5s209      0                 0                 0
n-R5s210      0                 0                 0
n-R5s211      0                 0                 0
n-R5s25       0                 0                 0
n-R5s28       0                 0                 0
n-R5s33       0                 0                 0
n-R5s60       0                 0                 0
n-R5s65       0                 0                 0
n-R5s7        0                 0                 0
n-R5s71       0                 0                 0
n-R5s92       0                 0                 0
n-R5s93       0                 0                 0
snoZ159       0                 0                 0
snoZ196       0                 0                 0
              BALB_cJ-P20.5.1 BALB_cJ-P20.5.2 BALB_cJ-P20.5.3 A_J-P20.5.1
0610006L08Rik    0.00            0.00            0.00            0.00
0610009B22Rik  599.00          530.00          724.00          809.00
0610009E02Rik    0.00            0.00            0.00            0.00
0610009L18Rik    0.00            0.00            0.00            0.00
0610010K14Rik  616.50          646.00          634.00          470.50
0610012D04Rik    0.00            0.00            0.00            0.00
0610012G03Rik  448.50          470.50          516.00          564.50
0610025J13Rik    0.00            0.00            0.00            0.00
0610030E20Rik 1185.00         1207.00         1323.00         1771.00
0610031O16Rik    0.00            0.00            0.00            0.00
0610033M10Rik    0.00            0.00            0.00            0.00
0610038B21Rik    0.00            0.00            0.00            0.00
0610039K10Rik    0.00            0.00            0.00            0.00
0610040B10Rik    0.00            0.00            0.00            0.00
0610040F04Rik    0.00            0.00            0.00            0.00
0610040J01Rik   38.00           73.25           43.00           17.00
0610043K17Rik    0.00            0.00            0.00            0.00
0710001A04Rik    0.00            0.00            0.00            0.00
1010001B22Rik    0.00            0.00            0.00            0.00
1100001I12Rik    0.00            0.00            0.00            0.00
1110002E22Rik    0.00            2.00            3.00            2.00
1110002J07Rik    0.00            0.00            0.00            0.00
1110003F10Rik   11.50           22.00           11.50            7.50
1110004F10Rik 3976.68         4152.79         4560.69         4560.17
1110006O24Rik    0.00            0.00            0.00            0.00
1110008E08Rik    0.00            0.00            0.00            0.00
1110013H19Rik    0.00            0.00            0.00            0.00
1110015O18Rik    0.00            0.00            0.00            0.00
1110017D15Rik  206.93          160.50          272.20          367.28
1110018N20Rik    0.00            0.00            0.00            0.00
⋮             ⋮               ⋮               ⋮               ⋮
n-R5s130      0               0               0               0
n-R5s133      0               0               0               0
n-R5s134      0               0               0               0
n-R5s136      0               0               0               0
n-R5s139      0               0               0               0
n-R5s141      0               0               0               0
n-R5s142      0               0               0               0
n-R5s143      0               0               0               0
n-R5s149      0               0               0               0
n-R5s151      0               0               0               0
n-R5s173      0               0               0               0
n-R5s185      0               0               0               0
n-R5s194      0               0               0               0
n-R5s195      0               0               0               0
n-R5s197      0               0               0               0
n-R5s2        0               0               0               0
n-R5s209      0               0               0               0
n-R5s210      0               0               0               0
n-R5s211      0               0               0               0
n-R5s25       0               0               0               0
n-R5s28       0               0               0               0
n-R5s33       0               0               0               0
n-R5s60       0               0               0               0
n-R5s65       0               0               0               0
n-R5s7        0               0               0               0
n-R5s71       0               0               0               0
n-R5s92       0               0               0               0
n-R5s93       0               0               0               0
snoZ159       0               0               0               0
snoZ196       0               0               0               0
              A_J-P20.5.2 A_J-P20.5.3 FVB_NJ-P20.5.1 ⋯ WSB_EiJ-P20.5.3
0610006L08Rik    0.00        0.00        0.00        ⋯    36.00
0610009B22Rik  660.00      630.00      690.00        ⋯     0.00
0610009E02Rik    0.00        0.00        0.00        ⋯   707.00
0610009L18Rik    0.00        0.00        0.00        ⋯     0.00
0610010K14Rik  462.50      451.00      491.50        ⋯     0.00
0610012D04Rik    0.00        0.00        0.00        ⋯     0.00
0610012G03Rik  491.50      508.00      465.50        ⋯     0.00
0610025J13Rik    0.00        0.00        0.00        ⋯   176.50
0610030E20Rik 1688.00     1500.00     1573.00        ⋯  1398.67
0610031O16Rik    0.00        0.00        0.00        ⋯    17.00
0610033M10Rik    0.00        0.00        0.00        ⋯   143.00
0610038B21Rik    0.00        0.00        0.00        ⋯     0.00
0610039K10Rik    0.00        0.00        0.00        ⋯   476.00
0610040B10Rik    0.00        0.00        0.00        ⋯  4906.67
0610040F04Rik    0.00        0.00        0.00        ⋯   185.00
0610040J01Rik   28.00       26.11       32.50        ⋯     0.00
0610043K17Rik    0.00        0.00        0.00        ⋯   174.20
0710001A04Rik    0.00        0.00        0.00        ⋯   208.00
1010001B22Rik    0.00        0.00        0.00        ⋯     7.00
1100001I12Rik    0.00        0.00        0.00        ⋯     8.62
1110002E22Rik    2.00        2.00        3.50        ⋯     0.00
1110002J07Rik    0.00        0.00        0.00        ⋯ 12697.94
1110003F10Rik    8.50        5.00        7.33        ⋯     0.00
1110004F10Rik 4464.52     4064.40     4593.63        ⋯   163.00
1110006O24Rik    0.00        0.00        0.00        ⋯     0.00
1110008E08Rik    0.00        0.00        0.00        ⋯   251.26
1110013H19Rik    0.00        0.00        0.00        ⋯    53.29
1110015O18Rik    0.00        0.00        0.00        ⋯     0.00
1110017D15Rik  320.00      252.40      357.76        ⋯  2598.00
1110018N20Rik    0.00        0.00        0.00        ⋯  1143.50
⋮             ⋮           ⋮           ⋮              ⋱ ⋮
n-R5s130      0           0           0              ⋯   57.00
n-R5s133      0           0           0              ⋯    6.50
n-R5s134      0           0           0              ⋯ 1676.90
n-R5s136      0           0           0              ⋯    0.00
n-R5s139      0           0           0              ⋯ 5618.50
n-R5s141      0           0           0              ⋯    0.00
n-R5s142      0           0           0              ⋯ 2173.21
n-R5s143      0           0           0              ⋯    0.00
n-R5s149      0           0           0              ⋯    0.00
n-R5s151      0           0           0              ⋯ 1835.50
n-R5s173      0           0           0              ⋯ 3996.00
n-R5s185      0           0           0              ⋯    0.00
n-R5s194      0           0           0              ⋯  127.25
n-R5s195      0           0           0              ⋯ 4090.17
n-R5s197      0           0           0              ⋯ 2109.50
n-R5s2        0           0           0              ⋯   30.06
n-R5s209      0           0           0              ⋯    0.00
n-R5s210      0           0           0              ⋯    0.00
n-R5s211      0           0           0              ⋯    0.00
n-R5s25       0           0           0              ⋯    0.00
n-R5s28       0           0           0              ⋯    0.00
n-R5s33       0           0           0              ⋯    0.00
n-R5s60       0           0           0              ⋯    0.00
n-R5s65       0           0           0              ⋯    0.00
n-R5s7        0           0           0              ⋯    1.00
n-R5s71       0           0           0              ⋯    0.00
n-R5s92       0           0           0              ⋯    0.00
n-R5s93       0           0           0              ⋯    0.00
snoZ159       0           0           0              ⋯    0.00
snoZ196       0           0           0              ⋯    0.00
              CAST_EiJ-P20.5.1 CAST_EiJ-P20.5.2 CAST_EiJ-P20.5.3
0610006L08Rik    0.00             0.00             0.00
0610009B22Rik  530.00           469.00           404.00
0610009E02Rik    0.00             0.00             0.00
0610009L18Rik    0.00             0.00             0.00
0610010K14Rik  454.00           493.00           641.00
0610012D04Rik    0.00             0.00             0.00
0610012G03Rik  424.50           392.50           443.00
0610025J13Rik    0.00             0.00             0.00
0610030E20Rik 1367.50          1072.00          1083.50
0610031O16Rik    0.00             0.00             0.00
0610033M10Rik    0.00             0.00             0.00
0610038B21Rik    0.00             0.00             0.00
0610039K10Rik    0.00             0.00             0.00
0610040B10Rik    0.00             0.00             0.00
0610040F04Rik    0.00             0.00             0.00
0610040J01Rik   86.50           115.61           100.50
0610043K17Rik    0.00             0.00             0.00
0710001A04Rik    0.00             0.00             0.00
1010001B22Rik    0.00             0.00             0.00
1100001I12Rik    0.00             0.00             0.00
1110002E22Rik    1.00             2.00             1.00
1110002J07Rik    0.00             0.00             0.00
1110003F10Rik    5.50            11.00            11.50
1110004F10Rik 3918.31          3775.50          3789.02
1110006O24Rik    0.00             0.00             0.00
1110008E08Rik    0.00             0.00             0.00
1110013H19Rik    0.00             0.00             0.00
1110015O18Rik    0.00             0.00             0.00
1110017D15Rik  193.33           148.00           126.50
1110018N20Rik    0.00             0.00             0.00
⋮             ⋮                ⋮                ⋮
n-R5s130      0                0                0
n-R5s133      0                0                0
n-R5s134      0                0                0
n-R5s136      0                0                0
n-R5s139      0                0                0
n-R5s141      0                0                0
n-R5s142      0                0                0
n-R5s143      0                0                0
n-R5s149      0                0                0
n-R5s151      0                0                0
n-R5s173      0                0                0
n-R5s185      0                0                0
n-R5s194      0                0                0
n-R5s195      0                0                0
n-R5s197      0                0                0
n-R5s2        0                0                0
n-R5s209      0                0                0
n-R5s210      0                0                0
n-R5s211      0                0                0
n-R5s25       0                0                0
n-R5s28       0                0                0
n-R5s33       0                0                0
n-R5s60       0                0                0
n-R5s65       0                0                0
n-R5s7        0                0                0
n-R5s71       0                0                0
n-R5s92       0                0                0
n-R5s93       0                0                0
snoZ159       0                0                0
snoZ196       0                0                0
              PWK_PhJ-P20.5.1 PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3 SPRET_EiJ-P20.5.1
0610006L08Rik     0.00            0.00            0.00           0.00
0610009B22Rik     4.00            2.00            1.00         476.00
0610009E02Rik     0.00            0.00            0.00           0.00
0610009L18Rik     0.00            0.00            0.00           0.00
0610010K14Rik  4127.17         4369.00         3784.00         761.00
0610012D04Rik   253.06          294.19          211.31           0.00
0610012G03Rik 11742.22        11812.48        11439.54         344.67
0610025J13Rik  1331.50         1426.00         1308.00           0.00
0610030E20Rik     0.00            1.00            1.25         824.50
0610031O16Rik   780.00          829.50          667.50           0.00
0610033M10Rik     0.00            0.00            0.00           0.00
0610038B21Rik     1.24            1.60            0.75           0.00
0610039K10Rik  5231.47         5381.32         4508.62           0.00
0610040B10Rik    59.69           50.64           48.03           0.00
0610040F04Rik  2622.40         2730.87         2603.80           0.00
0610040J01Rik     0.00            0.00            0.00          22.00
0610043K17Rik     0.00            0.00            0.00           0.00
0710001A04Rik     0.00            0.00            0.00           0.00
1010001B22Rik     4.00            1.00            0.00           0.00
1100001I12Rik     0.00            0.00            0.00           0.00
1110002E22Rik     0.00            0.00            0.00           2.00
1110002J07Rik   296.00          325.00          227.00           0.00
1110003F10Rik     0.00            0.00            0.00          18.00
1110004F10Rik     0.00            0.28            0.14        3559.10
1110006O24Rik     0.00            0.00            1.00           0.00
1110008E08Rik   682.00          664.00          663.00           0.00
1110013H19Rik     0.00            0.00            0.00           0.00
1110015O18Rik     2.00            0.50            0.50           0.00
1110017D15Rik     0.00            0.00            0.00          62.00
1110018N20Rik     0.00            0.00            0.00           0.00
⋮             ⋮               ⋮               ⋮               ⋮
n-R5s130        586.24          515.21          404.77        0
n-R5s133          0.00            0.00            0.00        0
n-R5s134          0.00            0.00            0.00        0
n-R5s136       2371.50         2526.50         2376.00        0
n-R5s139          0.00            0.00            0.00        0
n-R5s141          0.00            0.00            0.00        0
n-R5s142          1.00            0.00            0.00        0
n-R5s143         19.00           10.00            4.00        0
n-R5s149       2900.00         3404.00         3051.50        0
n-R5s151          0.00            0.00            0.00        0
n-R5s173          0.00            0.00            0.00        0
n-R5s185        182.00          165.07          173.00        0
n-R5s194          0.00            0.00            0.00        0
n-R5s195          0.00            0.00            0.00        0
n-R5s197        157.00          132.00          101.00        0
n-R5s2           39.00           51.50           41.50        0
n-R5s209         98.00           89.50           98.00        0
n-R5s210       1240.50         1316.00         1266.00        0
n-R5s211       1139.00         1116.12         1010.73        0
n-R5s25          70.50           74.00           61.50        0
n-R5s28       10226.50        11493.01        10142.52        0
n-R5s33       43845.33        44914.73        39436.67        0
n-R5s60        6473.49         6799.07         6247.87        0
n-R5s65           4.50            8.07            7.88        0
n-R5s7            0.00            0.00            0.25        0
n-R5s71        3012.00         3109.75         2772.00        0
n-R5s92         683.06          678.58          636.57        0
n-R5s93         456.83          442.50          448.25        0
snoZ159           0.00            0.00            0.00        0
snoZ196         118.00          141.00          148.50        0
              SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3
0610006L08Rik    0.00              0.00
0610009B22Rik  496.00            462.00
0610009E02Rik    0.00              0.00
0610009L18Rik    0.00              0.00
0610010K14Rik  793.50            763.50
0610012D04Rik    0.00              0.00
0610012G03Rik  390.00            337.67
0610025J13Rik    0.00              0.00
0610030E20Rik 1088.00            970.00
0610031O16Rik    0.00              0.00
0610033M10Rik    0.00              0.00
0610038B21Rik    0.00              0.00
0610039K10Rik    0.00              0.00
0610040B10Rik    0.00              0.00
0610040F04Rik    0.00              0.00
0610040J01Rik   20.03             18.00
0610043K17Rik    0.00              0.00
0710001A04Rik    0.00              0.00
1010001B22Rik    0.00              0.00
1100001I12Rik    0.00              0.00
1110002E22Rik    0.00              1.00
1110002J07Rik    0.00              0.00
1110003F10Rik   16.50             19.00
1110004F10Rik 3911.50           3695.66

In [28]:
# Now we build a DESeq2 Count dataset and normalize it.


cds <- DESeqDataSetFromMatrix(countData = round(mircounts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates, fitting model and testing: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [29]:
#rlog normalisations
rl=vst(cds)
pdf("P20.5_BarGraphBeforeAfter.pdf",paper="a4")
par(mfrow=c(2,1))

par(mar=c(10,4,0,2)) # increase y-axis margin.
prenorm=apply(mircounts,2,sum)
barplot(prenorm,col=as.factor(samplenames),las=2,names=samplenames)
postnorm=apply(counts(cds,normalized=TRUE),2,sum)
barplot(postnorm,col=as.factor(samplenames),las=2,names=samplenames)
dev.off()

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

png
  2

In [30]:
###
# Margins area


pdf("P20.5_InitialHeatMap.pdf",paper="special",width=17, height=17,title="E16,5",fillOddEven=T)
heatmap.2(cor(mircounts),trace="none",col=hmcol,main="E16.5",cexRow=1,cexCol=1,
    margins=c(10,10),na.rm=T,key=T,offsetRow=0,offsetCol=0,keysize=0.3,density.info='histogram')
dev.off()

png
  2

In [31]:
##And the Spearman Dendogram
foo_sub_1 = counts(cds, normalized = TRUE)

foo_cor_1 = cor(foo_sub_1, method = "spearman") #builds matrix of Spearman corrn and euclidean distances

foo_cor_dist_1 = dist(foo_cor_1, method = "euclidean")
pdf(file="P20.5_dendrogram.pdf", height=8, width=15)
plot(hclust(foo_cor_dist_1))
dev.off()

png
  2

In [32]:
# Now we build a DESeq2 Count dataset and normalize it.
mircounts <- rawdata_copy$counts

cds <- DESeqDataSetFromMatrix(countData = round(mircounts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates, fitting model and testing: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [33]:


custom_colors <- c(
  'C57BL_6NJ-E16.5' = '#0000FF',    # Blue
  'C57BL_6NJ-P12.5' = '#00FF00',    # Green
  'C57BL_6NJ-P20.5' = '#FF0000',    # Red
  'BALB_cJ-E16.5' = '#800080',      # Purple
  'BALB_cJ-P12.5' = '#FFA500',      # Orange
  'BALB_cJ-P20.5' = '#FF00FF',      # Magenta
  'A_J-E16.5' = '#A52A2A',          # Brown
  'A_J-P12.5' = '#FFC0CB',          # Pink
  'A_J-P20.5' = '#A9A9A9',          # Dark Gray
  'FVB_NJ-E16.5' = '#ADD8E6',       # Light Blue
  'FVB_NJ-P12.5' = '#90EE90',       # Light Green
  'FVB_NJ-P20.5' = '#FFB6C1',       # Light Red
  'C3H_HeJ-E16.5' = '#9400D3',      # Dark Purple
  'C3H_HeJ-P12.5' = '#FF8C00',      # Dark Orange
  'C3H_HeJ-P20.5' = '#8A2BE2',      # Dark Magenta
  '129S1_SvImJ-E16.5' = '#9370DB',  # Light Purple
  '129S1_SvImJ-P12.5' = '#FFD700',  # Light Orange
  '129S1_SvImJ-P20.5' = '#FFFFE0',  # Light Yellow
  'DBA_2J-E16.5' = '#D2691E',       # Light Brown
  'DBA_2J-P12.5' = '#FF69B4',       # Light Pink
  'DBA_2J-P20.5' = '#A9A9A9',       # Dark Gray
  'AKR_J-E16.5' = '#ADD8E6',        # Light Blue
  'AKR_J-P12.5' = '#90EE90',        # Light Green
  'AKR_J-P20.5' = '#FFB6C1',        # Light Red
  'CBA_J-E16.5' = '#9400D3',        # Dark Purple
  'CBA_J-P12.5' = '#008B8B',        # Dark Cyan
  'CBA_J-P20.5' = '#8A2BE2',        # Dark Magenta
  'NOD_ShiLtJ-E16.5' = '#9370DB',   # Light Purple
  'NOD_ShiLtJ-P12.5' = '#FFD700',   # Light Orange
  'NOD_ShiLtJ-P20.5' = '#E0FFFF',   # Light Cyan
  'WSB_EiJ-E16.5' = '#EE82EE',      # Light Magenta
  'WSB_EiJ-P12.5' = '#FFFF00',      # Light Yellow
  'WSB_EiJ-P20.5' = '#8B4513',      # Dark Brown
  'CAST_EiJ-E16.5' = '#FF69B4',     # Light Pink
  'CAST_EiJ-P12.5' = '#A9A9A9',     # Dark Gray
  'CAST_EiJ-P20.5' = '#ADD8E6',     # Light Blue
  'PWK_PhJ-E16.5' = '#90EE90',      # Light Green
  'PWK_PhJ-P12.5' = '#FFB6C1',      # Light Red
  'PWK_PhJ-P20.5' = '#9400D3',      # Dark Purple
  'SPRET_EiJ-E16.5' = '#FF8C00',    # Dark Orange
  'SPRET_EiJ-P12.5' = '#008B8B',    # Dark Cyan
  'SPRET_EiJ-P20.5' = '#8A2BE2'     # Dark Magenta
)

# Check for color duplication and assign separate colors if needed
duplicated_colors <- duplicated(custom_colors) | duplicated(custom_colors, fromLast = TRUE)

# Get a vector of unique colors
available_colors <- c('#000000', '#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF', '#00FFFF', '#FF6600', '#6600CC', '#00FF00', '#FF00FF', '#FFFF00', '#00FFFF', '#FFCC00', '#00CC66', '#9933CC', '#996633', '#6699CC', '#006600', '#6600CC', '#990099', '#FF6666', '#CCFF66', '#996633', '#FF9933', '#FFFF00', '#FF00CC', '#FF9900', '#666633', '#FF00FF', '#FF00CC', '#FF6600', '#CC0000', '#00CC00', '#666666', '#990000', '#FF66CC', '#FFFF00', '#FF6600', '#9933CC', '#9900CC', '#FF00CC', '#00CC00', '#FF00CC', '#CC6600', '#66CC66', '#660000', '#CC0000', '#CC00FF', '#FFCC00', '#990066', '#00FF00', '#0066FF', '#FF66FF', '#33CC33', '#996600', '#FF00FF', '#9966FF', '#FFFF00', '#FF3300', '#00FFFF', '#666633', '#33CC33', '#FF6600', '#FF6600', '#FF00FF', '#CC9900')

# Assign unique colors to duplicated entries
custom_colors[duplicated_colors] <- available_colors[!duplicated_colors]


# Extract strain names
strain_names <- sub("-(E|P)[0-9\\.]+", "", names(custom_colors))

# Generate a unique set of strain names
unique_strain_names <- unique(strain_names)
unique_strain_names
# Define a set of bright colors from ggplot2 palette

bright_colors <- c(
  '#1F4788',
  '#003300',
  '#B80000',
  '#6E2162',
  '#D46A00',
  '#880088',
  '#AC9600',
  '#7D3C1D',
  '#A63A50',
  '#3E5B2B',
  '#235F92',
  '#00662D',
  '#CF5E75',
  '#A29ACD',
  '#1B6F77',
  '#7E7E00'
)


# Create a color mapping for each unique strain name
color_mapping <- setNames(bright_colors, unique_strain_names)
color_mapping 
# Apply color mapping to the original custom_colors
reassigned_colors <- color_mapping[strain_names]

# Combine with the original labels to create the final color assignments
final_colors <- setNames(reassigned_colors, names(custom_colors))
final_colors

Warning message in custom_colors[duplicated_colors] <- available_colors[!duplicated_colors]:
“number of items to replace is not a multiple of replacement length”

 [1] "C57BL_6NJ"   "BALB_cJ"     "A_J"         "FVB_NJ"      "C3H_HeJ"
 [6] "129S1_SvImJ" "DBA_2J"      "AKR_J"       "CBA_J"       "NOD_ShiLtJ"
[11] "WSB_EiJ"     "CAST_EiJ"    "PWK_PhJ"     "SPRET_EiJ"

  C57BL_6NJ     BALB_cJ         A_J      FVB_NJ     C3H_HeJ 129S1_SvImJ
  "#1F4788"   "#003300"   "#B80000"   "#6E2162"   "#D46A00"   "#880088"
     DBA_2J       AKR_J       CBA_J  NOD_ShiLtJ     WSB_EiJ    CAST_EiJ
  "#AC9600"   "#7D3C1D"   "#A63A50"   "#3E5B2B"   "#235F92"   "#00662D"
    PWK_PhJ   SPRET_EiJ        <NA>        <NA>
  "#CF5E75"   "#A29ACD"   "#1B6F77"   "#7E7E00"

  C57BL_6NJ-E16.5   C57BL_6NJ-P12.5   C57BL_6NJ-P20.5     BALB_cJ-E16.5
        "#1F4788"         "#1F4788"         "#1F4788"         "#003300"
    BALB_cJ-P12.5     BALB_cJ-P20.5         A_J-E16.5         A_J-P12.5
        "#003300"         "#003300"         "#B80000"         "#B80000"
        A_J-P20.5      FVB_NJ-E16.5      FVB_NJ-P12.5      FVB_NJ-P20.5
        "#B80000"         "#6E2162"         "#6E2162"         "#6E2162"
    C3H_HeJ-E16.5     C3H_HeJ-P12.5     C3H_HeJ-P20.5 129S1_SvImJ-E16.5
        "#D46A00"         "#D46A00"         "#D46A00"         "#880088"
129S1_SvImJ-P12.5 129S1_SvImJ-P20.5      DBA_2J-E16.5      DBA_2J-P12.5
        "#880088"         "#880088"         "#AC9600"         "#AC9600"
     DBA_2J-P20.5       AKR_J-E16.5       AKR_J-P12.5       AKR_J-P20.5
        "#AC9600"         "#7D3C1D"         "#7D3C1D"         "#7D3C1D"
      CBA_J-E16.5       CBA_J-P12.5       CBA_J-P20.5  NOD_ShiLtJ-E16.5
        "#A63A50"         "#A63A50"         "#A63A50"         "#3E5B2B"
 NOD_ShiLtJ-P12.5  NOD_ShiLtJ-P20.5     WSB_EiJ-E16.5     WSB_EiJ-P12.5
        "#3E5B2B"         "#3E5B2B"         "#235F92"         "#235F92"
    WSB_EiJ-P20.5    CAST_EiJ-E16.5    CAST_EiJ-P12.5    CAST_EiJ-P20.5
        "#235F92"         "#00662D"         "#00662D"         "#00662D"
    PWK_PhJ-E16.5     PWK_PhJ-P12.5     PWK_PhJ-P20.5   SPRET_EiJ-E16.5
        "#CF5E75"         "#CF5E75"         "#CF5E75"         "#A29ACD"
  SPRET_EiJ-P12.5   SPRET_EiJ-P20.5
        "#A29ACD"         "#A29ACD"

In [34]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed()+ 
    theme(legend.text=element_text(size=5),panel.background = element_rect(fill = "white")) + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("P20.5_PCA_After_1vs3_Beginning_all_genes_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

[1] "P20.5"

Warning message:
“`aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.”

In [35]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
    ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) +
     theme(legend.text=element_text(size=5),panel.background = element_rect(fill = "white")) + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("P20.5_PCA_After_2vs3_Beginning_500_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = 500))
dev.off()
}

[1] "P20.5"

In [36]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 20000, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], Samples = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "Samples", label = "name")) + geom_point(size = 2) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + 
     theme(legend.text=element_text(size=5),panel.background = element_rect(fill = "white")) + ggtitle(timePoint) + scale_color_manual(values = final_colors ) +  guides(color = guide_legend(title = "Strains"))
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("P20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
#pdf(paste0("E16.5_PCA_After_2vs3_Beginning_500_",timePoint,".pdf"))
pdf(paste0("P20.5_PCA_After_1vs2_Beginning_500_",timePoint,".pdf"),paper="a4")
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = 500))
dev.off()
}

[1] "P20.5"

In [37]:
eigenvalue_indices <- 1:10

rv <- rowVars(assay(rl))
select <- order(rv, decreasing = TRUE)[seq_len(min(ntop = nrow(counts(cds)), length(rv)))]
pca <- prcomp(t(assay(rl)[select, ]))

# Calculate the variance explained by each eigenvalue
variance_explained <- pca$sdev^2 / sum(pca$sdev^2)

# Create a data frame for plotting
eigenvalue_data <- data.frame(
  Index = eigenvalue_indices,
  VarianceExplained = round(variance_explained[eigenvalue_indices] * 100),
  LabelPosition = variance_explained[eigenvalue_indices] * 50  # Position at the middle of each bar
)

# Create the barplot using ggplot
bar_plot <- ggplot(data = eigenvalue_data, aes(x = Index, y = VarianceExplained)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(
    title = "First 10 Principal Components",
    x = "Eigenvalue Index",
    y = "Variance Explained (%)"
  ) +
  scale_x_continuous(breaks = eigenvalue_indices, labels = eigenvalue_indices) +
  scale_y_continuous(limits = c(0, max(eigenvalue_data$VarianceExplained) * 1.1)) +
  geom_text(aes(label = round(VarianceExplained, 2)), y = max(eigenvalue_data$VarianceExplained) * 0.5,angle = 90) + 
  #geom_text(aes(label = round(VarianceExplained, 2)), vjust = -0.5, angle = 90) +  # Label position and rotation
  theme_minimal() + theme(plot.background = element_rect(fill = "white"))

# Save the plot to a PDF file
pdf("P20.5_eigenvariance_barplot_all_genes.pdf", width = 3, height = 4)
print(bar_plot)
dev.off()

png
  2

In [38]:
rv <- rowVars(assay(rl))
select <- order(rv, decreasing = TRUE)[seq_len(min(ntop = 500, length(rv)))]
pca <- prcomp(t(assay(rl)[select, ]))

# Calculate the variance explained by each eigenvalue
variance_explained <- pca$sdev^2 / sum(pca$sdev^2)

# Create a data frame for plotting
eigenvalue_data <- data.frame(
  Index = eigenvalue_indices,
  VarianceExplained = round(variance_explained[eigenvalue_indices] * 100),
  LabelPosition = variance_explained[eigenvalue_indices] * 50  # Position at the middle of each bar
)

# Create the barplot using ggplot
bar_plot <- ggplot(data = eigenvalue_data, aes(x = Index, y = VarianceExplained)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(
    title = "First 10 Principal Components",
    x = "Eigenvalue Index",
    y = "Variance Explained (%)"
  ) +
  scale_x_continuous(breaks = eigenvalue_indices, labels = eigenvalue_indices) +
  scale_y_continuous(limits = c(0, max(eigenvalue_data$VarianceExplained) * 1.1)) +
  geom_text(aes(label = round(VarianceExplained, 2)), y = max(eigenvalue_data$VarianceExplained) * 0.5,angle = 90) + 
  #geom_text(aes(label = round(VarianceExplained, 2)), vjust = -0.5, angle = 90) +  # Label position and rotation
  theme_minimal() + theme(plot.background = element_rect(fill = "white"))

# Save the plot to a PDF file
pdf("P20.5_eigenvariance_barplot_500.pdf", width = 3, height = 4)
print(bar_plot)
dev.off()

png
  2

In [39]:
# Load necessary packages
library(EnhancedVolcano)
library(clusterProfiler)
library(DESeq2)
library(doParallel)
##for z-score
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'NOD_ShiLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Load required libraries
library(foreach)
library(doParallel)
library(EnhancedVolcano)  # Make sure you have this package installed

# Create a directory to save the plots
if (!dir.exists("volcano_plots")) {
    dir.create("volcano_plots")
}

# Set up parallel processing
num_cores <- 50  # Set the number of CPU cores to use
registerDoParallel(cores = num_cores)

# Define a function for generating a volcano plot
generate_volcano_plot <- function(contrast, cds) {
    col1 <- contrast[2]
    col2 <- contrast[3]
    
    res <- results(cds, contrast = contrast)

    volcano_plot <- EnhancedVolcano(res,
                                        lab = rownames(res),
                                        x = 'log2FoldChange',
                                        y = 'pvalue',
                                        title = paste(col1, "vs", col2, "Volcano Plot"),
                                        pCutoff = 0.05,
                                        FCcutoff = 2,
                                        col=  c('green', 'black', 'blue', 'red3'),
                                        colAlpha = 1,    cutoffLineType = 'blank',
                                        cutoffLineCol = 'black',
                                        cutoffLineWidth = 0.8,
                                        hline = c(10e-12, 10e-36, 10e-60, 10e-84),
                                        hlineCol = c('grey0', 'grey25','grey50','grey75'),
                                        hlineType = 'longdash',
                                        hlineWidth = 0.8,
                                        gridlines.major = FALSE,
                                        gridlines.minor = FALSE,
                                        xlim = c(-10, 10))
    # Add text labels for upregulated, downregulated, and nonsignificant genes            
    
            
    
    plot_filename <- paste("volcano_plots/", col1, "_vs_", col2, "_volcano_plot.png", sep = "")
    png(plot_filename, width = 1000, height = 1200)
    print(volcano_plot)
    dev.off()

}


# Run volcano plots in parallel for each contrast
foreach(contrast = contrast_list, .packages = c("EnhancedVolcano")) %dopar% {
    generate_volcano_plot(contrast, cds)
}

# Stop parallel processing
stopImplicitCluster()

clusterProfiler v4.8.1  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141


Attaching package: ‘clusterProfiler’


The following object is masked from ‘package:lattice’:

    dotplot


The following object is masked from ‘package:IRanges’:

    slice


The following object is masked from ‘package:S4Vectors’:

    rename


The following object is masked from ‘package:purrr’:

    simplify


The following object is masked from ‘package:stats’:

    filter


Loading required package: foreach


Attaching package: ‘foreach’


The following objects are masked from ‘package:purrr’:

    accumulate, when


Loading required package: iterators

Loading required package: parallel

[[1]]
png
  2

[[2]]
png
  2

[[3]]
png
  2

[[4]]
png
  2

[[5]]
png
  2

[[6]]
png
  2

[[7]]
png
  2

[[8]]
png
  2

[[9]]
png
  2

[[10]]
png
  2

[[11]]
png
  2

[[12]]
png
  2

[[13]]
png
  2

[[14]]
png
  2

[[15]]
png
  2

[[16]]
png
  2

[[17]]
png
  2

In [40]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)

# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
  c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'NOD_ShiLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)

contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'))

output_dir <- "gene_intology_barplots"
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
   enriched_terms <- enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "BP", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)


 # Select the top 20 enriched terms
  top_terms <- head(enriched_terms, 20)
  
  # Extract term names and corresponding p-values
  term_names <- top_terms$Description
  p_values <- top_terms$pvalue
  
   # Order terms by decreasing p-values
  ordered_indices <- order(p_values)
  ordered_term_names <- term_names[ordered_indices]
  ordered_p_values <- p_values[ordered_indices]
  # Create a bar plot
  pdf_file <- file.path(output_dir, paste("barplot_", contrast, ".pdf", sep = ""))
  pdf(pdf_file)
  barplot(-log10(p_values), names.arg = term_names, horiz = TRUE,
          main = paste("Enriched GO Terms -", contrast),
          xlab = "-log10(p-value)",col = "skyblue",las = 2, cex.names = 0.8,)
  dev.off()
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

In [41]:
library(UpSetR)
# Combine descriptions of enriched terms for each contrast into a single data frame
all_descriptions <- lapply(go_enrichment_list, function(go_enrichment) {
  return(go_enrichment$Description)
})
all_descriptions_df <- do.call(rbind, all_descriptions)

# Create the UpSet plot
upset_data <- as.data.frame(table(all_descriptions_df))
upset_plot <- upset(fromList(upset_data), order.by = "freq", keep.order = TRUE,
                    main.bar.color = "skyblue")

# Save the UpSet plot to the directory
upset_filename <- "gene_ontology_upset_plot.png"
png(file = upset_filename, width = 800, height = 600)
print(upset_plot)
dev.off()

Attaching package: ‘UpSetR’


The following object is masked from ‘package:lattice’:

    histogram

ERROR: Error in go_enrichment$Description: $ operator is invalid for atomic vectors

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
      c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)


go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enriched_terms <- enrichGO(gene = DEGs,
                             OrgDb = org.Mm.eg.db,
                             keyType = "SYMBOL",
                             ont = "BP",
                             pAdjustMethod = "BH",
                             pvalueCutoff = 0.05)
  
  # Select the top 20 enriched terms
  top_terms <- head(enriched_terms, 20)
  
  # Extract term names and corresponding p-values
  term_names <- top_terms$Description
  p_values <- top_terms$pvalue
  
  # Create a bar plot
  barplot(-log10(p_values), names.arg = term_names, horiz = TRUE,
          main = paste("Enriched GO Terms -", contrast),
          xlab = "-log10(p-value)")
}


# Set up a directory to save the PDF files
output_dir <- "barplots"
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enriched_terms <- enrichGO(gene = DEGs,
                             OrgDb = org.Mm.eg.db,
                             keyType = "SYMBOL",
                             ont = "BP",
                             pAdjustMethod = "BH",
                             pvalueCutoff = 0.05)
  
  # Select the top 20 enriched terms
  top_terms <- head(enriched_terms, 20)
  
  # Extract term names and corresponding p-values
  term_names <- top_terms$Description
  p_values <- top_terms$pvalue
  
  # Create a bar plot
  pdf_file <- file.path(output_dir, paste("barplot_", contrast, ".pdf", sep = ""))
  pdf(pdf_file)
  barplot(-log10(p_values), names.arg = term_names, horiz = TRUE,
          main = paste("Enriched GO Terms -", contrast),
          xlab = "-log10(p-value)")
  dev.off()
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

clusterProfiler v4.8.1  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141


Attaching package: ‘clusterProfiler’


The following object is masked from ‘package:IRanges’:

    slice


The following object is masked from ‘package:S4Vectors’:

    rename


The following object is masked from ‘package:purrr’:

    simplify


The following object is masked from ‘package:stats’:

    filter


Loading required package: foreach


Attaching package: ‘foreach’


The following objects are masked from ‘package:purrr’:

    accumulate, when


Loading required package: iterators

Loading required package: parallel

ERROR: Error in {: task 17 failed - "NZO_HlLtJ-P20.5 and SPRET_EiJ-P20.5 should be levels of sample such that sample_NZO_HlLtJ.P20.5_vs_129S1_SvImJ.P20.5 and sample_SPRET_EiJ.P20.5_vs_129S1_SvImJ.P20.5 are contained in 'resultsNames(object)'"

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
      c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "BP",
           pAdjustMethod = "BH",
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`Count`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_BP.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

clusterProfiler v4.8.1  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141


Attaching package: ‘clusterProfiler’


The following object is masked from ‘package:IRanges’:

    slice


The following object is masked from ‘package:S4Vectors’:

    rename


The following object is masked from ‘package:purrr’:

    simplify


The following object is masked from ‘package:stats’:

    filter


Loading required package: foreach


Attaching package: ‘foreach’


The following objects are masked from ‘package:purrr’:

    accumulate, when


Loading required package: iterators

Loading required package: parallel

ERROR: Error in {: task 17 failed - "NZO_HlLtJ-P20.5 and SPRET_EiJ-P20.5 should be levels of sample such that sample_NZO_HlLtJ.P20.5_vs_129S1_SvImJ.P20.5 and sample_SPRET_EiJ.P20.5_vs_129S1_SvImJ.P20.5 are contained in 'resultsNames(object)'"

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'LP_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NZO_HlLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),   
   c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "MF",
           pAdjustMethod = "BH", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`Count`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_MF.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'LP_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NZO_HlLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "CC",
           pAdjustMethod = "BH", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`Count`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_CC.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'LP_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NZO_HlLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "BP",
           pAdjustMethod = "BH", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_p_value_BP.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'LP_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NZO_HlLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "MF",
           pAdjustMethod = "BH", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_p_value_MF.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2

In [ ]:
# Load necessary packages
library(clusterProfiler)
library(DESeq2)
library(doParallel)


# Assuming you have performed differential expression analysis using DESeq2 and have a DESeqDataSet named 'dds'

# List of contrasts for different conditions
# List of contrasts for different conditions
# List of contrasts for different conditions
contrast_list <- list(
  c('sample', 'C57BL_6NJ-P20.5', 'BALB_cJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'A_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'FVB_NJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'C3H_HeJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'LP_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', '129S1_SvImJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'DBA_2J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'AKR_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CBA_J-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NZO_HlLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'NOD_ShiLtJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'WSB_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'CAST_EiJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'PWK_PhJ-P20.5'),
  c('sample', 'C57BL_6NJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'SPRET_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'WSB_EiJ-P20.5'),
   c('sample', 'CAST_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'WSB_EiJ-P20.5', 'NZO_HlLtJ-P20.5'),
   c('sample', 'NZO_HlLtJ-P20.5', 'SPRET_EiJ-P20.5')
  # Add more contrasts here if needed
)



# Set up parallel processing
num_cores <- 20  # Number of cores or processors to use
cl <- makeCluster(num_cores)
registerDoParallel(cl)



# Your code for gene ontology enrichment analysis in parallel
go_enrichment_list <- foreach(contrast = contrast_list) %dopar% {
  library(clusterProfiler)
  library(DESeq2)
  library(org.Mm.eg.db)
  res <- results(cds, contrast = contrast)
  DEGs <- rownames(res)[res$padj < 0.05 & abs(res$log2FoldChange) >= 2]
  
  enrichGO(gene = DEGs,
           OrgDb = org.Mm.eg.db,
           keyType = "SYMBOL",
           ont = "CC",
           pAdjustMethod = "BH", #BP for Biological Process ontology; you can use "MF" or "CC" for Molecular Function or Cellular Component?
           pvalueCutoff = 0.05)
}

# Stop parallel processing
stopCluster(cl)
registerDoSEQ()  # Reset to sequential processing

# Now go_enrichment_list contains the results from the parallel computation


# Combine the results from all contrasts into a single data frame
all_go_data <- do.call(rbind, lapply(go_enrichment_list, function(go_enrichment) {
  data.frame(GOTerm = go_enrichment$Description,
             stringsAsFactors = FALSE)
}))

# Create a list of column names for the score columns
score_column_names <- sapply(contrast_list, function(contrast) {
  paste(contrast[-1], collapse = "_vs_")
})


#
# Remove duplicates from the 'Goterm' column
all_go_data$Goterm <- unique(all_go_data$Goterm)
for (i in seq_along(contrast_list)) {
  contrast_name <- score_column_names[i]
  col_name <- paste(contrast_name)
  
  # Create a vector of NA values with the same length as the number of rows
  score_vector <- rep(NA, nrow(all_go_data))
  
  # Populate the vector with actual scores where available
  enriched_indices <- match(go_enrichment_list[[i]]$Description, all_go_data$GOTerm)
  score_vector[enriched_indices] <- go_enrichment_list[[i]]$`p.adjust`
  
  # Add the vector as a new column
  all_go_data[col_name] <- score_vector
}



# Replace the 'Goterm' column with row names
rownames(all_go_data) = all_go_data$Goterm
# Load the dplyr package
library(dplyr)

# Group by the 'Group' column and calculate the average for all other columns
result <- all_go_data %>%
  group_by(GOTerm) %>%
  summarise_all(.funs = mean) %>%
  mutate_all(.funs = ~ifelse(is.na(.), 0, .))


library(gplots)


# Convert the tibble to a data frame
result_df <- as.data.frame(result)

# Set row names to be the values in the 'GOTerm' column
rownames(result_df) <- result$GOTerm

# Remove the Gene column
result_df <- result_df[, -1]

# Calculate the row scores (sum of values)
row_scores <- rowSums(result_df)

# Get indices of the top 50 highest scoring rows
top_indices <- order(row_scores, decreasing = TRUE)[1:50]

# Subset the matrix to include only the top 50 highest scoring rows
subset_matrix <- result_df[top_indices, , drop = FALSE]

labels_col <- as.character(colnames(subset_matrix)) 

# Create a PDF graphics device
pdf("heatmap_top_50_P20_gene_ontology_pvalue_CC.pdf", width = 10, height = 8)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 1.5, family = "sans")  # You can adjust the font size and family here

# Create the heatmap using heatmap.2 with margins on right and bottom
heatmap.2(as.matrix(subset_matrix),
         dendrogram = "both",
          col = myCol,
          main = "P20.5",
          center = NULL,trace="none",
          keysize = 1,
          margins = c(20, 25),offsetRow=0,offsetCol=0,density.info='histogram')  # Adjust the margin values as needed (right, bottom, top, left)

dev.off()

png
  2