In [1]:
###testing R in jyupter 
system("type R")

In [2]:
#package installation 
#install.packages("purrr")
#install.packages("tidyverse")
#conda install r-tidyverse r-purrr bioconductor-edger bioconductor-busparse bioconductor-rtracklayer r-dplyr -y 
#conda install -c conda-forge r-purrr -y
#conda install -c bioconda bioconductor-edger -y
#conda install -c bioconda bioconductor-busparse -y
#conda install -c bioconda bioconductor-rtracklayer -y
#conda install -c conda-forge r-dplyr -y

In [3]:
library(purrr)
library(tidyverse)
library(edgeR)
library(rtracklayer)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: limma

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:limma’:

    plotMA


The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:lubridate’:

    second, second<-


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:tidyr’:

    expand


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:lubridate’:

    %within%


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:purrr’:

    reduce


Loading required package: GenomeInfoDb

In [4]:
library(purrr)
library(tidyverse)
f_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = ".featureCounts$", full.names = T)

f_files

  [1] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts"
  [2] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts"
  [3] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts"
  [4] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts"
  [5] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts"
  [6] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts"
  [7] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts"
  [8] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts"
  [9] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts"
 [10] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts"
 [11] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts"
 [12] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts"
 [13] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts"
 [14] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts"
 [15] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts"
 [16] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts"
 [17] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts"
 [18] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts"
 [19] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts"
 [20] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts"
 [21] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts"
 [22] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts"
 [23] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts"
 [24] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts"
 [25] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts"
 [26] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts"
 [27] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts"
 [28] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts"
 [29] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts"
 [30] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts"
 [31] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts"
 [32] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts"
 [33] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts"
 [34] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts"
 [35] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts"
 [36] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts"
 [37] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts"
 [38] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts"
 [39] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts"
 [40] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts"
 [41] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts"
 [42] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts"
 [43] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts"
 [44] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts"
 [45] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts"
 [46] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts"
 [47] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts"
 [48] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts"
 [49] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts"
 [50] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts"
 [51] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts"
 [52] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts"
 [53] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts"
 [54] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts"
 [55] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts"
 [56] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts"
 [57] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts"
 [58] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts"
 [59] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts"
 [60] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts"
 [61] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts"
 [62] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts"
 [63] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts"
 [64] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts"
 [65] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts"
 [66] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts"
 [67] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts"
 [68] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts"
 [69] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts"
 [70] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts"
 [71] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts"
 [72] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts"
 [73] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts"
 [74] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts"
 [75] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts"
 [76] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts"
 [77] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts"
 [78] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts"
 [79] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts"
 [80] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts"
 [81] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts"
 [82] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts"
 [83] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts"
 [84] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts"
 [85] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts"
 [86] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts"
 [87] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts"
 [88] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts"
 [89] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts"
 [90] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts"
 [91] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.1.featureCounts"
 [92] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.2.featureCounts"
 [93] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.3.featureCounts"
 [94] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.1.featureCounts"
 [95] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.2.featureCounts"
 [96] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.3.featureCounts"
 [97] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.1.featureCounts"
 [98] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.2.featureCounts"
 [99] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.3.featureCounts"
[100] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts"
[101] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts"
[102] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts"
[103] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts"
[104] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts"
[105] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts"
[106] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts"
[107] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts"
[108] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts"
[109] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.1.featureCounts"
[110] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.2.featureCounts"
[111] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.3.featureCounts"
[112] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.1.featureCounts"
[113] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.2.featureCounts"
[114] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.3.featureCounts"
[115] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.1.featureCounts"
[116] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.2.featureCounts"
[117] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.3.featureCounts"
[118] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts"
[119] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts"
[120] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts"
[121] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts"
[122] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts"
[123] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts"
[124] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts"
[125] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts"
[126] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts"
[127] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts"
[128] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts"
[129] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts"
[130] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts"
[131] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts"
[132] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts"
[133] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts"
[134] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts"
[135] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts"
[136] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts"
[137] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts"
[138] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts"
[139] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts"
[140] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts"
[141] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts"
[142] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts"
[143] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts"
[144] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts"

In [5]:
f_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts')
f_files

  [1] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts"
  [2] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts"
  [3] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts"
  [4] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts"
  [5] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts"
  [6] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts"
  [7] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts"
  [8] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts"
  [9] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts"
 [10] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts"
 [11] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts"
 [12] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts"
 [13] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts"
 [14] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts"
 [15] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts"
 [16] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts"
 [17] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts"
 [18] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts"
 [19] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts"
 [20] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts"
 [21] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts"
 [22] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts"
 [23] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts"
 [24] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts"
 [25] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts"
 [26] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts"
 [27] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts"
 [28] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts"
 [29] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts"
 [30] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts"
 [31] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts"
 [32] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts"
 [33] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts"
 [34] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts"
 [35] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts"
 [36] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts"
 [37] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts"
 [38] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts"
 [39] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts"
 [40] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts"
 [41] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts"
 [42] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts"
 [43] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts"
 [44] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts"
 [45] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts"
 [46] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts"
 [47] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts"
 [48] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts"
 [49] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts"
 [50] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts"
 [51] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts"
 [52] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts"
 [53] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts"
 [54] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts"
 [55] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts"
 [56] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts"
 [57] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts"
 [58] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts"
 [59] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts"
 [60] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts"
 [61] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts"
 [62] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts"
 [63] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts"
 [64] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts"
 [65] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts"
 [66] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts"
 [67] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts"
 [68] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts"
 [69] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts"
 [70] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts"
 [71] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts"
 [72] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts"
 [73] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts"
 [74] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts"
 [75] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts"
 [76] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts"
 [77] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts"
 [78] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts"
 [79] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts"
 [80] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts"
 [81] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts"
 [82] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts"
 [83] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts"
 [84] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts"
 [85] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts"
 [86] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts"
 [87] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts"
 [88] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts"
 [89] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts"
 [90] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts"
 [91] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts"
 [92] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts"
 [93] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts"
 [94] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts"
 [95] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts"
 [96] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts"
 [97] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts"
 [98] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts"
 [99] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts"
[100] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts"
[101] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts"
[102] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts"
[103] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts"
[104] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts"
[105] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts"
[106] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts"
[107] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts"
[108] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts"
[109] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts"
[110] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts"
[111] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts"
[112] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts"
[113] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts"
[114] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts"
[115] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts"
[116] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts"
[117] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts"
[118] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts"
[119] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts"
[120] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts"
[121] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts"
[122] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts"
[123] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts"
[124] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts"
[125] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts"
[126] "/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts"

In [6]:
samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames

  [1] "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp"
  [4] "129S1_SvImJ-16.5dpc" "129S1_SvImJ-16.5dpc" "129S1_SvImJ-16.5dpc"
  [7] "129S1_SvImJ-20.5dpp" "129S1_SvImJ-20.5dpp" "129S1_SvImJ-20.5dpp"
 [10] "A_J-12.5dpp"         "A_J-12.5dpp"         "A_J-12.5dpp"
 [13] "A_J-16.5dpc"         "A_J-16.5dpc"         "A_J-16.5dpc"
 [16] "A_J-20.5dpp"         "A_J-20.5dpp"         "A_J-20.5dpp"
 [19] "AKR_J-12.5dpp"       "AKR_J-12.5dpp"       "AKR_J-12.5dpp"
 [22] "AKR_J-16.5dpc"       "AKR_J-16.5dpc"       "AKR_J-16.5dpc"
 [25] "AKR_J-20.5dpp"       "AKR_J-20.5dpp"       "AKR_J-20.5dpp"
 [28] "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"
 [31] "BALB_cJ-16.5dpc"     "BALB_cJ-16.5dpc"     "BALB_cJ-16.5dpc"
 [34] "BALB_cJ-20.5dpp"     "BALB_cJ-20.5dpp"     "BALB_cJ-20.5dpp"
 [37] "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"
 [40] "C3H_HeJ-16.5dpc"     "C3H_HeJ-16.5dpc"     "C3H_HeJ-16.5dpc"
 [43] "C3H_HeJ-20.5dpp"     "C3H_HeJ-20.5dpp"     "C3H_HeJ-20.5dpp"
 [46] "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"
 [49] "C57BL_6NJ-16.5dpc"   "C57BL_6NJ-16.5dpc"   "C57BL_6NJ-16.5dpc"
 [52] "C57BL_6NJ-20.5dpp"   "C57BL_6NJ-20.5dpp"   "C57BL_6NJ-20.5dpp"
 [55] "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"
 [58] "CAST_EiJ-16.5dpc"    "CAST_EiJ-16.5dpc"    "CAST_EiJ-16.5dpc"
 [61] "CAST_EiJ-20.5dpp"    "CAST_EiJ-20.5dpp"    "CAST_EiJ-20.5dpp"
 [64] "CBA_J-12.5dpp"       "CBA_J-12.5dpp"       "CBA_J-12.5dpp"
 [67] "CBA_J-16.5dpc"       "CBA_J-16.5dpc"       "CBA_J-16.5dpc"
 [70] "CBA_J-20.5dpp"       "CBA_J-20.5dpp"       "CBA_J-20.5dpp"
 [73] "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"
 [76] "DBA_2J-16.5dpc"      "DBA_2J-16.5dpc"      "DBA_2J-16.5dpc"
 [79] "DBA_2J-20.5dpp"      "DBA_2J-20.5dpp"      "DBA_2J-20.5dpp"
 [82] "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"
 [85] "FVB_NJ-16.5dpc"      "FVB_NJ-16.5dpc"      "FVB_NJ-16.5dpc"
 [88] "FVB_NJ-20.5dpp"      "FVB_NJ-20.5dpp"      "FVB_NJ-20.5dpp"
 [91] "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"
 [94] "NOD_ShiLtJ-16.5dpc"  "NOD_ShiLtJ-16.5dpc"  "NOD_ShiLtJ-16.5dpc"
 [97] "NOD_ShiLtJ-20.5dpp"  "NOD_ShiLtJ-20.5dpp"  "NOD_ShiLtJ-20.5dpp"
[100] "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"
[103] "PWK_PhJ-16.5dpc"     "PWK_PhJ-16.5dpc"     "PWK_PhJ-16.5dpc"
[106] "PWK_PhJ-20.5dpp"     "PWK_PhJ-20.5dpp"     "PWK_PhJ-20.5dpp"
[109] "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"
[112] "SPRET_EiJ-16.5dpc"   "SPRET_EiJ-16.5dpc"   "SPRET_EiJ-16.5dpc"
[115] "SPRET_EiJ-20.5dpp"   "SPRET_EiJ-20.5dpp"   "SPRET_EiJ-20.5dpp"
[118] "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"
[121] "WSB_EiJ-16.5dpc"     "WSB_EiJ-16.5dpc"     "WSB_EiJ-16.5dpc"
[124] "WSB_EiJ-20.5dpp"     "WSB_EiJ-20.5dpp"     "WSB_EiJ-20.5dpp"

In [7]:
#list of sample names with replicates 
lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))

lables

  [1] "129S1_SvImJ-12.5dpp.1" "129S1_SvImJ-12.5dpp.2" "129S1_SvImJ-12.5dpp.3"
  [4] "129S1_SvImJ-16.5dpc.1" "129S1_SvImJ-16.5dpc.2" "129S1_SvImJ-16.5dpc.3"
  [7] "129S1_SvImJ-20.5dpp.1" "129S1_SvImJ-20.5dpp.2" "129S1_SvImJ-20.5dpp.3"
 [10] "A_J-12.5dpp.1"         "A_J-12.5dpp.2"         "A_J-12.5dpp.3"
 [13] "A_J-16.5dpc.1"         "A_J-16.5dpc.2"         "A_J-16.5dpc.3"
 [16] "A_J-20.5dpp.1"         "A_J-20.5dpp.2"         "A_J-20.5dpp.3"
 [19] "AKR_J-12.5dpp.1"       "AKR_J-12.5dpp.2"       "AKR_J-12.5dpp.3"
 [22] "AKR_J-16.5dpc.1"       "AKR_J-16.5dpc.2"       "AKR_J-16.5dpc.3"
 [25] "AKR_J-20.5dpp.1"       "AKR_J-20.5dpp.2"       "AKR_J-20.5dpp.3"
 [28] "BALB_cJ-12.5dpp.1"     "BALB_cJ-12.5dpp.2"     "BALB_cJ-12.5dpp.3"
 [31] "BALB_cJ-16.5dpc.1"     "BALB_cJ-16.5dpc.2"     "BALB_cJ-16.5dpc.3"
 [34] "BALB_cJ-20.5dpp.1"     "BALB_cJ-20.5dpp.2"     "BALB_cJ-20.5dpp.3"
 [37] "C3H_HeJ-12.5dpp.1"     "C3H_HeJ-12.5dpp.2"     "C3H_HeJ-12.5dpp.3"
 [40] "C3H_HeJ-16.5dpc.1"     "C3H_HeJ-16.5dpc.2"     "C3H_HeJ-16.5dpc.3"
 [43] "C3H_HeJ-20.5dpp.1"     "C3H_HeJ-20.5dpp.2"     "C3H_HeJ-20.5dpp.3"
 [46] "C57BL_6NJ-12.5dpp.1"   "C57BL_6NJ-12.5dpp.2"   "C57BL_6NJ-12.5dpp.3"
 [49] "C57BL_6NJ-16.5dpc.1"   "C57BL_6NJ-16.5dpc.2"   "C57BL_6NJ-16.5dpc.3"
 [52] "C57BL_6NJ-20.5dpp.1"   "C57BL_6NJ-20.5dpp.2"   "C57BL_6NJ-20.5dpp.3"
 [55] "CAST_EiJ-12.5dpp.1"    "CAST_EiJ-12.5dpp.2"    "CAST_EiJ-12.5dpp.3"
 [58] "CAST_EiJ-16.5dpc.1"    "CAST_EiJ-16.5dpc.2"    "CAST_EiJ-16.5dpc.3"
 [61] "CAST_EiJ-20.5dpp.1"    "CAST_EiJ-20.5dpp.2"    "CAST_EiJ-20.5dpp.3"
 [64] "CBA_J-12.5dpp.1"       "CBA_J-12.5dpp.2"       "CBA_J-12.5dpp.3"
 [67] "CBA_J-16.5dpc.1"       "CBA_J-16.5dpc.2"       "CBA_J-16.5dpc.3"
 [70] "CBA_J-20.5dpp.1"       "CBA_J-20.5dpp.2"       "CBA_J-20.5dpp.3"
 [73] "DBA_2J-12.5dpp.1"      "DBA_2J-12.5dpp.2"      "DBA_2J-12.5dpp.3"
 [76] "DBA_2J-16.5dpc.1"      "DBA_2J-16.5dpc.2"      "DBA_2J-16.5dpc.3"
 [79] "DBA_2J-20.5dpp.1"      "DBA_2J-20.5dpp.2"      "DBA_2J-20.5dpp.3"
 [82] "FVB_NJ-12.5dpp.1"      "FVB_NJ-12.5dpp.2"      "FVB_NJ-12.5dpp.3"
 [85] "FVB_NJ-16.5dpc.1"      "FVB_NJ-16.5dpc.2"      "FVB_NJ-16.5dpc.3"
 [88] "FVB_NJ-20.5dpp.1"      "FVB_NJ-20.5dpp.2"      "FVB_NJ-20.5dpp.3"
 [91] "NOD_ShiLtJ-12.5dpp.1"  "NOD_ShiLtJ-12.5dpp.2"  "NOD_ShiLtJ-12.5dpp.3"
 [94] "NOD_ShiLtJ-16.5dpc.1"  "NOD_ShiLtJ-16.5dpc.2"  "NOD_ShiLtJ-16.5dpc.3"
 [97] "NOD_ShiLtJ-20.5dpp.1"  "NOD_ShiLtJ-20.5dpp.2"  "NOD_ShiLtJ-20.5dpp.3"
[100] "PWK_PhJ-12.5dpp.1"     "PWK_PhJ-12.5dpp.2"     "PWK_PhJ-12.5dpp.3"
[103] "PWK_PhJ-16.5dpc.1"     "PWK_PhJ-16.5dpc.2"     "PWK_PhJ-16.5dpc.3"
[106] "PWK_PhJ-20.5dpp.1"     "PWK_PhJ-20.5dpp.2"     "PWK_PhJ-20.5dpp.3"
[109] "SPRET_EiJ-12.5dpp.1"   "SPRET_EiJ-12.5dpp.2"   "SPRET_EiJ-12.5dpp.3"
[112] "SPRET_EiJ-16.5dpc.1"   "SPRET_EiJ-16.5dpc.2"   "SPRET_EiJ-16.5dpc.3"
[115] "SPRET_EiJ-20.5dpp.1"   "SPRET_EiJ-20.5dpp.2"   "SPRET_EiJ-20.5dpp.3"
[118] "WSB_EiJ-12.5dpp.1"     "WSB_EiJ-12.5dpp.2"     "WSB_EiJ-12.5dpp.3"
[121] "WSB_EiJ-16.5dpc.1"     "WSB_EiJ-16.5dpc.2"     "WSB_EiJ-16.5dpc.3"
[124] "WSB_EiJ-20.5dpp.1"     "WSB_EiJ-20.5dpp.2"     "WSB_EiJ-20.5dpp.3"

In [8]:
lables <- c('129S1_SvImJ-P12.5.1','129S1_SvImJ-P12.5.2','129S1_SvImJ-P12.5.3','129S1_SvImJ-E16.5.1','129S1_SvImJ-E16.5.2',
'129S1_SvImJ-E16.5.3','129S1_SvImJ-P20.5.1','129S1_SvImJ-P20.5.2','129S1_SvImJ-P20.5.3',
'A_J-P12.5.1','A_J-P12.5.2','A_J-P12.5.3','A_J-E16.5.1','A_J-E16.5.2','A_J-E16.5.3','A_J-P20.5.1','A_J-P20.5.2','A_J-P20.5.3',
'AKR_J-P12.5.1','AKR_J-P12.5.2','AKR_J-P12.5.3','AKR_J-E16.5.1','AKR_J-E16.5.2','AKR_J-E16.5.3',
'AKR_J-P20.5.1','AKR_J-P20.5.2','AKR_J-P20.5.3',
'BALB_cJ-P12.5.1','BALB_cJ-P12.5.2','BALB_cJ-P12.5.3','BALB_cJ-E16.5.1',
'BALB_cJ-E16.5.2','BALB_cJ-E16.5.3','BALB_cJ-P20.5.1','BALB_cJ-P20.5.2','BALB_cJ-P20.5.3','C3H_HeJ-P12.5.1',
'C3H_HeJ-P12.5.2','C3H_HeJ-P12.5.3','C3H_HeJ-E16.5.1','C3H_HeJ-E16.5.2','C3H_HeJ-E16.5.3','C3H_HeJ-P20.5.1','C3H_HeJ-P20.5.2',
'C3H_HeJ-P20.5.3','C57BL_6NJ-P12.5.1','C57BL_6NJ-P12.5.2','C57BL_6NJ-P12.5.3','C57BL_6NJ-E16.5.1','C57BL_6NJ-E16.5.2',
'C57BL_6NJ-E16.5.3','C57BL_6NJ-P20.5.1','C57BL_6NJ-P20.5.2','C57BL_6NJ-P20.5.3','CAST_EiJ-P12.5.1','CAST_EiJ-P12.5.2',
'CAST_EiJ-P12.5.3','CAST_EiJ-E16.5.1','CAST_EiJ-E16.5.2','CAST_EiJ-E16.5.3','CAST_EiJ-P20.5.1','CAST_EiJ-P20.5.2',
'CAST_EiJ-P20.5.3','CBA_J-P12.5.1','CBA_J-P12.5.2','CBA_J-P12.5.3','CBA_J-E16.5.1','CBA_J-E16.5.2','CBA_J-E16.5.3',
'CBA_J-P20.5.1','CBA_J-P20.5.2','CBA_J-P20.5.3','DBA_2J-P12.5.1','DBA_2J-P12.5.2','DBA_2J-P12.5.3','DBA_2J-E16.5.1','DBA_2J-E16.5.2',
'DBA_2J-E16.5.3','DBA_2J-P20.5.1','DBA_2J-P20.5.2','DBA_2J-P20.5.3','FVB_NJ-P12.5.1','FVB_NJ-P12.5.2','FVB_NJ-P12.5.3','FVB_NJ-E16.5.1',
'FVB_NJ-E16.5.2','FVB_NJ-E16.5.3','FVB_NJ-P20.5.1','FVB_NJ-P20.5.2','FVB_NJ-P20.5.3',
'NOD_ShiLtJ-P12.5.1','NOD_ShiLtJ-P12.5.2',
'NOD_ShiLtJ-P12.5.3','NOD_ShiLtJ-E16.5.1','NOD_ShiLtJ-E16.5.2','NOD_ShiLtJ-E16.5.3','NOD_ShiLtJ-P20.5.1','NOD_ShiLtJ-P20.5.2','NOD_ShiLtJ-P20.5.3',
'PWK_PhJ-P12.5.1','PWK_PhJ-P12.5.2','PWK_PhJ-P12.5.3','PWK_PhJ-E16.5.1','PWK_PhJ-E16.5.2','PWK_PhJ-E16.5.3',
'PWK_PhJ-P20.5.1','PWK_PhJ-P20.5.2','PWK_PhJ-P20.5.3','SPRET_EiJ-P12.5.1','SPRET_EiJ-P12.5.2','SPRET_EiJ-P12.5.3','SPRET_EiJ-E16.5.1',
'SPRET_EiJ-E16.5.2','SPRET_EiJ-E16.5.3','SPRET_EiJ-P20.5.1','SPRET_EiJ-P20.5.2','SPRET_EiJ-P20.5.3','WSB_EiJ-P12.5.1','WSB_EiJ-P12.5.2',
'WSB_EiJ-P12.5.3','WSB_EiJ-E16.5.1','WSB_EiJ-E16.5.2','WSB_EiJ-E16.5.3','WSB_EiJ-P20.5.1','WSB_EiJ-P20.5.2',
'WSB_EiJ-P20.5.3')
lables

  [1] "129S1_SvImJ-P12.5.1" "129S1_SvImJ-P12.5.2" "129S1_SvImJ-P12.5.3"
  [4] "129S1_SvImJ-E16.5.1" "129S1_SvImJ-E16.5.2" "129S1_SvImJ-E16.5.3"
  [7] "129S1_SvImJ-P20.5.1" "129S1_SvImJ-P20.5.2" "129S1_SvImJ-P20.5.3"
 [10] "A_J-P12.5.1"         "A_J-P12.5.2"         "A_J-P12.5.3"
 [13] "A_J-E16.5.1"         "A_J-E16.5.2"         "A_J-E16.5.3"
 [16] "A_J-P20.5.1"         "A_J-P20.5.2"         "A_J-P20.5.3"
 [19] "AKR_J-P12.5.1"       "AKR_J-P12.5.2"       "AKR_J-P12.5.3"
 [22] "AKR_J-E16.5.1"       "AKR_J-E16.5.2"       "AKR_J-E16.5.3"
 [25] "AKR_J-P20.5.1"       "AKR_J-P20.5.2"       "AKR_J-P20.5.3"
 [28] "BALB_cJ-P12.5.1"     "BALB_cJ-P12.5.2"     "BALB_cJ-P12.5.3"
 [31] "BALB_cJ-E16.5.1"     "BALB_cJ-E16.5.2"     "BALB_cJ-E16.5.3"
 [34] "BALB_cJ-P20.5.1"     "BALB_cJ-P20.5.2"     "BALB_cJ-P20.5.3"
 [37] "C3H_HeJ-P12.5.1"     "C3H_HeJ-P12.5.2"     "C3H_HeJ-P12.5.3"
 [40] "C3H_HeJ-E16.5.1"     "C3H_HeJ-E16.5.2"     "C3H_HeJ-E16.5.3"
 [43] "C3H_HeJ-P20.5.1"     "C3H_HeJ-P20.5.2"     "C3H_HeJ-P20.5.3"
 [46] "C57BL_6NJ-P12.5.1"   "C57BL_6NJ-P12.5.2"   "C57BL_6NJ-P12.5.3"
 [49] "C57BL_6NJ-E16.5.1"   "C57BL_6NJ-E16.5.2"   "C57BL_6NJ-E16.5.3"
 [52] "C57BL_6NJ-P20.5.1"   "C57BL_6NJ-P20.5.2"   "C57BL_6NJ-P20.5.3"
 [55] "CAST_EiJ-P12.5.1"    "CAST_EiJ-P12.5.2"    "CAST_EiJ-P12.5.3"
 [58] "CAST_EiJ-E16.5.1"    "CAST_EiJ-E16.5.2"    "CAST_EiJ-E16.5.3"
 [61] "CAST_EiJ-P20.5.1"    "CAST_EiJ-P20.5.2"    "CAST_EiJ-P20.5.3"
 [64] "CBA_J-P12.5.1"       "CBA_J-P12.5.2"       "CBA_J-P12.5.3"
 [67] "CBA_J-E16.5.1"       "CBA_J-E16.5.2"       "CBA_J-E16.5.3"
 [70] "CBA_J-P20.5.1"       "CBA_J-P20.5.2"       "CBA_J-P20.5.3"
 [73] "DBA_2J-P12.5.1"      "DBA_2J-P12.5.2"      "DBA_2J-P12.5.3"
 [76] "DBA_2J-E16.5.1"      "DBA_2J-E16.5.2"      "DBA_2J-E16.5.3"
 [79] "DBA_2J-P20.5.1"      "DBA_2J-P20.5.2"      "DBA_2J-P20.5.3"
 [82] "FVB_NJ-P12.5.1"      "FVB_NJ-P12.5.2"      "FVB_NJ-P12.5.3"
 [85] "FVB_NJ-E16.5.1"      "FVB_NJ-E16.5.2"      "FVB_NJ-E16.5.3"
 [88] "FVB_NJ-P20.5.1"      "FVB_NJ-P20.5.2"      "FVB_NJ-P20.5.3"
 [91] "NOD_ShiLtJ-P12.5.1"  "NOD_ShiLtJ-P12.5.2"  "NOD_ShiLtJ-P12.5.3"
 [94] "NOD_ShiLtJ-E16.5.1"  "NOD_ShiLtJ-E16.5.2"  "NOD_ShiLtJ-E16.5.3"
 [97] "NOD_ShiLtJ-P20.5.1"  "NOD_ShiLtJ-P20.5.2"  "NOD_ShiLtJ-P20.5.3"
[100] "PWK_PhJ-P12.5.1"     "PWK_PhJ-P12.5.2"     "PWK_PhJ-P12.5.3"
[103] "PWK_PhJ-E16.5.1"     "PWK_PhJ-E16.5.2"     "PWK_PhJ-E16.5.3"
[106] "PWK_PhJ-P20.5.1"     "PWK_PhJ-P20.5.2"     "PWK_PhJ-P20.5.3"
[109] "SPRET_EiJ-P12.5.1"   "SPRET_EiJ-P12.5.2"   "SPRET_EiJ-P12.5.3"
[112] "SPRET_EiJ-E16.5.1"   "SPRET_EiJ-E16.5.2"   "SPRET_EiJ-E16.5.3"
[115] "SPRET_EiJ-P20.5.1"   "SPRET_EiJ-P20.5.2"   "SPRET_EiJ-P20.5.3"
[118] "WSB_EiJ-P12.5.1"     "WSB_EiJ-P12.5.2"     "WSB_EiJ-P12.5.3"
[121] "WSB_EiJ-E16.5.1"     "WSB_EiJ-E16.5.2"     "WSB_EiJ-E16.5.3"
[124] "WSB_EiJ-P20.5.1"     "WSB_EiJ-P20.5.2"     "WSB_EiJ-P20.5.3"

In [9]:
#samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))
samplenames_order = c('C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'A_J-E16.5','A_J-E16.5','A_J-E16.5','A_J-P12.5','A_J-P12.5','A_J-P12.5','A_J-P20.5','A_J-P20.5','A_J-P20.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'129S1_SvImJ-P20.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-E16.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-E16.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')

In [10]:
#list of sample names with replicates 
#lables = tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))
lables_order  = c('C57BL_6NJ-E16.5.1','C57BL_6NJ-E16.5.2','C57BL_6NJ-E16.5.3','C57BL_6NJ-P12.5.1','C57BL_6NJ-P12.5.2','C57BL_6NJ-P12.5.3','C57BL_6NJ-P20.5.1','C57BL_6NJ-P20.5.2','C57BL_6NJ-P20.5.3',
'BALB_cJ-E16.5.1','BALB_cJ-E16.5.2','BALB_cJ-E16.5.3','BALB_cJ-P12.5.1','BALB_cJ-P12.5.2','BALB_cJ-P12.5.3','BALB_cJ-P20.5.1','BALB_cJ-P20.5.2','BALB_cJ-P20.5.3',
'A_J-E16.5.1','A_J-E16.5.2','A_J-E16.5.3','A_J-P12.5.1','A_J-P12.5.2','A_J-P12.5.3','A_J-P20.5.1','A_J-P20.5.2','A_J-P20.5.3',
'FVB_NJ-E16.5.1','FVB_NJ-E16.5.2','FVB_NJ-E16.5.3','FVB_NJ-P12.5.1','FVB_NJ-P12.5.2','FVB_NJ-P12.5.3','FVB_NJ-P20.5.1','FVB_NJ-P20.5.2','FVB_NJ-P20.5.3',
'C3H_HeJ-E16.5.1','C3H_HeJ-E16.5.2','C3H_HeJ-E16.5.3','C3H_HeJ-P12.5.1','C3H_HeJ-P12.5.2','C3H_HeJ-P12.5.3','C3H_HeJ-P20.5.1','C3H_HeJ-P20.5.2','C3H_HeJ-P20.5.3',
'129S1_SvImJ-E16.5.1','129S1_SvImJ-E16.5.2','129S1_SvImJ-E16.5.3','129S1_SvImJ-P12.5.1','129S1_SvImJ-P12.5.2','129S1_SvImJ-P12.5.3','129S1_SvImJ-P20.5.1','129S1_SvImJ-P20.5.2','129S1_SvImJ-P20.5.3',
'DBA_2J-E16.5.1','DBA_2J-E16.5.2','DBA_2J-E16.5.3','DBA_2J-P12.5.1','DBA_2J-P12.5.2','DBA_2J-P12.5.3','DBA_2J-P20.5.1','DBA_2J-P20.5.2','DBA_2J-P20.5.3',
'AKR_J-E16.5.1','AKR_J-E16.5.2','AKR_J-E16.5.3','AKR_J-P12.5.1','AKR_J-P12.5.2','AKR_J-P12.5.3','AKR_J-P20.5.1','AKR_J-P20.5.2','AKR_J-P20.5.3',
'CBA_J-E16.5.1','CBA_J-E16.5.2','CBA_J-E16.5.3','CBA_J-P12.5.1','CBA_J-P12.5.2','CBA_J-P12.5.3','CBA_J-P20.5.1','CBA_J-P20.5.2','CBA_J-P20.5.3',
'NOD_ShiLtJ-E16.5.1','NOD_ShiLtJ-E16.5.2','NOD_ShiLtJ-E16.5.3','NOD_ShiLtJ-P12.5.1','NOD_ShiLtJ-P12.5.2','NOD_ShiLtJ-P12.5.3','NOD_ShiLtJ-P20.5.1','NOD_ShiLtJ-P20.5.2','NOD_ShiLtJ-P20.5.3',
'WSB_EiJ-E16.5.1','WSB_EiJ-E16.5.2','WSB_EiJ-E16.5.3','WSB_EiJ-P12.5.1','WSB_EiJ-P12.5.2','WSB_EiJ-P12.5.3','WSB_EiJ-P20.5.1','WSB_EiJ-P20.5.2','WSB_EiJ-P20.5.3',
'CAST_EiJ-E16.5.1','CAST_EiJ-E16.5.2','CAST_EiJ-E16.5.3','CAST_EiJ-P12.5.1','CAST_EiJ-P12.5.2','CAST_EiJ-P12.5.3','CAST_EiJ-P20.5.1','CAST_EiJ-P20.5.2','CAST_EiJ-P20.5.3',
'PWK_PhJ-E16.5.1','PWK_PhJ-E16.5.2','PWK_PhJ-E16.5.3','PWK_PhJ-P12.5.1','PWK_PhJ-P12.5.2','PWK_PhJ-P12.5.3','PWK_PhJ-P20.5.1','PWK_PhJ-P20.5.2','PWK_PhJ-P20.5.3',
'SPRET_EiJ-E16.5.1','SPRET_EiJ-E16.5.2','SPRET_EiJ-E16.5.3','SPRET_EiJ-P12.5.1','SPRET_EiJ-P12.5.2','SPRET_EiJ-P12.5.3','SPRET_EiJ-P20.5.1','SPRET_EiJ-P20.5.2','SPRET_EiJ-P20.5.3')

In [11]:
A129S1_SvImJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/129S1_SvImJ_v3.2.gff3") #import gff3 file 
A129S1_SvImJ <- na.omit(mcols(A129S1_SvImJ)[,c("gene_id","Name",'type')])
A129S1_SvImJ <- A129S1_SvImJ[A129S1_SvImJ$type == 'gene', ]
A129S1_SvImJ
A129S1_SvImJ_geneName = A129S1_SvImJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(A129S1_SvImJ_geneName) <- A129S1_SvImJ_geneName$gene_id
A129S1_SvImJ_geneName$gene_id <- NULL
A129S1_SvImJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts')
#A129S1_SvImJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
A129S1_SvImJ_samplenames = c('129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-P20.5',
'129S1_SvImJ-P20.5','129S1_SvImJ-P20.5')

A129S1_SvImJ_lables = c('129S1_SvImJ-P12.5.1','129S1_SvImJ-P12.5.2','129S1_SvImJ-P12.5.3','129S1_SvImJ-E16.5.1','129S1_SvImJ-E16.5.2','129S1_SvImJ-E16.5.3','129S1_SvImJ-P20.5.1','129S1_SvImJ-P20.5.2','129S1_SvImJ-P20.5.3')

A129S1_SvImJ_raw <- readDGE(A129S1_SvImJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= A129S1_SvImJ_samplenames, labels = A129S1_SvImJ_lables)

library(dplyr)
A129S1_SvImJ_raw$counts <- merge(x=A129S1_SvImJ_raw$counts, y=A129S1_SvImJ_geneName, by = 0,all.x=TRUE ) #left merge 
A129S1_SvImJ_raw$counts['Row.names'] <- NULL
A129S1_SvImJ_raw$counts <- A129S1_SvImJ_raw$counts[!is.na(A129S1_SvImJ_raw$counts$Name),] #remove NA 
A129S1_SvImJ_raw$counts <- A129S1_SvImJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

A129S1_SvImJ_raw$counts <- as.data.frame(A129S1_SvImJ_raw$counts[!duplicated(A129S1_SvImJ_raw$counts$Name), ])  #remove dulicate values 
rownames(A129S1_SvImJ_raw$counts) <- A129S1_SvImJ_raw$counts$Name #set rawname to gene symbloes 
A129S1_SvImJ_raw$counts$Name <- NULL #remove genesybloe columns 
A129S1_SvImJ_raw

DataFrame with 20396 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00200002305        ugt1a1     gene
2     ENSMUSG00200002142          XKR4     gene
3     ENSMUSG00200001961           RP1     gene
4     ENSMUSG00200001998         SOX17     gene
5     ENSMUSG00200002527        MRPL15     gene
...                  ...           ...      ...
20392 ENSMUSG00200013771         AMELX     gene
20393 ENSMUSG00200013786          HCCS     gene
20394 ENSMUSG00200013810          rbmx     gene
20395 ENSMUSG00200013872          MID1     gene
20396 ENSMUSG00200013909 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                             files
129S1_SvImJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.1.featureCounts
129S1_SvImJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.2.featureCounts
129S1_SvImJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-12.5dpp.3.featureCounts
129S1_SvImJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.1.featureCounts
129S1_SvImJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.2.featureCounts
129S1_SvImJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-16.5dpc.3.featureCounts
129S1_SvImJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.1.featureCounts
129S1_SvImJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.2.featureCounts
129S1_SvImJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/129S1_SvImJ-20.5dpp.3.featureCounts
                                group lib.size norm.factors
129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5       NA            1
129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5       NA            1
129S1_SvImJ-P12.5.3 129S1_SvImJ-P12.5       NA            1
129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5       NA            1
129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5       NA            1
129S1_SvImJ-E16.5.3 129S1_SvImJ-E16.5       NA            1
129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5       NA            1
129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5       NA            1
129S1_SvImJ-P20.5.3 129S1_SvImJ-P20.5       NA            1

$counts
              129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
0610007P14Rik             1230.00             1233.50             1335.00
0610009B22Rik              395.00              390.00              408.00
0610009O20Rik             1209.00             1210.00             1349.00
0610010F05Rik             3900.83             3888.25             3582.75
0610010K14Rik              839.50              760.50              934.50
              129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
0610007P14Rik             1680.50              1897.0             1647.00
0610009B22Rik              467.25               547.0              460.25
0610009O20Rik             1950.00              2251.5             2220.50
0610010F05Rik             1398.60              1751.5             1737.00
0610010K14Rik              996.50               995.0              945.00
              129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3
0610007P14Rik               752.5               759.0              761.00
0610009B22Rik               918.0              1021.0              710.00
0610009O20Rik              2863.0              2785.5             2514.00
0610010F05Rik              4896.5              5130.5             4971.75
0610010K14Rik               435.0               423.0              394.00
19087 more rows ...

In [12]:
A_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/A_J_v3.2.gff3") #import gff3 file 
A_J <- na.omit(mcols(A_J)[,c("gene_id","Name",'type')])
A_J <- A_J[A_J$type == 'gene', ]
A_J
A_J_geneName = A_J[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(A_J_geneName) <- A_J_geneName$gene_id
A_J_geneName$gene_id <- NULL
A_J_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts')
#A_J_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "A_J.+.featureCounts$", full.names = T)
A_J_samplenames = c('A_J-P12.5','A_J-P12.5','A_J-P12.5','A_J-E16.5','A_J-E16.5','A_J-E16.5','A_J-P20.5','A_J-P20.5','A_J-P20.5')

A_J_lables = c('A_J-P12.5.1','A_J-P12.5.2','A_J-P12.5.3','A_J-E16.5.1','A_J-E16.5.2','A_J-E16.5.3','A_J-P20.5.1','A_J-P20.5.2','A_J-P20.5.3')

A_J_raw <- readDGE(A_J_files, columns = c(1, 7), comment.char = "#", sep="\t", group= A_J_samplenames, labels = A_J_lables)

library(dplyr)
A_J_raw$counts <- merge(x=A_J_raw$counts, y=A_J_geneName, by = 0,all.x=TRUE ) #left merge 
A_J_raw$counts['Row.names'] <- NULL
A_J_raw$counts <- A_J_raw$counts[!is.na(A_J_raw$counts$Name),] #remove NA 
A_J_raw$counts <- A_J_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

A_J_raw$counts <- as.data.frame(A_J_raw$counts[!duplicated(A_J_raw$counts$Name), ])  #remove dulicate values 
rownames(A_J_raw$counts) <- A_J_raw$counts$Name #set rawname to gene symbloes 
A_J_raw$counts$Name <- NULL #remove genesybloe columns 
A_J_raw

DataFrame with 20472 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00195002697          XKR4     gene
2     ENSMUSG00195002553           RP1     gene
3     ENSMUSG00195002578         SOX17     gene
4     ENSMUSG00195002659        MRPL15     gene
5     ENSMUSG00195002525        LYPLA1     gene
...                  ...           ...      ...
20468 ENSMUSG00195016023         AMELX     gene
20469 ENSMUSG00195016042          HCCS     gene
20470 ENSMUSG00195016074          rbmx     gene
20471 ENSMUSG00195015519          MID1     gene
20472 ENSMUSG00195015611 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                             files
A_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.1.featureCounts
A_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.2.featureCounts
A_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-12.5dpp.3.featureCounts
A_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.1.featureCounts
A_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.2.featureCounts
A_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-16.5dpc.3.featureCounts
A_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.1.featureCounts
A_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.2.featureCounts
A_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/A_J-20.5dpp.3.featureCounts
                group lib.size norm.factors
A_J-P12.5.1 A_J-P12.5       NA            1
A_J-P12.5.2 A_J-P12.5       NA            1
A_J-P12.5.3 A_J-P12.5       NA            1
A_J-E16.5.1 A_J-E16.5       NA            1
A_J-E16.5.2 A_J-E16.5       NA            1
A_J-E16.5.3 A_J-E16.5       NA            1
A_J-P20.5.1 A_J-P20.5       NA            1
A_J-P20.5.2 A_J-P20.5       NA            1
A_J-P20.5.3 A_J-P20.5       NA            1

$counts
              A_J-P12.5.1 A_J-P12.5.2 A_J-P12.5.3 A_J-E16.5.1 A_J-E16.5.2
0610007P14Rik     3019.00     3724.75     3516.07     6531.41     5648.35
0610009B22Rik      362.00      439.00      430.00      504.00      473.00
0610009O20Rik     1105.00     1351.50     1264.50     2068.00     1940.50
0610010F05Rik     3611.33     3864.82     3606.58     1532.05     1539.56
0610010K14Rik      691.00      933.00      764.00     1219.00     1063.00
              A_J-E16.5.3 A_J-P20.5.1 A_J-P20.5.2 A_J-P20.5.3
0610007P14Rik     5443.31     2712.36      2476.1     2408.24
0610009B22Rik      440.00      809.00       660.0      630.00
0610009O20Rik     1958.75     2531.00      2393.5     2136.00
0610010F05Rik     1399.74     4650.00      4613.5     4111.00
0610010K14Rik      964.00      470.50       462.5      451.00
19097 more rows ...

In [13]:
AKR_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/AKR_J_v3.2.gff3") #import gff3 file 
AKR_J <- na.omit(mcols(AKR_J)[,c("gene_id","Name",'type')])
AKR_J <- AKR_J[AKR_J$type == 'gene', ]
AKR_J
AKR_J_geneName = AKR_J[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(AKR_J_geneName) <- AKR_J_geneName$gene_id
AKR_J_geneName$gene_id <- NULL
AKR_J_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts')
#AKR_J_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
AKR_J_samplenames = c('AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5','AKR_J-E16.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5')

AKR_J_lables = c('AKR_J-P12.5.1','AKR_J-P12.5.2','AKR_J-P12.5.3','AKR_J-E16.5.1','AKR_J-E16.5.2','AKR_J-E16.5.3',
'AKR_J-P20.5.1','AKR_J-P20.5.2','AKR_J-P20.5.3')

AKR_J_raw <- readDGE(AKR_J_files, columns = c(1, 7), comment.char = "#", sep="\t", group= AKR_J_samplenames, labels = AKR_J_lables)
AKR_J_raw
library(dplyr)
AKR_J_raw$counts <- merge(x=AKR_J_raw$counts, y=AKR_J_geneName, by = 0,all.x=TRUE ) #left merge 
AKR_J_raw$counts['Row.names'] <- NULL
AKR_J_raw$counts <- AKR_J_raw$counts[!is.na(AKR_J_raw$counts$Name),] #remove NA 
AKR_J_raw$counts <- AKR_J_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

AKR_J_raw$counts <- as.data.frame(AKR_J_raw$counts[!duplicated(AKR_J_raw$counts$Name), ])  #remove dulicate values 
rownames(AKR_J_raw$counts) <- AKR_J_raw$counts$Name #set rawname to gene symbloes 
AKR_J_raw$counts$Name <- NULL #remove genesybloe columns 
AKR_J_raw

DataFrame with 20391 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00220003361          XKR4     gene
2     ENSMUSG00220003474           RP1     gene
3     ENSMUSG00220003489         SOX17     gene
4     ENSMUSG00220003074        MRPL15     gene
5     ENSMUSG00220003096        LYPLA1     gene
...                  ...           ...      ...
20387 ENSMUSG00220030338         AMELX     gene
20388 ENSMUSG00220030408          HCCS     gene
20389 ENSMUSG00220030465          rbmx     gene
20390 ENSMUSG00220010896          MID1     gene
20391 ENSMUSG00220010941 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                 files
AKR_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts
AKR_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts
AKR_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts
AKR_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts
AKR_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts
AKR_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts
AKR_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts
AKR_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts
AKR_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts
                    group lib.size norm.factors
AKR_J-P12.5.1 AKR_J-P12.5       NA            1
AKR_J-P12.5.2 AKR_J-P12.5       NA            1
AKR_J-P12.5.3 AKR_J-P12.5       NA            1
AKR_J-E16.5.1 AKR_J-E16.5       NA            1
AKR_J-E16.5.2 AKR_J-E16.5       NA            1
AKR_J-E16.5.3 AKR_J-E16.5       NA            1
AKR_J-P20.5.1 AKR_J-P20.5       NA            1
AKR_J-P20.5.2 AKR_J-P20.5       NA            1
AKR_J-P20.5.3 AKR_J-P20.5       NA            1

$counts
                    Samples
Tags                 AKR_J-P12.5.1 AKR_J-P12.5.2 AKR_J-P12.5.3 AKR_J-E16.5.1
  ENSMUSG00220004397          0.74          0.55          1.31          3.79
  ENSMUSG00220003652          0.00          0.00          0.00          0.00
  ENSMUSG00220003361       1255.13       1105.99       1444.79       5762.74
  ENSMUSG00220003634          9.50          2.00          9.00         37.50
  ENSMUSG00220003640          5.00          7.00          6.50         25.00
                    Samples
Tags                 AKR_J-E16.5.2 AKR_J-E16.5.3 AKR_J-P20.5.1 AKR_J-P20.5.2
  ENSMUSG00220004397          6.34         11.19          0.64          0.28
  ENSMUSG00220003652          0.00          0.00          0.00          0.00
  ENSMUSG00220003361       7581.04       6927.47        224.95        261.73
  ENSMUSG00220003634         43.00         42.00          0.50          0.50
  ENSMUSG00220003640         39.50         32.00          1.50          2.00
                    Samples
Tags                 AKR_J-P20.5.3
  ENSMUSG00220004397          1.05
  ENSMUSG00220003652          0.00
  ENSMUSG00220003361        232.94
  ENSMUSG00220003634          3.00
  ENSMUSG00220003640          0.00
25748 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                 files
AKR_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.1.featureCounts
AKR_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.2.featureCounts
AKR_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-12.5dpp.3.featureCounts
AKR_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.1.featureCounts
AKR_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.2.featureCounts
AKR_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-16.5dpc.3.featureCounts
AKR_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.1.featureCounts
AKR_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.2.featureCounts
AKR_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/AKR_J-20.5dpp.3.featureCounts
                    group lib.size norm.factors
AKR_J-P12.5.1 AKR_J-P12.5       NA            1
AKR_J-P12.5.2 AKR_J-P12.5       NA            1
AKR_J-P12.5.3 AKR_J-P12.5       NA            1
AKR_J-E16.5.1 AKR_J-E16.5       NA            1
AKR_J-E16.5.2 AKR_J-E16.5       NA            1
AKR_J-E16.5.3 AKR_J-E16.5       NA            1
AKR_J-P20.5.1 AKR_J-P20.5       NA            1
AKR_J-P20.5.2 AKR_J-P20.5       NA            1
AKR_J-P20.5.3 AKR_J-P20.5       NA            1

$counts
              AKR_J-P12.5.1 AKR_J-P12.5.2 AKR_J-P12.5.3 AKR_J-E16.5.1
0610007P14Rik       3295.50       3171.00       3255.63       5800.88
0610009B22Rik        471.00        464.00        394.00        457.00
0610009O20Rik       1276.00       1283.00       1250.00       2115.50
0610010F05Rik       3874.17       3813.32       4003.03       1330.25
0610010K14Rik        721.00        690.00        733.00        865.00
              AKR_J-E16.5.2 AKR_J-E16.5.3 AKR_J-P20.5.1 AKR_J-P20.5.2
0610007P14Rik       5995.95       6436.44       2774.47       2914.05
0610009B22Rik        539.00        512.00        879.00        872.00
0610009O20Rik       1957.50       2065.00       2431.50       2342.00
0610010F05Rik       1573.50       1420.00       4412.02       4566.75
0610010K14Rik        949.00       1038.00        466.00        492.50
              AKR_J-P20.5.3
0610007P14Rik       2544.57
0610009B22Rik        785.50
0610009O20Rik       2214.50
0610010F05Rik       4110.08
0610010K14Rik        435.00
19079 more rows ...

In [14]:
BALB_cJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/BALB_cJ_v3.2.gff3") #import gff3 file 
BALB_cJ <- na.omit(mcols(BALB_cJ)[,c("gene_id","Name",'type')])
BALB_cJ <- BALB_cJ[BALB_cJ$type == 'gene', ]
BALB_cJ
BALB_cJ_geneName = BALB_cJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(BALB_cJ_geneName) <- BALB_cJ_geneName$gene_id
BALB_cJ_geneName$gene_id <- NULL
BALB_cJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts')
#BALB_cJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
BALB_cJ_samplenames = c('BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-E16.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5')

BALB_cJ_lables = c('BALB_cJ-P12.5.1','BALB_cJ-P12.5.2','BALB_cJ-P12.5.3','BALB_cJ-E16.5.1','BALB_cJ-E16.5.2','BALB_cJ-E16.5.3',
'BALB_cJ-P20.5.1','BALB_cJ-P20.5.2','BALB_cJ-P20.5.3')

BALB_cJ_raw <- readDGE(BALB_cJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= BALB_cJ_samplenames, labels = BALB_cJ_lables)
BALB_cJ_raw
library(dplyr)
BALB_cJ_raw$counts <- merge(x=BALB_cJ_raw$counts, y=BALB_cJ_geneName, by = 0,all.x=TRUE ) #left merge 
BALB_cJ_raw$counts['Row.names'] <- NULL
BALB_cJ_raw$counts <- BALB_cJ_raw$counts[!is.na(BALB_cJ_raw$counts$Name),] #remove NA 
BALB_cJ_raw$counts <- BALB_cJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

BALB_cJ_raw$counts <- as.data.frame(BALB_cJ_raw$counts[!duplicated(BALB_cJ_raw$counts$Name), ])  #remove dulicate values 
rownames(BALB_cJ_raw$counts) <- BALB_cJ_raw$counts$Name #set rawname to gene symbloes 
BALB_cJ_raw$counts$Name <- NULL #remove genesybloe columns 
BALB_cJ_raw

DataFrame with 20490 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00180008421          XKR4     gene
2     ENSMUSG00180008881           RP1     gene
3     ENSMUSG00180008896         SOX17     gene
4     ENSMUSG00180008861        MRPL15     gene
5     ENSMUSG00180008716        LYPLA1     gene
...                  ...           ...      ...
20486 ENSMUSG00180017230          MID1     gene
20487 ENSMUSG00180017318 4933400A11Rik     gene
20488 ENSMUSG00180017370         HSPB7     gene
20489 ENSMUSG00180017573           GSN     gene
20490 ENSMUSG00180017649          ASMT     gene

An object of class "DGEList"
$samples
                                                                                                                                     files
BALB_cJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts
BALB_cJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts
BALB_cJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts
BALB_cJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts
BALB_cJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts
BALB_cJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts
BALB_cJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts
BALB_cJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts
BALB_cJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
BALB_cJ-P12.5.1 BALB_cJ-P12.5       NA            1
BALB_cJ-P12.5.2 BALB_cJ-P12.5       NA            1
BALB_cJ-P12.5.3 BALB_cJ-P12.5       NA            1
BALB_cJ-E16.5.1 BALB_cJ-E16.5       NA            1
BALB_cJ-E16.5.2 BALB_cJ-E16.5       NA            1
BALB_cJ-E16.5.3 BALB_cJ-E16.5       NA            1
BALB_cJ-P20.5.1 BALB_cJ-P20.5       NA            1
BALB_cJ-P20.5.2 BALB_cJ-P20.5       NA            1
BALB_cJ-P20.5.3 BALB_cJ-P20.5       NA            1

$counts
                    Samples
Tags                 BALB_cJ-P12.5.1 BALB_cJ-P12.5.2 BALB_cJ-P12.5.3
  ENSMUSG00180008413            0.00            0.00            1.00
  ENSMUSG00180009296            0.00            0.00            0.00
  ENSMUSG00180008421         2597.77         3038.11         3091.05
  ENSMUSG00180009311           23.00           13.00           23.00
  ENSMUSG00180009306           15.50           21.00           18.00
                    Samples
Tags                 BALB_cJ-E16.5.1 BALB_cJ-E16.5.2 BALB_cJ-E16.5.3
  ENSMUSG00180008413            0.00            0.00            0.00
  ENSMUSG00180009296            1.00            0.00            0.00
  ENSMUSG00180008421        12842.17         7192.17        11471.79
  ENSMUSG00180009311           85.00           58.00           80.50
  ENSMUSG00180009306           69.50           38.50           62.50
                    Samples
Tags                 BALB_cJ-P20.5.1 BALB_cJ-P20.5.2 BALB_cJ-P20.5.3
  ENSMUSG00180008413            0.00            0.00            0.00
  ENSMUSG00180009296            0.00            0.00            0.00
  ENSMUSG00180008421          861.38          934.57          587.09
  ENSMUSG00180009311            3.50            7.50            3.50
  ENSMUSG00180009306            5.50            7.00            2.50
26040 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                     files
BALB_cJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.1.featureCounts
BALB_cJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.2.featureCounts
BALB_cJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-12.5dpp.3.featureCounts
BALB_cJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.1.featureCounts
BALB_cJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.2.featureCounts
BALB_cJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-16.5dpc.3.featureCounts
BALB_cJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.1.featureCounts
BALB_cJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.2.featureCounts
BALB_cJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/BALB_cJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
BALB_cJ-P12.5.1 BALB_cJ-P12.5       NA            1
BALB_cJ-P12.5.2 BALB_cJ-P12.5       NA            1
BALB_cJ-P12.5.3 BALB_cJ-P12.5       NA            1
BALB_cJ-E16.5.1 BALB_cJ-E16.5       NA            1
BALB_cJ-E16.5.2 BALB_cJ-E16.5       NA            1
BALB_cJ-E16.5.3 BALB_cJ-E16.5       NA            1
BALB_cJ-P20.5.1 BALB_cJ-P20.5       NA            1
BALB_cJ-P20.5.2 BALB_cJ-P20.5       NA            1
BALB_cJ-P20.5.3 BALB_cJ-P20.5       NA            1

$counts
              BALB_cJ-P12.5.1 BALB_cJ-P12.5.2 BALB_cJ-P12.5.3 BALB_cJ-E16.5.1
0610007P14Rik         1988.76         2212.65         2136.75         3112.41
0610009B22Rik          327.00          369.00          436.17          472.00
0610009O20Rik          972.00         1173.50         1315.50         1926.50
0610010F05Rik         3364.50         3473.81         3617.92         1900.79
0610010K14Rik          820.50          881.00          913.00          666.00
              BALB_cJ-E16.5.2 BALB_cJ-E16.5.3 BALB_cJ-P20.5.1 BALB_cJ-P20.5.2
0610007P14Rik         3021.72         3894.10         1509.12         1661.61
0610009B22Rik          459.00          539.00          599.00          530.00
0610009O20Rik         1919.00         2392.00         1787.00         1788.50
0610010F05Rik         1358.03         1988.25         4241.50         4499.31
0610010K14Rik          779.50          837.00          616.50          646.00
              BALB_cJ-P20.5.3
0610007P14Rik         1733.63
0610009B22Rik          724.00
0610009O20Rik         2324.83
0610010F05Rik         4550.50
0610010K14Rik          634.00
19097 more rows ...

In [15]:
C3H_HeJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C3H_HeJ_v3.2.gff3") #import gff3 file 
C3H_HeJ <- na.omit(mcols(C3H_HeJ)[,c("gene_id","Name",'type')])
C3H_HeJ <- C3H_HeJ[C3H_HeJ$type == 'gene', ]
C3H_HeJ
C3H_HeJ_geneName = C3H_HeJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(C3H_HeJ_geneName) <- C3H_HeJ_geneName$gene_id
C3H_HeJ_geneName$gene_id <- NULL
C3H_HeJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts')
#C3H_HeJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
C3H_HeJ_samplenames = c('C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-E16.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5')

C3H_HeJ_lables = c('C3H_HeJ-P12.5.1','C3H_HeJ-P12.5.2','C3H_HeJ-P12.5.3','C3H_HeJ-E16.5.1','C3H_HeJ-E16.5.2','C3H_HeJ-E16.5.3',
'C3H_HeJ-P20.5.1','C3H_HeJ-P20.5.2','C3H_HeJ-P20.5.3')

C3H_HeJ_raw <- readDGE(C3H_HeJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= C3H_HeJ_samplenames, labels = C3H_HeJ_lables)
C3H_HeJ_raw
library(dplyr)
C3H_HeJ_raw$counts <- merge(x=C3H_HeJ_raw$counts, y=C3H_HeJ_geneName, by = 0,all.x=TRUE ) #left merge 
C3H_HeJ_raw$counts['Row.names'] <- NULL
C3H_HeJ_raw$counts <- C3H_HeJ_raw$counts[!is.na(C3H_HeJ_raw$counts$Name),] #remove NA 
C3H_HeJ_raw$counts <- C3H_HeJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

C3H_HeJ_raw$counts <- as.data.frame(C3H_HeJ_raw$counts[!duplicated(C3H_HeJ_raw$counts$Name), ])  #remove dulicate values 
rownames(C3H_HeJ_raw$counts) <- C3H_HeJ_raw$counts$Name #set rawname to gene symbloes 
C3H_HeJ_raw$counts$Name <- NULL #remove genesybloe columns 
C3H_HeJ_raw

DataFrame with 20427 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00175000235        CDCA7L     gene
2     ENSMUSG00175000248          XKR4     gene
3     ENSMUSG00175000083           RP1     gene
4     ENSMUSG00175000092         SOX17     gene
5     ENSMUSG00175000224        MRPL15     gene
...                  ...           ...      ...
20423 ENSMUSG00175010162          HCCS     gene
20424 ENSMUSG00175010173          rbmx     gene
20425 ENSMUSG00175010317          MID1     gene
20426 ENSMUSG00175010348 4933400A11Rik     gene
20427 ENSMUSG00175010363       DYNLRB2     gene

An object of class "DGEList"
$samples
                                                                                                                                     files
C3H_HeJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts
C3H_HeJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts
C3H_HeJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts
C3H_HeJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts
C3H_HeJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts
C3H_HeJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts
C3H_HeJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts
C3H_HeJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts
C3H_HeJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
C3H_HeJ-P12.5.1 C3H_HeJ-P12.5       NA            1
C3H_HeJ-P12.5.2 C3H_HeJ-P12.5       NA            1
C3H_HeJ-P12.5.3 C3H_HeJ-P12.5       NA            1
C3H_HeJ-E16.5.1 C3H_HeJ-E16.5       NA            1
C3H_HeJ-E16.5.2 C3H_HeJ-E16.5       NA            1
C3H_HeJ-E16.5.3 C3H_HeJ-E16.5       NA            1
C3H_HeJ-P20.5.1 C3H_HeJ-P20.5       NA            1
C3H_HeJ-P20.5.2 C3H_HeJ-P20.5       NA            1
C3H_HeJ-P20.5.3 C3H_HeJ-P20.5       NA            1

$counts
                    Samples
Tags                 C3H_HeJ-P12.5.1 C3H_HeJ-P12.5.2 C3H_HeJ-P12.5.3
  ENSMUSG00175000229           14.70           17.00           12.50
  ENSMUSG00175000233            3.00            0.50            5.50
  ENSMUSG00175000235           18.34           10.46           21.67
  ENSMUSG00175000240            0.97            0.29            1.64
  ENSMUSG00175000242            9.46            4.27           16.48
                    Samples
Tags                 C3H_HeJ-E16.5.1 C3H_HeJ-E16.5.2 C3H_HeJ-E16.5.3
  ENSMUSG00175000229           15.00           16.20           11.08
  ENSMUSG00175000233            6.00            3.50            4.50
  ENSMUSG00175000235           81.72           84.21           60.46
  ENSMUSG00175000240            5.81            6.35            2.79
  ENSMUSG00175000242           39.79           39.09           29.02
                    Samples
Tags                 C3H_HeJ-P20.5.1 C3H_HeJ-P20.5.2 C3H_HeJ-P20.5.3
  ENSMUSG00175000229            4.25            7.00            6.25
  ENSMUSG00175000233            1.00            0.75            4.00
  ENSMUSG00175000235            6.99           11.75           10.21
  ENSMUSG00175000240            0.57            0.58            1.54
  ENSMUSG00175000242            6.49            6.37           11.83
25883 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                     files
C3H_HeJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.1.featureCounts
C3H_HeJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.2.featureCounts
C3H_HeJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-12.5dpp.3.featureCounts
C3H_HeJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.1.featureCounts
C3H_HeJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.2.featureCounts
C3H_HeJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-16.5dpc.3.featureCounts
C3H_HeJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.1.featureCounts
C3H_HeJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.2.featureCounts
C3H_HeJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C3H_HeJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
C3H_HeJ-P12.5.1 C3H_HeJ-P12.5       NA            1
C3H_HeJ-P12.5.2 C3H_HeJ-P12.5       NA            1
C3H_HeJ-P12.5.3 C3H_HeJ-P12.5       NA            1
C3H_HeJ-E16.5.1 C3H_HeJ-E16.5       NA            1
C3H_HeJ-E16.5.2 C3H_HeJ-E16.5       NA            1
C3H_HeJ-E16.5.3 C3H_HeJ-E16.5       NA            1
C3H_HeJ-P20.5.1 C3H_HeJ-P20.5       NA            1
C3H_HeJ-P20.5.2 C3H_HeJ-P20.5       NA            1
C3H_HeJ-P20.5.3 C3H_HeJ-P20.5       NA            1

$counts
              C3H_HeJ-P12.5.1 C3H_HeJ-P12.5.2 C3H_HeJ-P12.5.3 C3H_HeJ-E16.5.1
0610007P14Rik         2682.33         2645.08         3183.66         5251.74
0610009B22Rik          397.00          343.00          393.00          514.00
0610009O20Rik         1359.71         1305.78         1398.13         2605.64
0610010F05Rik         3335.09         3385.75         3855.29         1652.89
0610010K14Rik          722.50          619.50          712.00          858.00
              C3H_HeJ-E16.5.2 C3H_HeJ-E16.5.3 C3H_HeJ-P20.5.1 C3H_HeJ-P20.5.2
0610007P14Rik         5931.97         5258.24         1998.90         2106.58
0610009B22Rik          532.00          503.00          792.00          816.00
0610009O20Rik         2919.36         2583.03         2831.34         2976.50
0610010F05Rik         1653.00         1680.84         4693.08         4745.25
0610010K14Rik          899.00          717.00          369.00          407.50
              C3H_HeJ-P20.5.3
0610007P14Rik         2021.06
0610009B22Rik          718.00
0610009O20Rik         2724.15
0610010F05Rik         4468.25
0610010K14Rik          392.00
19093 more rows ...

In [16]:
C57BL_6NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/C57BL_6NJ_v3.2.gff3") #import gff3 file 
C57BL_6NJ <- na.omit(mcols(C57BL_6NJ)[,c("gene_id","Name",'type')])
C57BL_6NJ <- C57BL_6NJ[C57BL_6NJ$type == 'gene', ]
C57BL_6NJ
C57BL_6NJ_geneName = C57BL_6NJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(C57BL_6NJ_geneName) <- C57BL_6NJ_geneName$gene_id
C57BL_6NJ_geneName$gene_id <- NULL
C57BL_6NJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts')
#C57BL_6NJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
C57BL_6NJ_samplenames = c('C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-E16.5',
'C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5')

C57BL_6NJ_lables = c('C57BL_6NJ-P12.5.1','C57BL_6NJ-P12.5.2','C57BL_6NJ-P12.5.3','C57BL_6NJ-E16.5.1','C57BL_6NJ-E16.5.2','C57BL_6NJ-E16.5.3',
'C57BL_6NJ-P20.5.1','C57BL_6NJ-P20.5.2','C57BL_6NJ-P20.5.3')

C57BL_6NJ_raw <- readDGE(C57BL_6NJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= C57BL_6NJ_samplenames, labels = C57BL_6NJ_lables)
C57BL_6NJ_raw
library(dplyr)
C57BL_6NJ_raw$counts <- merge(x=C57BL_6NJ_raw$counts, y=C57BL_6NJ_geneName, by = 0,all.x=TRUE ) #left merge 
C57BL_6NJ_raw$counts['Row.names'] <- NULL
C57BL_6NJ_raw$counts <- C57BL_6NJ_raw$counts[!is.na(C57BL_6NJ_raw$counts$Name),] #remove NA 
C57BL_6NJ_raw$counts <- C57BL_6NJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

C57BL_6NJ_raw$counts <- as.data.frame(C57BL_6NJ_raw$counts[!duplicated(C57BL_6NJ_raw$counts$Name), ])  #remove dulicate values 
rownames(C57BL_6NJ_raw$counts) <- C57BL_6NJ_raw$counts$Name #set rawname to gene symbloes 
C57BL_6NJ_raw$counts$Name <- NULL #remove genesybloe columns 
C57BL_6NJ_raw

DataFrame with 20459 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00215003924          XKR4     gene
2     ENSMUSG00215004064           RP1     gene
3     ENSMUSG00215004070         SOX17     gene
4     ENSMUSG00215004045        MRPL15     gene
5     ENSMUSG00215004089        LYPLA1     gene
...                  ...           ...      ...
20455 ENSMUSG00215015868         AMELX     gene
20456 ENSMUSG00215016025          HCCS     gene
20457 ENSMUSG00215016164          rbmx     gene
20458 ENSMUSG00215016408          MID1     gene
20459 ENSMUSG00215016857 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                         files
C57BL_6NJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts
C57BL_6NJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts
C57BL_6NJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts
C57BL_6NJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts
C57BL_6NJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts
C57BL_6NJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts
C57BL_6NJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts
C57BL_6NJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts
C57BL_6NJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
C57BL_6NJ-P12.5.1 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-P12.5.2 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-P12.5.3 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-E16.5.1 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-E16.5.2 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-E16.5.3 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5       NA            1
C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5       NA            1
C57BL_6NJ-P20.5.3 C57BL_6NJ-P20.5       NA            1

$counts
                    Samples
Tags                 C57BL_6NJ-P12.5.1 C57BL_6NJ-P12.5.2 C57BL_6NJ-P12.5.3
  ENSMUSG00215004188              2.00              3.00              0.00
  ENSMUSG00215003924           5153.36           3880.57           2029.29
  ENSMUSG00215004192             38.50             20.50             16.00
  ENSMUSG00215004193             28.50             24.50             11.50
  ENSMUSG00215004190              7.00              9.50              5.00
                    Samples
Tags                 C57BL_6NJ-E16.5.1 C57BL_6NJ-E16.5.2 C57BL_6NJ-E16.5.3
  ENSMUSG00215004188              0.00              0.00              0.00
  ENSMUSG00215003924           9320.22           6912.63           9572.17
  ENSMUSG00215004192             54.50             69.00             65.00
  ENSMUSG00215004193             41.00             31.50             49.50
  ENSMUSG00215004190             13.00             14.50             18.50
                    Samples
Tags                 C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5.3
  ENSMUSG00215004188              0.00              0.00              1.00
  ENSMUSG00215003924            506.66            330.24            316.26
  ENSMUSG00215004192              3.50              0.50              2.50
  ENSMUSG00215004193              2.50              1.00              0.00
  ENSMUSG00215004190              1.50              0.00              0.50
26128 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                         files
C57BL_6NJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.1.featureCounts
C57BL_6NJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.2.featureCounts
C57BL_6NJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-12.5dpp.3.featureCounts
C57BL_6NJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.1.featureCounts
C57BL_6NJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.2.featureCounts
C57BL_6NJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-16.5dpc.3.featureCounts
C57BL_6NJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.1.featureCounts
C57BL_6NJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.2.featureCounts
C57BL_6NJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/C57BL_6NJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
C57BL_6NJ-P12.5.1 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-P12.5.2 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-P12.5.3 C57BL_6NJ-P12.5       NA            1
C57BL_6NJ-E16.5.1 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-E16.5.2 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-E16.5.3 C57BL_6NJ-E16.5       NA            1
C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5       NA            1
C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5       NA            1
C57BL_6NJ-P20.5.3 C57BL_6NJ-P20.5       NA            1

$counts
              C57BL_6NJ-P12.5.1 C57BL_6NJ-P12.5.2 C57BL_6NJ-P12.5.3
0610007P14Rik           2248.13           1800.24           2323.98
0610009B22Rik            403.00            368.00            531.00
0610009O20Rik           1471.00           1222.50           1889.50
0610010F05Rik           3404.55           3233.50           3956.62
0610010K14Rik            959.00            707.50            829.00
              C57BL_6NJ-E16.5.1 C57BL_6NJ-E16.5.2 C57BL_6NJ-E16.5.3
0610007P14Rik           3343.90           4081.37           3890.25
0610009B22Rik            525.00            545.00            576.00
0610009O20Rik           2407.00           2995.00           2793.00
0610010F05Rik           1944.83           1865.90           1888.01
0610010K14Rik            807.50            950.00            886.00
              C57BL_6NJ-P20.5.1 C57BL_6NJ-P20.5.2 C57BL_6NJ-P20.5.3
0610007P14Rik           1452.37           1477.20           1445.81
0610009B22Rik            610.00            790.00            812.00
0610009O20Rik           2951.50           3494.50           3433.50
0610010F05Rik           4545.25           5064.61           4637.67
0610010K14Rik            437.00            466.00            412.50
19122 more rows ...

In [17]:
CAST_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CAST_EiJ_v3.2.gff3") #import gff3 file 
CAST_EiJ <- na.omit(mcols(CAST_EiJ)[,c("gene_id","Name",'type')])
CAST_EiJ <- CAST_EiJ[CAST_EiJ$type == 'gene', ]
CAST_EiJ
CAST_EiJ_geneName = CAST_EiJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(CAST_EiJ_geneName) <- CAST_EiJ_geneName$gene_id
CAST_EiJ_geneName$gene_id <- NULL
CAST_EiJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts')
#CAST_EiJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
CAST_EiJ_samplenames = c('CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-E16.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5')

CAST_EiJ_lables = c('CAST_EiJ-P12.5.1','CAST_EiJ-P12.5.2','CAST_EiJ-P12.5.3','CAST_EiJ-E16.5.1','CAST_EiJ-E16.5.2','CAST_EiJ-E16.5.3',
'CAST_EiJ-P20.5.1','CAST_EiJ-P20.5.2','CAST_EiJ-P20.5.3')

CAST_EiJ_raw <- readDGE(CAST_EiJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= CAST_EiJ_samplenames, labels = CAST_EiJ_lables)
CAST_EiJ_raw
library(dplyr)
CAST_EiJ_raw$counts <- merge(x=CAST_EiJ_raw$counts, y=CAST_EiJ_geneName, by = 0,all.x=TRUE ) #left merge 
CAST_EiJ_raw$counts['Row.names'] <- NULL
CAST_EiJ_raw$counts <- CAST_EiJ_raw$counts[!is.na(CAST_EiJ_raw$counts$Name),] #remove NA 
CAST_EiJ_raw$counts <- CAST_EiJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

CAST_EiJ_raw$counts <- as.data.frame(CAST_EiJ_raw$counts[!duplicated(CAST_EiJ_raw$counts$Name), ])  #remove dulicate values 
rownames(CAST_EiJ_raw$counts) <- CAST_EiJ_raw$counts$Name #set rawname to gene symbloes 
CAST_EiJ_raw$counts$Name <- NULL #remove genesybloe columns 
CAST_EiJ_raw

DataFrame with 20368 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSTCUG00005001819        MROH2A     gene
2     ENSTCUG00005001868         HJURP     gene
3     ENSTCUG00005002045          XKR4     gene
4     ENSTCUG00005001875           RP1     gene
5     ENSTCUG00005001952         SOX17     gene
...                  ...           ...      ...
20364 ENSTCUG00005024214          HCCS     gene
20365 ENSTCUG00005024248          rbmx     gene
20366 ENSTCUG00005023838          PRC1     gene
20367 ENSTCUG00005024102          MID1     gene
20368 ENSTCUG00005024201 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                       files
CAST_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts
CAST_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts
CAST_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts
CAST_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts
CAST_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts
CAST_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts
CAST_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts
CAST_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts
CAST_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts
                          group lib.size norm.factors
CAST_EiJ-P12.5.1 CAST_EiJ-P12.5       NA            1
CAST_EiJ-P12.5.2 CAST_EiJ-P12.5       NA            1
CAST_EiJ-P12.5.3 CAST_EiJ-P12.5       NA            1
CAST_EiJ-E16.5.1 CAST_EiJ-E16.5       NA            1
CAST_EiJ-E16.5.2 CAST_EiJ-E16.5       NA            1
CAST_EiJ-E16.5.3 CAST_EiJ-E16.5       NA            1
CAST_EiJ-P20.5.1 CAST_EiJ-P20.5       NA            1
CAST_EiJ-P20.5.2 CAST_EiJ-P20.5       NA            1
CAST_EiJ-P20.5.3 CAST_EiJ-P20.5       NA            1

$counts
                    Samples
Tags                 CAST_EiJ-P12.5.1 CAST_EiJ-P12.5.2 CAST_EiJ-P12.5.3
  ENSTCUG00005001695            18.58            14.17            21.25
  ENSTCUG00005001713             0.75             1.00             1.75
  ENSTCUG00005001708             3.75             5.00             3.75
  ENSTCUG00005002302             2.10             3.61             2.76
  ENSTCUG00005001717             1.50             2.00             3.50
                    Samples
Tags                 CAST_EiJ-E16.5.1 CAST_EiJ-E16.5.2 CAST_EiJ-E16.5.3
  ENSTCUG00005001695           451.08           560.83           566.50
  ENSTCUG00005001713            96.25           125.75           136.58
  ENSTCUG00005001708           123.25           159.25           209.83
  ENSTCUG00005002302             2.44             3.77             2.26
  ENSTCUG00005001717            62.83            78.00            88.50
                    Samples
Tags                 CAST_EiJ-P20.5.1 CAST_EiJ-P20.5.2 CAST_EiJ-P20.5.3
  ENSTCUG00005001695             5.75            19.50            22.50
  ENSTCUG00005001713             2.25             4.25             1.75
  ENSTCUG00005001708             2.75             3.25             4.75
  ENSTCUG00005002302             4.15             4.02             2.83
  ENSTCUG00005001717             2.00             3.50             0.50
25562 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                       files
CAST_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.1.featureCounts
CAST_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.2.featureCounts
CAST_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-12.5dpp.3.featureCounts
CAST_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.1.featureCounts
CAST_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.2.featureCounts
CAST_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-16.5dpc.3.featureCounts
CAST_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.1.featureCounts
CAST_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.2.featureCounts
CAST_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CAST_EiJ-20.5dpp.3.featureCounts
                          group lib.size norm.factors
CAST_EiJ-P12.5.1 CAST_EiJ-P12.5       NA            1
CAST_EiJ-P12.5.2 CAST_EiJ-P12.5       NA            1
CAST_EiJ-P12.5.3 CAST_EiJ-P12.5       NA            1
CAST_EiJ-E16.5.1 CAST_EiJ-E16.5       NA            1
CAST_EiJ-E16.5.2 CAST_EiJ-E16.5       NA            1
CAST_EiJ-E16.5.3 CAST_EiJ-E16.5       NA            1
CAST_EiJ-P20.5.1 CAST_EiJ-P20.5       NA            1
CAST_EiJ-P20.5.2 CAST_EiJ-P20.5       NA            1
CAST_EiJ-P20.5.3 CAST_EiJ-P20.5       NA            1

$counts
              CAST_EiJ-P12.5.1 CAST_EiJ-P12.5.2 CAST_EiJ-P12.5.3
0610007P14Rik          1841.43          2148.42          1956.72
0610009B22Rik           324.00           331.00           317.00
0610009O20Rik          1361.50          1563.50          1418.50
0610010F05Rik          2865.53          3202.17          3250.83
0610010K14Rik           854.00           929.50           866.50
              CAST_EiJ-E16.5.1 CAST_EiJ-E16.5.2 CAST_EiJ-E16.5.3
0610007P14Rik          2021.81          2251.87          2289.36
0610009B22Rik           432.00           516.00           470.00
0610009O20Rik          2346.25          2216.50          2528.50
0610010F05Rik          2088.08          2021.00          1794.89
0610010K14Rik           693.50           755.00           789.50
              CAST_EiJ-P20.5.1 CAST_EiJ-P20.5.2 CAST_EiJ-P20.5.3
0610007P14Rik          1099.87          1215.56          1244.76
0610009B22Rik           530.00           469.00           404.00
0610009O20Rik          2279.00          2138.50          2190.00
0610010F05Rik          4460.70          4218.87          4232.33
0610010K14Rik           454.00           493.00           641.00
19001 more rows ...

In [18]:
CBA_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/CBA_J_v3.2.gff3") #import gff3 file 
CBA_J <- na.omit(mcols(CBA_J)[,c("gene_id","Name",'type')])
CBA_J <- CBA_J[CBA_J$type == 'gene', ]
CBA_J
CBA_J_geneName = CBA_J[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(CBA_J_geneName) <- CBA_J_geneName$gene_id
CBA_J_geneName$gene_id <- NULL
CBA_J_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts')
#CBA_J_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
CBA_J_samplenames = c('CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5','CBA_J-E16.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5')

CBA_J_lables = c('CBA_J-P12.5.1','CBA_J-P12.5.2','CBA_J-P12.5.3','CBA_J-E16.5.1','CBA_J-E16.5.2','CBA_J-E16.5.3',
'CBA_J-P20.5.1','CBA_J-P20.5.2','CBA_J-P20.5.3')

CBA_J_raw <- readDGE(CBA_J_files, columns = c(1, 7), comment.char = "#", sep="\t", group= CBA_J_samplenames, labels = CBA_J_lables)
CBA_J_raw
library(dplyr)
CBA_J_raw$counts <- merge(x=CBA_J_raw$counts, y=CBA_J_geneName, by = 0,all.x=TRUE ) #left merge 
CBA_J_raw$counts['Row.names'] <- NULL
CBA_J_raw$counts <- CBA_J_raw$counts[!is.na(CBA_J_raw$counts$Name),] #remove NA 
CBA_J_raw$counts <- CBA_J_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

CBA_J_raw$counts <- as.data.frame(CBA_J_raw$counts[!duplicated(CBA_J_raw$counts$Name), ])  #remove dulicate values 
rownames(CBA_J_raw$counts) <- CBA_J_raw$counts$Name #set rawname to gene symbloes 
CBA_J_raw$counts$Name <- NULL #remove genesybloe columns 
CBA_J_raw

DataFrame with 20435 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00210001546          XKR4     gene
2     ENSMUSG00210001575           RP1     gene
3     ENSMUSG00210001604         SOX17     gene
4     ENSMUSG00210001755        MRPL15     gene
5     ENSMUSG00210001766        LYPLA1     gene
...                  ...           ...      ...
20431 ENSMUSG00210028259         AMELX     gene
20432 ENSMUSG00210028307          HCCS     gene
20433 ENSMUSG00210028366          rbmx     gene
20434 ENSMUSG00210027771          MID1     gene
20435 ENSMUSG00210027942 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                 files
CBA_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts
CBA_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts
CBA_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts
CBA_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts
CBA_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts
CBA_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts
CBA_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts
CBA_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts
CBA_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts
                    group lib.size norm.factors
CBA_J-P12.5.1 CBA_J-P12.5       NA            1
CBA_J-P12.5.2 CBA_J-P12.5       NA            1
CBA_J-P12.5.3 CBA_J-P12.5       NA            1
CBA_J-E16.5.1 CBA_J-E16.5       NA            1
CBA_J-E16.5.2 CBA_J-E16.5       NA            1
CBA_J-E16.5.3 CBA_J-E16.5       NA            1
CBA_J-P20.5.1 CBA_J-P20.5       NA            1
CBA_J-P20.5.2 CBA_J-P20.5       NA            1
CBA_J-P20.5.3 CBA_J-P20.5       NA            1

$counts
                    Samples
Tags                 CBA_J-P12.5.1 CBA_J-P12.5.2 CBA_J-P12.5.3 CBA_J-E16.5.1
  ENSMUSG00210002154          0.00          0.00           0.0          0.00
  ENSMUSG00210001546       2092.65       2011.75        1488.7      14060.35
  ENSMUSG00210002157         13.50         11.00           4.0         98.00
  ENSMUSG00210002159         12.50         11.50          10.5         85.00
  ENSMUSG00210002156          2.50          2.50           1.5         26.00
                    Samples
Tags                 CBA_J-E16.5.2 CBA_J-E16.5.3 CBA_J-P20.5.1 CBA_J-P20.5.2
  ENSMUSG00210002154          0.00          0.00          0.00          0.00
  ENSMUSG00210001546      14818.51      14000.46        547.79        425.36
  ENSMUSG00210002157         96.00         70.50          3.00          4.00
  ENSMUSG00210002159         80.00         78.00          2.50          2.50
  ENSMUSG00210002156         27.50         25.00          2.00          2.00
                    Samples
Tags                 CBA_J-P20.5.3
  ENSMUSG00210002154           0.0
  ENSMUSG00210001546         478.4
  ENSMUSG00210002157           2.0
  ENSMUSG00210002159           1.0
  ENSMUSG00210002156           0.0
25815 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                 files
CBA_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.1.featureCounts
CBA_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.2.featureCounts
CBA_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-12.5dpp.3.featureCounts
CBA_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.1.featureCounts
CBA_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.2.featureCounts
CBA_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-16.5dpc.3.featureCounts
CBA_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.1.featureCounts
CBA_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.2.featureCounts
CBA_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/CBA_J-20.5dpp.3.featureCounts
                    group lib.size norm.factors
CBA_J-P12.5.1 CBA_J-P12.5       NA            1
CBA_J-P12.5.2 CBA_J-P12.5       NA            1
CBA_J-P12.5.3 CBA_J-P12.5       NA            1
CBA_J-E16.5.1 CBA_J-E16.5       NA            1
CBA_J-E16.5.2 CBA_J-E16.5       NA            1
CBA_J-E16.5.3 CBA_J-E16.5       NA            1
CBA_J-P20.5.1 CBA_J-P20.5       NA            1
CBA_J-P20.5.2 CBA_J-P20.5       NA            1
CBA_J-P20.5.3 CBA_J-P20.5       NA            1

$counts
              CBA_J-P12.5.1 CBA_J-P12.5.2 CBA_J-P12.5.3 CBA_J-E16.5.1
0610007P14Rik       2605.13       2962.25       2665.03       5225.24
0610009B22Rik        382.00        446.00        392.00        545.00
0610009O20Rik       1226.00       1439.00       1287.00       2793.50
0610010F05Rik       3508.38       3931.71       3529.67       1960.06
0610010K14Rik        790.00        812.00        658.00        757.00
              CBA_J-E16.5.2 CBA_J-E16.5.3 CBA_J-P20.5.1 CBA_J-P20.5.2
0610007P14Rik       4588.88       6095.43       2571.93       2360.48
0610009B22Rik        429.50        625.00        712.00        699.00
0610009O20Rik       2294.50       3011.50       2120.00       1955.00
0610010F05Rik       1873.53       1811.60       4898.50       4344.75
0610010K14Rik        878.50        867.50        602.50        495.50
              CBA_J-P20.5.3
0610007P14Rik       2239.06
0610009B22Rik        615.00
0610009O20Rik       1921.50
0610010F05Rik       4412.50
0610010K14Rik        519.00
19093 more rows ...

In [19]:
DBA_2J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/DBA_2J_v3.2.gff3") #import gff3 file 
DBA_2J <- na.omit(mcols(DBA_2J)[,c("gene_id","Name",'type')])
DBA_2J <- DBA_2J[DBA_2J$type == 'gene', ]
DBA_2J
DBA_2J_geneName = DBA_2J[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(DBA_2J_geneName) <- DBA_2J_geneName$gene_id
DBA_2J_geneName$gene_id <- NULL
DBA_2J_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts')
#DBA_2J_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
DBA_2J_samplenames = c('DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-E16.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5')

DBA_2J_lables = c('DBA_2J-P12.5.1','DBA_2J-P12.5.2','DBA_2J-P12.5.3','DBA_2J-E16.5.1','DBA_2J-E16.5.2','DBA_2J-E16.5.3',
'DBA_2J-P20.5.1','DBA_2J-P20.5.2','DBA_2J-P20.5.3')

DBA_2J_raw <- readDGE(DBA_2J_files, columns = c(1, 7), comment.char = "#", sep="\t", group= DBA_2J_samplenames, labels = DBA_2J_lables)
DBA_2J_raw
library(dplyr)
DBA_2J_raw$counts <- merge(x=DBA_2J_raw$counts, y=DBA_2J_geneName, by = 0,all.x=TRUE ) #left merge 
DBA_2J_raw$counts['Row.names'] <- NULL
DBA_2J_raw$counts <- DBA_2J_raw$counts[!is.na(DBA_2J_raw$counts$Name),] #remove NA 
DBA_2J_raw$counts <- DBA_2J_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

DBA_2J_raw$counts <- as.data.frame(DBA_2J_raw$counts[!duplicated(DBA_2J_raw$counts$Name), ])  #remove dulicate values 
rownames(DBA_2J_raw$counts) <- DBA_2J_raw$counts$Name #set rawname to gene symbloes 
DBA_2J_raw$counts$Name <- NULL #remove genesybloe columns 
DBA_2J_raw

DataFrame with 20744 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00185003942        ugt1a1     gene
2     ENSMUSG00185003991         HJURP     gene
3     ENSMUSG00185003999         HJURP     gene
4     ENSMUSG00185004005        ugt1a1     gene
5     ENSMUSG00185004011        MROH2A     gene
...                  ...           ...      ...
20740 ENSMUSG00185029791         AMELX     gene
20741 ENSMUSG00185029830          HCCS     gene
20742 ENSMUSG00185029875          rbmx     gene
20743 ENSMUSG00185029083          MID1     gene
20744 ENSMUSG00185029146 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                   files
DBA_2J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts
DBA_2J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts
DBA_2J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts
DBA_2J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts
DBA_2J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts
DBA_2J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts
DBA_2J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts
DBA_2J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts
DBA_2J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts
                      group lib.size norm.factors
DBA_2J-P12.5.1 DBA_2J-P12.5       NA            1
DBA_2J-P12.5.2 DBA_2J-P12.5       NA            1
DBA_2J-P12.5.3 DBA_2J-P12.5       NA            1
DBA_2J-E16.5.1 DBA_2J-E16.5       NA            1
DBA_2J-E16.5.2 DBA_2J-E16.5       NA            1
DBA_2J-E16.5.3 DBA_2J-E16.5       NA            1
DBA_2J-P20.5.1 DBA_2J-P20.5       NA            1
DBA_2J-P20.5.2 DBA_2J-P20.5       NA            1
DBA_2J-P20.5.3 DBA_2J-P20.5       NA            1

$counts
                    Samples
Tags                 DBA_2J-P12.5.1 DBA_2J-P12.5.2 DBA_2J-P12.5.3
  ENSMUSG00185003942          10.67          10.67          13.50
  ENSMUSG00185003948          47.45          64.82          58.17
  ENSMUSG00185004797           0.22           0.26           0.31
  ENSMUSG00185003991        2832.66        2916.05        2963.83
  ENSMUSG00185003999         559.85         607.66         591.75
                    Samples
Tags                 DBA_2J-E16.5.1 DBA_2J-E16.5.2 DBA_2J-E16.5.3
  ENSMUSG00185003942           4.00           4.50           2.17
  ENSMUSG00185003948         176.43         151.46         156.49
  ENSMUSG00185004797           2.78           2.25           2.33
  ENSMUSG00185003991        4435.22        4612.76        4455.87
  ENSMUSG00185003999        1138.58        1024.35        1156.16
                    Samples
Tags                 DBA_2J-P20.5.1 DBA_2J-P20.5.2 DBA_2J-P20.5.3
  ENSMUSG00185003942          24.33          13.67          21.83
  ENSMUSG00185003948         618.42         716.97         733.42
  ENSMUSG00185004797           0.26           0.42           0.57
  ENSMUSG00185003991        3772.61        3726.11        3891.41
  ENSMUSG00185003999         458.52         420.91         452.20
26662 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                   files
DBA_2J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.1.featureCounts
DBA_2J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.2.featureCounts
DBA_2J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-12.5dpp.3.featureCounts
DBA_2J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.1.featureCounts
DBA_2J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.2.featureCounts
DBA_2J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-16.5dpc.3.featureCounts
DBA_2J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.1.featureCounts
DBA_2J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.2.featureCounts
DBA_2J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/DBA_2J-20.5dpp.3.featureCounts
                      group lib.size norm.factors
DBA_2J-P12.5.1 DBA_2J-P12.5       NA            1
DBA_2J-P12.5.2 DBA_2J-P12.5       NA            1
DBA_2J-P12.5.3 DBA_2J-P12.5       NA            1
DBA_2J-E16.5.1 DBA_2J-E16.5       NA            1
DBA_2J-E16.5.2 DBA_2J-E16.5       NA            1
DBA_2J-E16.5.3 DBA_2J-E16.5       NA            1
DBA_2J-P20.5.1 DBA_2J-P20.5       NA            1
DBA_2J-P20.5.2 DBA_2J-P20.5       NA            1
DBA_2J-P20.5.3 DBA_2J-P20.5       NA            1

$counts
              DBA_2J-P12.5.1 DBA_2J-P12.5.2 DBA_2J-P12.5.3 DBA_2J-E16.5.1
0610007P14Rik        3137.64         3196.4        3066.04        5260.48
0610009B22Rik         454.00          357.0         396.00         446.00
0610009O20Rik        1230.00         1004.5        1111.00        1708.00
0610010F05Rik        3527.94         3446.0        3513.75        1478.25
0610010K14Rik         785.50          838.0         809.00         852.50
              DBA_2J-E16.5.2 DBA_2J-E16.5.3 DBA_2J-P20.5.1 DBA_2J-P20.5.2
0610007P14Rik        4638.80        5358.79        2604.39        2494.51
0610009B22Rik         379.00         423.00         724.00         836.00
0610009O20Rik        1502.50        1763.00        2438.00        2484.75
0610010F05Rik        1531.33        1412.25        4815.11        4798.50
0610010K14Rik         799.50         910.50         518.50         470.00
              DBA_2J-P20.5.3
0610007P14Rik        2517.48
0610009B22Rik         859.00
0610009O20Rik        2620.50
0610010F05Rik        4927.33
0610010K14Rik         501.50
19104 more rows ...

In [20]:
FVB_NJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/FVB_NJ_v3.2.gff3") #import gff3 file 
FVB_NJ <- na.omit(mcols(FVB_NJ)[,c("gene_id","Name",'type')])
FVB_NJ <- FVB_NJ[FVB_NJ$type == 'gene', ]
FVB_NJ
FVB_NJ_geneName = FVB_NJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(FVB_NJ_geneName) <- FVB_NJ_geneName$gene_id
FVB_NJ_geneName$gene_id <- NULL
FVB_NJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts')
#FVB_NJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
FVB_NJ_samplenames = c('FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-E16.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5')

FVB_NJ_lables = c('FVB_NJ-P12.5.1','FVB_NJ-P12.5.2','FVB_NJ-P12.5.3','FVB_NJ-E16.5.1','FVB_NJ-E16.5.2','FVB_NJ-E16.5.3',
'FVB_NJ-P20.5.1','FVB_NJ-P20.5.2','FVB_NJ-P20.5.3')

FVB_NJ_raw <- readDGE(FVB_NJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= FVB_NJ_samplenames, labels = FVB_NJ_lables)
FVB_NJ_raw
library(dplyr)
FVB_NJ_raw$counts <- merge(x=FVB_NJ_raw$counts, y=FVB_NJ_geneName, by = 0,all.x=TRUE ) #left merge 
FVB_NJ_raw$counts['Row.names'] <- NULL
FVB_NJ_raw$counts <- FVB_NJ_raw$counts[!is.na(FVB_NJ_raw$counts$Name),] #remove NA 
FVB_NJ_raw$counts <- FVB_NJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

FVB_NJ_raw$counts <- as.data.frame(FVB_NJ_raw$counts[!duplicated(FVB_NJ_raw$counts$Name), ])  #remove dulicate values 
rownames(FVB_NJ_raw$counts) <- FVB_NJ_raw$counts$Name #set rawname to gene symbloes 
FVB_NJ_raw$counts$Name <- NULL #remove genesybloe columns 
FVB_NJ_raw

DataFrame with 20249 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00205004560          XKR4     gene
2     ENSMUSG00205004861           RP1     gene
3     ENSMUSG00205005121         SOX17     gene
4     ENSMUSG00205004846        MRPL15     gene
5     ENSMUSG00205004466        LYPLA1     gene
...                  ...           ...      ...
20245 ENSMUSG00205002553         AMELX     gene
20246 ENSMUSG00205002563          HCCS     gene
20247 ENSMUSG00205002570          rbmx     gene
20248 ENSMUSG00205002644          MID1     gene
20249 ENSMUSG00205002674 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                   files
FVB_NJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts
FVB_NJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts
FVB_NJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts
FVB_NJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts
FVB_NJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts
FVB_NJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts
FVB_NJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts
FVB_NJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts
FVB_NJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts
                      group lib.size norm.factors
FVB_NJ-P12.5.1 FVB_NJ-P12.5       NA            1
FVB_NJ-P12.5.2 FVB_NJ-P12.5       NA            1
FVB_NJ-P12.5.3 FVB_NJ-P12.5       NA            1
FVB_NJ-E16.5.1 FVB_NJ-E16.5       NA            1
FVB_NJ-E16.5.2 FVB_NJ-E16.5       NA            1
FVB_NJ-E16.5.3 FVB_NJ-E16.5       NA            1
FVB_NJ-P20.5.1 FVB_NJ-P20.5       NA            1
FVB_NJ-P20.5.2 FVB_NJ-P20.5       NA            1
FVB_NJ-P20.5.3 FVB_NJ-P20.5       NA            1

$counts
                    Samples
Tags                 FVB_NJ-P12.5.1 FVB_NJ-P12.5.2 FVB_NJ-P12.5.3
  ENSMUSG00205005509           0.00           0.00            0.0
  ENSMUSG00205004560        1862.36        2717.41         2141.8
  ENSMUSG00205005503          12.00          17.00            9.5
  ENSMUSG00205005500           9.00           9.50            9.5
  ENSMUSG00205005496           3.00           5.00            3.5
                    Samples
Tags                 FVB_NJ-E16.5.1 FVB_NJ-E16.5.2 FVB_NJ-E16.5.3
  ENSMUSG00205005509           0.00           1.00           1.00
  ENSMUSG00205004560        7623.65        6009.78        5385.98
  ENSMUSG00205005503          36.00          33.00          30.50
  ENSMUSG00205005500          35.50          35.50          29.00
  ENSMUSG00205005496          13.00           9.50           9.00
                    Samples
Tags                 FVB_NJ-P20.5.1 FVB_NJ-P20.5.2 FVB_NJ-P20.5.3
  ENSMUSG00205005509           0.00           0.00           0.00
  ENSMUSG00205004560         194.77         251.86         358.42
  ENSMUSG00205005503           0.00           1.50           3.50
  ENSMUSG00205005500           0.50           2.50           1.50
  ENSMUSG00205005496           0.00           0.50           0.00
25652 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                   files
FVB_NJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.1.featureCounts
FVB_NJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.2.featureCounts
FVB_NJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-12.5dpp.3.featureCounts
FVB_NJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.1.featureCounts
FVB_NJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.2.featureCounts
FVB_NJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-16.5dpc.3.featureCounts
FVB_NJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.1.featureCounts
FVB_NJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.2.featureCounts
FVB_NJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/FVB_NJ-20.5dpp.3.featureCounts
                      group lib.size norm.factors
FVB_NJ-P12.5.1 FVB_NJ-P12.5       NA            1
FVB_NJ-P12.5.2 FVB_NJ-P12.5       NA            1
FVB_NJ-P12.5.3 FVB_NJ-P12.5       NA            1
FVB_NJ-E16.5.1 FVB_NJ-E16.5       NA            1
FVB_NJ-E16.5.2 FVB_NJ-E16.5       NA            1
FVB_NJ-E16.5.3 FVB_NJ-E16.5       NA            1
FVB_NJ-P20.5.1 FVB_NJ-P20.5       NA            1
FVB_NJ-P20.5.2 FVB_NJ-P20.5       NA            1
FVB_NJ-P20.5.3 FVB_NJ-P20.5       NA            1

$counts
              FVB_NJ-P12.5.1 FVB_NJ-P12.5.2 FVB_NJ-P12.5.3 FVB_NJ-E16.5.1
0610007P14Rik        1814.41        2188.30        2074.95        3286.01
0610009B22Rik         357.00         448.00         437.00         542.00
0610009O20Rik        1129.00        1506.50        1361.00        2169.00
0610010F05Rik        2865.78        3696.75        3220.12        1948.20
0610010K14Rik         705.50         895.50         779.00         829.00
              FVB_NJ-E16.5.2 FVB_NJ-E16.5.3 FVB_NJ-P20.5.1 FVB_NJ-P20.5.2
0610007P14Rik        2879.91        2969.49        1490.95        1506.99
0610009B22Rik         486.00         512.00         690.00         701.00
0610009O20Rik        1868.67        2013.50        2157.00        2105.00
0610010F05Rik        1808.75        1934.20        4680.67        4702.14
0610010K14Rik         710.50         709.00         491.50         513.00
              FVB_NJ-P20.5.3
0610007P14Rik        1530.55
0610009B22Rik         623.00
0610009O20Rik        2079.50
0610010F05Rik        4396.17
0610010K14Rik         494.50
18998 more rows ...

In [21]:
NOD_ShiLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NOD_ShiLtJ_v3.2.gff3") #import gff3 file 
NOD_ShiLtJ <- na.omit(mcols(NOD_ShiLtJ)[,c("gene_id","Name",'type')])
NOD_ShiLtJ <- NOD_ShiLtJ[NOD_ShiLtJ$type == 'gene', ]
NOD_ShiLtJ
NOD_ShiLtJ_geneName = NOD_ShiLtJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(NOD_ShiLtJ_geneName) <- NOD_ShiLtJ_geneName$gene_id
NOD_ShiLtJ_geneName$gene_id <- NULL
NOD_ShiLtJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts')
#NOD_ShiLtJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
NOD_ShiLtJ_samplenames = c('NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-E16.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5')

NOD_ShiLtJ_lables = c('NOD_ShiLtJ-P12.5.1','NOD_ShiLtJ-P12.5.2','NOD_ShiLtJ-P12.5.3','NOD_ShiLtJ-E16.5.1','NOD_ShiLtJ-E16.5.2','NOD_ShiLtJ-E16.5.3',
'NOD_ShiLtJ-P20.5.1','NOD_ShiLtJ-P20.5.2','NOD_ShiLtJ-P20.5.3')

NOD_ShiLtJ_raw <- readDGE(NOD_ShiLtJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= NOD_ShiLtJ_samplenames, labels = NOD_ShiLtJ_lables)
NOD_ShiLtJ_raw
library(dplyr)
NOD_ShiLtJ_raw$counts <- merge(x=NOD_ShiLtJ_raw$counts, y=NOD_ShiLtJ_geneName, by = 0,all.x=TRUE ) #left merge 
NOD_ShiLtJ_raw$counts['Row.names'] <- NULL
NOD_ShiLtJ_raw$counts <- NOD_ShiLtJ_raw$counts[!is.na(NOD_ShiLtJ_raw$counts$Name),] #remove NA 
NOD_ShiLtJ_raw$counts <- NOD_ShiLtJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

NOD_ShiLtJ_raw$counts <- as.data.frame(NOD_ShiLtJ_raw$counts[!duplicated(NOD_ShiLtJ_raw$counts$Name), ])  #remove dulicate values 
rownames(NOD_ShiLtJ_raw$counts) <- NOD_ShiLtJ_raw$counts$Name #set rawname to gene symbloes 
NOD_ShiLtJ_raw$counts$Name <- NULL #remove genesybloe columns 
NOD_ShiLtJ_raw

DataFrame with 20402 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00190001012          XKR4     gene
2     ENSMUSG00190001200           RP1     gene
3     ENSMUSG00190001204         SOX17     gene
4     ENSMUSG00190000988        MRPL15     gene
5     ENSMUSG00190001005        LYPLA1     gene
...                  ...           ...      ...
20398 ENSMUSG00190021047          HCCS     gene
20399 ENSMUSG00190021097          rbmx     gene
20400 ENSMUSG00190021319          MID1     gene
20401 ENSMUSG00190021390 4933400A11Rik     gene
20402 ENSMUSG00190021442          ASMT     gene

An object of class "DGEList"
$samples
                                                                                                                                           files
NOD_ShiLtJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts
NOD_ShiLtJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts
NOD_ShiLtJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts
NOD_ShiLtJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts
NOD_ShiLtJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts
NOD_ShiLtJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts
NOD_ShiLtJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts
NOD_ShiLtJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts
NOD_ShiLtJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts
                              group lib.size norm.factors
NOD_ShiLtJ-P12.5.1 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-P12.5.2 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-P12.5.3 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-E16.5.1 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-E16.5.2 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-E16.5.3 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-P20.5.1 NOD_ShiLtJ-P20.5       NA            1
NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5       NA            1
NOD_ShiLtJ-P20.5.3 NOD_ShiLtJ-P20.5       NA            1

$counts
                    Samples
Tags                 NOD_ShiLtJ-P12.5.1 NOD_ShiLtJ-P12.5.2 NOD_ShiLtJ-P12.5.3
  ENSMUSG00190001414               0.00               0.00               0.00
  ENSMUSG00190001012            4851.02            4447.79             992.64
  ENSMUSG00190001407              21.50              28.00               3.50
  ENSMUSG00190001411              23.50              25.00               5.50
  ENSMUSG00190001405               8.50               9.50               2.00
                    Samples
Tags                 NOD_ShiLtJ-E16.5.1 NOD_ShiLtJ-E16.5.2 NOD_ShiLtJ-E16.5.3
  ENSMUSG00190001414               0.00               0.00               3.00
  ENSMUSG00190001012            7729.27            9089.67            6666.64
  ENSMUSG00190001407              48.50              44.50              30.00
  ENSMUSG00190001411              30.50              46.00              38.00
  ENSMUSG00190001405              16.00              17.00              16.50
                    Samples
Tags                 NOD_ShiLtJ-P20.5.1 NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5.3
  ENSMUSG00190001414               0.00               0.00               2.00
  ENSMUSG00190001012             482.08             505.09             309.79
  ENSMUSG00190001407               2.50               3.00               1.00
  ENSMUSG00190001411               2.00               1.50               1.00
  ENSMUSG00190001405               1.00               0.00               1.00
25882 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                           files
NOD_ShiLtJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.1.featureCounts
NOD_ShiLtJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.2.featureCounts
NOD_ShiLtJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-12.5dpp.3.featureCounts
NOD_ShiLtJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.1.featureCounts
NOD_ShiLtJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.2.featureCounts
NOD_ShiLtJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-16.5dpc.3.featureCounts
NOD_ShiLtJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.1.featureCounts
NOD_ShiLtJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.2.featureCounts
NOD_ShiLtJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NOD_ShiLtJ-20.5dpp.3.featureCounts
                              group lib.size norm.factors
NOD_ShiLtJ-P12.5.1 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-P12.5.2 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-P12.5.3 NOD_ShiLtJ-P12.5       NA            1
NOD_ShiLtJ-E16.5.1 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-E16.5.2 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-E16.5.3 NOD_ShiLtJ-E16.5       NA            1
NOD_ShiLtJ-P20.5.1 NOD_ShiLtJ-P20.5       NA            1
NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5       NA            1
NOD_ShiLtJ-P20.5.3 NOD_ShiLtJ-P20.5       NA            1

$counts
              NOD_ShiLtJ-P12.5.1 NOD_ShiLtJ-P12.5.2 NOD_ShiLtJ-P12.5.3
0610007P14Rik            3353.67            2733.54            2699.38
0610009B22Rik             297.00             295.00             466.00
0610009O20Rik            1281.43            1265.56            1968.75
0610010F05Rik            4653.50            4244.67            3891.11
0610010K14Rik             718.00             707.00             669.50
              NOD_ShiLtJ-E16.5.1 NOD_ShiLtJ-E16.5.2 NOD_ShiLtJ-E16.5.3
0610007P14Rik            4019.65            4473.82            4150.14
0610009B22Rik             435.00             449.00             419.00
0610009O20Rik            2260.07            2381.06            2261.11
0610010F05Rik            1750.79            1956.50            1788.35
0610010K14Rik             672.00             766.00             714.50
              NOD_ShiLtJ-P20.5.1 NOD_ShiLtJ-P20.5.2 NOD_ShiLtJ-P20.5.3
0610007P14Rik            2318.81            2487.33            2239.81
0610009B22Rik             553.00             609.00            1051.00
0610009O20Rik            1775.84            2196.22            2943.05
0610010F05Rik            4077.75            4561.25            6036.70
0610010K14Rik             555.00             615.00             415.00
19080 more rows ...

In [22]:
PWK_PhJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/PWK_PhJ_v3.2.gff3") #import gff3 file 
PWK_PhJ <- na.omit(mcols(PWK_PhJ)[,c("gene_id","Name",'type')])
PWK_PhJ <- PWK_PhJ[PWK_PhJ$type == 'gene', ]
PWK_PhJ
PWK_PhJ_geneName = PWK_PhJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(PWK_PhJ_geneName) <- PWK_PhJ_geneName$gene_id
PWK_PhJ_geneName$gene_id <- NULL
PWK_PhJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts')
#PWK_PhJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
PWK_PhJ_samplenames = c('PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-E16.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5')

PWK_PhJ_lables = c('PWK_PhJ-P12.5.1','PWK_PhJ-P12.5.2','PWK_PhJ-P12.5.3','PWK_PhJ-E16.5.1','PWK_PhJ-E16.5.2','PWK_PhJ-E16.5.3',
'PWK_PhJ-P20.5.1','PWK_PhJ-P20.5.2','PWK_PhJ-P20.5.3')

PWK_PhJ_raw <- readDGE(PWK_PhJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= PWK_PhJ_samplenames, labels = PWK_PhJ_lables)
PWK_PhJ_raw
library(dplyr)
PWK_PhJ_raw$counts <- merge(x=PWK_PhJ_raw$counts, y=PWK_PhJ_geneName, by = 0,all.x=TRUE ) #left merge 
PWK_PhJ_raw$counts['Row.names'] <- NULL
PWK_PhJ_raw$counts <- PWK_PhJ_raw$counts[!is.na(PWK_PhJ_raw$counts$Name),] #remove NA 
PWK_PhJ_raw$counts <- PWK_PhJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

PWK_PhJ_raw$counts <- as.data.frame(PWK_PhJ_raw$counts[!duplicated(PWK_PhJ_raw$counts$Name), ])  #remove dulicate values 
rownames(PWK_PhJ_raw$counts) <- PWK_PhJ_raw$counts$Name #set rawname to gene symbloes 
PWK_PhJ_raw$counts$Name <- NULL #remove genesybloe columns 
PWK_PhJ_raw

DataFrame with 20311 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSLUMG00010002333          XKR4     gene
2     ENSLUMG00010002218           RP1     gene
3     ENSLUMG00010002217         SOX17     gene
4     ENSLUMG00010002301        MRPL15     gene
5     ENSLUMG00010002268        LYPLA1     gene
...                  ...           ...      ...
20307 ENSLUMG00010001640          HCCS     gene
20308 ENSLUMG00010001642          rbmx     gene
20309 ENSLUMG00010001632          MID1     gene
20310 ENSLUMG00010001635 4933400A11Rik     gene
20311 ENSLUMG00010001636       DYNLRB2     gene

An object of class "DGEList"
$samples
                                                                                                                                     files
PWK_PhJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts
PWK_PhJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts
PWK_PhJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts
PWK_PhJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts
PWK_PhJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts
PWK_PhJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts
PWK_PhJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts
PWK_PhJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts
PWK_PhJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
PWK_PhJ-P12.5.1 PWK_PhJ-P12.5       NA            1
PWK_PhJ-P12.5.2 PWK_PhJ-P12.5       NA            1
PWK_PhJ-P12.5.3 PWK_PhJ-P12.5       NA            1
PWK_PhJ-E16.5.1 PWK_PhJ-E16.5       NA            1
PWK_PhJ-E16.5.2 PWK_PhJ-E16.5       NA            1
PWK_PhJ-E16.5.3 PWK_PhJ-E16.5       NA            1
PWK_PhJ-P20.5.1 PWK_PhJ-P20.5       NA            1
PWK_PhJ-P20.5.2 PWK_PhJ-P20.5       NA            1
PWK_PhJ-P20.5.3 PWK_PhJ-P20.5       NA            1

$counts
                    Samples
Tags                 PWK_PhJ-P12.5.1 PWK_PhJ-P12.5.2 PWK_PhJ-P12.5.3
  ENSLUMG00010002743            1.00            0.00            0.00
  ENSLUMG00010002333         4344.85         3719.29         4063.25
  ENSLUMG00010002734           30.00           24.00           28.50
  ENSLUMG00010002736           21.00           26.00           28.00
  ENSLUMG00010002731            8.50            6.50            9.00
                    Samples
Tags                 PWK_PhJ-E16.5.1 PWK_PhJ-E16.5.2 PWK_PhJ-E16.5.3
  ENSLUMG00010002743            1.00            1.00            0.00
  ENSLUMG00010002333        22452.31        21380.88        22525.46
  ENSLUMG00010002734          142.00          165.50          150.00
  ENSLUMG00010002736          134.50          118.00          125.50
  ENSLUMG00010002731           36.50           32.00           44.50
                    Samples
Tags                 PWK_PhJ-P20.5.1 PWK_PhJ-P20.5.2 PWK_PhJ-P20.5.3
  ENSLUMG00010002743             0.0            0.00            0.00
  ENSLUMG00010002333           519.2          591.17          494.63
  ENSLUMG00010002734             2.5            2.00            5.50
  ENSLUMG00010002736             2.0            4.00            3.00
  ENSLUMG00010002731             1.0            1.00            0.00
25614 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                     files
PWK_PhJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.1.featureCounts
PWK_PhJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.2.featureCounts
PWK_PhJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-12.5dpp.3.featureCounts
PWK_PhJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.1.featureCounts
PWK_PhJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.2.featureCounts
PWK_PhJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-16.5dpc.3.featureCounts
PWK_PhJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.1.featureCounts
PWK_PhJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.2.featureCounts
PWK_PhJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/PWK_PhJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
PWK_PhJ-P12.5.1 PWK_PhJ-P12.5       NA            1
PWK_PhJ-P12.5.2 PWK_PhJ-P12.5       NA            1
PWK_PhJ-P12.5.3 PWK_PhJ-P12.5       NA            1
PWK_PhJ-E16.5.1 PWK_PhJ-E16.5       NA            1
PWK_PhJ-E16.5.2 PWK_PhJ-E16.5       NA            1
PWK_PhJ-E16.5.3 PWK_PhJ-E16.5       NA            1
PWK_PhJ-P20.5.1 PWK_PhJ-P20.5       NA            1
PWK_PhJ-P20.5.2 PWK_PhJ-P20.5       NA            1
PWK_PhJ-P20.5.3 PWK_PhJ-P20.5       NA            1

$counts
              PWK_PhJ-P12.5.1 PWK_PhJ-P12.5.2 PWK_PhJ-P12.5.3 PWK_PhJ-E16.5.1
0610007P14Rik         1268.00         1328.50         1284.00         2052.83
0610009B22Rik          476.00          533.00          583.00          928.00
0610009O20Rik         1685.00         1681.33         1644.50         2242.50
0610010F05Rik         3461.78         3336.13         3421.58         1658.17
0610010K14Rik          786.50          817.50          828.00         1144.50
              PWK_PhJ-E16.5.2 PWK_PhJ-E16.5.3 PWK_PhJ-P20.5.1 PWK_PhJ-P20.5.2
0610007P14Rik         2045.50         2172.00         1097.00          1068.5
0610009B22Rik         1005.00          923.00         1113.00          1101.0
0610009O20Rik         2231.00         2292.00         3466.75          3427.5
0610010F05Rik         1499.88         1481.17         4145.08          4439.8
0610010K14Rik         1221.00         1109.00          555.50           534.0
              PWK_PhJ-P20.5.3
0610007P14Rik         1025.00
0610009B22Rik         1087.00
0610009O20Rik         3237.50
0610010F05Rik         4168.75
0610010K14Rik          461.50
18973 more rows ...

In [23]:
SPRET_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/SPRET_EiJ_v3.2.gff3") #import gff3 file 
SPRET_EiJ <- na.omit(mcols(SPRET_EiJ)[,c("gene_id","Name",'type')])
SPRET_EiJ <- SPRET_EiJ[SPRET_EiJ$type == 'gene', ]
SPRET_EiJ
SPRET_EiJ_geneName = SPRET_EiJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(SPRET_EiJ_geneName) <- SPRET_EiJ_geneName$gene_id
SPRET_EiJ_geneName$gene_id <- NULL
SPRET_EiJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts')
#SPRET_EiJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
SPRET_EiJ_samplenames = c('SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-E16.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')

SPRET_EiJ_lables = c('SPRET_EiJ-P12.5.1','SPRET_EiJ-P12.5.2','SPRET_EiJ-P12.5.3','SPRET_EiJ-E16.5.1','SPRET_EiJ-E16.5.2','SPRET_EiJ-E16.5.3',
'SPRET_EiJ-P20.5.1','SPRET_EiJ-P20.5.2','SPRET_EiJ-P20.5.3')

SPRET_EiJ_raw <- readDGE(SPRET_EiJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= SPRET_EiJ_samplenames, labels = SPRET_EiJ_lables)
SPRET_EiJ_raw
library(dplyr)
SPRET_EiJ_raw$counts <- merge(x=SPRET_EiJ_raw$counts, y=SPRET_EiJ_geneName, by = 0,all.x=TRUE ) #left merge 
SPRET_EiJ_raw$counts['Row.names'] <- NULL
SPRET_EiJ_raw$counts <- SPRET_EiJ_raw$counts[!is.na(SPRET_EiJ_raw$counts$Name),] #remove NA 
SPRET_EiJ_raw$counts <- SPRET_EiJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

SPRET_EiJ_raw$counts <- as.data.frame(SPRET_EiJ_raw$counts[!duplicated(SPRET_EiJ_raw$counts$Name), ])  #remove dulicate values 
rownames(SPRET_EiJ_raw$counts) <- SPRET_EiJ_raw$counts$Name #set rawname to gene symbloes 
SPRET_EiJ_raw$counts$Name <- NULL #remove genesybloe columns 
SPRET_EiJ_raw

DataFrame with 19975 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMSPG00010013869          XKR4     gene
2     ENSMSPG00010013465           RP1     gene
3     ENSMSPG00010013678         SOX17     gene
4     ENSMSPG00010013963        MRPL15     gene
5     ENSMSPG00010013304        LYPLA1     gene
...                  ...           ...      ...
19971 ENSMSPG00010025834         BUD13     gene
19972 ENSMSPG00010025902          MID1     gene
19973 ENSMSPG00010026011 4933400A11Rik     gene
19974 ENSMSPG00010025005         CLCN4     gene
19975 ENSMSPG00010025308          WWC3     gene

An object of class "DGEList"
$samples
                                                                                                                                         files
SPRET_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts
SPRET_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts
SPRET_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts
SPRET_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts
SPRET_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts
SPRET_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts
SPRET_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts
SPRET_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts
SPRET_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
SPRET_EiJ-P12.5.1 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-P12.5.2 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-P12.5.3 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-E16.5.1 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-E16.5.2 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-E16.5.3 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5       NA            1
SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5       NA            1
SPRET_EiJ-P20.5.3 SPRET_EiJ-P20.5       NA            1

$counts
                    Samples
Tags                 SPRET_EiJ-P12.5.1 SPRET_EiJ-P12.5.2 SPRET_EiJ-P12.5.3
  ENSMSPG00010014769              0.00              0.00              0.00
  ENSMSPG00010013869           4032.74           4113.18           6661.65
  ENSMSPG00010014798             22.00             22.50             39.50
  ENSMSPG00010014805             21.00             30.50             50.50
  ENSMSPG00010014791              8.50              9.50             12.00
                    Samples
Tags                 SPRET_EiJ-E16.5.1 SPRET_EiJ-E16.5.2 SPRET_EiJ-E16.5.3
  ENSMSPG00010014769              0.00              0.00              0.00
  ENSMSPG00010013869          27519.13          27233.43          24584.08
  ENSMSPG00010014798            166.50            193.00            193.00
  ENSMSPG00010014805            178.00            179.00            131.50
  ENSMSPG00010014791             46.00             55.33             49.50
                    Samples
Tags                 SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3
  ENSMSPG00010014769              0.00              0.00              0.00
  ENSMSPG00010013869            981.16            802.25            653.49
  ENSMSPG00010014798              5.50              7.00              5.00
  ENSMSPG00010014805              5.00              4.50              4.50
  ENSMSPG00010014791              2.50              0.00              2.00
25150 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                         files
SPRET_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.1.featureCounts
SPRET_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.2.featureCounts
SPRET_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-12.5dpp.3.featureCounts
SPRET_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.1.featureCounts
SPRET_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.2.featureCounts
SPRET_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-16.5dpc.3.featureCounts
SPRET_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.1.featureCounts
SPRET_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.2.featureCounts
SPRET_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/SPRET_EiJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
SPRET_EiJ-P12.5.1 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-P12.5.2 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-P12.5.3 SPRET_EiJ-P12.5       NA            1
SPRET_EiJ-E16.5.1 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-E16.5.2 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-E16.5.3 SPRET_EiJ-E16.5       NA            1
SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5       NA            1
SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5       NA            1
SPRET_EiJ-P20.5.3 SPRET_EiJ-P20.5       NA            1

$counts
              SPRET_EiJ-P12.5.1 SPRET_EiJ-P12.5.2 SPRET_EiJ-P12.5.3
0610007P14Rik            666.41            775.64            815.70
0610009B22Rik            392.00            538.00            542.50
0610010F05Rik           3362.41           3796.62           3719.79
0610010K14Rik            916.00           1125.00           1088.00
0610037L13Rik            672.00            878.50            847.75
              SPRET_EiJ-E16.5.1 SPRET_EiJ-E16.5.2 SPRET_EiJ-E16.5.3
0610007P14Rik           1014.85            838.96            854.24
0610009B22Rik            716.50            552.00            586.00
0610010F05Rik           2009.47           1864.31           1676.28
0610010K14Rik            906.50            892.50           1082.00
0610037L13Rik           1029.00            915.50           1131.00
              SPRET_EiJ-P20.5.1 SPRET_EiJ-P20.5.2 SPRET_EiJ-P20.5.3
0610007P14Rik            605.25            572.16            552.65
0610009B22Rik            476.00            496.00            462.00
0610010F05Rik           4527.82           4451.79           3890.56
0610010K14Rik            761.00            793.50            763.50
0610037L13Rik            823.62           1008.00            973.75
18755 more rows ...

In [24]:
WSB_EiJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/WSB_EiJ_v3.2.gff3") #import gff3 file 
WSB_EiJ <- na.omit(mcols(WSB_EiJ)[,c("gene_id","Name",'type')])
WSB_EiJ <- WSB_EiJ[WSB_EiJ$type == 'gene', ]
WSB_EiJ
WSB_EiJ_geneName = WSB_EiJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(WSB_EiJ_geneName) <- WSB_EiJ_geneName$gene_id
WSB_EiJ_geneName$gene_id <- NULL
WSB_EiJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts')
#WSB_EiJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
WSB_EiJ_samplenames = c('WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-E16.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5')

WSB_EiJ_lables = c('WSB_EiJ-P12.5.1','WSB_EiJ-P12.5.2','WSB_EiJ-P12.5.3','WSB_EiJ-E16.5.1','WSB_EiJ-E16.5.2','WSB_EiJ-E16.5.3',
'WSB_EiJ-P20.5.1','WSB_EiJ-P20.5.2','WSB_EiJ-P20.5.3')

WSB_EiJ_raw <- readDGE(WSB_EiJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= WSB_EiJ_samplenames, labels = WSB_EiJ_lables)
WSB_EiJ_raw
library(dplyr)
WSB_EiJ_raw$counts <- merge(x=WSB_EiJ_raw$counts, y=WSB_EiJ_geneName, by = 0,all.x=TRUE ) #left merge 
WSB_EiJ_raw$counts['Row.names'] <- NULL
WSB_EiJ_raw$counts <- WSB_EiJ_raw$counts[!is.na(WSB_EiJ_raw$counts$Name),] #remove NA 
WSB_EiJ_raw$counts <- WSB_EiJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

WSB_EiJ_raw$counts <- as.data.frame(WSB_EiJ_raw$counts[!duplicated(WSB_EiJ_raw$counts$Name), ])  #remove dulicate values 
rownames(WSB_EiJ_raw$counts) <- WSB_EiJ_raw$counts$Name #set rawname to gene symbloes 
WSB_EiJ_raw$counts$Name <- NULL #remove genesybloe columns 
WSB_EiJ_raw

DataFrame with 20295 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSIUOG00005011030      C16orf92     gene
2     ENSIUOG00005011041          XKR4     gene
3     ENSIUOG00005010731           RP1     gene
4     ENSIUOG00005010829         SOX17     gene
5     ENSIUOG00005010349        MRPL15     gene
...                  ...           ...      ...
20291 ENSIUOG00005010896         AMELX     gene
20292 ENSIUOG00005010918          HCCS     gene
20293 ENSIUOG00005010927          rbmx     gene
20294 ENSIUOG00005011018          MID1     gene
20295 ENSIUOG00005011033 4933400A11Rik     gene

An object of class "DGEList"
$samples
                                                                                                                                     files
WSB_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts
WSB_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts
WSB_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts
WSB_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts
WSB_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts
WSB_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts
WSB_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts
WSB_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts
WSB_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
WSB_EiJ-P12.5.1 WSB_EiJ-P12.5       NA            1
WSB_EiJ-P12.5.2 WSB_EiJ-P12.5       NA            1
WSB_EiJ-P12.5.3 WSB_EiJ-P12.5       NA            1
WSB_EiJ-E16.5.1 WSB_EiJ-E16.5       NA            1
WSB_EiJ-E16.5.2 WSB_EiJ-E16.5       NA            1
WSB_EiJ-E16.5.3 WSB_EiJ-E16.5       NA            1
WSB_EiJ-P20.5.1 WSB_EiJ-P20.5       NA            1
WSB_EiJ-P20.5.2 WSB_EiJ-P20.5       NA            1
WSB_EiJ-P20.5.3 WSB_EiJ-P20.5       NA            1

$counts
                    Samples
Tags                 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
  ENSIUOG00005011030           12.03            7.32            9.94
  ENSIUOG00005011650            0.00            0.00            0.00
  ENSIUOG00005011041         2793.72         4628.96         4075.52
  ENSIUOG00005011663           18.50           30.00           25.00
  ENSIUOG00005011668           13.00           31.00           25.00
                    Samples
Tags                 WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3
  ENSIUOG00005011030            9.33           17.76           14.81
  ENSIUOG00005011650            0.00            0.00            0.00
  ENSIUOG00005011041        20317.76        23721.68        29307.07
  ENSIUOG00005011663          121.00          136.00          183.00
  ENSIUOG00005011668           99.00          105.50          146.00
                    Samples
Tags                 WSB_EiJ-P20.5.1 WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
  ENSIUOG00005011030            8.55           19.87           23.82
  ENSIUOG00005011650            0.00            0.00            0.00
  ENSIUOG00005011041          548.99          351.36          441.36
  ENSIUOG00005011663            2.50            1.50            2.00
  ENSIUOG00005011668            1.00            0.50            2.00
25576 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                     files
WSB_EiJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.1.featureCounts
WSB_EiJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.2.featureCounts
WSB_EiJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-12.5dpp.3.featureCounts
WSB_EiJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.1.featureCounts
WSB_EiJ-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.2.featureCounts
WSB_EiJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-16.5dpc.3.featureCounts
WSB_EiJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.1.featureCounts
WSB_EiJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.2.featureCounts
WSB_EiJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/WSB_EiJ-20.5dpp.3.featureCounts
                        group lib.size norm.factors
WSB_EiJ-P12.5.1 WSB_EiJ-P12.5       NA            1
WSB_EiJ-P12.5.2 WSB_EiJ-P12.5       NA            1
WSB_EiJ-P12.5.3 WSB_EiJ-P12.5       NA            1
WSB_EiJ-E16.5.1 WSB_EiJ-E16.5       NA            1
WSB_EiJ-E16.5.2 WSB_EiJ-E16.5       NA            1
WSB_EiJ-E16.5.3 WSB_EiJ-E16.5       NA            1
WSB_EiJ-P20.5.1 WSB_EiJ-P20.5       NA            1
WSB_EiJ-P20.5.2 WSB_EiJ-P20.5       NA            1
WSB_EiJ-P20.5.3 WSB_EiJ-P20.5       NA            1

$counts
              WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3 WSB_EiJ-E16.5.1
0610007P14Rik         1262.50         1215.50         1270.00         1574.50
0610009B22Rik          435.00          411.00          440.00          532.00
0610009O20Rik         1433.00         1567.50         1598.50         2544.50
0610010F05Rik         3332.25         2658.92         3089.33         1621.25
0610010K14Rik          655.00          597.50          622.00          735.50
              WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1 WSB_EiJ-P20.5.2
0610007P14Rik         1452.00         1787.50         1182.50         1108.50
0610009B22Rik          515.00          683.00          587.00          594.00
0610009O20Rik         2413.00         2690.50         2789.00         2195.50
0610010F05Rik         1673.75         2012.58         4390.42         3760.75
0610010K14Rik          626.00          622.00          537.00          506.00
              WSB_EiJ-P20.5.3
0610007P14Rik          1109.0
0610009B22Rik           617.0
0610009O20Rik          2334.5
0610010F05Rik          3660.0
0610010K14Rik           492.5
19039 more rows ...

In [25]:
NZO_HlLtJ <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/NZO_HlLtJ_v3.2.gff3") #import gff3 file 
#NZO_HlLtJ_geneName = na.omit(mcols(NZO_HlLtJ)[,c("gene_id","Name",'type')]) #get gene symbloes for respective gene id 
NZO_HlLtJ <- na.omit(mcols(NZO_HlLtJ)[,c("gene_id","Name",'type')])
#colnames(NZO_HlLtJ)[which(names(NZO_HlLtJ) == "Name")] <- "Name" #change columns name
NZO_HlLtJ <- NZO_HlLtJ[NZO_HlLtJ$type == 'gene', ]
NZO_HlLtJ

# Now try using dplyr functions like group_by
library(dplyr)
duplicated_names <- as.data.frame(NZO_HlLtJ) %>%
  group_by(Name) %>%
  filter(n() > 1)
duplicated_names
length(unique(duplicated_names$Name))

NZO_HlLtJ_geneName = NZO_HlLtJ[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(NZO_HlLtJ_geneName) <- NZO_HlLtJ_geneName$gene_id
NZO_HlLtJ_geneName$gene_id <- NULL
NZO_HlLtJ_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.1.featureCounts',
#'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.3.featureCounts')
#NZO_HlLtJ_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
NZO_HlLtJ_samplenames = c('NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-E16.5',
'NZO_HlLtJ-E16.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5')
#'NZO_HlLtJ-E16.5',
NZO_HlLtJ_lables = c('NZO_HlLtJ-P12.5.1','NZO_HlLtJ-P12.5.2','NZO_HlLtJ-P12.5.3','NZO_HlLtJ-E16.5.1','NZO_HlLtJ-E16.5.3',
'NZO_HlLtJ-P20.5.1','NZO_HlLtJ-P20.5.2','NZO_HlLtJ-P20.5.3')
#'NZO_HlLtJ-E16.5.2',
NZO_HlLtJ_raw <- readDGE(NZO_HlLtJ_files, columns = c(1, 7), comment.char = "#", sep="\t", group= NZO_HlLtJ_samplenames, labels = NZO_HlLtJ_lables)
NZO_HlLtJ_raw
library(dplyr)
NZO_HlLtJ_raw$counts <- merge(x=NZO_HlLtJ_raw$counts, y=NZO_HlLtJ_geneName, by = 0,all.x=TRUE ) #left merge 
NZO_HlLtJ_raw$counts['Row.names'] <- NULL
NZO_HlLtJ_raw$counts$Name[NZO_HlLtJ_raw$counts$Name == "PARP2"] <- "CCNB1IP1"
NZO_HlLtJ_raw$counts <- NZO_HlLtJ_raw$counts[!is.na(NZO_HlLtJ_raw$counts$Name),] #remove NA 
NZO_HlLtJ_raw$counts <- NZO_HlLtJ_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))

NZO_HlLtJ_raw$counts <- as.data.frame(NZO_HlLtJ_raw$counts[!duplicated(NZO_HlLtJ_raw$counts$Name), ])  #remove dulicate values 
rownames(NZO_HlLtJ_raw$counts) <- NZO_HlLtJ_raw$counts$Name #set rawname to gene symbloes 
NZO_HlLtJ_raw$counts$Name <- NULL #remove genesybloe columns 
NZO_HlLtJ_raw

DataFrame with 20573 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00225000084       MPV17L2     gene
2     ENSMUSG00225000096         HJURP     gene
3     ENSMUSG00225000140        ugt1a1     gene
4     ENSMUSG00225000142         HJURP     gene
5     ENSMUSG00225000071        ugt1a1     gene
...                  ...           ...      ...
20569 ENSMUSG00225038352 4933400A11Rik     gene
20570 ENSMUSG00225038391           NGF     gene
20571 ENSMUSG00225028175         SPHK1     gene
20572 ENSMUSG00225028213           GSN     gene
20573 ENSMUSG00225028240          ASMT     gene

     gene_id            Name          type
1    ENSMUSG00225000084 MPV17L2       gene
2    ENSMUSG00225000096 HJURP         gene
3    ENSMUSG00225000140 ugt1a1        gene
4    ENSMUSG00225000142 HJURP         gene
5    ENSMUSG00225000071 ugt1a1        gene
6    ENSMUSG00225000075 HJURP         gene
7    ENSMUSG00225000088 TCEA1         gene
8    ENSMUSG00225000090 HMGB3         gene
9    ENSMUSG00225000092 RGS20         gene
10   ENSMUSG00225000124 Gm4737        gene
11   ENSMUSG00225004902 COPS5         gene
12   ENSMUSG00225000499 cetn4         gene
13   ENSMUSG00225000521 Khdc1b        gene
14   ENSMUSG00225000442 Khdc1b        gene
15   ENSMUSG00225000477 Khdc1b        gene
16   ENSMUSG00225000358 rpl13         gene
17   ENSMUSG00225000426 MTCH2         gene
18   ENSMUSG00225013899 4931428L18Rik gene
19   ENSMUSG00225013913 4931428L18Rik gene
20   ENSMUSG00225013929 4931428L18Rik gene
21   ENSMUSG00225013760 COX5B         gene
22   ENSMUSG00225014148 RPL31         gene
23   ENSMUSG00225000438 rpl12         gene
24   ENSMUSG00225000228 DNAH7         gene
25   ENSMUSG00225008513 rpl23a        gene
26   ENSMUSG00225007477 DNAH7         gene
27   ENSMUSG00225008923 hspd1         gene
28   ENSMUSG00225007492 Akr1b3        gene
29   ENSMUSG00225008161 XDH           gene
30   ENSMUSG00225007586 CFLAR         gene
⋮    ⋮                  ⋮             ⋮
2466 ENSMUSG00225041873 PFDN5         gene
2467 ENSMUSG00225042139 HTR2C         gene
2468 ENSMUSG00225042246 Vmn1r41       gene
2469 ENSMUSG00225042167 LUZP4         gene
2470 ENSMUSG00225042183 LUZP4         gene
2471 ENSMUSG00225042192 LUZP4         gene
2472 ENSMUSG00225042205 LUZP4         gene
2473 ENSMUSG00225042216 LUZP4         gene
2474 ENSMUSG00225042261 LUZP4         gene
2475 ENSMUSG00225042271 LUZP4         gene
2476 ENSMUSG00225041519 MLLT11        gene
2477 ENSMUSG00225042032 rpl21         gene
2478 ENSMUSG00225042048 NSA2          gene
2479 ENSMUSG00225041496 ndufc2        gene
2480 ENSMUSG00225042059 2210013O21Rik gene
2481 ENSMUSG00225041464 MAGEA1        gene
2482 ENSMUSG00225041475 MAGEA1        gene
2483 ENSMUSG00225041483 MAGEA1        gene
2484 ENSMUSG00225041488 MAGEA1        gene
2485 ENSMUSG00225041692 RNF168        gene
2486 ENSMUSG00225041637 SUCLG2        gene
2487 ENSMUSG00225041886 SMS           gene
2488 ENSMUSG00225041449 EIF1AX        gene
2489 ENSMUSG00225037848 FSD2          gene
2490 ENSMUSG00225038298 Siah1b        gene
2491 ENSMUSG00225038670 SAXO1         gene
2492 ENSMUSG00225038265 rbmx          gene
2493 ENSMUSG00225038391 NGF           gene
2494 ENSMUSG00225028175 SPHK1         gene
2495 ENSMUSG00225028213 GSN           gene

[1] 840

An object of class "DGEList"
$samples
                                                                                                                                         files
NZO_HlLtJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.1.featureCounts
NZO_HlLtJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.2.featureCounts
NZO_HlLtJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.3.featureCounts
NZO_HlLtJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.1.featureCounts
NZO_HlLtJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.3.featureCounts
NZO_HlLtJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.1.featureCounts
NZO_HlLtJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.2.featureCounts
NZO_HlLtJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
NZO_HlLtJ-P12.5.1 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-P12.5.2 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-P12.5.3 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-E16.5.1 NZO_HlLtJ-E16.5       NA            1
NZO_HlLtJ-E16.5.3 NZO_HlLtJ-E16.5       NA            1
NZO_HlLtJ-P20.5.1 NZO_HlLtJ-P20.5       NA            1
NZO_HlLtJ-P20.5.2 NZO_HlLtJ-P20.5       NA            1
NZO_HlLtJ-P20.5.3 NZO_HlLtJ-P20.5       NA            1

$counts
                    Samples
Tags                 NZO_HlLtJ-P12.5.1 NZO_HlLtJ-P12.5.2 NZO_HlLtJ-P12.5.3
  ENSMUSG00225000084            424.89            363.88            471.17
  ENSMUSG00225000096           1674.89           1632.66           1715.66
  ENSMUSG00225000140             10.12              4.48              8.98
  ENSMUSG00225000142           1598.19           1493.82           1520.24
  ENSMUSG00225000071             23.37             14.87             22.08
                    Samples
Tags                 NZO_HlLtJ-E16.5.1 NZO_HlLtJ-E16.5.3 NZO_HlLtJ-P20.5.1
  ENSMUSG00225000084            448.35            431.67            416.71
  ENSMUSG00225000096           2749.25           2757.51           1284.44
  ENSMUSG00225000140              1.58              3.40             14.95
  ENSMUSG00225000142           2316.74           2335.10           1110.36
  ENSMUSG00225000071              2.72              1.95             33.88
                    Samples
Tags                 NZO_HlLtJ-P20.5.2 NZO_HlLtJ-P20.5.3
  ENSMUSG00225000084            550.57            483.18
  ENSMUSG00225000096           1361.28           1414.98
  ENSMUSG00225000140             12.45             10.47
  ENSMUSG00225000142           1150.19           1211.39
  ENSMUSG00225000071             24.50             27.15
26279 more rows ...

An object of class "DGEList"
$samples
                                                                                                                                         files
NZO_HlLtJ-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.1.featureCounts
NZO_HlLtJ-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.2.featureCounts
NZO_HlLtJ-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-12.5dpp.3.featureCounts
NZO_HlLtJ-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.1.featureCounts
NZO_HlLtJ-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-16.5dpc.3.featureCounts
NZO_HlLtJ-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.1.featureCounts
NZO_HlLtJ-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.2.featureCounts
NZO_HlLtJ-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/NZO_HlLtJ-20.5dpp.3.featureCounts
                            group lib.size norm.factors
NZO_HlLtJ-P12.5.1 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-P12.5.2 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-P12.5.3 NZO_HlLtJ-P12.5       NA            1
NZO_HlLtJ-E16.5.1 NZO_HlLtJ-E16.5       NA            1
NZO_HlLtJ-E16.5.3 NZO_HlLtJ-E16.5       NA            1
NZO_HlLtJ-P20.5.1 NZO_HlLtJ-P20.5       NA            1
NZO_HlLtJ-P20.5.2 NZO_HlLtJ-P20.5       NA            1
NZO_HlLtJ-P20.5.3 NZO_HlLtJ-P20.5       NA            1

$counts
              NZO_HlLtJ-P12.5.1 NZO_HlLtJ-P12.5.2 NZO_HlLtJ-P12.5.3
0610007P14Rik           1420.50           1382.50           1503.50
0610009B22Rik            562.50            533.00            642.00
0610009O20Rik           1398.60           1325.18           1558.60
0610010F05Rik           3337.53           3071.25           4035.75
0610010K14Rik            961.50            949.00            991.50
              NZO_HlLtJ-E16.5.1 NZO_HlLtJ-E16.5.3 NZO_HlLtJ-P20.5.1
0610007P14Rik           2065.50           2044.50           1047.50
0610009B22Rik            813.00            760.00           1062.00
0610009O20Rik           1913.06           1868.53           2450.35
0610010F05Rik           1735.00           1723.25           4706.25
0610010K14Rik           1004.00           1071.00            611.50
              NZO_HlLtJ-P20.5.2 NZO_HlLtJ-P20.5.3
0610007P14Rik           1052.50           1116.00
0610009B22Rik           1072.00            924.00
0610009O20Rik           2655.26           2497.97
0610010F05Rik           4342.83           4475.14
0610010K14Rik            557.50            567.00
18912 more rows ...

In [26]:
LP_J <- import("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/resources/annotation/LP_J_v3.2.gff3") #import gff3 file 
LP_J = na.omit(mcols(LP_J)[,c("gene_id","Name",'type')]) #get gene symbloes for respective gene id 
#LP_J <- na.omit(mcols(LP_J)[,c("gene_id","Name",'type')])
#colnames(LP_J)[which(names(LP_J) == "Name")] <- "Name" #change columns name
LP_J <- LP_J[LP_J$type == 'gene', ]
LP_J

# Now try using dplyr functions like group_by
library(dplyr)
duplicated_names <- as.data.frame(LP_J) %>%
  group_by(Name) %>%
  filter(n() > 1)
duplicated_names
length(unique(duplicated_names$Name))

LP_J_geneName = LP_J[,c("gene_id","Name")] #get gene symbloes for respective gene id 
rownames(LP_J_geneName) <- LP_J_geneName$gene_id
LP_J_geneName$gene_id <- NULL
LP_J_files <- c('/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.3.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.1.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.2.featureCounts',
'/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.3.featureCounts')
#LP_J_files <- list.files("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy", pattern = "129S1_SvImJ.+.featureCounts$", full.names = T)
LP_J_samplenames = c('LP_J-P12.5','LP_J-P12.5','LP_J-P12.5','LP_J-E16.5',
'LP_J-E16.5','LP_J-E16.5','LP_J-P20.5','LP_J-P20.5','LP_J-P20.5')

LP_J_lables = c('LP_J-P12.5.1','LP_J-P12.5.2','LP_J-P12.5.3','LP_J-E16.5.1','LP_J-E16.5.2','LP_J-E16.5.3',
'LP_J-P20.5.1','LP_J-P20.5.2','LP_J-P20.5.3')

LP_J_raw <- readDGE(LP_J_files, columns = c(1, 7), comment.char = "#", sep="\t", group= LP_J_samplenames, labels = LP_J_lables)
#LP_J_raw
library(dplyr)
LP_J_raw$counts <- merge(x=LP_J_raw$counts, y=LP_J_geneName, by = 0,all.x=TRUE ) #left merge 
LP_J_raw$counts['Row.names'] <- NULL
# Replace "old_value" with "new_value" in the "Name" column
#LP_J_raw$Name[LP_J_raw$Name == "PARP2"] #<- "CCNB1IP1"

LP_J_raw$counts <- LP_J_raw$counts[!is.na(LP_J_raw$counts$Name),] #remove NA 
LP_J_raw$counts[LP_J_raw$counts$Name == "PARP2", ]
LP_J_raw$counts[LP_J_raw$counts$Name == "CCNB1IP1", ]
# Replace "old_value" with "new_value" in the "ColumnName" column
#LP_J_raw$Name <- ifelse(LP_J_raw$Name == "PARP2", "CCNB1IP1", LP_J_raw$Name)
LP_J_raw$counts$Name[LP_J_raw$counts$Name == "PARP2"] <- "CCNB1IP1"
LP_J_raw$counts[LP_J_raw$counts$Name == "CCNB1IP1", ]
LP_J_raw$counts[LP_J_raw$counts$Name == "PARP2", ]
LP_J_raw$counts <- LP_J_raw$counts %>% 
  group_by(Name) %>% 
  summarise(across(everything(), sum))
LP_J_raw$counts[LP_J_raw$counts$Name == "CCNB1IP1", ]
#LP_J_raw$counts[LP_J_raw$counts$Name == "LUZP4", ]
LP_J_raw$counts <- as.data.frame(LP_J_raw$counts[!duplicated(LP_J_raw$counts$Name), ])  #remove dulicate values 
#LP_J_raw$counts[LP_J_raw$counts$Name == "LUZP4", ]
rownames(LP_J_raw$counts) <- LP_J_raw$counts$Name #set rawname to gene symbloes 
LP_J_raw$counts$Name <- NULL #remove genesybloe columns 
LP_J_raw

DataFrame with 20584 rows and 3 columns
                 gene_id          Name     type
             <character>   <character> <factor>
1     ENSMUSG00230001954        ugt1a1     gene
2     ENSMUSG00230001994        MROH2A     gene
3     ENSMUSG00230002012         HJURP     gene
4     ENSMUSG00230002276          XKR4     gene
5     ENSMUSG00230001712           RP1     gene
...                  ...           ...      ...
20580 ENSMUSG00230025268          MID1     gene
20581 ENSMUSG00230025421 4933400A11Rik     gene
20582 ENSMUSG00230025630          glsa     gene
20583 ENSMUSG00230025776           GSN     gene
20584 ENSMUSG00230025861          ASMT     gene

     gene_id            Name          type
1    ENSMUSG00230001954 ugt1a1        gene
2    ENSMUSG00230001994 MROH2A        gene
3    ENSMUSG00230002012 HJURP         gene
4    ENSMUSG00230001779 TCEA1         gene
5    ENSMUSG00230001786 HMGB3         gene
6    ENSMUSG00230001800 RGS20         gene
7    ENSMUSG00230001684 Gm4737        gene
8    ENSMUSG00230002131 COPS5         gene
9    ENSMUSG00230015720 RPL5          gene
10   ENSMUSG00230016312 RETN          gene
11   ENSMUSG00230018706 cetn4         gene
12   ENSMUSG00230017825 Khdc1b        gene
13   ENSMUSG00230018234 Khdc1b        gene
14   ENSMUSG00230015880 Khdc1b        gene
15   ENSMUSG00230000389 rpl13         gene
16   ENSMUSG00230000374 4931428L18Rik gene
17   ENSMUSG00230000378 4931428L18Rik gene
18   ENSMUSG00230000382 4931428L18Rik gene
19   ENSMUSG00230023864 SLA2          gene
20   ENSMUSG00230023453 COX5B         gene
21   ENSMUSG00230025036 mrpl30        gene
22   ENSMUSG00230021801 RPL31         gene
23   ENSMUSG00230000934 DNAH7         gene
24   ENSMUSG00230001011 rpl23a        gene
25   ENSMUSG00230000948 NEMP2         gene
26   ENSMUSG00230023739 DNAH7         gene
27   ENSMUSG00230028586 hspd1         gene
28   ENSMUSG00230028630 HSPE1         gene
29   ENSMUSG00230027753 Akr1b3        gene
30   ENSMUSG00230024300 CBX3          gene
⋮    ⋮                  ⋮             ⋮
2521 ENSMUSG00230030916 LUZP4         gene
2522 ENSMUSG00230030940 LUZP4         gene
2523 ENSMUSG00230031002 LUZP4         gene
2524 ENSMUSG00230031033 LUZP4         gene
2525 ENSMUSG00230031054 LUZP4         gene
2526 ENSMUSG00230031061 LUZP4         gene
2527 ENSMUSG00230031087 LUZP4         gene
2528 ENSMUSG00230031118 LUZP4         gene
2529 ENSMUSG00230031125 LUZP4         gene
2530 ENSMUSG00230031128 LUZP4         gene
2531 ENSMUSG00230031133 LUZP4         gene
2532 ENSMUSG00230031141 LUZP4         gene
2533 ENSMUSG00230032350 rpl21         gene
2534 ENSMUSG00230011416 ndufc2        gene
2535 ENSMUSG00230011905 2210013O21Rik gene
2536 ENSMUSG00230011435 MAGEA1        gene
2537 ENSMUSG00230011450 MAGEA1        gene
2538 ENSMUSG00230011548 MAGEA1        gene
2539 ENSMUSG00230011569 MAGEA1        gene
2540 ENSMUSG00230011592 MAGEA1        gene
2541 ENSMUSG00230011328 RNF168        gene
2542 ENSMUSG00230013405 SUCLG2        gene
2543 ENSMUSG00230012497 SMS           gene
2544 ENSMUSG00230013361 SCML2         gene
2545 ENSMUSG00230012204 FSD2          gene
2546 ENSMUSG00230025547 SYAP1         gene
2547 ENSMUSG00230023798 SAXO1         gene
2548 ENSMUSG00230024818 RPL7A         gene
2549 ENSMUSG00230026126 rbmx          gene
2550 ENSMUSG00230025776 GSN           gene

[1] 881

      LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
24322 281837.5     290733       274963.1     290833.4     260175
      LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3 Name
24322 281042       178826.4     178653.2     229725.9     PARP2

      LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
24320 701          530.5        478.5        283          291
      LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3 Name
24320 246          742          668          875.35       CCNB1IP1

      LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
24320    701.0        530.5        478.5        283.0        291
24322 281837.5     290733.0     274963.1     290833.4     260175
      LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3 Name
24320    246          742.0        668.0        875.35    CCNB1IP1
24322 281042       178826.4     178653.2     229725.85    CCNB1IP1

     LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
     LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3 Name

  Name     LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
1 CCNB1IP1 282538.5     291263.5     275441.6     291116.4     260466
  LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3
1 281288       179568.4     179321.2     230601.2

An object of class "DGEList"
$samples
                                                                                                                               files
LP_J-P12.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.1.featureCounts
LP_J-P12.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.2.featureCounts
LP_J-P12.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-12.5dpp.3.featureCounts
LP_J-E16.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.1.featureCounts
LP_J-E16.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.2.featureCounts
LP_J-E16.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-16.5dpc.3.featureCounts
LP_J-P20.5.1 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.1.featureCounts
LP_J-P20.5.2 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.2.featureCounts
LP_J-P20.5.3 /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/featureCount_rna/strains_copy/LP_J-20.5dpp.3.featureCounts
                  group lib.size norm.factors
LP_J-P12.5.1 LP_J-P12.5       NA            1
LP_J-P12.5.2 LP_J-P12.5       NA            1
LP_J-P12.5.3 LP_J-P12.5       NA            1
LP_J-E16.5.1 LP_J-E16.5       NA            1
LP_J-E16.5.2 LP_J-E16.5       NA            1
LP_J-E16.5.3 LP_J-E16.5       NA            1
LP_J-P20.5.1 LP_J-P20.5       NA            1
LP_J-P20.5.2 LP_J-P20.5       NA            1
LP_J-P20.5.3 LP_J-P20.5       NA            1

$counts
              LP_J-P12.5.1 LP_J-P12.5.2 LP_J-P12.5.3 LP_J-E16.5.1 LP_J-E16.5.2
0610007P14Rik      2980.90      3319.68      3386.16      4244.86      4036.07
0610009B22Rik       449.00       450.00       405.00       547.00       490.00
0610009O20Rik      1149.86      1238.00      1169.00      1836.50      1722.50
0610010F05Rik      3877.75      4319.50      4535.75      1673.37      1551.50
0610010K14Rik       862.00       953.50       935.50       796.00       848.50
              LP_J-E16.5.3 LP_J-P20.5.1 LP_J-P20.5.2 LP_J-P20.5.3
0610007P14Rik      4067.67      2134.95      2119.21      2262.23
0610009B22Rik       473.00       788.00       841.00       673.00
0610009O20Rik      1654.50      2477.50      2323.50      2202.50
0610010F05Rik      1670.58      4984.00      4819.75      4766.02
0610010K14Rik       733.17       432.00       397.00       526.00
18909 more rows ...

In [27]:
library(edgeR)

# Combine two DGEList objects
# Assuming you have a list of DGEList objects: dge_list
dge_list <- list(A129S1_SvImJ_raw, 
    A_J_raw,
    AKR_J_raw, 
    BALB_cJ_raw,
    C3H_HeJ_raw,
    C57BL_6NJ_raw,
    CAST_EiJ_raw,
    CBA_J_raw,
    DBA_2J_raw,
    FVB_NJ_raw,
    LP_J_raw,
    NOD_ShiLtJ_raw,
    NZO_HlLtJ_raw,
    PWK_PhJ_raw,
    SPRET_EiJ_raw,
    WSB_EiJ_raw)  # List of DGEList objects
gene_lists <- lapply(dge_list, rownames)

# Find common genes across all gene lists
common_genes <- Reduce(intersect, gene_lists)


all_strains_dge <- cbind(A129S1_SvImJ_raw$counts[common_genes,], 
        A_J_raw$counts[common_genes,],
        AKR_J_raw$counts[common_genes,], 
        BALB_cJ_raw$counts[common_genes,],
        C3H_HeJ_raw$counts[common_genes,],
        C57BL_6NJ_raw$counts[common_genes,],
        CAST_EiJ_raw$counts[common_genes,],
        CBA_J_raw$counts[common_genes,],
        DBA_2J_raw$counts[common_genes,],
        FVB_NJ_raw$counts[common_genes,], 
        LP_J_raw$counts[common_genes,],
        NOD_ShiLtJ_raw$counts[common_genes,],
        NZO_HlLtJ_raw$counts[common_genes,],
        PWK_PhJ_raw$counts[common_genes,],
        SPRET_EiJ_raw$counts[common_genes,],
        WSB_EiJ_raw$counts[common_genes,])
all_strains_dge

              129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
0610007P14Rik 1230.00             1233.50             1335.00
0610009B22Rik  395.00              390.00              408.00
0610010F05Rik 3900.83             3888.25             3582.75
0610010K14Rik  839.50              760.50              934.50
0610037L13Rik  862.00              994.50             1133.00
0610040J01Rik  100.09               62.63               82.89
1110002E22Rik    5.00                6.50                2.00
1110004F10Rik 2832.50             3073.50             2799.53
1110008F13Rik 1572.21             1398.09             1639.09
1110008L16Rik 1009.59              962.87             1022.18
1110008P14Rik  325.50              304.50              375.00
1110017D15Rik   10.33               11.50                6.50
1110032A03Rik  499.50              512.50              530.50
1110032F04Rik   20.50               12.50                5.50
1110034G24Rik  602.45              578.34              669.85
1110037F02Rik 6053.79             6041.25             6184.08
1110038F14Rik  384.00              377.00              430.00
1110051M20Rik 3318.15             4083.57             3665.46
1110059E24Rik 1749.17             1812.33             1721.25
1110059G10Rik  399.00              449.50              421.00
1110065P20Rik  853.83              842.67             1017.67
1190002N15Rik 1231.00             1301.00             1112.00
1190005I06Rik  119.50              126.00              110.50
1300017J02Rik  299.00              423.00              345.00
1500009C09Rik    9.00               13.00                8.00
1500009L16Rik 1456.00             1441.75             1647.50
1500011K16Rik  143.00              112.00              123.00
1500015O10Rik  167.00              152.50              179.00
1600002H07Rik  377.00              372.25              406.50
1600012H06Rik  729.00              767.00              726.00
⋮             ⋮                   ⋮                   ⋮
uncx              4.00                7.00                1.00
uox              10.08                3.59                5.83
uqcrh          1343.11             1213.58             1411.58
urad              1.00                1.00                3.00
usp18           266.00              278.00              290.00
usp32         11394.15            12840.86            10595.54
vamp2           369.00              474.50              408.00
vdac1          2437.73             2322.04             2463.50
vgf               5.50                3.00                9.33
vhl            2217.50             2056.25             2192.75
vmn2r1          157.75              139.00              120.33
vps33a         3357.00             3986.42             3990.18
vps33b         1005.50             1061.08             1133.25
wdfy1          2127.00             2175.00             2137.56
wdr34           574.97              722.33              792.50
wdr82          6279.51             6437.49             6585.84
wdr92           569.00              595.50              625.75
wdr95            31.74               32.22               32.00
wdyhv1          696.74              707.11              739.27
wnt8a            10.00               10.00                4.00
xylt1          2384.83             2183.74             2356.17
ybx1           6355.96             7052.04             6602.22
zak            1689.58             1494.65             1539.05
zbtb42           90.00               83.00               97.00
zbtb8b          134.00               98.00              110.00
zc3h11a        3495.95             3594.67             3553.62
zdhhc11          13.17                5.00               10.00
zfpm1          1621.00             1693.00             1735.00
zfyve16        3280.18             3566.38             3417.21
znrd1           314.00              312.50              349.00
              129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
0610007P14Rik 1680.50             1897.00             1647.00
0610009B22Rik  467.25              547.00              460.25
0610010F05Rik 1398.60             1751.50             1737.00
0610010K14Rik  996.50              995.00              945.00
0610037L13Rik 1471.00             1500.00             1447.75
0610040J01Rik  201.20              250.13              291.92
1110002E22Rik   14.50               17.50               14.00
1110004F10Rik 2444.35             2928.50             2792.90
1110008F13Rik 1901.14             2146.10             1936.77
1110008L16Rik 1174.83             1322.82             1528.89
1110008P14Rik  451.50              444.50              420.83
1110017D15Rik   11.00                9.50                7.67
1110032A03Rik  454.00              441.50              463.50
1110032F04Rik  121.00              217.50              227.00
1110034G24Rik  479.47              612.37              657.74
1110037F02Rik 6205.42             7323.45             6804.00
1110038F14Rik  476.50              503.00              502.50
1110051M20Rik 2064.48             2471.91             2559.06
1110059E24Rik 2270.71             2435.88             2566.20
1110059G10Rik  401.50              422.50              480.00
1110065P20Rik  683.33              769.17              701.33
1190002N15Rik 1258.00             1417.00             1435.00
1190005I06Rik  200.50              207.52              172.00
1300017J02Rik  168.00              231.00              169.00
1500009C09Rik   21.00               18.00               13.50
1500009L16Rik  699.25              890.00              784.33
1500011K16Rik  197.00              176.00              175.00
1500015O10Rik  166.00              169.00              131.00
1600002H07Rik  575.00              596.50              623.00
1600012H06Rik  880.00              911.50              927.50
⋮             ⋮                   ⋮                   ⋮
uncx              6.00                5.00                2.00
uox              24.05               22.69               36.04
uqcrh          1928.08             1766.08             1781.83
urad              3.00                1.00                5.00
usp18           355.00              430.50              406.00
usp32          3303.23             4369.19             4595.26
vamp2           324.00              374.00              453.00
vdac1          3584.33             4303.92             4002.00
vgf               7.00               15.00                9.00
vhl            1375.50             1499.00             1443.00
vmn2r1           64.33               90.00              109.08
vps33a         2999.58             3228.06             3011.64
vps33b          803.50              953.50              890.50
wdfy1          2553.56             2793.64             2752.00
wdr34           576.25              618.00              639.50
wdr82          5368.96             6351.86             6398.97
wdr92          1248.00             1180.00             1124.00
wdr95           232.00              275.49              257.77
wdyhv1         1024.36             1225.12             1255.46
wnt8a             6.00               13.00               17.00
xylt1          4182.00             6683.15             7477.43
ybx1          10320.31            11161.02            11114.85
zak            1637.19             2140.46             2228.07
zbtb42           92.00              107.50              110.00
zbtb8b          262.83              239.50              245.00
zc3h11a        4490.43             5530.51             5584.42
zdhhc11          37.50               59.75               46.70
zfpm1           897.00             1426.75             1477.00
zfyve16        2836.27             3369.73             2976.74
znrd1           367.00              370.00              495.50
              129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3
0610007P14Rik  752.50              759.00              761.00
0610009B22Rik  918.00             1021.00              710.00
0610010F05Rik 4896.50             5130.50             4971.75
0610010K14Rik  435.00              423.00              394.00
0610037L13Rik 1769.00             1733.50             1523.00
0610040J01Rik   29.70               46.65               30.40
1110002E22Rik    2.00                3.17                3.00
1110004F10Rik 4146.53             4333.00             4345.83
1110008F13Rik  816.54              854.03              854.33
1110008L16Rik  844.80              929.39              875.42
1110008P14Rik  347.50              373.50              274.50
1110017D15Rik  188.33              237.75              171.67
1110032A03Rik 4090.00             4366.67             3509.50
1110032F04Rik    4.00                3.25                2.00
1110034G24Rik  194.31              220.18              258.37
1110037F02Rik 5064.50             5504.00             5459.25
1110038F14Rik  308.00              276.00              279.00
1110051M20Rik 5392.23             5860.12             6214.07
1110059E24Rik 1247.33             1498.07             1412.67
1110059G10Rik  322.50              336.00              343.00
1110065P20Rik 1823.17             1963.67             1466.67
1190002N15Rik  585.00              535.00              531.00
1190005I06Rik   79.52               90.02               81.92
1300017J02Rik 1086.00             1497.00             1208.25
1500009C09Rik   34.00               53.00               45.00
1500009L16Rik  650.00              676.00              633.50
1500011K16Rik  109.00              108.00               97.00
1500015O10Rik   71.00               86.00               81.00
1600002H07Rik  151.00              152.50              141.00
1600012H06Rik  657.50              625.39              620.00
⋮             ⋮                   ⋮                   ⋮
uncx              0.00                0.00                0.00
uox              29.12               41.05               21.00
uqcrh          1102.17             1143.08             1107.08
urad              0.00                0.00                1.00
usp18           110.00               94.00              102.00
usp32         13455.15            15324.89            15396.14
vamp2           333.00              359.00              407.00
vdac1          1053.00             1043.00             1049.50
vgf               1.00                4.50                2.00
vhl            1609.25             1715.25             1381.50
vmn2r1          104.50              115.27              106.16
vps33a         7786.32             7881.51             7314.89
vps33b          864.50              804.00              792.50
wdfy1          4367.50             4902.00             4163.50
wdr34          1825.50             1850.05             1700.00
wdr82          3460.74             3755.66             3777.32
wdr92          1463.00             1472.00             1365.00
wdr95            83.83              171.67              101.17
wdyhv1          204.31              213.20              206.20
wnt8a             7.00               12.50               10.00
xylt1           474.38              531.31              632.40
ybx1          24754.52            26243.79            22867.78
zak            1231.42             1384.08             1316.30
zbtb42         1850.00             2044.00             1228.00
zbtb8b           39.00               40.00               37.75
zc3h11a        2272.92             2551.96             2501.19
zdhhc11         198.00              406.00              207.00
zfpm1          1096.00             1225.25             1049.00
zfyve16        3157.50             3504.56             3390.99
znrd1           386.50              423.00              378.00
              A_J-P12.5.1 ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2
0610007P14Rik 3019.00     ⋯  552.65           1262.50         1215.50
0610009B22Rik  362.00     ⋯  462.00            435.00          411.00
0610010F05Rik 3611.33     ⋯ 3890.56           3332.25         2658.92
0610010K14Rik  691.00     ⋯  763.50            655.00          597.50
0610037L13Rik  848.00     ⋯  973.75            941.00          869.00
0610040J01Rik   53.00     ⋯   14.00             45.00           92.50
1110002E22Rik    0.50     ⋯    1.00              4.50            2.00
1110004F10Rik 2714.29     ⋯ 3698.16           2945.79         2657.28
1110008F13Rik 1213.03     ⋯ 1542.00           1770.17         1712.27
1110008L16Rik 1030.66     ⋯ 1262.53           1019.28         1068.63
1110008P14Rik  272.00     ⋯  326.50            294.00          260.00
1110017D15Rik   21.67     ⋯   88.00             11.50           13.50
1110032A03Rik  469.50     ⋯ 1342.00            424.50          457.00
1110032F04Rik    5.00     ⋯    6.00             32.50           60.00
1110034G24Rik  659.86     ⋯  278.33            569.23          522.15
1110037F02Rik 5956.84     ⋯ 8855.50           6696.08         6234.00
1110038F14Rik  322.50     ⋯  543.00            479.00          326.00
1110051M20Rik 4133.36     ⋯ 3380.40           2636.73         2611.67
1110059E24Rik 1654.00     ⋯  951.00           2017.02         2020.94
1110059G10Rik  380.00     ⋯  549.50            397.00          348.00
1110065P20Rik  831.67     ⋯ 1139.83            904.83          839.50
1190002N15Rik 1104.00     ⋯  716.00           1281.00         1205.00
1190005I06Rik  111.83     ⋯   44.03             28.00           28.50
1300017J02Rik  186.50     ⋯  109.00            345.99          187.75
1500009C09Rik    4.00     ⋯    7.00             16.00           14.00
1500009L16Rik 1260.00     ⋯  533.50           2464.00         2272.00
1500011K16Rik  137.00     ⋯  101.00            125.00          124.00
1500015O10Rik  131.00     ⋯  145.00            173.50          193.00
1600002H07Rik  365.00     ⋯  284.00            337.50          340.11
1600012H06Rik  697.50     ⋯  395.00            511.50          478.17
⋮             ⋮           ⋱ ⋮                 ⋮               ⋮
uncx              0.00    ⋯     7.00              1.00            0.00
uox               6.63    ⋯     9.00              1.93           17.23
uqcrh          1210.67    ⋯  1993.03           1680.14         1711.75
urad              1.00    ⋯     0.00              0.00            0.00
usp18           254.00    ⋯   125.00            350.00          269.00
usp32         11374.70    ⋯ 10095.54          11840.62        10347.04
vamp2           363.00    ⋯   435.00            460.00          446.00
vdac1          2152.33    ⋯  1742.50           3357.60         3291.56
vgf               3.00    ⋯    13.00              9.00            4.00
vhl            1832.00    ⋯  1720.00           2140.00         2021.50
vmn2r1          131.50    ⋯     4.00            217.00          227.02
vps33a         3384.11    ⋯  1494.71           2439.60         2212.90
vps33b          971.83    ⋯   818.50            803.50          721.00
wdfy1          2079.59    ⋯  2314.50           2251.36         2494.77
wdr34           639.50    ⋯  1399.00            438.00          347.75
wdr82          5407.01    ⋯  6415.25           8544.09         8079.78
wdr92           606.00    ⋯   881.50            649.00          623.00
wdr95            39.84    ⋯   839.95             12.86           32.75
wdyhv1          588.85    ⋯   345.00            400.00          416.00
wnt8a             7.00    ⋯    12.50              5.00            7.00
xylt1          4652.30    ⋯  1556.25           6144.05         7374.23
ybx1           7175.30    ⋯  5573.16           6409.78         5312.52
zak            1577.61    ⋯   826.00           1842.60         2194.53
zbtb42           51.00    ⋯   172.00             44.00           40.00
zbtb8b          129.00    ⋯    54.00             82.00           69.00
zc3h11a        3825.58    ⋯  2667.75           3736.52         3959.76
zdhhc11           9.00    ⋯    64.00             10.00            2.00
zfpm1          1525.00    ⋯  1213.00           2007.50         2045.00
zfyve16        3351.62    ⋯  5021.46           3928.83         3323.07
znrd1           287.00    ⋯   538.00            264.50          260.00
              WSB_EiJ-P12.5.3 WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3
0610007P14Rik 1270.00         1574.50         1452.00         1787.50
0610009B22Rik  440.00          532.00          515.00          683.00
0610010F05Rik 3089.33         1621.25         1673.75         2012.58
0610010K14Rik  622.00          735.50          626.00          622.00
0610037L13Rik 1049.50         1492.00         1509.00         1465.00
0610040J01Rik   54.00          142.00           93.50          106.02
1110002E22Rik    1.50           22.50           19.50           13.50
1110004F10Rik 2844.92         3167.03         3163.34         3305.28
1110008F13Rik 1872.50         1645.00         1595.50         1772.50
1110008L16Rik 1171.26         1067.46         1018.25         1060.66
1110008P14Rik  295.00          303.00          283.00          288.50
1110017D15Rik   10.50           17.00           12.50            4.00
1110032A03Rik  477.83          397.50          364.00          404.50
1110032F04Rik   49.50          105.50          121.00          128.00
1110034G24Rik  527.38          383.83          421.32          448.02
1110037F02Rik 6668.50         6080.75         6212.75         6501.17
1110038F14Rik  402.00          481.50          502.00          477.00
1110051M20Rik 2747.18         2306.95         2583.89         2500.21
1110059E24Rik 2193.50         2108.18         2346.93         2512.77
1110059G10Rik  367.50          442.00          421.00          452.00
1110065P20Rik  913.75          705.50          671.33          784.67
1190002N15Rik 1246.00         1396.75         1620.00         1758.00
1190005I06Rik   40.50           36.50           31.25           46.50
1300017J02Rik  202.00          188.00          170.00          120.50
1500009C09Rik    9.00            7.00            5.00            5.00
1500009L16Rik 2517.62         1455.00         1409.00         1433.50
1500011K16Rik  173.00          191.00          184.00          211.00
1500015O10Rik  198.50          200.00          132.00          167.50
1600002H07Rik  344.00          551.50          612.50          591.00
1600012H06Rik  509.17          523.83          519.17          582.33
⋮             ⋮               ⋮               ⋮               ⋮
uncx              1.00            0.00           0.00            1.00
uox               9.89           24.54           6.86            9.20
uqcrh          1808.83         2336.58        2258.20         2625.35
urad              0.00            1.00           0.00            0.00
usp18           316.00          315.00         373.00          353.00
usp32         10451.34         3292.08        3835.44         3861.74
vamp2           392.00          380.00         382.00          321.00
vdac1          3502.49         4197.98        4140.82         4427.71
vgf               1.00            1.00           0.00            1.00
vhl            2180.00         1574.00        1522.25         1795.00
vmn2r1          205.00          112.56          95.75          134.10
vps33a         2408.62         1647.63        1757.16         1929.31
vps33b          780.00          805.50         887.17          887.33
wdfy1          2673.81         2548.10        2620.92         2785.33
wdr34           337.33          406.00         462.00          362.50
wdr82          8510.67         6434.50        6436.34         6913.73
wdr92           678.00          918.50         818.00         1006.00
wdr95            16.40           53.73          41.08           31.88
wdyhv1          484.50          822.50         856.00          903.50
wnt8a             5.00            3.00           2.00            4.00
xylt1          7437.19         4366.65        4781.15         5037.58
ybx1           5731.62        10094.77        9693.72         8838.29
zak            2098.43         2095.46        1873.42         2124.04
zbtb42           59.25           89.00          73.00           79.00

In [28]:
all_strains_dge <- all_strains_dge[row.names(all_strains_dge) != 'CCNB1IP1', ]

all_strains_dge <- all_strains_dge[!rowSums(is.na(all_strains_dge)) > 0, ]  #Removing genes with missing values:

In [29]:

combined_dge <- DGEList(counts = all_strains_dge)

samplenames <- c('129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5',
'129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5',
'129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'A_J-P12.5','A_J-P12.5','A_J-P12.5',
'A_J-E16.5','A_J-E16.5','A_J-E16.5',
'A_J-P20.5','A_J-P20.5','A_J-P20.5',
'AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-E16.5',
'AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-E16.5',
'BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-E16.5',
'C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5',
'C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-E16.5',
'C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-E16.5',
'CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-E16.5',
'CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-E16.5',
'DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-E16.5','
FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'LP_J-P12.5','LP_J-P12.5','LP_J-P12.5',
'LP_J-E16.5','LP_J-E16.5','LP_J-E16.5',
'LP_J-P20.5','LP_J-P20.5','LP_J-P20.5',
'NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5',
'NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5',
'NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5',#'NZO_HlLtJ-E16.5',
'NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5',
'PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-E16.5',
'PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-E16.5',
'SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5',
'WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-E16.5',
'WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5')
samplenames


combined_dge$samples$group <- samplenames

combined_dge$samples

  [1] "129S1_SvImJ-P12.5" "129S1_SvImJ-P12.5" "129S1_SvImJ-P12.5"
  [4] "129S1_SvImJ-E16.5" "129S1_SvImJ-E16.5" "129S1_SvImJ-E16.5"
  [7] "129S1_SvImJ-P20.5" "129S1_SvImJ-P20.5" "129S1_SvImJ-P20.5"
 [10] "A_J-P12.5"         "A_J-P12.5"         "A_J-P12.5"
 [13] "A_J-E16.5"         "A_J-E16.5"         "A_J-E16.5"
 [16] "A_J-P20.5"         "A_J-P20.5"         "A_J-P20.5"
 [19] "AKR_J-P12.5"       "AKR_J-P12.5"       "AKR_J-P12.5"
 [22] "AKR_J-E16.5"       "AKR_J-E16.5"       "AKR_J-E16.5"
 [25] "AKR_J-P20.5"       "AKR_J-P20.5"       "AKR_J-P20.5"
 [28] "BALB_cJ-P12.5"     "BALB_cJ-P12.5"     "BALB_cJ-P12.5"
 [31] "BALB_cJ-E16.5"     "BALB_cJ-E16.5"     "BALB_cJ-E16.5"
 [34] "BALB_cJ-P20.5"     "BALB_cJ-P20.5"     "BALB_cJ-P20.5"
 [37] "C3H_HeJ-P12.5"     "C3H_HeJ-P12.5"     "C3H_HeJ-P12.5"
 [40] "C3H_HeJ-E16.5"     "C3H_HeJ-E16.5"     "C3H_HeJ-E16.5"
 [43] "C3H_HeJ-P20.5"     "C3H_HeJ-P20.5"     "C3H_HeJ-P20.5"
 [46] "C57BL_6NJ-P12.5"   "C57BL_6NJ-P12.5"   "C57BL_6NJ-P12.5"
 [49] "C57BL_6NJ-E16.5"   "C57BL_6NJ-E16.5"   "C57BL_6NJ-E16.5"
 [52] "C57BL_6NJ-P20.5"   "C57BL_6NJ-P20.5"   "C57BL_6NJ-P20.5"
 [55] "CAST_EiJ-P12.5"    "CAST_EiJ-P12.5"    "CAST_EiJ-P12.5"
 [58] "CAST_EiJ-E16.5"    "CAST_EiJ-E16.5"    "CAST_EiJ-E16.5"
 [61] "CAST_EiJ-P20.5"    "CAST_EiJ-P20.5"    "CAST_EiJ-P20.5"
 [64] "CBA_J-P12.5"       "CBA_J-P12.5"       "CBA_J-P12.5"
 [67] "CBA_J-E16.5"       "CBA_J-E16.5"       "CBA_J-E16.5"
 [70] "CBA_J-P20.5"       "CBA_J-P20.5"       "CBA_J-P20.5"
 [73] "DBA_2J-P12.5"      "DBA_2J-P12.5"      "DBA_2J-P12.5"
 [76] "DBA_2J-E16.5"      "DBA_2J-E16.5"      "DBA_2J-E16.5"
 [79] "DBA_2J-P20.5"      "DBA_2J-P20.5"      "DBA_2J-P20.5"
 [82] "FVB_NJ-P12.5"      "FVB_NJ-P12.5"      "FVB_NJ-P12.5"
 [85] "FVB_NJ-E16.5"      "FVB_NJ-E16.5"      "FVB_NJ-E16.5"
 [88] "\nFVB_NJ-P20.5"    "FVB_NJ-P20.5"      "FVB_NJ-P20.5"
 [91] "LP_J-P12.5"        "LP_J-P12.5"        "LP_J-P12.5"
 [94] "LP_J-E16.5"        "LP_J-E16.5"        "LP_J-E16.5"
 [97] "LP_J-P20.5"        "LP_J-P20.5"        "LP_J-P20.5"
[100] "NOD_ShiLtJ-P12.5"  "NOD_ShiLtJ-P12.5"  "NOD_ShiLtJ-P12.5"
[103] "NOD_ShiLtJ-E16.5"  "NOD_ShiLtJ-E16.5"  "NOD_ShiLtJ-E16.5"
[106] "NOD_ShiLtJ-P20.5"  "NOD_ShiLtJ-P20.5"  "NOD_ShiLtJ-P20.5"
[109] "NZO_HlLtJ-P12.5"   "NZO_HlLtJ-P12.5"   "NZO_HlLtJ-P12.5"
[112] "NZO_HlLtJ-E16.5"   "NZO_HlLtJ-E16.5"   "NZO_HlLtJ-P20.5"
[115] "NZO_HlLtJ-P20.5"   "NZO_HlLtJ-P20.5"   "PWK_PhJ-P12.5"
[118] "PWK_PhJ-P12.5"     "PWK_PhJ-P12.5"     "PWK_PhJ-E16.5"
[121] "PWK_PhJ-E16.5"     "PWK_PhJ-E16.5"     "PWK_PhJ-P20.5"
[124] "PWK_PhJ-P20.5"     "PWK_PhJ-P20.5"     "SPRET_EiJ-P12.5"
[127] "SPRET_EiJ-P12.5"   "SPRET_EiJ-P12.5"   "SPRET_EiJ-E16.5"
[130] "SPRET_EiJ-E16.5"   "SPRET_EiJ-E16.5"   "SPRET_EiJ-P20.5"
[133] "SPRET_EiJ-P20.5"   "SPRET_EiJ-P20.5"   "WSB_EiJ-P12.5"
[136] "WSB_EiJ-P12.5"     "WSB_EiJ-P12.5"     "WSB_EiJ-E16.5"
[139] "WSB_EiJ-E16.5"     "WSB_EiJ-E16.5"     "WSB_EiJ-P20.5"
[142] "WSB_EiJ-P20.5"     "WSB_EiJ-P20.5"

                    group             lib.size norm.factors
129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5 29595060 1
129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5 29743012 1
129S1_SvImJ-P12.5.3 129S1_SvImJ-P12.5 29889725 1
129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5 28638681 1
129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5 33434793 1
129S1_SvImJ-E16.5.3 129S1_SvImJ-E16.5 33519669 1
129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5 29080346 1
129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5 31746436 1
129S1_SvImJ-P20.5.3 129S1_SvImJ-P20.5 29274919 1
A_J-P12.5.1         A_J-P12.5         27578862 1
A_J-P12.5.2         A_J-P12.5         31442710 1
A_J-P12.5.3         A_J-P12.5         29579177 1
A_J-E16.5.1         A_J-E16.5         31988109 1
A_J-E16.5.2         A_J-E16.5         31204067 1
A_J-E16.5.3         A_J-E16.5         29032532 1
A_J-P20.5.1         A_J-P20.5         28946618 1
A_J-P20.5.2         A_J-P20.5         27982329 1
A_J-P20.5.3         A_J-P20.5         26143845 1
AKR_J-P12.5.1       AKR_J-P12.5       29708683 1
AKR_J-P12.5.2       AKR_J-P12.5       30516696 1
AKR_J-P12.5.3       AKR_J-P12.5       32299805 1
AKR_J-E16.5.1       AKR_J-E16.5       27865495 1
AKR_J-E16.5.2       AKR_J-E16.5       31311727 1
AKR_J-E16.5.3       AKR_J-E16.5       31843175 1
AKR_J-P20.5.1       AKR_J-P20.5       31245932 1
AKR_J-P20.5.2       AKR_J-P20.5       30617348 1
AKR_J-P20.5.3       AKR_J-P20.5       26932847 1
BALB_cJ-P12.5.1     BALB_cJ-P12.5     27617868 1
BALB_cJ-P12.5.2     BALB_cJ-P12.5     28315469 1
BALB_cJ-P12.5.3     BALB_cJ-P12.5     29272869 1
⋮                   ⋮                 ⋮        ⋮
NZO_HlLtJ-P20.5.1   NZO_HlLtJ-P20.5   31265719 1
NZO_HlLtJ-P20.5.2   NZO_HlLtJ-P20.5   29845777 1
NZO_HlLtJ-P20.5.3   NZO_HlLtJ-P20.5   30875836 1
PWK_PhJ-P12.5.1     PWK_PhJ-P12.5     31395653 1
PWK_PhJ-P12.5.2     PWK_PhJ-P12.5     31288240 1
PWK_PhJ-P12.5.3     PWK_PhJ-P12.5     31743540 1
PWK_PhJ-E16.5.1     PWK_PhJ-E16.5     31227333 1
PWK_PhJ-E16.5.2     PWK_PhJ-E16.5     31015940 1
PWK_PhJ-E16.5.3     PWK_PhJ-E16.5     30578604 1
PWK_PhJ-P20.5.1     PWK_PhJ-P20.5     30502059 1
PWK_PhJ-P20.5.2     PWK_PhJ-P20.5     31789437 1
PWK_PhJ-P20.5.3     PWK_PhJ-P20.5     29655373 1
SPRET_EiJ-P12.5.1   SPRET_EiJ-P12.5   28935602 1
SPRET_EiJ-P12.5.2   SPRET_EiJ-P12.5   33482058 1
SPRET_EiJ-P12.5.3   SPRET_EiJ-P12.5   34103708 1
SPRET_EiJ-E16.5.1   SPRET_EiJ-E16.5   31788066 1
SPRET_EiJ-E16.5.2   SPRET_EiJ-E16.5   31168004 1
SPRET_EiJ-E16.5.3   SPRET_EiJ-E16.5   31888285 1
SPRET_EiJ-P20.5.1   SPRET_EiJ-P20.5   29229770 1
SPRET_EiJ-P20.5.2   SPRET_EiJ-P20.5   28686709 1
SPRET_EiJ-P20.5.3   SPRET_EiJ-P20.5   26238494 1
WSB_EiJ-P12.5.1     WSB_EiJ-P12.5     30065304 1
WSB_EiJ-P12.5.2     WSB_EiJ-P12.5     29656361 1
WSB_EiJ-P12.5.3     WSB_EiJ-P12.5     31082455 1
WSB_EiJ-E16.5.1     WSB_EiJ-E16.5     29669425 1
WSB_EiJ-E16.5.2     WSB_EiJ-E16.5     30634593 1
WSB_EiJ-E16.5.3     WSB_EiJ-E16.5     32840701 1
WSB_EiJ-P20.5.1     WSB_EiJ-P20.5     30916377 1
WSB_EiJ-P20.5.2     WSB_EiJ-P20.5     29003283 1
WSB_EiJ-P20.5.3     WSB_EiJ-P20.5     28762498 1

In [30]:
rawdata_copy <- combined_dge

In [31]:
# Extract rows by multiple row names
row_names_to_extract <- c('Piwil1', 'Piwil2', 'Piwil4')
piwi_sub_1 <- subset(combined_dge$counts, tolower(row.names(combined_dge)) %in% tolower(row_names_to_extract))
piwi_sub_1

       129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
PIWIL1  210.62              675.91              356.09
PIWIL2 5538.99             7260.23             6849.96
PIWIL4  435.00              367.00              357.00
       129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
PIWIL1  373.54              372.44              336.21
PIWIL2 9240.15             9364.36             8122.41
PIWIL4 5369.33             4892.00             4805.50
       129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1
PIWIL1 13372.73            15457.47            15421.02             425.79
PIWIL2 12207.64            12940.58            13241.52            7204.38
PIWIL4    68.00               62.00               76.00             400.00
       ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
PIWIL1 ⋯  4282.17            62.49           41.95           36.69
PIWIL2 ⋯ 12777.34          2745.50         2166.03         2595.87
PIWIL4 ⋯    60.74            67.00           55.00           74.00
       WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
PIWIL1  133.57          101.11           75.53          7693.00
PIWIL2 3329.53         2496.78         2251.50         11898.85
PIWIL4  827.00          657.50          621.43            76.17
       WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
PIWIL1  3653.61         3964.42
PIWIL2 11716.61        11079.12
PIWIL4    70.00           65.00

In [32]:
#DESeq and PCA and Dandogram 

#conda install -c bioconda bioconductor-deseq2 r-gplots r-rcolorbrewer r-ggplot2 r-tidyr r-ggrepel r-dplyr -y 
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘gplots’


The following object is masked from ‘package:rtracklayer’:

    space


The following object is masked from ‘package:IRanges’:

    space


The following object is masked from ‘package:S4Vectors’:

    space


The following object is masked from ‘package:stats’:

    lowess

In [33]:

#save results in this folder 
#mkdir -p  /mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/AKR_J
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/RNA_deSeq/all_timepoints_genes_deseq2")

In [34]:
# Now we build a DESeq2 Count dataset and normalize it.
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"
cds <- DESeqDataSetFromMatrix(countData = round(combined_dge$counts), colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)
norm_counts <-counts(cds,normalized=TRUE)
norm_counts

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates, fitting model and testing: 124 workers

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

              129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
0610007P14Rik 1225.232342         1245.457348         1300.452491
0610009B22Rik  393.468923          393.621042          397.441660
0610010F05Rik 3885.879159         3924.099002         3490.278109
0610010K14Rik  836.744038          767.056389          909.829683
0610037L13Rik  858.658763         1003.229014         1103.679904
0610040J01Rik   99.612386           63.584938           80.852102
1110002E22Rik    4.980619            6.055708            1.948243
1110004F10Rik 2821.022758         3102.541238         2727.540805
1110008F13Rik 1565.906700         1410.980043         1596.585493
1110008L16Rik 1006.085094          971.941188          995.552394
1110008P14Rik  324.736377          306.822556          365.295644
1110017D15Rik    9.961239           12.111417            5.844730
1110032A03Rik  498.061928          516.753778          516.284510
1110032F04Rik   19.922477           12.111417            5.844730
1110034G24Rik  599.666561          583.366570          652.661550
1110037F02Rik 6030.533819         6097.089011         6023.968692
1110038F14Rik  382.511560          380.500341          418.872338
1110051M20Rik 3305.138951         4121.918808         3570.156089
1110059E24Rik 1742.220623         1828.823918         1676.463473
1110059G10Rik  397.453418          454.178125          410.105242
1110065P20Rik  850.689772          850.827021          991.655907
1190002N15Rik 1226.228466         1313.079424         1083.223348
1190005I06Rik  119.534863          127.169875          107.153389
1300017J02Rik  297.841033          426.927438          336.071992
1500009C09Rik    8.965115           13.120701            7.792974
1500009L16Rik 1450.356333         1455.388570         1605.352588
1500011K16Rik  142.445711          113.039889          119.816971
1500015O10Rik  166.352684          153.411278          174.367787
1600002H07Rik  375.538693          375.453917          395.493417
1600012H06Rik  726.174290          774.121382          707.212366
⋮             ⋮                   ⋮                   ⋮
uncx          3.984495e+00            7.064993        9.741217e-01
uox           9.961239e+00            4.037139        5.844730e+00
uqcrh         1.337794e+03         1225.271654        1.375460e+03
urad          9.961239e-01            1.009285        2.922365e+00
usp18         2.649689e+02          280.581153        2.824953e+02
usp32         1.134984e+04        12960.225126        1.032179e+04
vamp2         3.675697e+02          478.400959        3.974417e+02
vdac1         2.428550e+03         2343.559126        2.400236e+03
vgf           5.976743e+00            3.027854        8.767095e+00
vhl           2.209403e+03         2075.089390        2.136249e+03
vmn2r1        1.573876e+02          140.290576        1.168946e+02
vps33a        3.343988e+03         4023.008905        3.886746e+03
vps33b        1.002101e+03         1070.851091        1.103680e+03
wdfy1         2.118755e+03         2195.194272        2.082672e+03
wdr34         5.727712e+02          728.703570        7.715044e+02
wdr82         6.255658e+03         6496.765761        6.415566e+03
wdr92         5.667945e+02          601.533695        6.098002e+02
wdr95         3.187596e+01           32.297111        3.117189e+01
wdyhv1        6.942983e+02          713.564299        7.198759e+02
wnt8a         9.961239e+00           10.092847        3.896487e+00
xylt1         2.375755e+03         2204.277835        2.295031e+03
ybx1          6.331363e+03         7117.475865        6.431152e+03
zak           1.683449e+03         1508.880661        1.499173e+03
zbtb42        8.965115e+01           83.770632        9.448981e+01
zbtb8b        1.334806e+02           98.909903        1.071534e+02
zc3h11a       3.482449e+03         3628.378579        3.462029e+03
zdhhc11       1.294961e+01            5.046424        9.741217e+00
zfpm1         1.614717e+03         1708.719036        1.690101e+03
zfyve16       3.267286e+03         3599.109322        3.328574e+03
znrd1         3.127829e+02          314.896834        3.399685e+02
              129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
0610007P14Rik 1589.17538          1559.572834         1367.583353
0610009B22Rik  441.75292           449.702868          381.960135
0610010F05Rik 1323.36688          1440.364579         1442.314684
0610010K14Rik  942.15398           818.015272          784.678973
0610037L13Rik 1391.47440          1233.188852         1202.344077
0610040J01Rik  190.13348           205.531475          242.461651
1110002E22Rik   13.24313            14.798266           11.624874
1110004F10Rik 2311.87181          2407.184638         2319.162299
1110008F13Rik 1798.22762          1764.282184         1608.384308
1110008L16Rik 1111.47683          1087.672567         1269.602275
1110008P14Rik  427.56385           365.023900          349.576558
1110017D15Rik   10.40532             8.221259            6.642785
1110032A03Rik  429.45573           363.379648          385.281528
1110032F04Rik  114.45847           179.223446          188.489023
1110034G24Rik  453.10417           503.141051          546.369063
1110037F02Rik 5869.54360          6020.427974         5649.688607
1110038F14Rik  450.26636           413.529328          416.834756
1110051M20Rik 1952.41547          2032.295228         2124.860839
1110059E24Rik 2148.22458          2002.698695         2130.673275
1110059G10Rik  380.26697           346.937130          398.567097
1110065P20Rik  646.07547           632.214818          582.074032
1190002N15Rik 1189.98966          1164.952402         1191.549552
1190005I06Rik  189.18755           171.002187          142.819877
1300017J02Rik  158.91754           189.911083          140.328832
1500009C09Rik   19.86469            14.798266           11.624874
1500009L16Rik  661.21047           731.692052          650.992926
1500011K16Rik  186.34973           144.694159          145.310921
1500015O10Rik  157.02566           138.939277          108.775604
1600002H07Rik  543.91419           489.987037          517.306879
1600012H06Rik  832.42520           749.778822          770.563055
⋮             ⋮                   ⋮                   ⋮
uncx             5.675626            4.1106295           1.660696
uox             22.702505           18.9088957          29.892532
uqcrh         1823.767939         1451.8743413        1479.680349
urad             2.837813            0.8221259           4.151741
usp18          335.807893          353.5141375         337.121337
usp32         3124.432314         3591.8680619        3815.449610
vamp2          306.483824          307.4750870         376.147698
vdac1         3390.240816         3538.4298783        3323.053175
vgf              6.621564           12.3318885           7.473133
vhl           1301.610313         1232.3667258        1198.192337
vmn2r1          60.540015           73.9913311          90.507945
vps33a        2837.813183         2653.8224088        2501.008537
vps33b         760.533933          784.3081097         739.009827
wdfy1         2415.924956         2297.0197677        2285.118026
wdr34          544.860131          508.0738069         531.422797
wdr82         5078.739659         5222.1437238        5313.397619
wdr92         1180.530284          970.1085633         933.311287
wdr95          219.457553          226.0846228         214.229815
wdyhv1         968.640233         1007.1042289        1042.086890
wnt8a            5.675626           10.6876367          14.115918
xylt1         3955.911577         5494.2673971        6208.512892
ybx1          9762.077348         9175.7471822        9229.319351
zak           1548.500060         1759.3494284        1850.015611
zbtb42          87.026271           88.7895973          91.338293
zbtb8b         248.781622          197.3102163         203.435289
zc3h11a       4247.260397         4547.1783590        4636.663901
zdhhc11         35.945634           49.3275541          39.026362
zfpm1          848.506142         1173.1736609        1226.424173
zfyve16       2682.679395         2770.5642867        2471.946353
znrd1          347.159146          304.1865834         411.852667
              129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3
0610007P14Rik 1012.957168          947.942730          980.337482
0610009B22Rik 1236.562075         1275.164067          914.638124
0610010F05Rik 6594.997734         6407.043746         6405.043311
0610010K14Rik  585.952617          528.300098          507.559748
0610037L13Rik 2382.873977         2165.655722         1961.963186
0610040J01Rik   40.410525           58.700011           38.646681
1110002E22Rik    2.694035            3.746809            3.864668
1110004F10Rik 5586.081618         5411.641433         5598.615895
1110008F13Rik 1100.513306         1066.591688         1100.142194
1110008L16Rik 1138.229797         1160.261918         1127.194871
1110008P14Rik  468.762094          467.102215          352.973022
1110017D15Rik  253.239292          297.246864          221.574306
1110032A03Rik 5509.301620         5454.105270         4521.661710
1110032F04Rik    5.388070            3.746809            2.576445
1110034G24Rik  261.321397          274.766009          332.361459
1110037F02Rik 6821.296675         6874.145960         7032.407771
1110038F14Rik  414.881393          344.706447          359.414136
1110051M20Rik 7263.118419         7318.767319         8005.015916
1110059E24Rik 1679.730836         1870.906731         1820.258688
1110059G10Rik  433.739639          419.642631          441.860389
1110065P20Rik 2455.612922         2452.911095         1889.822715
1190002N15Rik  788.005244          668.180975          684.046259
1190005I06Rik  107.761401          112.404276          105.634262
1300017J02Rik 1462.861017         1869.657795         1556.173033
1500009C09Rik   45.798595           66.193629           57.970022
1500009L16Rik  875.561382          844.281008          816.733198
1500011K16Rik  146.824909          134.885131          124.957603
1500015O10Rik   95.638243          107.408531          104.346039
1600002H07Rik  203.399644          189.838333          181.639402
1600012H06Rik  886.337522          780.585252          798.698080
⋮             ⋮                   ⋮                   ⋮
uncx              0.000000            0.000000            0.000000
uox              39.063508           51.206393           27.052677
uqcrh          1484.413297         1427.534308         1426.062539
urad              0.000000            0.000000            1.288223
usp18           148.171926          117.400022          131.398716
usp32         18124.120610        19139.950370        19833.476834
vamp2           448.556831          448.368169          524.306643
vdac1          1418.409439         1302.640668         1352.633845
vgf               1.347018            4.995746            2.576445
vhl            2167.351175         2141.925931         1780.323784
vmn2r1          140.089821          143.627686          136.551607
vps33a        10487.878340         9844.116726         9423.349119
vps33b         1163.823129         1004.144868         1020.272386
wdfy1          5883.772488         6122.286246         5364.159362
wdr34          2459.653975         2310.532345         2189.978606
wdr82          4662.027605         4691.005128         4865.617173
wdr92          1970.686618         1838.434385         1758.423998
wdr95           113.149471          214.817061          130.110494
wdyhv1          274.791572          266.023454          265.373878
wnt8a             9.429123           14.987237           12.882227
xylt1           638.486300          663.185230          814.156752
ybx1          33345.418483        32777.086951        29459.076918
zak            1658.178556         1728.527981         1695.301086
zbtb42         2491.982395         2552.826007         1581.937487
zbtb8b           52.533683           49.957456           48.952463
zc3h11a        3061.770802         3187.285700         3221.844996
zdhhc11         266.709467          507.068179          266.662101
zfpm1          1476.331192         1529.947093         1351.345622
zfyve16        4253.881300         4377.522091         4368.363208
znrd1           519.948759          528.300098          486.948184
              A_J-P12.5.1  ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2
0610007P14Rik 3344.253430  ⋯  607.830659       1379.294891     1400.666675
0610009B22Rik  401.000246  ⋯  507.807892        475.430489      473.416121
0610010F05Rik 4000.032837  ⋯ 4276.797640       3641.688253     3062.806487
0610010K14Rik  765.445220  ⋯  839.751580        715.878093      688.814697
0610037L13Rik  939.359692  ⋯ 1070.573349       1028.459978     1000.969852
0610040J01Rik   58.709981  ⋯   15.388118         49.182464      105.971492
1110002E22Rik    0.000000  ⋯    1.099151          4.371775        2.303728
1110004F10Rik 3006.394107  ⋯ 4064.661442       3219.812003     3060.502759
1110008F13Rik 1343.683144  ⋯ 1694.891277       1934.510267     1971.991240
1110008L16Rik 1142.075285  ⋯ 1388.228070       1113.709583     1231.342661
1110008P14Rik  301.304052  ⋯  358.323318        321.325434      299.484651
1110017D15Rik   24.370181  ⋯   96.725313         13.115324       16.126097
1110032A03Rik  520.635678  ⋯ 1475.061021        463.408109      526.401867
1110032F04Rik    5.538677  ⋯    6.594908         34.974197       69.111843
1110034G24Rik  731.105420  ⋯  305.564057        621.884939      601.273030
1110037F02Rik 6598.780286  ⋯ 9734.083757       7318.350703     7180.720437
1110038F14Rik  356.690826  ⋯  596.839146        523.520010      375.507678
1110051M20Rik 4578.270761  ⋯ 3715.131335       2882.092414     3008.668878
1110059E24Rik 1832.194493  ⋯ 1045.292870       2204.467349     2327.917229
1110059G10Rik  420.939484  ⋯  604.533205        433.898630      400.848687
1110065P20Rik  921.635924  ⋯ 1253.032462        989.114006      967.565795
1190002N15Rik 1222.939976  ⋯  786.992318       1400.060820     1387.996171
1190005I06Rik  124.066374  ⋯   48.362656         30.602422       32.252193
1300017J02Rik  206.038800  ⋯  119.807490        378.158504      216.550440
1500009C09Rik    4.430942  ⋯    7.694059         17.487098       16.126097
1500009L16Rik 1395.746711  ⋯  586.946785       2693.013162     2617.035103
1500011K16Rik  151.759761  ⋯  111.014280        136.617957      142.831141
1500015O10Rik  145.113349  ⋯  159.376936        190.172196      222.309760
1600002H07Rik  404.323452  ⋯  312.158964        369.414955      391.633774
1600012H06Rik  773.199369  ⋯  434.164757        559.587151      550.591012
⋮             ⋮            ⋱ ⋮                 ⋮               ⋮
uncx              0.000000 ⋯     7.694059          1.092944        0.000000
uox               7.754148 ⋯     9.892362          2.185887       19.581689
uqcrh          1341.467673 ⋯  2190.608506       1836.145338     1971.991240
urad              1.107735 ⋯     0.000000          0.000000        0.000000
usp18           281.364813 ⋯   137.393910        382.530279      309.851427
usp32         12600.491145 ⋯ 11097.031347      12941.545800    11918.337242
vamp2           402.107981 ⋯   478.130808        502.754081      513.731363
vdac1          2383.846764 ⋯  1914.721534       3670.104788     3791.936426
vgf               3.323206 ⋯    14.288967          9.836493        4.607456
vhl            2029.371409 ⋯  1890.540206       2338.899418     2329.069093
vmn2r1          146.221084 ⋯     4.396605        237.168773      261.473138
vps33a         3748.576882 ⋯  1643.231167       2666.782514     2549.075125
vps33b         1076.718892 ⋯   899.105749        878.726697      830.493974
wdfy1          2304.089809 ⋯  2543.436068       2460.216164     2873.900785
wdr34           708.950711 ⋯  1537.712644        478.709320      400.848687
wdr82          5989.525769 ⋯  7051.055477       9338.110575     9307.061459
wdr92           671.287704 ⋯   969.451431        709.320431      717.611298
wdr95            44.309419 ⋯   923.287077         14.208267       38.011513
wdyhv1          652.456201 ⋯   379.207192        437.177461      479.175441
wnt8a             7.754148 ⋯    13.189815          5.464718        8.063048
xylt1          5153.185477 ⋯  1710.279395       6715.045806     8493.845445
ybx1           7948.002107 ⋯  6125.570097       7005.768818     6119.853655
zak            1748.006596 ⋯   907.898959       2014.295153     2528.341572
zbtb42           56.494510 ⋯   189.054021         48.089521       46.074562
zbtb8b          142.897878 ⋯    59.354169         89.621380       79.478619
zc3h11a        4238.195967 ⋯  2932.535621       4084.330433     4561.381606
zdhhc11           9.969619 ⋯    70.345682         10.929437        2.303728
zfpm1          1689.296615 ⋯  1333.270506       2194.630856     2355.561966
zfyve16        3713.129347 ⋯  5518.838589       4294.175614     3827.644211
znrd1           317.920084 ⋯   591.343390        288.537124      299.484651
              WSB_EiJ-P12.5.3 WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3
0610007P14Rik 1366.939509     1590.939452     1452.054410     1719.586665
0610009B22Rik  473.585342      537.725406      515.019298      656.866718
0610010F05Rik 3324.784364     1638.445268     1674.062729     1935.977604
0610010K14Rik  669.477460      743.920862      626.023458      598.200730
0610037L13Rik 1130.146838     1508.056964     1509.056546     1408.945450
0610040J01Rik   58.121837      143.528210       94.003522      101.944176
1110002E22Rik    2.152661       22.236765       20.000749       13.464325
1110004F10Rik 3062.159766     3201.083382     3163.118525     3178.542465
1110008F13Rik 2014.890363     1662.703557     1596.059806     1704.198865
1110008L16Rik 1260.382807     1078.483097     1018.038147     1020.403496
1110008P14Rik  317.517445      306.260898      283.010605      276.980402
1110017D15Rik   10.763303       17.182955       12.000450        3.846950
1110032A03Rik  514.485894      402.283292      364.013640      388.541953
1110032F04Rik   53.816516      107.140776      121.004534      123.102401
1110034G24Rik  567.226080      388.132624      421.015776      430.858404
1110037F02Rik 7176.970586     6146.443968     6213.232815     6252.255541
1110038F14Rik  432.684789      487.187304      502.018811      458.748791
1110051M20Rik 2956.679394     2331.828027     2584.096828     2404.343770
1110059E24Rik 2361.468726     2130.686381     2347.087947     2416.846358
1110059G10Rik  396.089558      446.756822      421.015776      434.705354
1110065P20Rik  983.765914      713.598001      671.025144      754.963944
1190002N15Rik 1341.107581     1412.034571     1620.060705     1690.734539
1190005I06Rik   43.053213       36.387433       31.001162       44.239925
1300017J02Rik  217.418725      190.023264      170.006370      115.408501
1500009C09Rik    9.686973        7.075334        5.000187        4.808688
1500009L16Rik 2710.199750     1470.658769     1409.052798     1379.131587
1500011K16Rik  186.205146      193.055550      184.006895      202.926614
1500015O10Rik  213.113404      202.152408      132.004946      161.571901
1600002H07Rik  370.257631      557.940646      612.022933      568.386867
1600012H06Rik  547.852134      529.639309      519.019448      559.731230
⋮             ⋮               ⋮               ⋮               ⋮
uncx              1.076330        0.000000       0.000000        0.9617375
uox              10.763303       25.269051       7.000262        8.6556376
uqcrh          1947.081552     2362.150889    2258.084612     2524.5609590
urad              0.000000        1.010762       0.000000        0.0000000
usp18           340.120382      318.390043     373.013977      339.4933404
usp32         11248.728194     3327.428637    3835.143706     3714.2302566
vamp2           421.921486      384.089575     382.014314      308.7177401
vdac1          3769.308787     4243.179046    4141.155173     4258.5736863

In [35]:
norm_counts

              129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
0610007P14Rik 1225.232342         1245.457348         1300.452491
0610009B22Rik  393.468923          393.621042          397.441660
0610010F05Rik 3885.879159         3924.099002         3490.278109
0610010K14Rik  836.744038          767.056389          909.829683
0610037L13Rik  858.658763         1003.229014         1103.679904
0610040J01Rik   99.612386           63.584938           80.852102
1110002E22Rik    4.980619            6.055708            1.948243
1110004F10Rik 2821.022758         3102.541238         2727.540805
1110008F13Rik 1565.906700         1410.980043         1596.585493
1110008L16Rik 1006.085094          971.941188          995.552394
1110008P14Rik  324.736377          306.822556          365.295644
1110017D15Rik    9.961239           12.111417            5.844730
1110032A03Rik  498.061928          516.753778          516.284510
1110032F04Rik   19.922477           12.111417            5.844730
1110034G24Rik  599.666561          583.366570          652.661550
1110037F02Rik 6030.533819         6097.089011         6023.968692
1110038F14Rik  382.511560          380.500341          418.872338
1110051M20Rik 3305.138951         4121.918808         3570.156089
1110059E24Rik 1742.220623         1828.823918         1676.463473
1110059G10Rik  397.453418          454.178125          410.105242
1110065P20Rik  850.689772          850.827021          991.655907
1190002N15Rik 1226.228466         1313.079424         1083.223348
1190005I06Rik  119.534863          127.169875          107.153389
1300017J02Rik  297.841033          426.927438          336.071992
1500009C09Rik    8.965115           13.120701            7.792974
1500009L16Rik 1450.356333         1455.388570         1605.352588
1500011K16Rik  142.445711          113.039889          119.816971
1500015O10Rik  166.352684          153.411278          174.367787
1600002H07Rik  375.538693          375.453917          395.493417
1600012H06Rik  726.174290          774.121382          707.212366
⋮             ⋮                   ⋮                   ⋮
uncx          3.984495e+00            7.064993        9.741217e-01
uox           9.961239e+00            4.037139        5.844730e+00
uqcrh         1.337794e+03         1225.271654        1.375460e+03
urad          9.961239e-01            1.009285        2.922365e+00
usp18         2.649689e+02          280.581153        2.824953e+02
usp32         1.134984e+04        12960.225126        1.032179e+04
vamp2         3.675697e+02          478.400959        3.974417e+02
vdac1         2.428550e+03         2343.559126        2.400236e+03
vgf           5.976743e+00            3.027854        8.767095e+00
vhl           2.209403e+03         2075.089390        2.136249e+03
vmn2r1        1.573876e+02          140.290576        1.168946e+02
vps33a        3.343988e+03         4023.008905        3.886746e+03
vps33b        1.002101e+03         1070.851091        1.103680e+03
wdfy1         2.118755e+03         2195.194272        2.082672e+03
wdr34         5.727712e+02          728.703570        7.715044e+02
wdr82         6.255658e+03         6496.765761        6.415566e+03
wdr92         5.667945e+02          601.533695        6.098002e+02
wdr95         3.187596e+01           32.297111        3.117189e+01
wdyhv1        6.942983e+02          713.564299        7.198759e+02
wnt8a         9.961239e+00           10.092847        3.896487e+00
xylt1         2.375755e+03         2204.277835        2.295031e+03
ybx1          6.331363e+03         7117.475865        6.431152e+03
zak           1.683449e+03         1508.880661        1.499173e+03
zbtb42        8.965115e+01           83.770632        9.448981e+01
zbtb8b        1.334806e+02           98.909903        1.071534e+02
zc3h11a       3.482449e+03         3628.378579        3.462029e+03
zdhhc11       1.294961e+01            5.046424        9.741217e+00
zfpm1         1.614717e+03         1708.719036        1.690101e+03
zfyve16       3.267286e+03         3599.109322        3.328574e+03
znrd1         3.127829e+02          314.896834        3.399685e+02
              129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
0610007P14Rik 1589.17538          1559.572834         1367.583353
0610009B22Rik  441.75292           449.702868          381.960135
0610010F05Rik 1323.36688          1440.364579         1442.314684
0610010K14Rik  942.15398           818.015272          784.678973
0610037L13Rik 1391.47440          1233.188852         1202.344077
0610040J01Rik  190.13348           205.531475          242.461651
1110002E22Rik   13.24313            14.798266           11.624874
1110004F10Rik 2311.87181          2407.184638         2319.162299
1110008F13Rik 1798.22762          1764.282184         1608.384308
1110008L16Rik 1111.47683          1087.672567         1269.602275
1110008P14Rik  427.56385           365.023900          349.576558
1110017D15Rik   10.40532             8.221259            6.642785
1110032A03Rik  429.45573           363.379648          385.281528
1110032F04Rik  114.45847           179.223446          188.489023
1110034G24Rik  453.10417           503.141051          546.369063
1110037F02Rik 5869.54360          6020.427974         5649.688607
1110038F14Rik  450.26636           413.529328          416.834756
1110051M20Rik 1952.41547          2032.295228         2124.860839
1110059E24Rik 2148.22458          2002.698695         2130.673275
1110059G10Rik  380.26697           346.937130          398.567097
1110065P20Rik  646.07547           632.214818          582.074032
1190002N15Rik 1189.98966          1164.952402         1191.549552
1190005I06Rik  189.18755           171.002187          142.819877
1300017J02Rik  158.91754           189.911083          140.328832
1500009C09Rik   19.86469            14.798266           11.624874
1500009L16Rik  661.21047           731.692052          650.992926
1500011K16Rik  186.34973           144.694159          145.310921
1500015O10Rik  157.02566           138.939277          108.775604
1600002H07Rik  543.91419           489.987037          517.306879
1600012H06Rik  832.42520           749.778822          770.563055
⋮             ⋮                   ⋮                   ⋮
uncx             5.675626            4.1106295           1.660696
uox             22.702505           18.9088957          29.892532
uqcrh         1823.767939         1451.8743413        1479.680349
urad             2.837813            0.8221259           4.151741
usp18          335.807893          353.5141375         337.121337
usp32         3124.432314         3591.8680619        3815.449610
vamp2          306.483824          307.4750870         376.147698
vdac1         3390.240816         3538.4298783        3323.053175
vgf              6.621564           12.3318885           7.473133
vhl           1301.610313         1232.3667258        1198.192337
vmn2r1          60.540015           73.9913311          90.507945
vps33a        2837.813183         2653.8224088        2501.008537
vps33b         760.533933          784.3081097         739.009827
wdfy1         2415.924956         2297.0197677        2285.118026
wdr34          544.860131          508.0738069         531.422797
wdr82         5078.739659         5222.1437238        5313.397619
wdr92         1180.530284          970.1085633         933.311287
wdr95          219.457553          226.0846228         214.229815
wdyhv1         968.640233         1007.1042289        1042.086890
wnt8a            5.675626           10.6876367          14.115918
xylt1         3955.911577         5494.2673971        6208.512892
ybx1          9762.077348         9175.7471822        9229.319351
zak           1548.500060         1759.3494284        1850.015611
zbtb42          87.026271           88.7895973          91.338293
zbtb8b         248.781622          197.3102163         203.435289
zc3h11a       4247.260397         4547.1783590        4636.663901
zdhhc11         35.945634           49.3275541          39.026362
zfpm1          848.506142         1173.1736609        1226.424173
zfyve16       2682.679395         2770.5642867        2471.946353
znrd1          347.159146          304.1865834         411.852667
              129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3
0610007P14Rik 1012.957168          947.942730          980.337482
0610009B22Rik 1236.562075         1275.164067          914.638124
0610010F05Rik 6594.997734         6407.043746         6405.043311
0610010K14Rik  585.952617          528.300098          507.559748
0610037L13Rik 2382.873977         2165.655722         1961.963186
0610040J01Rik   40.410525           58.700011           38.646681
1110002E22Rik    2.694035            3.746809            3.864668
1110004F10Rik 5586.081618         5411.641433         5598.615895
1110008F13Rik 1100.513306         1066.591688         1100.142194
1110008L16Rik 1138.229797         1160.261918         1127.194871
1110008P14Rik  468.762094          467.102215          352.973022
1110017D15Rik  253.239292          297.246864          221.574306
1110032A03Rik 5509.301620         5454.105270         4521.661710
1110032F04Rik    5.388070            3.746809            2.576445
1110034G24Rik  261.321397          274.766009          332.361459
1110037F02Rik 6821.296675         6874.145960         7032.407771
1110038F14Rik  414.881393          344.706447          359.414136
1110051M20Rik 7263.118419         7318.767319         8005.015916
1110059E24Rik 1679.730836         1870.906731         1820.258688
1110059G10Rik  433.739639          419.642631          441.860389
1110065P20Rik 2455.612922         2452.911095         1889.822715
1190002N15Rik  788.005244          668.180975          684.046259
1190005I06Rik  107.761401          112.404276          105.634262
1300017J02Rik 1462.861017         1869.657795         1556.173033
1500009C09Rik   45.798595           66.193629           57.970022
1500009L16Rik  875.561382          844.281008          816.733198
1500011K16Rik  146.824909          134.885131          124.957603
1500015O10Rik   95.638243          107.408531          104.346039
1600002H07Rik  203.399644          189.838333          181.639402
1600012H06Rik  886.337522          780.585252          798.698080
⋮             ⋮                   ⋮                   ⋮
uncx              0.000000            0.000000            0.000000
uox              39.063508           51.206393           27.052677
uqcrh          1484.413297         1427.534308         1426.062539
urad              0.000000            0.000000            1.288223
usp18           148.171926          117.400022          131.398716
usp32         18124.120610        19139.950370        19833.476834
vamp2           448.556831          448.368169          524.306643
vdac1          1418.409439         1302.640668         1352.633845
vgf               1.347018            4.995746            2.576445
vhl            2167.351175         2141.925931         1780.323784
vmn2r1          140.089821          143.627686          136.551607
vps33a        10487.878340         9844.116726         9423.349119
vps33b         1163.823129         1004.144868         1020.272386
wdfy1          5883.772488         6122.286246         5364.159362
wdr34          2459.653975         2310.532345         2189.978606
wdr82          4662.027605         4691.005128         4865.617173
wdr92          1970.686618         1838.434385         1758.423998
wdr95           113.149471          214.817061          130.110494
wdyhv1          274.791572          266.023454          265.373878
wnt8a             9.429123           14.987237           12.882227
xylt1           638.486300          663.185230          814.156752
ybx1          33345.418483        32777.086951        29459.076918
zak            1658.178556         1728.527981         1695.301086
zbtb42         2491.982395         2552.826007         1581.937487
zbtb8b           52.533683           49.957456           48.952463
zc3h11a        3061.770802         3187.285700         3221.844996
zdhhc11         266.709467          507.068179          266.662101
zfpm1          1476.331192         1529.947093         1351.345622
zfyve16        4253.881300         4377.522091         4368.363208
znrd1           519.948759          528.300098          486.948184
              A_J-P12.5.1  ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2
0610007P14Rik 3344.253430  ⋯  607.830659       1379.294891     1400.666675
0610009B22Rik  401.000246  ⋯  507.807892        475.430489      473.416121
0610010F05Rik 4000.032837  ⋯ 4276.797640       3641.688253     3062.806487
0610010K14Rik  765.445220  ⋯  839.751580        715.878093      688.814697
0610037L13Rik  939.359692  ⋯ 1070.573349       1028.459978     1000.969852
0610040J01Rik   58.709981  ⋯   15.388118         49.182464      105.971492
1110002E22Rik    0.000000  ⋯    1.099151          4.371775        2.303728
1110004F10Rik 3006.394107  ⋯ 4064.661442       3219.812003     3060.502759
1110008F13Rik 1343.683144  ⋯ 1694.891277       1934.510267     1971.991240
1110008L16Rik 1142.075285  ⋯ 1388.228070       1113.709583     1231.342661
1110008P14Rik  301.304052  ⋯  358.323318        321.325434      299.484651
1110017D15Rik   24.370181  ⋯   96.725313         13.115324       16.126097
1110032A03Rik  520.635678  ⋯ 1475.061021        463.408109      526.401867
1110032F04Rik    5.538677  ⋯    6.594908         34.974197       69.111843
1110034G24Rik  731.105420  ⋯  305.564057        621.884939      601.273030
1110037F02Rik 6598.780286  ⋯ 9734.083757       7318.350703     7180.720437
1110038F14Rik  356.690826  ⋯  596.839146        523.520010      375.507678
1110051M20Rik 4578.270761  ⋯ 3715.131335       2882.092414     3008.668878
1110059E24Rik 1832.194493  ⋯ 1045.292870       2204.467349     2327.917229
1110059G10Rik  420.939484  ⋯  604.533205        433.898630      400.848687
1110065P20Rik  921.635924  ⋯ 1253.032462        989.114006      967.565795
1190002N15Rik 1222.939976  ⋯  786.992318       1400.060820     1387.996171
1190005I06Rik  124.066374  ⋯   48.362656         30.602422       32.252193
1300017J02Rik  206.038800  ⋯  119.807490        378.158504      216.550440
1500009C09Rik    4.430942  ⋯    7.694059         17.487098       16.126097
1500009L16Rik 1395.746711  ⋯  586.946785       2693.013162     2617.035103
1500011K16Rik  151.759761  ⋯  111.014280        136.617957      142.831141
1500015O10Rik  145.113349  ⋯  159.376936        190.172196      222.309760
1600002H07Rik  404.323452  ⋯  312.158964        369.414955      391.633774
1600012H06Rik  773.199369  ⋯  434.164757        559.587151      550.591012
⋮             ⋮            ⋱ ⋮                 ⋮               ⋮
uncx              0.000000 ⋯     7.694059          1.092944        0.000000
uox               7.754148 ⋯     9.892362          2.185887       19.581689
uqcrh          1341.467673 ⋯  2190.608506       1836.145338     1971.991240
urad              1.107735 ⋯     0.000000          0.000000        0.000000
usp18           281.364813 ⋯   137.393910        382.530279      309.851427
usp32         12600.491145 ⋯ 11097.031347      12941.545800    11918.337242
vamp2           402.107981 ⋯   478.130808        502.754081      513.731363
vdac1          2383.846764 ⋯  1914.721534       3670.104788     3791.936426
vgf               3.323206 ⋯    14.288967          9.836493        4.607456
vhl            2029.371409 ⋯  1890.540206       2338.899418     2329.069093
vmn2r1          146.221084 ⋯     4.396605        237.168773      261.473138
vps33a         3748.576882 ⋯  1643.231167       2666.782514     2549.075125
vps33b         1076.718892 ⋯   899.105749        878.726697      830.493974
wdfy1          2304.089809 ⋯  2543.436068       2460.216164     2873.900785
wdr34           708.950711 ⋯  1537.712644        478.709320      400.848687
wdr82          5989.525769 ⋯  7051.055477       9338.110575     9307.061459
wdr92           671.287704 ⋯   969.451431        709.320431      717.611298
wdr95            44.309419 ⋯   923.287077         14.208267       38.011513
wdyhv1          652.456201 ⋯   379.207192        437.177461      479.175441
wnt8a             7.754148 ⋯    13.189815          5.464718        8.063048
xylt1          5153.185477 ⋯  1710.279395       6715.045806     8493.845445
ybx1           7948.002107 ⋯  6125.570097       7005.768818     6119.853655
zak            1748.006596 ⋯   907.898959       2014.295153     2528.341572
zbtb42           56.494510 ⋯   189.054021         48.089521       46.074562
zbtb8b          142.897878 ⋯    59.354169         89.621380       79.478619
zc3h11a        4238.195967 ⋯  2932.535621       4084.330433     4561.381606
zdhhc11           9.969619 ⋯    70.345682         10.929437        2.303728
zfpm1          1689.296615 ⋯  1333.270506       2194.630856     2355.561966
zfyve16        3713.129347 ⋯  5518.838589       4294.175614     3827.644211
znrd1           317.920084 ⋯   591.343390        288.537124      299.484651
              WSB_EiJ-P12.5.3 WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3
0610007P14Rik 1366.939509     1590.939452     1452.054410     1719.586665
0610009B22Rik  473.585342      537.725406      515.019298      656.866718
0610010F05Rik 3324.784364     1638.445268     1674.062729     1935.977604
0610010K14Rik  669.477460      743.920862      626.023458      598.200730
0610037L13Rik 1130.146838     1508.056964     1509.056546     1408.945450
0610040J01Rik   58.121837      143.528210       94.003522      101.944176
1110002E22Rik    2.152661       22.236765       20.000749       13.464325
1110004F10Rik 3062.159766     3201.083382     3163.118525     3178.542465
1110008F13Rik 2014.890363     1662.703557     1596.059806     1704.198865
1110008L16Rik 1260.382807     1078.483097     1018.038147     1020.403496
1110008P14Rik  317.517445      306.260898      283.010605      276.980402
1110017D15Rik   10.763303       17.182955       12.000450        3.846950
1110032A03Rik  514.485894      402.283292      364.013640      388.541953
1110032F04Rik   53.816516      107.140776      121.004534      123.102401
1110034G24Rik  567.226080      388.132624      421.015776      430.858404
1110037F02Rik 7176.970586     6146.443968     6213.232815     6252.255541
1110038F14Rik  432.684789      487.187304      502.018811      458.748791
1110051M20Rik 2956.679394     2331.828027     2584.096828     2404.343770
1110059E24Rik 2361.468726     2130.686381     2347.087947     2416.846358
1110059G10Rik  396.089558      446.756822      421.015776      434.705354
1110065P20Rik  983.765914      713.598001      671.025144      754.963944
1190002N15Rik 1341.107581     1412.034571     1620.060705     1690.734539
1190005I06Rik   43.053213       36.387433       31.001162       44.239925
1300017J02Rik  217.418725      190.023264      170.006370      115.408501
1500009C09Rik    9.686973        7.075334        5.000187        4.808688
1500009L16Rik 2710.199750     1470.658769     1409.052798     1379.131587
1500011K16Rik  186.205146      193.055550      184.006895      202.926614
1500015O10Rik  213.113404      202.152408      132.004946      161.571901
1600002H07Rik  370.257631      557.940646      612.022933      568.386867
1600012H06Rik  547.852134      529.639309      519.019448      559.731230
⋮             ⋮               ⋮               ⋮               ⋮
uncx              1.076330        0.000000       0.000000        0.9617375
uox              10.763303       25.269051       7.000262        8.6556376
uqcrh          1947.081552     2362.150889    2258.084612     2524.5609590
urad              0.000000        1.010762       0.000000        0.0000000
usp18           340.120382      318.390043     373.013977      339.4933404
usp32         11248.728194     3327.428637    3835.143706     3714.2302566
vamp2           421.921486      384.089575     382.014314      308.7177401
vdac1          3769.308787     4243.179046    4141.155173     4258.5736863

In [36]:
other_gene_list <- c('MORC3','TCFL5','Ddx4','Mael','Gtsf1','Mybl1','Mov10l1','Pld6','Asz1','Henmt1','Tdrd1','Tdrd5','Tdrd6','Tdrd9','Tdrd12','Tdrkh','Gpat2','Rnf17','Tcfl5','Tex15','Tex19.1','Tex19.2','Spocd1','Fkbp6')
other_gene_sub <- subset(norm_counts, tolower(row.names(norm_counts)) %in% tolower(other_gene_list))
other_gene_sub

# Desired order
desired_gene_order <- c("DDX4", "TDRD1", "TDRD9","RNF17" , "MAEL","TEX15","FKBP6", "TCFL5" ,"TDRD5", "MYBL1", "TDRD12", "GPAT2", "ASZ1", "PLD6" , "TDRKH", "Tex19.2", "HENMT1", "GTSF1" , "Tex19.1", "TDRD6",'MORC3')


# Reorder dataframe by raw 
other_gene_sub <- other_gene_sub[desired_gene_order, ]

library(gplots)
library(RColorBrewer)


samplenames_order <- c(
'C57BL_6NJ-E16.5','C57BL_6NJ-E16.5','C57BL_6NJ-E16.5',
'BALB_cJ-E16.5','BALB_cJ-E16.5','BALB_cJ-E16.5',
'A_J-E16.5','A_J-E16.5','A_J-E16.5',
'FVB_NJ-E16.5','FVB_NJ-E16.5','FVB_NJ-E16.5',
'C3H_HeJ-E16.5','C3H_HeJ-E16.5','C3H_HeJ-E16.5',
'LP_J-E16.5','LP_J-E16.5','LP_J-E16.5',
'129S1_SvImJ-E16.5','129S1_SvImJ-E16.5','129S1_SvImJ-E16.5',
'DBA_2J-E16.5','DBA_2J-E16.5','DBA_2J-E16.5',
'AKR_J-E16.5','AKR_J-E16.5','AKR_J-E16.5',
'CBA_J-E16.5','CBA_J-E16.5','CBA_J-E16.5',
'NZO_HlLtJ-E16.5','NZO_HlLtJ-E16.5',#'NZO_HlLtJ-E16.5',
'NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5','NOD_ShiLtJ-E16.5',
'WSB_EiJ-E16.5','WSB_EiJ-E16.5','WSB_EiJ-E16.5',
'CAST_EiJ-E16.5','CAST_EiJ-E16.5','CAST_EiJ-E16.5',
'PWK_PhJ-E16.5','PWK_PhJ-E16.5','PWK_PhJ-E16.5',
'SPRET_EiJ-E16.5','SPRET_EiJ-E16.5','SPRET_EiJ-E16.5',
'C57BL_6NJ-P12.5','C57BL_6NJ-P12.5','C57BL_6NJ-P12.5',
'BALB_cJ-P12.5','BALB_cJ-P12.5','BALB_cJ-P12.5',
'A_J-P12.5','A_J-P12.5','A_J-P12.5',
'FVB_NJ-P12.5','FVB_NJ-P12.5','FVB_NJ-P12.5',
'C3H_HeJ-P12.5','C3H_HeJ-P12.5','C3H_HeJ-P12.5',
'LP_J-P12.5','LP_J-P12.5','LP_J-P12.5',
'129S1_SvImJ-P12.5','129S1_SvImJ-P12.5','129S1_SvImJ-P12.5',
'DBA_2J-P12.5','DBA_2J-P12.5','DBA_2J-P12.5',
'AKR_J-P12.5','AKR_J-P12.5','AKR_J-P12.5',
'CBA_J-P12.5','CBA_J-P12.5','CBA_J-P12.5',
'NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5','NZO_HlLtJ-P12.5',
'NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5','NOD_ShiLtJ-P12.5',
'WSB_EiJ-P12.5','WSB_EiJ-P12.5','WSB_EiJ-P12.5',
'CAST_EiJ-P12.5','CAST_EiJ-P12.5','CAST_EiJ-P12.5',
'PWK_PhJ-P12.5','PWK_PhJ-P12.5','PWK_PhJ-P12.5',
'SPRET_EiJ-P12.5','SPRET_EiJ-P12.5','SPRET_EiJ-P12.5',
'C57BL_6NJ-P20.5','C57BL_6NJ-P20.5','C57BL_6NJ-P20.5',
'BALB_cJ-P20.5','BALB_cJ-P20.5','BALB_cJ-P20.5',
'A_J-P20.5','A_J-P20.5','A_J-P20.5',
'FVB_NJ-P20.5','FVB_NJ-P20.5','FVB_NJ-P20.5',
'C3H_HeJ-P20.5','C3H_HeJ-P20.5','C3H_HeJ-P20.5',
'LP_J-P20.5','LP_J-P20.5','LP_J-P20.5',
'129S1_SvImJ-P20.5','129S1_SvImJ-P20.5','129S1_SvImJ-P20.5',
'DBA_2J-P20.5','DBA_2J-P20.5','DBA_2J-P20.5',
'AKR_J-P20.5','AKR_J-P20.5','AKR_J-P20.5',
'CBA_J-P20.5','CBA_J-P20.5','CBA_J-P20.5',
'NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5','NZO_HlLtJ-P20.5',
'NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5','NOD_ShiLtJ-P20.5',
'WSB_EiJ-P20.5','WSB_EiJ-P20.5','WSB_EiJ-P20.5',
'CAST_EiJ-P20.5','CAST_EiJ-P20.5','CAST_EiJ-P20.5',
'PWK_PhJ-P20.5','PWK_PhJ-P20.5','PWK_PhJ-P20.5',
'SPRET_EiJ-P20.5','SPRET_EiJ-P20.5','SPRET_EiJ-P20.5')




# Remove duplicates from the samplenames_order vector
unique_samplenames_order <- unique(samplenames_order)
unique_samplenames_order
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)
# Create a heatmap with log-normalized values
#heatmap.2(log2(piwi_sub_1+ 1), scale = "none", col = colorRampPalette(c("blue", "white", "red"))(100))

other_gene_sub <- as.data.frame.matrix(other_gene_sub) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate


foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(other_gene_sub), ncol = 0))

row.names(foo_sub1_mean) <- row.names(other_gene_sub)

for (sample in unique_samplenames_order) {
foo_sub1_mean[sample] <- apply(other_gene_sub[ , grepl(paste0( "^",sample) , names( other_gene_sub) ) ], 1, mean)
}

foo_sub1_mean

# Calculate Z-scores row-wise
z_scores <- t(scale(t(foo_sub1_mean)))

# Convert the matrix to a data frame
z_scores_df <- as.data.frame(z_scores)
z_scores_df

# Create a vector to specify column breaks
#col_breaks <- rep(1:length(myCol), each = 16)
# Create a PDF graphics device
pdf("z-score_heatmap_other_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
myCol <- colorRampPalette(brewer.pal(11, "RdBu"))(100)
# Define a color palette using RColorBrewer

#myCol <- brewer.pal(11, "BrBG")  # Using "BrBG" palette
#col_breaks <- seq(-1, 1, length.out = length(myCol) + 1)  # Adjust as per your data range

heatmap.2(t(scale(t(foo_sub1_mean))),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          #col = myCol,
          col = rev(myCol),#myCol[col_breaks],  , # Use the custom color palette
          main = "Piwi Pathways Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)  # Add white space every 16 columns
)
dev.off()


# Create a PDF graphics device
pdf("log10_heatmap_other_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a blue color palette
myCol <- colorRampPalette(brewer.pal(11, "GnBu"))(100)


heatmap.2(log10(as.matrix(foo_sub1_mean) + 1),
          Rowv = TRUE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = myCol,
          main = "Piwi Pathways Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)  # Add white space every 16 columns
)
dev.off()

        129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
ASZ1     1793.0229           2155.8322           1765.10855
DDX4     5638.0610           7293.0914           5985.97795
FKBP6    5974.7509           5988.0863           6444.78927
GPAT2    2552.0693           2984.4549           3181.48152
GTSF1     481.1278            638.8772            479.26788
HENMT1    320.7519            318.9340            303.92598
MAEL     5474.6967           6453.3665           6267.49912
MORC3    5115.0960           4835.4831           4884.24628
MYBL1    3226.4452           4440.8528           3367.53877
PLD6     1630.6548           1713.7655           1768.03091
RNF17   11253.2112          13174.1935          11198.50325
TCFL5    1656.5540           1933.7895           1712.50598
TDRD1    2603.8678           3156.0333           2871.71082
TDRD12   2093.8523           2910.7771           2537.58707
TDRD5     965.2440           1522.0014           1249.79816
TDRD6      41.8372            128.1792             51.62845
TDRD9    3530.2629           4863.7431           4202.36108
TDRKH     994.1316           1155.6310            987.75942
TEX15   10222.2230          10662.0838           9383.71449
Tex19.1  1124.6238           1042.5911           1253.69465
Tex19.2   607.6356            651.9979            800.72805
        129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
ASZ1     1409.44721          1152.62051          1190.71920
DDX4     3700.50839          3441.41902          2887.12041
FKBP6    5218.73844          3941.27157          3749.85211
GPAT2    3081.86512          2395.67488          2295.08220
GTSF1     443.64479           408.59657           407.70093
HENMT1    332.97008           316.51847           259.06861
MAEL     8094.38913          6611.53650          6644.44565
MORC3    3711.85964          3744.78348          3623.63919
MYBL1    1535.25693          1691.93510          1678.13355
PLD6     1707.41760          1793.87872          1726.29374
RNF17    4697.52675          4317.80523          4216.50775
TCFL5    1880.52420          1562.03921          1531.16193
TDRD1    4880.09274          3836.03945          3575.47900
TDRD12   1004.58587           791.70724           817.06255
TDRD5    1979.84766          1927.88524          1839.22109
TDRD6      60.54001            55.90456            46.49949
TDRD9   13006.64375         11485.92096         10009.01624
TDRKH     450.26636           417.63996           392.75466
TEX15    7278.04488          6646.06578          6907.66601
Tex19.1  1631.74258          1206.05870          1099.38091
Tex19.2   392.56416           316.51847           269.03279
        129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1
ASZ1     3603.2718           3536.9879           3815.7157           2602.07065
DDX4    24758.1819          27632.7179          25099.7313           5924.16938
FKBP6    3863.2462           3404.6006           4045.0193           6892.33019
GPAT2    4037.0115           3651.8900           4008.9491           2939.92998
GTSF1    3028.0954           3389.6134           2559.6985            617.00867
HENMT1   1577.3575           1544.9343           1522.6792            326.78197
MAEL    44867.8063          44764.3785          38796.1151           6730.60081
MORC3    8255.8703           7569.8035           7385.3808           4881.79028
MYBL1   11176.2043          11501.4553          10741.2010           3528.13752
PLD6     5254.7153           5449.1095           4927.4519           1613.97060
RNF17   26001.4790          26541.1475          27079.7296          12819.82277
TCFL5   16987.2378          15996.3774          13423.2806           2127.95987
TDRD1   21099.6823          20025.4463          22162.5835           3241.23403
TDRD12  10636.0503           9945.2806          11752.4558           4393.27893
TDRD5   11729.8285          11673.8086          12088.6819           1537.53685
TDRD6   52264.2794          54899.4975          40926.8355             98.58846
TDRD9   15673.8958          15273.2433          15555.2892           4924.99197
TDRKH    1722.8354           1900.8812           2165.5024           1032.40947
TEX15    4189.2245           4213.9114           4005.0844           9227.43659
Tex19.1   610.1989            584.5022            608.0411           1430.08651
Tex19.2  1171.9052           1140.2789           1011.2548            841.87897
        ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
ASZ1    ⋯  2325.8041         997.85756       656.56250       774.95783
DDX4    ⋯ 10993.7111        2376.05950      1216.36843      1370.16850
FKBP6   ⋯  4906.6113        4473.41837      3939.37502      3912.46072
GPAT2   ⋯  4464.7525        1077.64244       590.90625       673.78278
GTSF1   ⋯  1338.7663         220.77462        99.06031       115.16734
HENMT1  ⋯   407.7851         120.22380       140.52741       123.77799
MAEL    ⋯ 15081.4547        2934.55371      1763.50385      2034.26431
MORC3   ⋯  5062.6908        4145.53528      3929.00825      4022.24641
MYBL1   ⋯  6493.7858        3111.61058      2175.87118      2377.61368
PLD6    ⋯  3152.3659        1371.64429      1443.28564      1465.96190
RNF17   ⋯ 13754.7791        6325.95787      3323.12776      3692.88933
TCFL5   ⋯  5880.4594         733.36519       483.78290       574.76039
TDRD1   ⋯  8286.5015        1180.37915      1021.70341      1060.18537
TDRD12  ⋯  6121.1735        1202.23802       601.27303       616.73727
TDRD5   ⋯  4296.5824         480.89521       363.98904       393.93690
TDRD6   ⋯  4220.7409          18.58004        28.79660        18.29762
TDRD9   ⋯  9585.6983        1713.73565       979.08444      1102.16225
TDRKH   ⋯  2024.6367         406.57504       247.65077       291.68552
TEX15   ⋯  9585.6983        5807.90257      2989.08719      3462.55465
Tex19.1 ⋯  1136.5224         516.96235       532.16119       519.86755
Tex19.2 ⋯  1172.7944         743.20168       579.38761       626.42425
        WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
ASZ1     615.55408       518.01941       502.026979      2176.1500
DDX4    1268.50636      1051.03938       903.071520      9433.9800
FKBP6   1218.97902       809.03032       697.259693      3860.7179
GPAT2    944.05175       708.02653       677.063206      2796.6225
GTSF1    420.47701       295.01105       279.865615       952.1905
HENMT1   141.50669        90.00337        87.518113       614.4776
MAEL    2712.88532      2094.07847      2079.276493     12478.3919
MORC3   3823.71280      4303.16124      4520.166289      4365.2890
MYBL1   2156.96619      2446.09166      2654.395523      5523.3046
PLD6    1896.18959      1912.07165      1910.010691      2449.9173
RNF17   1889.11425      1472.05516      1577.249513     13215.7651
TCFL5    705.51190       498.01866       554.922542      4897.8363
TDRD1   1697.06947      1158.04339      1102.151184      9692.7600
TDRD12   372.97119       306.01147       326.990753      6662.3362
TDRD5    976.39613       944.03537       806.897769      5861.0175
TDRD6     26.27981        11.00041         6.732163      9644.8008
TDRD9   3365.83759      2394.08971      2145.636381      8284.9568
TDRKH    157.67888       158.00592       157.724951       943.1982
TEX15   4104.70465      3165.11860      3078.521764      3689.8632
Tex19.1  445.74606       269.01008       279.865615       567.5175
Tex19.2  106.13001        82.00307        92.326801      1185.9918
        WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
ASZ1     2538.9154       2396.6751
DDX4     8546.6104       8001.7506
FKBP6    4603.2571       4216.9076
GPAT2    2980.2795       2736.7655
GTSF1     700.6121        735.7932
HENMT1    319.2391        322.9790
MAEL    10531.6780      10301.1042
MORC3    4433.9961       4219.0465
MYBL1    5256.7332       5041.4665
PLD6     1911.1498       1888.6784
RNF17   13853.6934      12994.0216
TCFL5    3736.5978       3758.1063
TDRD1    7374.6385       7676.6327
TDRD12   5738.8057       5404.0157
TDRD5    4095.4740       4204.0740
TDRD6    4134.0398       4782.6555
TDRD9    8280.9349       7846.6779
TDRKH    1049.8469       1006.3683
TEX15    6126.6063       5387.9737
Tex19.1   779.8862        680.1809
Tex19.2  1285.5268       1292.9854

 [1] "C57BL_6NJ-E16.5"   "BALB_cJ-E16.5"     "A_J-E16.5"
 [4] "FVB_NJ-E16.5"      "C3H_HeJ-E16.5"     "LP_J-E16.5"
 [7] "129S1_SvImJ-E16.5" "DBA_2J-E16.5"      "AKR_J-E16.5"
[10] "CBA_J-E16.5"       "NZO_HlLtJ-E16.5"   "NOD_ShiLtJ-E16.5"
[13] "WSB_EiJ-E16.5"     "CAST_EiJ-E16.5"    "PWK_PhJ-E16.5"
[16] "SPRET_EiJ-E16.5"   "C57BL_6NJ-P12.5"   "BALB_cJ-P12.5"
[19] "A_J-P12.5"         "FVB_NJ-P12.5"      "C3H_HeJ-P12.5"
[22] "LP_J-P12.5"        "129S1_SvImJ-P12.5" "DBA_2J-P12.5"
[25] "AKR_J-P12.5"       "CBA_J-P12.5"       "NZO_HlLtJ-P12.5"
[28] "NOD_ShiLtJ-P12.5"  "WSB_EiJ-P12.5"     "CAST_EiJ-P12.5"
[31] "PWK_PhJ-P12.5"     "SPRET_EiJ-P12.5"   "C57BL_6NJ-P20.5"
[34] "BALB_cJ-P20.5"     "A_J-P20.5"         "FVB_NJ-P20.5"
[37] "C3H_HeJ-P20.5"     "LP_J-P20.5"        "129S1_SvImJ-P20.5"
[40] "DBA_2J-P20.5"      "AKR_J-P20.5"       "CBA_J-P20.5"
[43] "NZO_HlLtJ-P20.5"   "NOD_ShiLtJ-P20.5"  "WSB_EiJ-P20.5"
[46] "CAST_EiJ-P20.5"    "PWK_PhJ-P20.5"     "SPRET_EiJ-P20.5"

        C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5  FVB_NJ-E16.5 C3H_HeJ-E16.5
DDX4     2572.6826      2493.0033      3256.6010 2098.8134    2501.54407
TDRD1    3211.7564      3280.1568      5518.8066 3175.0156    2695.85811
TDRD9    7585.4611      9836.9857     11404.0886 9222.2029    5560.50571
RNF17    3581.4377      3105.7601      5428.9434 4031.8168    3520.32408
MAEL     5247.1546      5583.7178      8050.1173 6352.3866    4721.73827
TEX15   11849.6670      5028.1598      9213.6341 6692.8198    4726.53352
FKBP6    3352.2233      4625.3966      4609.1026 3649.8421    2232.52185
TCFL5    1561.8241      1394.2075      2126.9084 1355.9668     957.20531
TDRD5    1369.9554       891.6238      2288.7294 1246.3702    1569.73442
MYBL1    1935.7580      1793.7488      1833.9990 2273.7731    1889.46984
TDRD12    935.4576       580.7281      1148.7727  803.6784    1106.98416
GPAT2    1590.5275      1928.6482      3059.0404 2052.1068    1847.00735
ASZ1      961.3724       571.9242      1559.6244  778.9778    1259.50529
PLD6     1769.6562      1747.2214      1682.5526 1629.0484     638.65067
TDRKH     285.9650       249.6966       442.0919  288.7371     307.89002
Tex19.2   307.3076       330.9803       390.6404  297.0475     276.24369
HENMT1    242.9981       250.6681       359.5154  331.3146     177.29881
GTSF1     459.2693       359.7079      1308.6257 1045.8417     636.66584
Tex19.1  1020.8028      1249.3539      2079.7621 1313.8269    1175.89603
TDRD6     299.7128       125.3431        45.5303   89.5624      23.65815
MORC3    3723.1773      3635.7567      3910.3175 3952.8212    4269.08583
        LP_J-E16.5  129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
DDX4     4068.93629  3343.01594       3568.9868    3864.8799   1195.45416  ⋯
TDRD1    4212.84909  4097.20373       4196.0590    4112.8035   1636.61502  ⋯
TDRD9   11846.22726 11500.52698       6370.7373    9935.1435   3559.11311  ⋯
RNF17    5312.26477  4410.61325       5043.0855    4777.1218   1859.58746  ⋯
MAEL     8187.48154  7116.79043       7141.1576    7786.4828   2972.27322  ⋯
TEX15   22220.15529  6943.92556       7210.6246    7975.4071   3123.57688  ⋯
FKBP6    4387.91032  4303.28737       3453.8087    4153.7504   1373.01141  ⋯
TCFL5    1739.54092  1657.90845       1474.6145    1961.3413    565.25720  ⋯
TDRD5    2145.57572  1915.65133       1644.5800    1857.2495    626.29728  ⋯
MYBL1    2008.96216  1635.10853       2107.6414    1585.7894   1605.95229  ⋯
TDRD12    952.37410   871.11855        872.7993    1032.0351    407.09905  ⋯
GPAT2    2440.84807  2590.87407       2291.4499    2719.6207   1049.15543  ⋯
ASZ1     1642.88692  1250.92898       1075.0448    1242.8354    454.64703  ⋯
PLD6     1633.61191  1742.53002       1604.0100    1762.5922    682.37649  ⋯
TDRKH     408.47612   420.22033        324.6573     419.9575    174.69786  ⋯
Tex19.2   374.81034   326.03847        241.7282     321.4013    112.00687  ⋯
HENMT1    355.63038   302.85239        294.4203     354.4432    105.15590  ⋯
GTSF1     603.06127   419.98076       1090.2922    1340.1176    414.42969  ⋯
Tex19.1  1396.28007  1312.39406       1038.2173    1306.1901    357.00343  ⋯
TDRD6      58.33268    54.31469         59.3916      30.0674     61.01678  ⋯
MORC3    4201.43991  3693.42744       3871.8477    4092.3734   4083.51432  ⋯
        129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
DDX4    25830.2103        21139.0754   21432.8492  15125.6345  15161.3332
TDRD1   21095.9040        19998.0467   13020.3836  10739.1344  12253.7199
TDRD9   15500.8094        12776.9075   13125.0459  10222.7927   9686.3771
RNF17   26540.7854        22948.3060   20720.5346  17533.8689  19616.8522
MAEL    42809.4333        28565.8050   37900.7980  21123.7056  21131.7110
TEX15    4136.0734         4390.8277    3683.6512   4224.0327  19052.3567
FKBP6    3770.9554         4073.0989    3355.9394   4261.5248   4404.5202
TCFL5   15468.9653        13429.3083   12407.7540   7946.2206   7625.9562
TDRD5   11830.7730         9390.6709    7471.8007   5373.0527   7619.8866
MYBL1   11139.6202         9992.3084    9149.1274   7060.9864   7283.7296
TDRD12  10777.9289        13561.0055    9921.0450   7030.4550  10860.2666
GPAT2    3899.2835         4625.6027    2709.1618   3675.7557   3117.3387
ASZ1     3651.9918         3838.7011    3327.8158   3136.4534   3246.4980
PLD6     5210.4256         4499.8499    4670.6863   2135.6573   3558.2775
TDRKH    1929.7397         1711.5181    1384.8116   1301.2927   1656.6217
Tex19.2  1107.8130         1205.8099     997.8555   1061.6620   1052.1495
HENMT1   1548.3237         1414.5358    1226.8341    774.8955   1425.0615
GTSF1    2992.4691         2204.2228    2753.2575   1559.8817   1418.2488
Tex19.1   600.9141          804.1198     571.7644    880.7293    913.2102
TDRD6   49363.5375        38442.3399   43922.4851  20914.7740  16366.2183
MORC3    7737.0182         7541.8092    6810.0076   5605.0761   6167.4056
        NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
DDX4    16843.0384        8660.7803    12414.5871     16380.108
TDRD1   14160.0805        8248.0104    14230.7160     14211.906
TDRD9   11934.1436        8137.5232    10727.4313     13032.443
RNF17   21963.0688       13354.4934    15186.7128     22021.647
MAEL    25712.8949       11103.7247    14044.9016     19919.087
TEX15    5841.7953        5068.1477    19096.1341     15707.771
FKBP6    4755.4059        4226.9609     5530.9142      5230.662
TCFL5    8460.2234        4130.8468     5737.4815      7667.874
TDRD5    6342.2024        4720.1885     4659.1066      6970.883
MYBL1    7837.2922        5273.8347     5823.8382      7229.788
TDRD12  11721.5538        5935.0526     8798.8168     10751.374
GPAT2    3364.1686        2837.8892     3962.0092      4545.054
ASZ1     3293.5461        2370.5802     3511.5478      4030.064
PLD6     3698.7741        2083.2485     1439.4129      2736.478
TDRKH    1685.0233         999.8044     1720.3638      1594.289
Tex19.2  1082.3696        1254.8346     1250.7294      1921.717
HENMT1    970.5265         418.8986      600.5477      1237.895
GTSF1    2027.3124         796.1986     1132.7183      1705.560
Tex19.1   795.6264         675.8616      872.8563      1070.660
TDRD6   22672.9515        6187.1654     8928.3012     18551.647
MORC3    6216.3419        4339.4439     5533.6869      6196.906
        SPRET_EiJ-P20.5
DDX4     9879.8751
TDRD1    6657.0292
TDRD9    8224.2224
RNF17   12829.0222
MAEL    12764.1988
TEX15   10317.9163
FKBP6    4895.5359
TCFL5    4715.9285
TDRD5    3544.9889
MYBL1    5852.4490
TDRD12   5303.6159
GPAT2    4138.0904
ASZ1     2160.5568
PLD6     2772.0883
TDRKH    1834.3531
Tex19.2   971.4496
HENMT1    330.5206
GTSF1    1166.8718
Tex19.1  1043.1948
TDRD6    2993.3335
MORC3    5044.4923

        C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5   FVB_NJ-E16.5 C3H_HeJ-E16.5
DDX4    -0.80650209     -0.81761337   -0.71112961 -0.87258318  -0.8164224
TDRD1   -0.63138269     -0.61981031   -0.24106256 -0.63759871  -0.7186654
TDRD9   -0.08940738      0.46598483    0.85254813  0.31433400  -0.5889109
RNF17   -1.07812222     -1.14291983   -0.82645191 -1.01677083  -1.0864472
MAEL    -0.66010730     -0.62820813   -0.39444493 -0.55535437  -0.7099058
TEX15    0.16767700     -0.76826689   -0.19399951 -0.53986746  -0.8096515
FKBP6   -0.90256270      0.07387948    0.06138303 -0.67430819  -1.7613019
TCFL5   -0.61581608     -0.65650345   -0.47864712 -0.66578603  -0.7625817
TDRD5   -0.65668137     -0.80942146   -0.36329989 -0.69614439  -0.5928882
MYBL1   -0.78130658     -0.82952229   -0.81585634 -0.66654184  -0.7970226
TDRD12  -0.86420417     -0.94917874   -0.81310507 -0.89577155  -0.8231154
GPAT2   -1.12973118     -0.78458863    0.36927900 -0.65856611  -0.8679249
ASZ1    -1.10847882     -1.46424250   -0.56197150 -1.27509762  -0.8361324
PLD6    -0.28370718     -0.30239936   -0.35627998 -0.40085844  -1.2260355
TDRKH   -1.07783307     -1.13979432   -0.81110439 -1.07309711  -1.0403761
Tex19.2 -1.04435801     -0.99371567   -0.86608658 -1.06630721  -1.1108122
HENMT1  -0.71481091     -0.69598794   -0.42886647 -0.49807379  -0.8760432
GTSF1   -0.80171458     -0.94089503    0.38563142  0.01827622  -0.5537256
Tex19.1 -0.18000056      0.35885686    2.31671927  0.51086557   0.1856645
TDRD6   -0.57081105     -0.58346510   -0.58925713 -0.58606171  -0.5908444
MORC3   -1.15412715     -1.23148311   -0.98853226 -0.95092190  -0.6710685
        LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
DDX4    -0.5978494 -0.6990790        -0.66756739  -0.62630507 -0.9985567  ⋯
TDRD1   -0.4620120 -0.4815776        -0.46485266  -0.47893831 -0.8978742  ⋯
TDRD9    0.9616122  0.8763370        -0.38904799   0.49019781 -1.0826021  ⋯
RNF17   -0.8423461 -0.9651705        -0.87901413  -0.91524414 -1.3126755  ⋯
MAEL    -0.3814257 -0.4829048        -0.48059535  -0.41943198 -0.8757186  ⋯
TEX15    1.5905583 -0.5054145        -0.46882213  -0.36389027 -1.0295849  ⋯
FKBP6   -0.1082572 -0.1731576        -0.82465324  -0.28784286 -2.4204913  ⋯
TCFL5   -0.5726770 -0.5924925        -0.63698541  -0.51883700 -0.8577235  ⋯
TDRD5   -0.4090115 -0.4824306        -0.56898868  -0.50107937 -0.8941451  ⋯
MYBL1   -0.7564519 -0.8833847        -0.72294777  -0.90012981 -0.8932840  ⋯
TDRD12  -0.8601519 -0.8796164        -0.87921381  -0.84106929 -0.9907711  ⋯
GPAT2   -0.2617516 -0.1086100        -0.41425243   0.02281042 -1.6823462  ⋯
ASZ1    -0.4859106 -0.8439669        -1.00463839  -0.85136046 -1.5713760  ⋯
PLD6    -0.3970562 -0.3063081        -0.42171992  -0.28959282 -1.1896041  ⋯
TDRKH   -0.8685339 -0.8484699        -1.01173073  -0.84891900 -1.2679229  ⋯
Tex19.2 -0.8999513 -1.0042876        -1.18465013  -1.01420784 -1.4621595  ⋯
HENMT1  -0.4384006 -0.5679228        -0.58861590  -0.44131410 -1.0530887  ⋯
GTSF1   -0.6007026 -0.8566375         0.08041513   0.42965513 -0.8643975  ⋯
Tex19.1  0.7052663  0.5074874        -0.13894209   0.49286029 -1.7450475  ⋯
TDRD6   -0.5883281 -0.5886196        -0.58825121  -0.59037927 -0.5881333  ⋯
MORC3   -0.7309264 -1.1804520        -1.02257307  -0.82743626 -0.8352754  ⋯
        129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
DDX4     2.4367619         1.7825828    1.82354958  0.94400802  0.94898620
TDRD1    2.3943611         2.2086192    1.02809773  0.64214276  0.89838913
TDRD9    1.8631020         1.1911867    1.27706330  0.56115335  0.42883363
RNF17    2.0494384         1.5600649    1.25659417  0.82250125  1.10624872
MAEL     2.9000128         1.5500141    2.43477662  0.84465840  0.84541713
TEX15   -0.8906655        -0.8557120   -0.95274000 -0.87859704  1.15592099
FKBP6   -0.5814221        -0.3496974   -0.89971270 -0.20518681 -0.09551853
TCFL5    2.7600134         2.2649056    2.01693277  0.93393692  0.85619571
TDRD5    2.6836503         1.9044808    1.29175021  0.62158132  1.33903675
MYBL1    2.3436390         1.9540974    1.66781598  0.95883897  1.03446596
TDRD12   1.4935350         2.1602140    1.28827064  0.59583708  1.51325881
GPAT2    1.2269718         1.9683748    0.01213424  0.99880190  0.42878793
ASZ1     1.3494205         1.5199807    1.05328354  0.87847262  0.97899918
PLD6     2.5830642         1.9910286    2.13336564  0.02123661  1.20653173
TDRKH    1.7304077         1.3575959    0.79944720  0.65676283  1.26381023
Tex19.2  0.6681409         0.8777828    0.43291192  0.56941138  0.54906155
HENMT1   2.4885819         2.1602538    1.69961604  0.59051581  2.18608475
GTSF1    2.7395370         1.6376189    2.40513440  0.73687127  0.53887746
Tex19.1 -1.1699767        -0.6908763   -1.23870329 -0.51025335 -0.43367266
TDRD6    2.9897603         2.1972069    2.59490206  0.92522798  0.59513839
MORC3    2.3976044         2.2248696    1.57731948  0.51111051  1.00869964
        NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
DDX4     1.1835001        0.042483606   0.56595225     1.11894444
TDRD1    1.2209183        0.220679965   1.23286878     1.22968646
TDRD9    0.9832988        0.046771894   0.68563448     1.25422070
RNF17    1.4258543        0.253179734   0.50276772     1.43383383
MAEL     1.2796178       -0.105026681   0.17373551     0.73048567
TEX15   -0.6566322       -0.762780358   1.16192745     0.69702764
FKBP6    0.1735883       -0.231695135   0.76835344     0.53807942
TCFL5    1.0587063        0.007790333   0.39778600     0.86637078
TDRD5    0.9310487        0.413109757   0.39360520     1.13179807
MYBL1    1.2224145        0.352055472   0.53879564     1.01615129
TDRD12   1.7195780        0.333436201   1.01944370     1.48717378
GPAT2    0.6807439        0.143535018   1.29100006     1.88615357
ASZ1     1.0219779        0.178842155   1.22112401     1.69479188
PLD6     1.3235903       -0.022429206  -0.55885849     0.52182727
TDRKH    1.3123319        0.141697235   1.37270799     1.15732060
Tex19.2  0.6137105        0.982660133   0.97387786     2.40930342
HENMT1   1.0706127       -0.283134431   0.16264979     1.72676006
GTSF1    1.3903095       -0.330708971   0.13972408     0.94052033
Tex19.1 -0.7109014       -0.993272243  -0.52881557    -0.06245078
TDRD6    1.0528193       -0.143557466   0.05536729     0.75373537
MORC3    1.0520019       -0.608810750   0.44794030     1.03480330
        SPRET_EiJ-P20.5
DDX4     0.21248647
TDRD1   -0.04849147
TDRD9    0.06815831
RNF17    0.18159917
MAEL     0.05235161
TEX15   -0.04248663
FKBP6    0.28105902
TCFL5    0.14981348
TDRD5    0.03784689
MYBL1    0.54850973
TDRD12   0.18217714
GPAT2    1.47073806
ASZ1    -0.01301566
PLD6     0.55149655
TDRKH    1.56744833
Tex19.2  0.37642252
HENMT1  -0.50002246
GTSF1    0.18746856
Tex19.1 -0.12720665
TDRD6   -0.37533447
MORC3    0.01506616

Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

Warning message in brewer.pal(11, "GnBu"):
“n too large, allowed maximum for palette GnBu is 9
Returning the palette you asked for with that many colors
”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = TRUE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `both'. Omitting column dendogram.”

png
  2

In [37]:
library(gplots)

# Extract rows by multiple row names
row_names_to_extract <- c('Piwil2', 'Piwil1', 'Piwil4')
piwi_sub_1 <- subset(norm_counts, tolower(row.names(norm_counts)) %in% tolower(row_names_to_extract))
piwi_sub_1

# Desired order
desired_gene_order <- c("PIWIL2", "PIWIL1", "PIWIL4")

# Reorder dataframe by raw 
piwi_sub_1<- piwi_sub_1[desired_gene_order, ]

# Remove duplicates from the samplenames_order vector
unique_samplenames_order <- unique(samplenames_order)
unique_samplenames_order
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)
# Create a heatmap with log-normalized values
#heatmap.2(log2(piwi_sub_1+ 1), scale = "none", col = colorRampPalette(c("blue", "white", "red"))(100))

piwi_sub_1 <- as.data.frame.matrix(piwi_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate


foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(piwi_sub_1), ncol = 0))


row.names(foo_sub1_mean) <- row.names(piwi_sub_1)


for (sample in unique_samplenames_order) {
foo_sub1_mean[sample] <- apply(piwi_sub_1[ , grepl(paste0( "^",sample) , names( piwi_sub_1) ) ], 1, mean)
}



# Calculate Z-scores row-wise
z_scores <- t(scale(t(foo_sub1_mean)))

# Convert the matrix to a data frame
z_scores_df <- as.data.frame(z_scores)
z_scores_df

# Create a PDF graphics device
pdf("z-score_heatmap_piwi_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed
#Log expression (GnBu) and z-score (RdBu) with red for positive zscore
# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
#myCol <-  colorRampPalette(c("blue", "white", "red")) 
myCol <- colorRampPalette(brewer.pal(11, "RdBu"))(100)
heatmap.2(t(scale(t(foo_sub1_mean))),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = rev(myCol),
          main = "Piwi Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()


# Create a PDF graphics device
pdf("log10_heatmap_piwi_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a blue color palette
myCol <- colorRampPalette(brewer.pal(11, "GnBu"))(100)

heatmap.2(log10(as.matrix(foo_sub1_mean) + 1),
          Rowv = TRUE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = myCol,
          main = "Piwi Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()

       129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
PIWIL1  210.1821            682.2765            346.7873
PIWIL2 5517.5300           7327.4071           6672.7338
PIWIL4  433.3139            370.4075            347.7615
       129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
PIWIL1  353.7807            305.8308            278.997
PIWIL2 8740.4646           7698.3869           6744.087
PIWIL4 5078.7397           4021.8399           3990.653
       129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1
PIWIL1 18013.66517         19304.80998         19865.68240          471.8953
PIWIL2 16444.38977         16162.48599         17058.64512         7980.1264
PIWIL4    91.59719            77.43406            97.90493          443.0942
       ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
PIWIL1 ⋯  4706.56579         67.76251        48.37829        39.82422
PIWIL2 ⋯ 14043.85594       3001.22327      2494.93751      2794.15352
PIWIL4 ⋯    67.04823         73.22722        63.35252        79.64844
       WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
PIWIL1  135.4421        101.0038         73.09205       7686.46561
PIWIL2 3365.8376       2497.0936       2165.83287      11888.89306
PIWIL4  835.9002        658.0247        597.23899         75.93545
       WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
PIWIL1  3914.42899      4239.36640
PIWIL2 12552.09754     11848.62268
PIWIL4    74.98906        69.51534

 [1] "C57BL_6NJ-E16.5"   "BALB_cJ-E16.5"     "A_J-E16.5"
 [4] "FVB_NJ-E16.5"      "C3H_HeJ-E16.5"     "LP_J-E16.5"
 [7] "129S1_SvImJ-E16.5" "DBA_2J-E16.5"      "AKR_J-E16.5"
[10] "CBA_J-E16.5"       "NZO_HlLtJ-E16.5"   "NOD_ShiLtJ-E16.5"
[13] "WSB_EiJ-E16.5"     "CAST_EiJ-E16.5"    "PWK_PhJ-E16.5"
[16] "SPRET_EiJ-E16.5"   "C57BL_6NJ-P12.5"   "BALB_cJ-P12.5"
[19] "A_J-P12.5"         "FVB_NJ-P12.5"      "C3H_HeJ-P12.5"
[22] "LP_J-P12.5"        "129S1_SvImJ-P12.5" "DBA_2J-P12.5"
[25] "AKR_J-P12.5"       "CBA_J-P12.5"       "NZO_HlLtJ-P12.5"
[28] "NOD_ShiLtJ-P12.5"  "WSB_EiJ-P12.5"     "CAST_EiJ-P12.5"
[31] "PWK_PhJ-P12.5"     "SPRET_EiJ-P12.5"   "C57BL_6NJ-P20.5"
[34] "BALB_cJ-P20.5"     "A_J-P20.5"         "FVB_NJ-P20.5"
[37] "C3H_HeJ-P20.5"     "LP_J-P20.5"        "129S1_SvImJ-P20.5"
[40] "DBA_2J-P20.5"      "AKR_J-P20.5"       "CBA_J-P20.5"
[43] "NZO_HlLtJ-P20.5"   "NOD_ShiLtJ-P20.5"  "WSB_EiJ-P20.5"
[46] "CAST_EiJ-P20.5"    "PWK_PhJ-P20.5"     "SPRET_EiJ-P20.5"

       C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5  FVB_NJ-E16.5 C3H_HeJ-E16.5
PIWIL2 -0.7222780      -0.5588142    -0.2034255 -0.6791769   -0.9700242
PIWIL1 -0.6208349      -0.6408865    -0.5905902 -0.6366317   -0.6499054
PIWIL4  1.0849928       0.6395308     2.1872777  0.9061757    0.8406940
       LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
PIWIL2 -0.1534008 -0.3567973        -0.5577739   -0.3141054  -1.3945236  ⋯
PIWIL1 -0.6374560 -0.6428558        -0.6269765   -0.6162679  -0.6689511  ⋯
PIWIL4  1.8142624  1.6593776         1.8282311    1.7870247   0.2923632  ⋯
       129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
PIWIL2  1.4841129         1.5301407    0.6532755   0.5442974   1.0590264
PIWIL1  2.5963736         2.3373454    1.2066249   0.6442418   0.9321724
PIWIL4 -0.7238956        -0.6931391   -0.6833867  -0.7065527  -0.6598794
       NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
PIWIL2  1.3532213        0.5543001     1.4508744      1.9505800
PIWIL1  1.1369276        0.2153431     0.6928975      1.5283311
PIWIL4 -0.6694253       -0.7325365    -0.6401517     -0.6390137
       SPRET_EiJ-P20.5
PIWIL2  0.61541970
PIWIL1 -0.07827837
PIWIL4 -0.72050596

Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

Warning message in brewer.pal(11, "GnBu"):
“n too large, allowed maximum for palette GnBu is 9
Returning the palette you asked for with that many colors
”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = TRUE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `both'. Omitting column dendogram.”

png
  2

In [38]:
marker_gene_list <- c('Sycp3', 'Meiob','Dnmt3b','Dnmt3c', 'Dnmt1','Dnmt3a','Ddx4','Dnmt3l', 'Nanos2','Nanos3')
marker_gene_sub_1 <- subset(norm_counts, tolower(row.names(norm_counts)) %in% tolower(marker_gene_list))
marker_gene_sub_1

#list order 'Sycp3', 'Meiob','Dnmt3b','Dnmt3c', 'Dnmt1','Dnmt3a','Ddx4','Dnmt3l', 'Nanos2','Nanos3'

# Desired order
desired_gene_order <- c("SYCP3","MEIOB" ,"DNMT3B","DNMT3C","DNMT1","DNMT3A","DDX4","Dnmt3l", "NANOS2")


# Reorder dataframe by raw 
marker_gene_sub_1 <- marker_gene_sub_1[desired_gene_order, ]
# Remove duplicates from the samplenames_order vector
unique_samplenames_order <- unique(samplenames_order)
unique_samplenames_order
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)
# Create a heatmap with log-normalized values
#heatmap.2(log2(piwi_sub_1+ 1), scale = "none", col = colorRampPalette(c("blue", "white", "red"))(100))

marker_gene_sub_1 <- as.data.frame.matrix(marker_gene_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate


foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(marker_gene_sub_1), ncol = 0))

row.names(foo_sub1_mean) <- row.names(marker_gene_sub_1)

for (sample in unique_samplenames_order) {
foo_sub1_mean[sample] <- apply(marker_gene_sub_1[ , grepl(paste0( "^",sample) , names( marker_gene_sub_1) ) ], 1, mean)
}

foo_sub1_mean

# Calculate Z-scores row-wise
z_scores <- t(scale(t(foo_sub1_mean)))

# Convert the matrix to a data frame
z_scores_df <- as.data.frame(z_scores)
z_scores_df

# Create a PDF graphics device
pdf("z-score_heatmap_marker_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a bright color palette (e.g., using the 'viridis' palette)
myCol <- colorRampPalette(brewer.pal(11, "RdBu"))(100)
heatmap.2(t(scale(t(foo_sub1_mean))),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = rev(myCol),
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()


# Create a PDF graphics device
pdf("log10_heatmap_marker_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a blue color palette
myCol <- colorRampPalette(brewer.pal(11, "GnBu"))(100)


heatmap.2(log10(as.matrix(foo_sub1_mean) + 1),
          Rowv = TRUE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = myCol,
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()

       129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
DDX4   5638.061020         7293.09141          5985.977945
DNMT1  7511.769992         6822.76473          7524.116135
DNMT3A 4926.828588         4828.41811          4855.996755
DNMT3B 2133.697298         1900.48313          1777.772132
DNMT3C  383.507684          417.84388           434.458285
Dnmt3l   20.918601           10.09285            11.689461
MEIOB  2664.631313         4162.29020          3023.673807
NANOS2    8.965115           10.09285             7.792974
SYCP3  3747.417943         5115.05498          3890.642134
       129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
DDX4   3700.5084           3441.41902          2887.12041
DNMT1  9071.5428           8938.15280          8637.28114
DNMT3A 8311.0089           9587.63226          8921.26020
DNMT3B  871.2086            885.42960           855.25856
DNMT3C  513.6442            445.59224           383.62083
Dnmt3l 2590.9234           2058.60326          1893.19371
MEIOB   142.8366            132.36227           146.14127
NANOS2  118.2422             64.12582            60.61541
SYCP3   393.5101            312.40784           330.47855
       129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1
DDX4   24758.18185         27632.7179          25099.73127         5924.16938
DNMT1   5693.84302          5370.4265           5583.15722         6682.96818
DNMT3A  1981.46276          2110.7025           2341.98889         4833.04992
DNMT3B   864.78524           816.8044            926.23213         2571.05406
DNMT3C   255.93333           237.2979            240.89765          640.27111
Dnmt3l    33.67544            68.6915             46.37602           17.72377
MEIOB   4395.31814          3966.6220           4637.60175         3284.43571
NANOS2    37.71649            41.2149             28.34090           12.18509
SYCP3   7094.74123          6614.3672           6634.34695         4774.33994
       ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
DDX4   ⋯ 10993.71113       2376.059502     1216.368428     1370.168500
DNMT1  ⋯  4321.86284       4908.409947     4676.568010     5010.317648
DNMT3A ⋯  3396.37746       5746.697730     5390.723716     5056.599852
DNMT3B ⋯  1281.61040       1500.611636     1664.443541     1676.922641
DNMT3C ⋯   464.94099        665.602685      672.688600      611.355623
Dnmt3l ⋯    12.09066          5.464718        4.607456        3.228991
MEIOB  ⋯  3682.15680       1121.360188      292.573467      471.432681
NANOS2 ⋯    12.09066          4.371775        3.455592        6.457982
SYCP3  ⋯  6459.71209       1742.152184      832.797702     1035.429770
       WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
DDX4   1268.50636      1051.03938       903.07152      9433.980024
DNMT1  8678.40288      8616.32286      8836.44423      3662.886123
DNMT3A 8416.61551      9607.36000      7574.64461      3001.448421
DNMT3B  911.70736       945.03541       924.22975       851.276317
DNMT3C  212.26003       189.00708       163.49538       472.598237
Dnmt3l  456.86444       224.00839       198.11793         8.992355
MEIOB    51.54886        47.00176        27.89039      2948.493439
NANOS2   45.48429        56.00210        43.27819        12.988958
SYCP3   276.94880       275.01030       282.75083      3067.392361
       WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
DDX4   8546.61041      8001.750601
DNMT1  4615.04107      4212.629727
DNMT3A 2768.16762      2778.474748
DNMT3B 1204.11007      1133.634808
DNMT3C  532.42233       552.914336
Dnmt3l   10.71272         8.555734
MEIOB  4011.91476      3610.519918
NANOS2   17.14036         7.486268
SYCP3  4198.31615      3845.802614

 [1] "C57BL_6NJ-E16.5"   "BALB_cJ-E16.5"     "A_J-E16.5"
 [4] "FVB_NJ-E16.5"      "C3H_HeJ-E16.5"     "LP_J-E16.5"
 [7] "129S1_SvImJ-E16.5" "DBA_2J-E16.5"      "AKR_J-E16.5"
[10] "CBA_J-E16.5"       "NZO_HlLtJ-E16.5"   "NOD_ShiLtJ-E16.5"
[13] "WSB_EiJ-E16.5"     "CAST_EiJ-E16.5"    "PWK_PhJ-E16.5"
[16] "SPRET_EiJ-E16.5"   "C57BL_6NJ-P12.5"   "BALB_cJ-P12.5"
[19] "A_J-P12.5"         "FVB_NJ-P12.5"      "C3H_HeJ-P12.5"
[22] "LP_J-P12.5"        "129S1_SvImJ-P12.5" "DBA_2J-P12.5"
[25] "AKR_J-P12.5"       "CBA_J-P12.5"       "NZO_HlLtJ-P12.5"
[28] "NOD_ShiLtJ-P12.5"  "WSB_EiJ-P12.5"     "CAST_EiJ-P12.5"
[31] "PWK_PhJ-P12.5"     "SPRET_EiJ-P12.5"   "C57BL_6NJ-P20.5"
[34] "BALB_cJ-P20.5"     "A_J-P20.5"         "FVB_NJ-P20.5"
[37] "C3H_HeJ-P20.5"     "LP_J-P20.5"        "129S1_SvImJ-P20.5"
[40] "DBA_2J-P20.5"      "AKR_J-P20.5"       "CBA_J-P20.5"
[43] "NZO_HlLtJ-P20.5"   "NOD_ShiLtJ-P20.5"  "WSB_EiJ-P20.5"
[46] "CAST_EiJ-P20.5"    "PWK_PhJ-P20.5"     "SPRET_EiJ-P20.5"

       C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5  FVB_NJ-E16.5 C3H_HeJ-E16.5
SYCP3   475.49782       343.96752     410.70546  358.3392     488.53935
MEIOB   145.49754        90.32948      84.76505  117.7444      41.73614
DNMT3B  913.50381       823.44150    1224.35537 1055.0020     804.86586
DNMT3C  316.83005       265.51796     290.03520  343.9902     236.36153
DNMT1  8844.05180      8536.32457    9150.84632 9039.2707    8753.31264
DNMT3A 8034.44363      8561.76673    9895.77174 8893.5183    9383.26915
DDX4   2572.68256      2493.00331    3256.60100 2098.8134    2501.54407
Dnmt3l 1375.62395      1804.33113    2790.61449 1946.1749     992.80772
NANOS2   45.07526        37.61111     222.26365   30.5179     235.13269
       LP_J-E16.5  129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
SYCP3    893.53038  345.46550         373.86248    402.55766   302.79781  ⋯
MEIOB    174.92963  140.44671         117.77998    132.93086    32.87573  ⋯
DNMT3B   838.95004  870.63227         834.52526    956.78000   812.42987  ⋯
DNMT3C   464.09283  447.61909         419.03851    419.89618   176.06275  ⋯
DNMT1   8424.63764 8882.32558        8454.90573   8658.46135  9487.18773  ⋯
DNMT3A 10125.41589 8939.96711        9352.07633   9393.82204  8651.91579  ⋯
DDX4    4068.93629 3343.01594        3568.98684   3864.87992  1195.45416  ⋯
Dnmt3l  2349.19713 2180.90680        1800.69237   2530.42392   701.47045  ⋯
NANOS2    68.22918   80.99448          99.21947     85.47922    27.17543  ⋯
       129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
SYCP3   6781.15179        6100.04467   5682.52617  6240.77342  7462.72317
MEIOB   4333.18064        5301.99942   4142.95511  4253.97470  4538.05106
DNMT3B   869.27393        1082.42566    910.47087   993.35527  1159.39238
DNMT3C   244.70963         303.71689    317.58980   378.45922   264.52003
DNMT1   5549.14226        5046.10468   4355.72308  4552.69961  5317.23606
DNMT3A  2144.71805        2091.74478   2000.19530  2733.22101  2808.80871
DDX4   25830.21034       21139.07537  21432.84923 15125.63454 15161.33320
Dnmt3l    49.58099          28.77849     78.54079    26.47536    18.82652
NANOS2    35.75743          26.28708     25.74397    20.26533    16.74928
       NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
SYCP3   6566.05207      3703.837040    6000.85351     6989.451967
MEIOB   4675.95801      3523.642707    4251.15727     3771.723100
DNMT3B  1036.13253      1063.007064    1582.04044     1320.853777
DNMT3C   371.99749       519.311635     322.94045      377.419105
DNMT1   5392.24227      4163.518973    6778.31842     5239.651082
DNMT3A  2602.47558      2849.363598    2341.01572     2583.591436
DDX4   16843.03837      8660.780346   12414.58714    16380.108022
Dnmt3l    67.77006         9.420271      10.07660        8.989871
NANOS2    20.63312        12.538527      17.54188     2687.381763
       SPRET_EiJ-P20.5
SYCP3  6044.322248
MEIOB  3598.761773
DNMT3B 1354.533474
DNMT3C  463.391297
DNMT1  4618.720408
DNMT3A 4030.089218
DDX4   9879.875137
Dnmt3l   12.828363
NANOS2    9.438794

       C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5   FVB_NJ-E16.5 C3H_HeJ-E16.5
SYCP3  -1.0560573      -1.1027676    -1.07906696 -1.0976638   -1.05142585
MEIOB  -1.0545024      -1.0826134    -1.08544876 -1.0686441   -1.10737422
DNMT3B -0.8499376      -0.9938347    -0.35327449 -0.6238589   -1.02351390
DNMT3C -0.6245678      -1.0463046    -0.84479609 -0.4013372   -1.28594283
DNMT1   1.2473549       1.0547911     1.43933506  1.3695154    1.19057384
DNMT3A  0.9820206       1.1796764     1.67969986  1.3040265    1.48759916
DDX4   -0.8065021      -0.8176134    -0.71112961 -0.8725832   -0.81642236
Dnmt3l  0.9243612       1.4123868     2.53513806  1.5738568    0.48857625
NANOS2 -0.2534473      -0.2645928     0.01113302 -0.2751845    0.03034927
       LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
SYCP3  -0.9076016 -1.1022356        -1.0921510   -1.0819605  -1.1173882  ⋯
MEIOB  -1.0395052 -1.0570761        -1.0686259   -1.0609058  -1.1118891  ⋯
DNMT3B -0.9690559 -0.9184356        -0.9761256   -0.7807931  -1.0114285  ⋯
DNMT3C  0.5857926  0.4503941         0.2154888    0.2225381  -1.7815416  ⋯
DNMT1   0.9849017  1.2713052         1.0038423    1.1312196   1.6498045  ⋯
DNMT3A  1.7657771  1.3214368         1.4759072    1.4915547   1.2134669  ⋯
DDX4   -0.5978494 -0.6990790        -0.6675674   -0.6263051  -0.9985567  ⋯
Dnmt3l  2.0326436  1.8410677         1.4082445    2.2389460   0.1569279  ⋯
NANOS2 -0.2188735 -0.1998121        -0.1725983   -0.1931155  -0.2801755  ⋯
       129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
SYCP3   1.1832666         0.9413853    0.7931122   0.9913623   1.4253127
MEIOB   1.0793396         1.5730030    0.9824098   1.0389800   1.1837317
DNMT3B -0.9206059        -0.5800427   -0.8547835  -0.7223549  -0.4570691
DNMT3C -1.2173293        -0.7323456   -0.6183234  -0.1180345  -1.0545066
DNMT1  -0.8144723        -1.1292538   -1.5612679  -1.4380076  -0.9595902
DNMT3A -1.2256178        -1.2454737   -1.2797891  -1.0050300  -0.9766975
DDX4    2.4367619         1.7825828    1.8235496   0.9440080   0.9489862
Dnmt3l -0.5851608        -0.6088417   -0.5521940  -0.6114635  -0.6201707
NANOS2 -0.2673608        -0.2815020   -0.2823130  -0.2904938  -0.2957440
       NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
SYCP3   1.1068783        0.09042126    0.90615961     1.2572401
MEIOB   1.2540024        0.66683796    1.03754440     0.7932478
DNMT3B -0.6540076       -0.61106877    0.21821686    -0.1990942
DNMT3C -0.1711438        1.03963886   -0.57434612    -0.1265832
DNMT1  -0.9126542       -1.68154182   -0.04530129    -1.0081399
DNMT3A -1.0540371       -0.96149641   -1.15203980    -1.0611155
DDX4    1.1835001        0.04248361    0.56595225     1.1189444
Dnmt3l -0.5644550       -0.63087842   -0.63013127    -0.6313684
NANOS2 -0.2899446       -0.30203158   -0.29456050     3.6920833
       SPRET_EiJ-P20.5
SYCP3   0.9215966
MEIOB   0.7051150
DNMT3B -0.1452824
DNMT3C  0.5800267
DNMT1  -1.3966943
DNMT3A -0.5189265
DDX4    0.2124865
Dnmt3l -0.6269988
NANOS2 -0.3066601

Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

Warning message in brewer.pal(11, "GnBu"):
“n too large, allowed maximum for palette GnBu is 9
Returning the palette you asked for with that many colors
”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = TRUE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `both'. Omitting column dendogram.”

png
  2

In [39]:
#utr gene list 1700029I15Rik


marker_gene_list <- c('MORC3','Apitd1','CNIH4','exosc6','Gm10643','Gm9938','H2afx','INAFM1','rpl21','RPL32','RPLP2','TCEAL9')
marker_gene_sub_1 <- subset(norm_counts, tolower(row.names(norm_counts)) %in% tolower(marker_gene_list))
marker_gene_sub_1

#list order 'Sycp3', 'Meiob','Dnmt3b','Dnmt3c', 'Dnmt1','Dnmt3a','Ddx4','Dnmt3l', 'Nanos2','Nanos3'

# Desired order
desired_gene_order <- c('Apitd1','CNIH4','exosc6','Gm10643','Gm9938','H2afx','INAFM1','rpl21','RPL32','RPLP2','TCEAL9','MORC3')


# Reorder dataframe by raw 
#marker_gene_sub_1 <- marker_gene_sub_1[desired_gene_order, ]
# Remove duplicates from the samplenames_order vector
unique_samplenames_order <- unique(samplenames_order)
unique_samplenames_order
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)
# Create a heatmap with log-normalized values
#heatmap.2(log2(piwi_sub_1+ 1), scale = "none", col = colorRampPalette(c("blue", "white", "red"))(100))

marker_gene_sub_1 <- as.data.frame.matrix(marker_gene_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate


foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(marker_gene_sub_1), ncol = 0))

row.names(foo_sub1_mean) <- row.names(marker_gene_sub_1)

for (sample in unique_samplenames_order) {
foo_sub1_mean[sample] <- apply(marker_gene_sub_1[ , grepl(paste0( "^",sample) , names( marker_gene_sub_1) ) ], 1, mean)
}

foo_sub1_mean

# Calculate Z-scores row-wise
z_scores <- t(scale(t(foo_sub1_mean)))

# Convert the matrix to a data frame
z_scores_df <- as.data.frame(z_scores)
z_scores_df

# Create a PDF graphics device
pdf("z-score_heatmap_utr_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a bright color palette (e.g., using the 'viridis' palette)
myCol <- colorRampPalette(brewer.pal(11, "RdBu"))(100)
heatmap.2(t(scale(t(foo_sub1_mean))),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = rev(myCol),
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()


# Create a PDF graphics device
pdf("log10_heatmap_utr_genes_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a blue color palette
myCol <- colorRampPalette(brewer.pal(11, "GnBu"))(100)


heatmap.2(log10(as.matrix(foo_sub1_mean) + 1),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = myCol,
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()

        129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
Apitd1    257.99608           306.82256           290.28827
CNIH4    1410.51138          1528.05707          1500.14744
Gm10643    77.69766            84.77992            93.51568
H2afx   15009.59425         16454.36884         19527.24392
INAFM1    133.48060           133.22558           132.48055
MORC3    5115.09600          4835.48311          4884.24628
RPL32    6587.36705          5396.64541          6834.43796
RPLP2    3383.83274          2971.33422          3717.24847
exosc6    164.36044           153.41128           177.29015
rpl21    5454.77423          4804.19528          5567.10561
        129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
Apitd1    156.07973           172.64644           166.06962
CNIH4    1310.12375          1336.77672          1311.11968
Gm10643    52.02658            39.46204            39.85671
H2afx    2845.38068          2913.61419          3075.60944
INAFM1    270.53819           269.65730           275.67558
MORC3    3711.85964          3744.78348          3623.63919
RPL32   15047.03143         11740.77999         10561.19774
RPLP2    6179.81117          5282.98104          5059.31109
exosc6    174.05254           157.02605           137.83779
rpl21   12076.78697          9487.33290          9779.84015
        129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1
Apitd1    288.26175           314.73197           288.5619            283.58028
CNIH4    1194.80453          1129.03851          1228.9645           1548.61421
Gm10643    64.65684            86.17661            56.6818             58.70998
H2afx   14147.72492         12087.20650         12089.9701          11250.16159
INAFM1    172.41824           201.07876           139.1281             64.24866
MORC3    8255.87032          7569.80354          7385.3808           4881.79028
RPL32    6997.75597          6318.36926          5687.5033           5742.50076
RPLP2    2396.34415          2205.62169          2165.5024           3335.39155
exosc6    110.45544           112.40428           118.5165            167.26806
rpl21    4838.48690          4335.05825          4629.8724           5444.51991
        ⋯ SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
Apitd1  ⋯   43.96605         155.19800        82.93421        86.10643
CNIH4   ⋯ 1830.08689        1344.32069      1222.12775      1059.10904
Gm10643 ⋯   89.03125          56.83307        33.40406        44.12954
H2afx   ⋯ 8488.74535        7513.98762      4448.49893      4923.13489
INAFM1  ⋯  179.16166          81.97077        84.08608        66.73248
MORC3   ⋯ 5062.69081        4145.53528      3929.00825      4022.24641
RPL32   ⋯ 5670.52147        5976.21590      6960.71441      7107.00912
RPLP2   ⋯ 3759.09739        4105.09636      4663.89751      4359.13780
exosc6  ⋯  160.47609         183.61453       163.56469       176.51817
rpl21   ⋯ 3176.54721        3718.19431      4372.47590      4267.64973
        WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
Apitd1    136.45288       153.00573        98.09723      152.87004
CNIH4    1318.03370      1502.05628      1312.77170     1318.87880
Gm10643    53.57039        44.00165        53.85730       41.96433
H2afx    3424.46179      3414.12793      3436.28812     9016.33507
INAFM1    153.63583       156.00585       135.60499       95.91846
MORC3    3823.71280      4303.16124      4520.16629     4365.28900
RPL32   13971.76369     11518.43161     14403.94266     6002.89684
RPLP2    7107.67867      6504.24372      6699.46348     3558.97446
exosc6    188.00174       198.00742       218.31441      147.87429
rpl21    7456.39157      6572.24627      7663.12447     3130.33885
        WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
Apitd1    157.47703       130.47495
CNIH4    1302.66712      1253.41509
Gm10643    57.84870        53.47334
H2afx   11709.00624     10394.14783
INAFM1     94.27196       100.52988
MORC3    4433.99605      4219.04653
RPL32    6468.34215      5841.42766
RPLP2    3676.60653      3390.20976
exosc6    163.90466       171.11469
rpl21    3870.50682      3601.96418

 [1] "C57BL_6NJ-E16.5"   "BALB_cJ-E16.5"     "A_J-E16.5"
 [4] "FVB_NJ-E16.5"      "C3H_HeJ-E16.5"     "LP_J-E16.5"
 [7] "129S1_SvImJ-E16.5" "DBA_2J-E16.5"      "AKR_J-E16.5"
[10] "CBA_J-E16.5"       "NZO_HlLtJ-E16.5"   "NOD_ShiLtJ-E16.5"
[13] "WSB_EiJ-E16.5"     "CAST_EiJ-E16.5"    "PWK_PhJ-E16.5"
[16] "SPRET_EiJ-E16.5"   "C57BL_6NJ-P12.5"   "BALB_cJ-P12.5"
[19] "A_J-P12.5"         "FVB_NJ-P12.5"      "C3H_HeJ-P12.5"
[22] "LP_J-P12.5"        "129S1_SvImJ-P12.5" "DBA_2J-P12.5"
[25] "AKR_J-P12.5"       "CBA_J-P12.5"       "NZO_HlLtJ-P12.5"
[28] "NOD_ShiLtJ-P12.5"  "WSB_EiJ-P12.5"     "CAST_EiJ-P12.5"
[31] "PWK_PhJ-P12.5"     "SPRET_EiJ-P12.5"   "C57BL_6NJ-P20.5"
[34] "BALB_cJ-P20.5"     "A_J-P20.5"         "FVB_NJ-P20.5"
[37] "C3H_HeJ-P20.5"     "LP_J-P20.5"        "129S1_SvImJ-P20.5"
[40] "DBA_2J-P20.5"      "AKR_J-P20.5"       "CBA_J-P20.5"
[43] "NZO_HlLtJ-P20.5"   "NOD_ShiLtJ-P20.5"  "WSB_EiJ-P20.5"
[46] "CAST_EiJ-P20.5"    "PWK_PhJ-P20.5"     "SPRET_EiJ-P20.5"

        C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5   FVB_NJ-E16.5 C3H_HeJ-E16.5
Apitd1    186.5999        144.26279     195.02856  220.9111      169.15685
CNIH4    1277.3433       1208.08110    1424.79309 1336.2176     1505.72629
Gm10643    53.6215         55.92554      45.74002   52.5014       36.48118
H2afx    3088.3145       2484.74144    2927.16153 2598.0250     2883.63046
INAFM1    135.3098        127.19335     126.36084  264.0263      275.76112
MORC3    3723.1773       3635.75672    3910.31747 3952.8212     4269.08583
RPL32   13926.9129      11617.09851   13158.53536 7487.7282    21724.18801
RPLP2    4973.0344       4757.73607    5724.36371 6520.2377     5732.38805
exosc6    199.4893        183.91017     157.92961  172.1244      186.78855
rpl21    6003.5194       8019.86946   12128.96748 4519.0192     7767.51057
        LP_J-E16.5  129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
Apitd1    154.02819   164.93193        175.76449     153.26491   140.14114 ⋯
CNIH4    1447.59464  1319.34005       1322.56073    1414.76307  1280.95663 ⋯
Gm10643    42.97567    43.78178         36.59279      48.84097    38.29418 ⋯
H2afx    3254.24248  2944.86810       2679.16090    2585.72100  3563.17794 ⋯
INAFM1    260.55065   271.95702        256.57559     121.81279   341.68181 ⋯
MORC3    4201.43991  3693.42744       3871.84767    4092.37338  4083.51432 ⋯
RPL32   11839.62603 12449.66972       3284.08974   14919.79466 18973.44929 ⋯
RPLP2    4845.63968  5507.36777       4516.35205    5567.14289  4832.30599 ⋯
exosc6    154.68134   156.30546        137.20766     163.15442   216.87229 ⋯
rpl21    6007.72323 10447.98667       9142.82245    4840.59695  8959.20365 ⋯
        129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
Apitd1    297.18520         304.78848   241.47205    243.58931   357.36852
CNIH4    1184.26917        1136.64208  1192.41046   1150.95265  1519.26816
Gm10643    69.17175          43.49094    73.99651     49.89119    48.61480
H2afx   12774.96718       13469.09525  8497.45968  10106.20231 12291.65018
INAFM1    170.87502         191.55282    74.74541    148.77400    75.73774
MORC3    7737.01822        7541.80924  6810.00756   5605.07606  6167.40562
RPL32    6334.54283        1720.53446  7244.54525   8684.46324  6918.01324
RPLP2    2255.82274        2428.43185  2340.23852   2388.83052  2540.04858
exosc6    113.79207         130.05907   108.07484    118.60849   141.89174
rpl21    4601.13919        3785.33540  2037.81226   3394.77411  2863.48343
        NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
Apitd1    359.3081         146.94067     311.60921      285.36807
CNIH4    1417.7105        1291.65367    1073.88548     1755.30650
Gm10643    67.6549          51.09546      51.46356       59.89212
H2afx   11016.4260       10373.16305   15983.29987     9591.19473
INAFM1    146.1040          96.90677      50.93974      182.76179
MORC3    6216.3419        4339.44386    5533.68689     6196.90557
RPL32    7953.4720        6104.22222    7044.21674    10862.30763
RPLP2    2392.6447        3541.93025    3410.53557     3479.65495
exosc6    133.7171         160.96455     174.98231      169.08491
rpl21    3311.7567        3534.26995    3400.78480     3749.00566
        SPRET_EiJ-P20.5
Apitd1    46.79141
CNIH4   1856.66077
Gm10643   97.99458
H2afx   7595.33162
INAFM1   173.04268
MORC3   5044.49227
RPL32   5356.38218
RPLP2   3660.57240
exosc6   175.22765
rpl21   3094.85985

        C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5  FVB_NJ-E16.5 C3H_HeJ-E16.5
Apitd1  -0.4955904      -0.99630890   -0.3959045 -0.08979283  -0.7018880
CNIH4   -0.4829058      -0.83859763    0.2743135 -0.18056041   0.6899410
Gm10643 -0.1425354       0.01795631   -0.6915331 -0.22055761  -1.3364730
H2afx   -1.1108865      -1.24995480   -1.1480175 -1.22385332  -1.1580474
INAFM1  -0.1277488      -0.24327377   -0.2551232  1.70433332   1.8713609
MORC3   -1.1541272      -1.23148311   -0.9885323 -0.95092190  -0.6710685
RPL32    1.0157213       0.51036882    0.8476119 -0.39307502   2.7216473
RPLP2    0.5794314       0.43557215    1.0814586  1.61325001   1.0868204
exosc6   1.3859386       0.81165259   -0.1460588  0.37719658   0.9177573
rpl21    0.4902852       1.39759571    3.2465940 -0.17770526   1.2840401
        LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
Apitd1  -0.8808140 -0.7518560        -0.6237398   -0.88984126 -1.0450554  ⋯
CNIH4    0.3914095 -0.2672341        -0.2506945    0.22280495 -0.4643498  ⋯
Gm10643 -0.8840881 -0.8279377        -1.3286988   -0.47553086 -1.2101855  ⋯
H2afx   -1.0726552 -1.1439377        -1.2051589   -1.22668825 -1.0014739  ⋯
INAFM1   1.6548633  1.8172154         1.5982843   -0.31985789  2.8096411  ⋯
MORC3   -0.7309264 -1.1804520        -1.0225731   -0.82743626 -0.8352754  ⋯
RPL32    0.5590545  0.6925228        -1.3127676    1.23294883  2.1198272  ⋯
RPLP2    0.4943081  0.9364651         0.2742829    0.97640598  0.4853987  ⋯
exosc6  -0.2657985 -0.2059292        -0.9099238    0.04654134  2.0267224  ⋯
rpl21    0.4921768  2.4901918         1.9028984   -0.03300279  1.8202742  ⋯
        129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
Apitd1   0.8122972         0.9022208    0.1533803   0.17842109  1.5240824
CNIH4   -0.9608823        -1.2054683   -0.9190733  -1.13197727  0.7594844
Gm10643  0.9406435        -0.8481962    1.2767200  -0.40237601 -0.4912850
H2afx    1.1210004         1.2809334    0.1354265   0.50609439  1.0096401
INAFM1   0.3784679         0.6727847   -0.9897899   0.06389369 -0.9756656
MORC3    2.3976044         2.2248696    1.5773195   0.51111051  1.0086996
RPL32   -0.6453746        -1.6548499   -0.4462798  -0.13124747 -0.5177200
RPLP2   -1.2361698        -1.1208349   -1.1797644  -1.14729596 -1.0462543
exosc6  -1.7730838        -1.1734398   -1.9838357  -1.59553786 -0.7372566
rpl21   -0.1407532        -0.5078459   -1.2941906  -0.68358936 -0.9226578
        NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
Apitd1   1.54702129      -0.96463769    0.9828892      0.6725365
CNIH4    0.23794137      -0.40941583   -1.5277510      1.9716448
Gm10643  0.83498495      -0.31849102   -0.2928499      0.2942554
H2afx    0.71581764       0.56760441    1.8602275      0.3874323
INAFM1   0.02589071      -0.67435693   -1.3286271      0.5476578
MORC3    1.05200195      -0.60881075    0.4479403      1.0348033
RPL32   -0.29117732      -0.69576522   -0.4901086      0.3452320
RPLP2   -1.14474739      -0.37681155   -0.4646076     -0.4184230
exosc6  -1.03859659      -0.03418303    0.4825485      0.2651549
rpl21   -0.72094528      -0.62081948   -0.6808847     -0.5241934
        SPRET_EiJ-P20.5
Apitd1  -2.14909823
CNIH4    2.49214341
Gm10643  2.94834597
H2afx   -0.07243150
INAFM1   0.40932121
MORC3    0.01506616
RPL32   -0.85938132
RPLP2   -0.29753660
exosc6   0.49159239
rpl21   -0.81854378

Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

Warning message in brewer.pal(11, "GnBu"):
“n too large, allowed maximum for palette GnBu is 9
Returning the palette you asked for with that many colors
”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

In [40]:
#utr gene list 1700029I15Rik


marker_gene_list <- c('NOCT','Ddx4')
marker_gene_sub_1 <- subset(norm_counts, tolower(row.names(norm_counts)) %in% tolower(marker_gene_list))
marker_gene_sub_1

#list order 'Sycp3', 'Meiob','Dnmt3b','Dnmt3c', 'Dnmt1','Dnmt3a','Ddx4','Dnmt3l', 'Nanos2','Nanos3'

# Desired order
desired_gene_order <- c('NOCT','Ddx4')


# Reorder dataframe by raw 
#marker_gene_sub_1 <- marker_gene_sub_1[desired_gene_order, ]
# Remove duplicates from the samplenames_order vector
unique_samplenames_order <- unique(samplenames_order)
unique_samplenames_order
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)
# Create a heatmap with log-normalized values
#heatmap.2(log2(piwi_sub_1+ 1), scale = "none", col = colorRampPalette(c("blue", "white", "red"))(100))

marker_gene_sub_1 <- as.data.frame.matrix(marker_gene_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate


foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(marker_gene_sub_1), ncol = 0))

row.names(foo_sub1_mean) <- row.names(marker_gene_sub_1)

for (sample in unique_samplenames_order) {
foo_sub1_mean[sample] <- apply(marker_gene_sub_1[ , grepl(paste0( "^",sample) , names( marker_gene_sub_1) ) ], 1, mean)
}

foo_sub1_mean

# Calculate Z-scores row-wise
z_scores <- t(scale(t(foo_sub1_mean)))

# Convert the matrix to a data frame
z_scores_df <- as.data.frame(z_scores)
z_scores_df

# Create a PDF graphics device
pdf("z-score_heatmap_noct_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a bright color palette (e.g., using the 'viridis' palette)
myCol <- colorRampPalette(brewer.pal(11, "RdBu"))(100)
heatmap.2(t(scale(t(foo_sub1_mean))),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = rev(myCol),
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()


# Create a PDF graphics device
pdf("log10_heatmap_noct_all_timepoints.pdf",width=14,height=6)  # Adjust width and height as needed

# Adjust font size and family for better quality labels
par(cex.lab = 6, family = "sans")  # You can adjust the font size and family here
# Define a blue color palette
myCol <- colorRampPalette(brewer.pal(11, "GnBu"))(100)


heatmap.2(log10(as.matrix(foo_sub1_mean) + 1),
          Rowv = FALSE,     # Dendrogram for rows
          Colv = FALSE,    # No dendrogram for columns
          col = myCol,
          main = "Marker Genes",
          center = NULL,
          trace = "none",
          keysize = 1,
          margins = c(10, 10),  # Adjust margin values as needed (right, bottom, top, left)
          offsetRow = 0,
          offsetCol = 0,
          density.info = 'histogram',
          sepcol = rep(16, ncol(foo_sub1_mean) %/% 16)
)
dev.off()

     129S1_SvImJ-P12.5.1 129S1_SvImJ-P12.5.2 129S1_SvImJ-P12.5.3
DDX4 5638.0610           7293.0914           5985.9779
NOCT  629.5503            767.0564            640.9721
     129S1_SvImJ-E16.5.1 129S1_SvImJ-E16.5.2 129S1_SvImJ-E16.5.3
DDX4 3700.5084           3441.4190           2887.1204
NOCT  246.8897            316.5185            312.2109
     129S1_SvImJ-P20.5.1 129S1_SvImJ-P20.5.2 129S1_SvImJ-P20.5.3 A_J-P12.5.1 ⋯
DDX4 24758.1819          27632.7179          25099.7313          5924.169    ⋯
NOCT   948.3003            964.1789            930.0968          1493.227    ⋯
     SPRET_EiJ-P20.5.3 WSB_EiJ-P12.5.1 WSB_EiJ-P12.5.2 WSB_EiJ-P12.5.3
DDX4 10993.7111        2376.0595       1216.3684       1370.1685
NOCT   795.7855         628.4426        592.0581        597.3633
     WSB_EiJ-E16.5.1 WSB_EiJ-E16.5.2 WSB_EiJ-E16.5.3 WSB_EiJ-P20.5.1
DDX4 1268.5064       1051.0394       903.0715        9433.9800
NOCT  246.6259        245.0092       256.7839         645.4513
     WSB_EiJ-P20.5.2 WSB_EiJ-P20.5.3
DDX4 8546.610        8001.7506
NOCT  613.839         578.5815

 [1] "C57BL_6NJ-E16.5"   "BALB_cJ-E16.5"     "A_J-E16.5"
 [4] "FVB_NJ-E16.5"      "C3H_HeJ-E16.5"     "LP_J-E16.5"
 [7] "129S1_SvImJ-E16.5" "DBA_2J-E16.5"      "AKR_J-E16.5"
[10] "CBA_J-E16.5"       "NZO_HlLtJ-E16.5"   "NOD_ShiLtJ-E16.5"
[13] "WSB_EiJ-E16.5"     "CAST_EiJ-E16.5"    "PWK_PhJ-E16.5"
[16] "SPRET_EiJ-E16.5"   "C57BL_6NJ-P12.5"   "BALB_cJ-P12.5"
[19] "A_J-P12.5"         "FVB_NJ-P12.5"      "C3H_HeJ-P12.5"
[22] "LP_J-P12.5"        "129S1_SvImJ-P12.5" "DBA_2J-P12.5"
[25] "AKR_J-P12.5"       "CBA_J-P12.5"       "NZO_HlLtJ-P12.5"
[28] "NOD_ShiLtJ-P12.5"  "WSB_EiJ-P12.5"     "CAST_EiJ-P12.5"
[31] "PWK_PhJ-P12.5"     "SPRET_EiJ-P12.5"   "C57BL_6NJ-P20.5"
[34] "BALB_cJ-P20.5"     "A_J-P20.5"         "FVB_NJ-P20.5"
[37] "C3H_HeJ-P20.5"     "LP_J-P20.5"        "129S1_SvImJ-P20.5"
[40] "DBA_2J-P20.5"      "AKR_J-P20.5"       "CBA_J-P20.5"
[43] "NZO_HlLtJ-P20.5"   "NOD_ShiLtJ-P20.5"  "WSB_EiJ-P20.5"
[46] "CAST_EiJ-P20.5"    "PWK_PhJ-P20.5"     "SPRET_EiJ-P20.5"

     C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5 FVB_NJ-E16.5 C3H_HeJ-E16.5
DDX4 2572.6826       2493.0033     3256.6010 2098.8134    2501.5441
NOCT  701.0658        633.7133      749.6043  306.7912     221.1254
     LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
DDX4 4068.9363  3343.016          3568.9868    3864.8799   1195.4542   ⋯
NOCT  272.8198   291.873           682.7464     607.0855    252.0388   ⋯
     129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
DDX4 25830.2103        21139.075    21432.849   15125.635   15161.333
NOCT   947.5253         1190.339     1031.009     702.385    1159.232
     NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
DDX4 16843.0384       8660.780      12414.5871     16380.1080
NOCT   744.3237        612.624        643.3563       697.7565
     SPRET_EiJ-P20.5
DDX4 9879.8751
NOCT  788.7704

     C57BL_6NJ-E16.5 BALB_cJ-E16.5 A_J-E16.5    FVB_NJ-E16.5 C3H_HeJ-E16.5
DDX4 -0.8065021      -0.8176134    -0.711129615 -0.8725832   -0.8164224
NOCT -0.1455330      -0.3538628     0.004602895 -1.3650744   -1.6300497
     LP_J-E16.5 129S1_SvImJ-E16.5 DBA_2J-E16.5 AKR_J-E16.5 CBA_J-E16.5 ⋯
DDX4 -0.5978494 -0.699079         -0.6675674   -0.6263051  -0.9985567  ⋯
NOCT -1.4701524 -1.411218         -0.2021971   -0.4362259  -1.5344307  ⋯
     129S1_SvImJ-P20.5 DBA_2J-P20.5 AKR_J-P20.5 CBA_J-P20.5 NZO_HlLtJ-P20.5
DDX4 2.4367619         1.782583     1.8235496    0.9440080  0.9489862
NOCT 0.6167978         1.367851     0.8750232   -0.1414526  1.2716346
     NOD_ShiLtJ-P20.5 WSB_EiJ-P20.5 CAST_EiJ-P20.5 PWK_PhJ-P20.5
DDX4  1.18350011       0.04248361    0.5659522      1.118944
NOCT -0.01173071      -0.41909483   -0.3240359     -0.155769
     SPRET_EiJ-P20.5
DDX4 0.2124865
NOCT 0.1257486

Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(t(scale(t(foo_sub1_mean))), Rowv = FALSE, Colv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2

Warning message in brewer.pal(11, "GnBu"):
“n too large, allowed maximum for palette GnBu is 9
Returning the palette you asked for with that many colors
”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = FALSE, :
“Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row dendogram.”
Warning message in heatmap.2(log10(as.matrix(foo_sub1_mean) + 1), Rowv = FALSE, :
“Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column dendogram.”

png
  2