In [1]:
###testing R in jyupter

In [1]:
library(purrr)
library(tidyverse)
library(edgeR)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ dplyr   1.0.9
✔ tibble  3.1.7     ✔ stringr 1.4.0
✔ tidyr   1.2.0     ✔ forcats 0.5.1
✔ readr   2.1.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: limma

In [2]:
lfbl=function(pattern,level=1){
    if(!exists("lof")) lof=vector("character",0)
    temp=list.files(pattern=pattern,no..=T)
    if(!is.na(temp[1])) lof=c(lof,paste0(getwd(),"/",temp))
    if(level>0){
        dirf=list.dirs(full.names=F,recursive=F)
        for(i in dirf){
            setwd(i)
            lof=c(lof,lfbl(pattern,level-1))
            setwd("..")
        }
    }
    return(lof)
}

In [3]:
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/")
getwd()

[1] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount"

In [4]:
f_files = lfbl(pattern = 'raw.count.gz$',level=0)
f_files

  [1] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.1.raw.count.gz"
  [2] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.2.raw.count.gz"
  [3] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.3.raw.count.gz"
  [4] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.1.raw.count.gz"
  [5] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.2.raw.count.gz"
  [6] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.3.raw.count.gz"
  [7] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-20.5dpp.1.raw.count.gz"
  [8] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-20.5dpp.2.raw.count.gz"
  [9] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-20.5dpp.3.raw.count.gz"
 [10] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.1.raw.count.gz"
 [11] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.2.raw.count.gz"
 [12] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.3.raw.count.gz"
 [13] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.1.raw.count.gz"
 [14] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.2.raw.count.gz"
 [15] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.3.raw.count.gz"
 [16] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-20.5dpp.1.raw.count.gz"
 [17] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-20.5dpp.2.raw.count.gz"
 [18] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-20.5dpp.3.raw.count.gz"
 [19] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.1.raw.count.gz"
 [20] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.2.raw.count.gz"
 [21] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.3.raw.count.gz"
 [22] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.1.raw.count.gz"
 [23] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.2.raw.count.gz"
 [24] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.3.raw.count.gz"
 [25] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-20.5dpp.1.raw.count.gz"
 [26] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-20.5dpp.2.raw.count.gz"
 [27] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-20.5dpp.3.raw.count.gz"
 [28] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.1.raw.count.gz"
 [29] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.2.raw.count.gz"
 [30] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.3.raw.count.gz"
 [31] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.1.raw.count.gz"
 [32] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.2.raw.count.gz"
 [33] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.3.raw.count.gz"
 [34] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-20.5dpp.1.raw.count.gz"
 [35] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-20.5dpp.2.raw.count.gz"
 [36] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-20.5dpp.3.raw.count.gz"
 [37] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.1.raw.count.gz"
 [38] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.2.raw.count.gz"
 [39] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.3.raw.count.gz"
 [40] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.1.raw.count.gz"
 [41] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.2.raw.count.gz"
 [42] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.3.raw.count.gz"
 [43] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-20.5dpp.1.raw.count.gz"
 [44] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-20.5dpp.2.raw.count.gz"
 [45] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-20.5dpp.3.raw.count.gz"
 [46] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.1.raw.count.gz"
 [47] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.2.raw.count.gz"
 [48] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.3.raw.count.gz"
 [49] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.1.raw.count.gz"
 [50] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.2.raw.count.gz"
 [51] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.3.raw.count.gz"
 [52] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-20.5dpp.1.raw.count.gz"
 [53] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-20.5dpp.2.raw.count.gz"
 [54] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-20.5dpp.3.raw.count.gz"
 [55] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.1.raw.count.gz"
 [56] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.2.raw.count.gz"
 [57] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.3.raw.count.gz"
 [58] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.1.raw.count.gz"
 [59] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.2.raw.count.gz"
 [60] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.3.raw.count.gz"
 [61] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-20.5dpp.1.raw.count.gz"
 [62] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-20.5dpp.2.raw.count.gz"
 [63] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-20.5dpp.3.raw.count.gz"
 [64] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.1.raw.count.gz"
 [65] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.2.raw.count.gz"
 [66] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.3.raw.count.gz"
 [67] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.1.raw.count.gz"
 [68] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.2.raw.count.gz"
 [69] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.3.raw.count.gz"
 [70] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-20.5dpp.1.raw.count.gz"
 [71] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-20.5dpp.2.raw.count.gz"
 [72] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-20.5dpp.3.raw.count.gz"
 [73] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.1.raw.count.gz"
 [74] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.2.raw.count.gz"
 [75] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.3.raw.count.gz"
 [76] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.1.raw.count.gz"
 [77] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.2.raw.count.gz"
 [78] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.3.raw.count.gz"
 [79] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-20.5dpp.1.raw.count.gz"
 [80] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-20.5dpp.2.raw.count.gz"
 [81] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-20.5dpp.3.raw.count.gz"
 [82] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.1.raw.count.gz"
 [83] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.2.raw.count.gz"
 [84] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.3.raw.count.gz"
 [85] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.1.raw.count.gz"
 [86] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.2.raw.count.gz"
 [87] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.3.raw.count.gz"
 [88] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-20.5dpp.1.raw.count.gz"
 [89] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-20.5dpp.2.raw.count.gz"
 [90] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-20.5dpp.3.raw.count.gz"
 [91] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.1.raw.count.gz"
 [92] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.2.raw.count.gz"
 [93] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.3.raw.count.gz"
 [94] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.1.raw.count.gz"
 [95] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.2.raw.count.gz"
 [96] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.3.raw.count.gz"
 [97] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-20.5dpp.1.raw.count.gz"
 [98] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-20.5dpp.2.raw.count.gz"
 [99] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-20.5dpp.3.raw.count.gz"
[100] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.1.raw.count.gz"
[101] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.2.raw.count.gz"
[102] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.3.raw.count.gz"
[103] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.1.raw.count.gz"
[104] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.2.raw.count.gz"
[105] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.3.raw.count.gz"
[106] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-20.5dpp.1.raw.count.gz"
[107] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-20.5dpp.2.raw.count.gz"
[108] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-20.5dpp.3.raw.count.gz"
[109] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.1.raw.count.gz"
[110] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.2.raw.count.gz"
[111] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.3.raw.count.gz"
[112] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.1.raw.count.gz"
[113] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.2.raw.count.gz"
[114] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.3.raw.count.gz"
[115] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-20.5dpp.1.raw.count.gz"
[116] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-20.5dpp.2.raw.count.gz"
[117] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-20.5dpp.3.raw.count.gz"
[118] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.1.raw.count.gz"
[119] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.2.raw.count.gz"
[120] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.3.raw.count.gz"
[121] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.1.raw.count.gz"
[122] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.2.raw.count.gz"
[123] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.3.raw.count.gz"
[124] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-20.5dpp.1.raw.count.gz"
[125] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-20.5dpp.2.raw.count.gz"
[126] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-20.5dpp.3.raw.count.gz"
[127] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.1.raw.count.gz"
[128] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.2.raw.count.gz"
[129] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.3.raw.count.gz"
[130] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.1.raw.count.gz"
[131] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.2.raw.count.gz"
[132] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.3.raw.count.gz"
[133] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-20.5dpp.1.raw.count.gz"
[134] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-20.5dpp.2.raw.count.gz"
[135] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-20.5dpp.3.raw.count.gz"
[136] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.1.raw.count.gz"
[137] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.2.raw.count.gz"
[138] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.3.raw.count.gz"
[139] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.1.raw.count.gz"
[140] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.2.raw.count.gz"
[141] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.3.raw.count.gz"
[142] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-20.5dpp.1.raw.count.gz"
[143] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-20.5dpp.2.raw.count.gz"
[144] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-20.5dpp.3.raw.count.gz"

In [52]:

samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))))
samplenames

 [1] "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp"
 [4] "A_J-12.5dpp"         "A_J-12.5dpp"         "A_J-12.5dpp"
 [7] "AKR_J-12.5dpp"       "AKR_J-12.5dpp"       "AKR_J-12.5dpp"
[10] "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"
[13] "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"
[16] "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"
[19] "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"
[22] "CBA_J-12.5dpp"       "CBA_J-12.5dpp"       "CBA_J-12.5dpp"
[25] "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"
[28] "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"
[31] "LP_J-12.5dpp"        "LP_J-12.5dpp"        "LP_J-12.5dpp"
[34] "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"
[37] "NZO_HlLtJ-12.5dpp"   "NZO_HlLtJ-12.5dpp"   "NZO_HlLtJ-12.5dpp"
[40] "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"
[43] "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"
[46] "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"

In [53]:

#list of sample names with replicates 
lables = tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))))

lables

 [1] "129S1_SvImJ-12.5dpp.1" "129S1_SvImJ-12.5dpp.2" "129S1_SvImJ-12.5dpp.3"
 [4] "A_J-12.5dpp.1"         "A_J-12.5dpp.2"         "A_J-12.5dpp.3"
 [7] "AKR_J-12.5dpp.1"       "AKR_J-12.5dpp.2"       "AKR_J-12.5dpp.3"
[10] "BALB_cJ-12.5dpp.1"     "BALB_cJ-12.5dpp.2"     "BALB_cJ-12.5dpp.3"
[13] "C3H_HeJ-12.5dpp.1"     "C3H_HeJ-12.5dpp.2"     "C3H_HeJ-12.5dpp.3"
[16] "C57BL_6NJ-12.5dpp.1"   "C57BL_6NJ-12.5dpp.2"   "C57BL_6NJ-12.5dpp.3"
[19] "CAST_EiJ-12.5dpp.1"    "CAST_EiJ-12.5dpp.2"    "CAST_EiJ-12.5dpp.3"
[22] "CBA_J-12.5dpp.1"       "CBA_J-12.5dpp.2"       "CBA_J-12.5dpp.3"
[25] "DBA_2J-12.5dpp.1"      "DBA_2J-12.5dpp.2"      "DBA_2J-12.5dpp.3"
[28] "FVB_NJ-12.5dpp.1"      "FVB_NJ-12.5dpp.2"      "FVB_NJ-12.5dpp.3"
[31] "LP_J-12.5dpp.1"        "LP_J-12.5dpp.2"        "LP_J-12.5dpp.3"
[34] "NOD_ShiLtJ-12.5dpp.1"  "NOD_ShiLtJ-12.5dpp.2"  "NOD_ShiLtJ-12.5dpp.3"
[37] "NZO_HlLtJ-12.5dpp.1"   "NZO_HlLtJ-12.5dpp.2"   "NZO_HlLtJ-12.5dpp.3"
[40] "PWK_PhJ-12.5dpp.1"     "PWK_PhJ-12.5dpp.2"     "PWK_PhJ-12.5dpp.3"
[43] "SPRET_EiJ-12.5dpp.1"   "SPRET_EiJ-12.5dpp.2"   "SPRET_EiJ-12.5dpp.3"
[46] "WSB_EiJ-12.5dpp.1"     "WSB_EiJ-12.5dpp.2"     "WSB_EiJ-12.5dpp.3"

In [54]:
	
df = readDGE(f_files, path=NULL, columns=c(1,3), group= samplenames, labels = lables,sep="\t" )

In [65]:
head(df)

An object of class "DGEList"
$samples
                                                                                                                                                   files
129S1_SvImJ-12.5dpp.1 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.1.raw.count.gz
129S1_SvImJ-12.5dpp.2 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.2.raw.count.gz
129S1_SvImJ-12.5dpp.3 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.3.raw.count.gz
A_J-12.5dpp.1                 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.1.raw.count.gz
A_J-12.5dpp.2                 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.2.raw.count.gz
                                    group lib.size norm.factors
129S1_SvImJ-12.5dpp.1 129S1_SvImJ-12.5dpp 35665240            1
129S1_SvImJ-12.5dpp.2 129S1_SvImJ-12.5dpp 56344296            1
129S1_SvImJ-12.5dpp.3 129S1_SvImJ-12.5dpp 35739075            1
A_J-12.5dpp.1                 A_J-12.5dpp 37456350            1
A_J-12.5dpp.2                 A_J-12.5dpp 60394672            1
43 more rows ...

$counts
                                      Samples
Tags                                   129S1_SvImJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                            638693
  GGGGATGTAGCTCAGTGGTAGAG                             129302
  TCACTTTGTAGACCAGGCTGGCCT                            129099
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                100025
  TACAGAGTGAGTTCCAGGACAG                               84777
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                    73265
                                      Samples
Tags                                   129S1_SvImJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                           1133155
  GGGGATGTAGCTCAGTGGTAGAG                             224610
  TCACTTTGTAGACCAGGCTGGCCT                            200425
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                130667
  TACAGAGTGAGTTCCAGGACAG                              123171
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                   148030
                                      Samples
Tags                                   129S1_SvImJ-12.5dpp.3 A_J-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                            744844        694455
  GGGGATGTAGCTCAGTGGTAGAG                             182632        115999
  TCACTTTGTAGACCAGGCTGGCCT                            119927        130843
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                110059        246742
  TACAGAGTGAGTTCCAGGACAG                               75979         53502
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                    87752        100273
                                      Samples
Tags                                   A_J-12.5dpp.2 A_J-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                    942803       1252940
  GGGGATGTAGCTCAGTGGTAGAG                     156616        224119
  TCACTTTGTAGACCAGGCTGGCCT                    186098        150822
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA        250355         38767
  TACAGAGTGAGTTCCAGGACAG                       49049         84607
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT           247920        139962
                                      Samples
Tags                                   AKR_J-12.5dpp.1 AKR_J-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                     1279520         1651514
  GGGGATGTAGCTCAGTGGTAGAG                       199362          299617
  TCACTTTGTAGACCAGGCTGGCCT                      262844          276275
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          207447          188074
  TACAGAGTGAGTTCCAGGACAG                        132228          144780
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT             147553          135207
                                      Samples
Tags                                   AKR_J-12.5dpp.3 BALB_cJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                     1477368            865512
  GGGGATGTAGCTCAGTGGTAGAG                       469663            189724
  TCACTTTGTAGACCAGGCTGGCCT                      213066            262418
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          317784            202701
  TACAGAGTGAGTTCCAGGACAG                        128666             86082
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT              22749            208167
                                      Samples
Tags                                   BALB_cJ-12.5dpp.2 BALB_cJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                        553850            877906
  GGGGATGTAGCTCAGTGGTAGAG                         178926            234783
  TCACTTTGTAGACCAGGCTGGCCT                        304115            464189
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            136896            172329
  TACAGAGTGAGTTCCAGGACAG                          147113            228574
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                33716             51794
                                      Samples
Tags                                   C3H_HeJ-12.5dpp.1 C3H_HeJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                       1745498           1509788
  GGGGATGTAGCTCAGTGGTAGAG                         555896            391528
  TCACTTTGTAGACCAGGCTGGCCT                        188753            150289
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             66820             87952
  TACAGAGTGAGTTCCAGGACAG                           83655             83174
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT               133545            142491
                                      Samples
Tags                                   C3H_HeJ-12.5dpp.3 C57BL_6NJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                        519228              776042
  GGGGATGTAGCTCAGTGGTAGAG                         123697              212250
  TCACTTTGTAGACCAGGCTGGCCT                         91122              338819
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             48882               48143
  TACAGAGTGAGTTCCAGGACAG                           23472              112141
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT               207840               29669
                                      Samples
Tags                                   C57BL_6NJ-12.5dpp.2 C57BL_6NJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                          649994             1042636
  GGGGATGTAGCTCAGTGGTAGAG                           169211              246349
  TCACTTTGTAGACCAGGCTGGCCT                          250687              249165
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA              111318               54257
  TACAGAGTGAGTTCCAGGACAG                             98743              135628
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                  63246               55801
                                      Samples
Tags                                   CAST_EiJ-12.5dpp.1 CAST_EiJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                         535048             183674
  GGGGATGTAGCTCAGTGGTAGAG                          172336             104060
  TCACTTTGTAGACCAGGCTGGCCT                         211244             253256
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA              75797              64897
  TACAGAGTGAGTTCCAGGACAG                            89026              91981
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                 17766              19453
                                      Samples
Tags                                   CAST_EiJ-12.5dpp.3 CBA_J-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                        2014469         2885757
  GGGGATGTAGCTCAGTGGTAGAG                          583403         1095998
  TCACTTTGTAGACCAGGCTGGCCT                         400731          444987
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             120642          443525
  TACAGAGTGAGTTCCAGGACAG                           194563          287607
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                 97269          139036
                                      Samples
Tags                                   CBA_J-12.5dpp.2 CBA_J-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                     3334121         1768003
  GGGGATGTAGCTCAGTGGTAGAG                      1126288          403402
  TCACTTTGTAGACCAGGCTGGCCT                      275160          287367
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          235203          143756
  TACAGAGTGAGTTCCAGGACAG                        198775          208428
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT             180860          231886
                                      Samples
Tags                                   DBA_2J-12.5dpp.1 DBA_2J-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                      1003704           476085
  GGGGATGTAGCTCAGTGGTAGAG                        265532           129129
  TCACTTTGTAGACCAGGCTGGCCT                       161629           168962
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            14343           143421
  TACAGAGTGAGTTCCAGGACAG                          90425            53596
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT               92629            30292
                                      Samples
Tags                                   DBA_2J-12.5dpp.3 FVB_NJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                       580738          1937690
  GGGGATGTAGCTCAGTGGTAGAG                        200484           319621
  TCACTTTGTAGACCAGGCTGGCCT                       379238           158394
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           141501            80164
  TACAGAGTGAGTTCCAGGACAG                         215156           133314
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT              129210           169654
                                      Samples
Tags                                   FVB_NJ-12.5dpp.2 FVB_NJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                       875442          1122904
  GGGGATGTAGCTCAGTGGTAGAG                        169199           228730
  TCACTTTGTAGACCAGGCTGGCCT                        89880           150222
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           162056           125963
  TACAGAGTGAGTTCCAGGACAG                          66190           114103
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT              101875           191266
                                      Samples
Tags                                   LP_J-12.5dpp.1 LP_J-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                    2364642         366085
  GGGGATGTAGCTCAGTGGTAGAG                      517310          98773
  TCACTTTGTAGACCAGGCTGGCCT                     453524         245004
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          99359          31323
  TACAGAGTGAGTTCCAGGACAG                       349947         159740
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT            299483          24827
                                      Samples
Tags                                   LP_J-12.5dpp.3 NOD_ShiLtJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                     511611               181881
  GGGGATGTAGCTCAGTGGTAGAG                      128841                44105
  TCACTTTGTAGACCAGGCTGGCCT                     340021               118573
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          58409                52102
  TACAGAGTGAGTTCCAGGACAG                       192852                39056
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT             67281                33817
                                      Samples
Tags                                   NOD_ShiLtJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                           612131
  GGGGATGTAGCTCAGTGGTAGAG                            203061
  TCACTTTGTAGACCAGGCTGGCCT                           657738
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                72340
  TACAGAGTGAGTTCCAGGACAG                             247116
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                   20057
                                      Samples
Tags                                   NOD_ShiLtJ-12.5dpp.3 NZO_HlLtJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                           449307             1476021
  GGGGATGTAGCTCAGTGGTAGAG                             63499              297621
  TCACTTTGTAGACCAGGCTGGCCT                           109795              239148
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA               111329              143070
  TACAGAGTGAGTTCCAGGACAG                              65065              121422
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                   74149              129181
                                      Samples
Tags                                   NZO_HlLtJ-12.5dpp.2 NZO_HlLtJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                          632478             1467150
  GGGGATGTAGCTCAGTGGTAGAG                           135629              286499
  TCACTTTGTAGACCAGGCTGGCCT                          164582              385253
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA               26854              124191
  TACAGAGTGAGTTCCAGGACAG                             79110              177346
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                 108072              225333
                                      Samples
Tags                                   PWK_PhJ-12.5dpp.1 PWK_PhJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                        571880            246805
  GGGGATGTAGCTCAGTGGTAGAG                         126260             85216
  TCACTTTGTAGACCAGGCTGGCCT                        546158            410722
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             49234             77386
  TACAGAGTGAGTTCCAGGACAG                          207836            152580
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT               145679             42744
                                      Samples
Tags                                   PWK_PhJ-12.5dpp.3 SPRET_EiJ-12.5dpp.1
  GTAGTCGTGGCCGAGTGGTTAAGG                        566777             3986358
  GGGGATGTAGCTCAGTGGTAGAG                         165116              857683
  TCACTTTGTAGACCAGGCTGGCCT                        408904              218355
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            158192              641985
  TACAGAGTGAGTTCCAGGACAG                          114049               54724
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT               134816              298138
                                      Samples
Tags                                   SPRET_EiJ-12.5dpp.2 SPRET_EiJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                         3822467             2851329
  GGGGATGTAGCTCAGTGGTAGAG                           865670              791467
  TCACTTTGTAGACCAGGCTGGCCT                          266510              276570
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA              533770              509945
  TACAGAGTGAGTTCCAGGACAG                             62967               83220
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                  57195               21505
                                      Samples
Tags                                   WSB_EiJ-12.5dpp.1 WSB_EiJ-12.5dpp.2
  GTAGTCGTGGCCGAGTGGTTAAGG                       6922944           4050697
  GGGGATGTAGCTCAGTGGTAGAG                        1532876            667443
  TCACTTTGTAGACCAGGCTGGCCT                        550691            653933
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           1630689            525934
  TACAGAGTGAGTTCCAGGACAG                          255937            290655
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                55388             62871
                                      Samples
Tags                                   WSB_EiJ-12.5dpp.3
  GTAGTCGTGGCCGAGTGGTTAAGG                      10338438
  GGGGATGTAGCTCAGTGGTAGAG                        1281088
  TCACTTTGTAGACCAGGCTGGCCT                        807161
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           1159328
  TACAGAGTGAGTTCCAGGACAG                          448917
  GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT                44166

In [66]:
mircounts <- df$counts

In [67]:
dim(mircounts)

[1] 202794781        48

In [68]:
head(mircounts,n=100)

                                     129S1_SvImJ-12.5dpp.1
GTAGTCGTGGCCGAGTGGTTAAGG             638693
GGGGATGTAGCTCAGTGGTAGAG              129302
TCACTTTGTAGACCAGGCTGGCCT             129099
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 100025
TACAGAGTGAGTTCCAGGACAG                84777
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT     73265
TCACTCTGTAGACCAGGCTGGCCT              73261
TCACTTTGTAGACCAGGCTGGCC               68009
GTAGTCGTGGCTGAGTGGTTAAGG              67491
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT     61226
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA  58104
GACTCTTAGCGGTGGATCACTCGGCTC           58044
GTTTCCGTAGTGTAGTGGTTATCA              54463
GTTTCCGTAGTGTAGTGGTTATC               50608
TCTGAGTTCGAGGCTAGCCTGGTCT             49389
GAGAAAGACATATAGGATATG                 44709
AAGAAAGATTGCAAGAACTGCTAATT            42264
CGACTCTTAGCGGTGGATCACTCGGCT           38055
GGGGGTGTAGCTCAGTGGTAGAG               37268
GTAGTCGTGGCCGAGTGGTTAAG               34465
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA   33001
GGGGATGTAGCTCAGTGGTAGA                27613
ACCAGGATGGCCGAGTGGTTAAGG              27036
GACTCTTAGCGGTGGATCACTCGGCT            23832
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   23439
TCACTCTGTAGACCAGGCTGGCCTCGA           22927
GTCAGGATGGCCGAGCGGTCTAAGGC            22250
TACAAAGTGAGTTCCAGGACAG                21822
GAGAAAGGCATATAGGATATG                 21679
GGCCGTGATCGTATAGTGGTTAGTACTC          20913
⋮                                    ⋮
GGGTTCGTTTCCCGGTCAGGGAACCA           10184
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     10162
TCACTCTGTAGACCAGGCTGGCCTCGAA         10047
TCTTTGTGTAGCCCTGAAGACCATACC          10019
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA    9982
GAATTGCAGGACACATTGATCATCGAC           9690
GGCCGTGATCGTATAGTGGTTAGTACTCTG        9654
AGAAGACCCTGTTGAGCTTGACTCTAGT          9497
TTCCAATGCTGTAAGAACTGAGGCAC            9481
TACAGAGTGAGTTCCAGGACAGCCAATG          9464
GACGAGGTGGCCGAGTGGTTAAGG              9451
GGGGATGTAGCTCAGTGGTAG                 9449
CTCACTTTGTAGACCAGGCTGGCCT             9444
TTAATACCGAATGGATCTTCTGGCCC            9297
ATCCAACTCACAATCTTCTGGGCTCCT           9170
TCTGAGTTCGAGGCTAGCCTGGTC              8990
TACTGATGGATCAAAAACTGGCATAGGT          8984
TATATACTGATGGATCAAAAACTGGCATA         8928
TGAATCTGTAGATTGCTTTTGGCAAGA           8897
TCACTTTGTAGATCAGGCTGGCCT              8584
TTTCTGATACAGGACAATTCTTGGGC            8558
TGCAAGCTCAGAACCCAACAAACACGT           8553
GGCCGTGATCGTATAGTGGTTAGTACT           8387
GCATTGTGGTTCAATGGTAGAATTCTCGCCTCCCA   8366
CACTTTGTAGACCAGGCTGGCC                8343
TGAGTTGGATCCCAGACATTGGACAGTT          8324
TCACTCTGTAGACCAGGCTGGCCTTGAA          8319
TCTGAGTTCGAGGCTAGCCTGG                8279
CAAACGAGAACTTTGAAGGCCGAAGT            8267
AGAAAGATTGCAGAGCTCCAGATAAAC           8246
                                     129S1_SvImJ-12.5dpp.2
GTAGTCGTGGCCGAGTGGTTAAGG             1133155
GGGGATGTAGCTCAGTGGTAGAG               224610
TCACTTTGTAGACCAGGCTGGCCT              200425
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  130667
TACAGAGTGAGTTCCAGGACAG                123171
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT     148030
TCACTCTGTAGACCAGGCTGGCCT              114197
TCACTTTGTAGACCAGGCTGGCC               108333
GTAGTCGTGGCTGAGTGGTTAAGG              110733
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT     140112
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA   81484
GACTCTTAGCGGTGGATCACTCGGCTC           115044
GTTTCCGTAGTGTAGTGGTTATCA              176666
GTTTCCGTAGTGTAGTGGTTATC                65525
TCTGAGTTCGAGGCTAGCCTGGTCT              76135
GAGAAAGACATATAGGATATG                  84258
AAGAAAGATTGCAAGAACTGCTAATT             76526
CGACTCTTAGCGGTGGATCACTCGGCT            67340
GGGGGTGTAGCTCAGTGGTAGAG                56942
GTAGTCGTGGCCGAGTGGTTAAG                65860
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    43777
GGGGATGTAGCTCAGTGGTAGA                 36731
ACCAGGATGGCCGAGTGGTTAAGG               45123
GACTCTTAGCGGTGGATCACTCGGCT             39395
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT    58450
TCACTCTGTAGACCAGGCTGGCCTCGA            32494
GTCAGGATGGCCGAGCGGTCTAAGGC             26880
TACAAAGTGAGTTCCAGGACAG                 33055
GAGAAAGGCATATAGGATATG                  37820
GGCCGTGATCGTATAGTGGTTAGTACTC           33372
⋮                                    ⋮
GGGTTCGTTTCCCGGTCAGGGAACCA           12179
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     19036
TCACTCTGTAGACCAGGCTGGCCTCGAA         13103
TCTTTGTGTAGCCCTGAAGACCATACC          15460
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA   11646
GAATTGCAGGACACATTGATCATCGAC          20017
GGCCGTGATCGTATAGTGGTTAGTACTCTG       14442
AGAAGACCCTGTTGAGCTTGACTCTAGT         15298
TTCCAATGCTGTAAGAACTGAGGCAC           14563
TACAGAGTGAGTTCCAGGACAGCCAATG         14668
GACGAGGTGGCCGAGTGGTTAAGG             15363
GGGGATGTAGCTCAGTGGTAG                12737
CTCACTTTGTAGACCAGGCTGGCCT            14056
TTAATACCGAATGGATCTTCTGGCCC           16004
ATCCAACTCACAATCTTCTGGGCTCCT          16793
TCTGAGTTCGAGGCTAGCCTGGTC             13078
TACTGATGGATCAAAAACTGGCATAGGT         13567
TATATACTGATGGATCAAAAACTGGCATA        12168
TGAATCTGTAGATTGCTTTTGGCAAGA          14521
TCACTTTGTAGATCAGGCTGGCCT             11893
TTTCTGATACAGGACAATTCTTGGGC           13131
TGCAAGCTCAGAACCCAACAAACACGT          11663
GGCCGTGATCGTATAGTGGTTAGTACT          12449
GCATTGTGGTTCAATGGTAGAATTCTCGCCTCCCA   9881
CACTTTGTAGACCAGGCTGGCC               11791
TGAGTTGGATCCCAGACATTGGACAGTT         12555
TCACTCTGTAGACCAGGCTGGCCTTGAA         12137
TCTGAGTTCGAGGCTAGCCTGG               12215
CAAACGAGAACTTTGAAGGCCGAAGT           14742
AGAAAGATTGCAGAGCTCCAGATAAAC          13220
                                     129S1_SvImJ-12.5dpp.3 A_J-12.5dpp.1
GTAGTCGTGGCCGAGTGGTTAAGG             744844                694455
GGGGATGTAGCTCAGTGGTAGAG              182632                115999
TCACTTTGTAGACCAGGCTGGCCT             119927                130843
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 110059                246742
TACAGAGTGAGTTCCAGGACAG                75979                 53502
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT     87752                100273
TCACTCTGTAGACCAGGCTGGCCT              68036                 81102
TCACTTTGTAGACCAGGCTGGCC               79173                 60039
GTAGTCGTGGCTGAGTGGTTAAGG              70131                 78625
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT     77887                 64400
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA  54070                 88655
GACTCTTAGCGGTGGATCACTCGGCTC           82757                 74289
GTTTCCGTAGTGTAGTGGTTATCA             148855                 83901
GTTTCCGTAGTGTAGTGGTTATC               64482                 43000
TCTGAGTTCGAGGCTAGCCTGGTCT             44215                 43486
GAGAAAGACATATAGGATATG                 88052                 38478
AAGAAAGATTGCAAGAACTGCTAATT            68698                 55894
CGACTCTTAGCGGTGGATCACTCGGCT           41626                 53480
GGGGGTGTAGCTCAGTGGTAGAG               49200                 29958
GTAGTCGTGGCCGAGTGGTTAAG               61426                 29454
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA   32085                 62167
GGGGATGTAGCTCAGTGGTAGA                32595                 17510
ACCAGGATGGCCGAGTGGTTAAGG              27380                 29727
GACTCTTAGCGGTGGATCACTCGGCT            25036                 33303
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   37691                 38809
TCACTCTGTAGACCAGGCTGGCCTCGA           24110                 25202
GTCAGGATGGCCGAGCGGTCTAAGGC            25379                 21567
TACAAAGTGAGTTCCAGGACAG                21420                 16970
GAGAAAGGCATATAGGATATG                 32010                 17945
GGCCGTGATCGTATAGTGGTTAGTACTC          26025                 37092
⋮                                    ⋮                     ⋮
GGGTTCGTTTCCCGGTCAGGGAACCA           18838                 15017
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     12301                 12265
TCACTCTGTAGACCAGGCTGGCCTCGAA          9662                  9356
TCTTTGTGTAGCCCTGAAGACCATACC          11272                  3606
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA    8694                  9756
GAATTGCAGGACACATTGATCATCGAC          12685                 10616
GGCCGTGATCGTATAGTGGTTAGTACTCTG       11538                 14749
AGAAGACCCTGTTGAGCTTGACTCTAGT         11639                 10913
TTCCAATGCTGTAAGAACTGAGGCAC            7626                  8651
TACAGAGTGAGTTCCAGGACAGCCAATG         11227                  7692
GACGAGGTGGCCGAGTGGTTAAGG             11436                 10701
GGGGATGTAGCTCAGTGGTAG                11725                  5020
CTCACTTTGTAGACCAGGCTGGCCT             8622                 15242
TTAATACCGAATGGATCTTCTGGCCC           10177                  9477
ATCCAACTCACAATCTTCTGGGCTCCT          11133                 13074
TCTGAGTTCGAGGCTAGCCTGGTC              9916                  6530
TACTGATGGATCAAAAACTGGCATAGGT          9675                 12429
TATATACTGATGGATCAAAAACTGGCATA         8408                  5614
TGAATCTGTAGATTGCTTTTGGCAAGA          10921                 10120
TCACTTTGTAGATCAGGCTGGCCT              7186                  9202
TTTCTGATACAGGACAATTCTTGGGC            8013                 13746
TGCAAGCTCAGAACCCAACAAACACGT           7983                  3590
GGCCGTGATCGTATAGTGGTTAGTACT          10099                 12325
GCATTGTGGTTCAATGGTAGAATTCTCGCCTCCCA   7042                  9637
CACTTTGTAGACCAGGCTGGCC                7905                  5166
TGAGTTGGATCCCAGACATTGGACAGTT          8421                 11379
TCACTCTGTAGACCAGGCTGGCCTTGAA          8138                  7934
TCTGAGTTCGAGGCTAGCCTGG               12355                  6251
CAAACGAGAACTTTGAAGGCCGAAGT            8802                 10614
AGAAAGATTGCAGAGCTCCAGATAAAC          10144                 15497
                                     A_J-12.5dpp.2 A_J-12.5dpp.3
GTAGTCGTGGCCGAGTGGTTAAGG             942803        1252940
GGGGATGTAGCTCAGTGGTAGAG              156616         224119
TCACTTTGTAGACCAGGCTGGCCT             186098         150822
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 250355          38767
TACAGAGTGAGTTCCAGGACAG                49049          84607
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT    247920         139962
TCACTCTGTAGACCAGGCTGGCCT             119507          88904
TCACTTTGTAGACCAGGCTGGCC               76171          83176
GTAGTCGTGGCTGAGTGGTTAAGG              97291         132524
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT    128550          42939
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA 125326          45523
GACTCTTAGCGGTGGATCACTCGGCTC          123314          93472
GTTTCCGTAGTGTAGTGGTTATCA             147576         241781
GTTTCCGTAGTGTAGTGGTTATC               54755          88103
TCTGAGTTCGAGGCTAGCCTGGTCT             72483          49380
GAGAAAGACATATAGGATATG                 44311          96178
AAGAAAGATTGCAAGAACTGCTAATT           160252          89063
CGACTCTTAGCGGTGGATCACTCGGCT           88128          62708
GGGGGTGTAGCTCAGTGGTAGAG               44623          44112
GTAGTCGTGGCCGAGTGGTTAAG               40520          49577
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA   80420          13446
GGGGATGTAGCTCAGTGGTAGA                18847          29230
ACCAGGATGGCCGAGTGGTTAAGG              35959          53028
GACTCTTAGCGGTGGATCACTCGGCT            51179          38509
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   63678          31872
TCACTCTGTAGACCAGGCTGGCCTCGA           38358          26645
GTCAGGATGGCCGAGCGGTCTAAGGC            43393          26086
TACAAAGTGAGTTCCAGGACAG                18175          25520
GAGAAAGGCATATAGGATATG                 18837          40540
GGCCGTGATCGTATAGTGGTTAGTACTC          63003          36780
⋮                                    ⋮             ⋮
GGGTTCGTTTCCCGGTCAGGGAACCA           32621         14489
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     20276         13233
TCACTCTGTAGACCAGGCTGGCCTCGAA         14470          8882
TCTTTGTGTAGCCCTGAAGACCATACC           6088          4271
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA   14739          1549
GAATTGCAGGACACATTGATCATCGAC          18977         13447
GGCCGTGATCGTATAGTGGTTAGTACTCTG       24139         14565
AGAAGACCCTGTTGAGCTTGACTCTAGT         18881         12282
TTCCAATGCTGTAAGAACTGAGGCAC           13945         11160
TACAGAGTGAGTTCCAGGACAGCCAATG         12812          7772
GACGAGGTGGCCGAGTGGTTAAGG             14716         16967
GGGGATGTAGCTCAGTGGTAG                 4533         10551
CTCACTTTGTAGACCAGGCTGGCCT            22961         15213
TTAATACCGAATGGATCTTCTGGCCC           17126         11795
ATCCAACTCACAATCTTCTGGGCTCCT          22323         16287
TCTGAGTTCGAGGCTAGCCTGGTC             10514          8549
TACTGATGGATCAAAAACTGGCATAGGT         22224         12896
TATATACTGATGGATCAAAAACTGGCATA         9098          5566
TGAATCTGTAGATTGCTTTTGGCAAGA          18945         12053
TCACTTTGTAGATCAGGCTGGCCT             12325         10241
TTTCTGATACAGGACAATTCTTGGGC           22414         15679
TGCAAGCTCAGAACCCAACAAACACGT           5946          3451
GGCCGTGATCGTATAGTGGTTAGTACT          24352         13932
GCATTGTGGTTCAATGGTAGAATTCTCGCCTCCCA  12613          1541
CACTTTGTAGACCAGGCTGGCC                4814          7893
TGAGTTGGATCCCAGACATTGGACAGTT         19536         13243
TCACTCTGTAGACCAGGCTGGCCTTGAA         12493          8294
TCTGAGTTCGAGGCTAGCCTGG                7363          9961
CAAACGAGAACTTTGAAGGCCGAAGT           19110         11866
AGAAAGATTGCAGAGCTCCAGATAAAC          27226         16421
                                     AKR_J-12.5dpp.1 AKR_J-12.5dpp.2
GTAGTCGTGGCCGAGTGGTTAAGG             1279520         1651514
GGGGATGTAGCTCAGTGGTAGAG               199362          299617
TCACTTTGTAGACCAGGCTGGCCT              262844          276275
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  207447          188074
TACAGAGTGAGTTCCAGGACAG                132228          144780
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT     147553          135207
TCACTCTGTAGACCAGGCTGGCCT              144348          145840
TCACTTTGTAGACCAGGCTGGCC               138243          141442
GTAGTCGTGGCTGAGTGGTTAAGG              135957          165047
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT     100301          102846
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA  164153           87850
GACTCTTAGCGGTGGATCACTCGGCTC           130211          127039
GTTTCCGTAGTGTAGTGGTTATCA              107594          238334
GTTTCCGTAGTGTAGTGGTTATC               124367          122035
TCTGAGTTCGAGGCTAGCCTGGTCT             122291          132676
GAGAAAGACATATAGGATATG                 102741          145762
AAGAAAGATTGCAAGAACTGCTAATT            103348          125082
CGACTCTTAGCGGTGGATCACTCGGCT            84483           83515
GGGGGTGTAGCTCAGTGGTAGAG                57406           75550
GTAGTCGTGGCCGAGTGGTTAAG                77125           96986
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    62723           55043
GGGGATGTAGCTCAGTGGTAGA                 48938           54453
ACCAGGATGGCCGAGTGGTTAAGG               47882           61348
GACTCTTAGCGGTGGATCACTCGGCT             54390           56229
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT    22216           53506
TCACTCTGTAGACCAGGCTGGCCTCGA            31436           29047
GTCAGGATGGCCGAGCGGTCTAAGGC             60218           47307
TACAAAGTGAGTTCCAGGACAG                 36615           36828
GAGAAAGGCATATAGGATATG                  62842           69843
GGCCGTGATCGTATAGTGGTTAGTACTC           60866           50814
⋮                                    ⋮               ⋮
GGGTTCGTTTCCCGGTCAGGGAACCA           41748           28016
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     27912           24241
TCACTCTGTAGACCAGGCTGGCCTCGAA         11441           10965
TCTTTGTGTAGCCCTGAAGACCATACC          12805           11278
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA     423             395
GAATTGCAGGACACATTGATCATCGAC          19959           19235
GGCCGTGATCGTATAGTGGTTAGTACTCTG       23099           20589
AGAAGACCCTGTTGAGCTTGACTCTAGT         21539           19611
TTCCAATGCTGTAAGAACTGAGGCAC           19037           16970
TACAGAGTGAGTTCCAGGACAGCCAATG         17075           16873
GACGAGGTGGCCGAGTGGTTAAGG             21942           28292
GGGGATGTAGCTCAGTGGTAG                12797           20326
CTCACTTTGTAGACCAGGCTGGCCT            20881           22019
TTAATACCGAATGGATCTTCTGGCCC           20670           20137
ATCCAACTCACAATCTTCTGGGCTCCT          18870           20010
TCTGAGTTCGAGGCTAGCCTGGTC             21702           23919
TACTGATGGATCAAAAACTGGCATAGGT         24183           21727
TATATACTGATGGATCAAAAACTGGCATA        22841           19858
TGAATCTGTAGATTGCTTTTGGCAAGA          14647           13483
TCACTTTGTAGATCAGGCTGGCCT             17716           18880
TTTCTGATACAGGACAATTCTTGGGC           27538           24016
TGCAAGCTCAGAACCCAACAAACACGT           8385            7412
GGCCGTGATCGTATAGTGGTTAGTACT          25132           19397
GCATTGTGGTTCAATGGTAGAATTCTCGCCTCCCA    522             513
CACTTTGTAGACCAGGCTGGCC               14310           15506
TGAGTTGGATCCCAGACATTGGACAGTT         19730           20935
TCACTCTGTAGACCAGGCTGGCCTTGAA         12766           11509
TCTGAGTTCGAGGCTAGCCTGG               20542           21728
CAAACGAGAACTTTGAAGGCCGAAGT           22299           20389
AGAAAGATTGCAGAGCTCCAGATAAAC          25884           24491
                                     AKR_J-12.5dpp.3 BALB_cJ-12.5dpp.1 ⋯
GTAGTCGTGGCCGAGTGGTTAAGG             1477368         865512            ⋯
GGGGATGTAGCTCAGTGGTAGAG               469663         189724            ⋯
TCACTTTGTAGACCAGGCTGGCCT              213066         262418            ⋯
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  317784         202701            ⋯
TACAGAGTGAGTTCCAGGACAG                128666          86082            ⋯
GCCCGGCTAGCTCAGTCGGTAGAGCATGGGACT      22749         208167            ⋯
TCACTCTGTAGACCAGGCTGGCCT              111007         165387            ⋯
TCACTTTGTAGACCAGGCTGGCC               125712         109742            ⋯
GTAGTCGTGGCTGAGTGGTTAAGG               82988          63903            ⋯
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCCT     101298         143339            ⋯
CGGGAGACCGGGGTTCGATTCCCCGACGGGGAGCCA   66304          48793            ⋯
GACTCTTAGCGGTGGATCACTCGGCTC            96141         158568            ⋯
GTTTCCGTAGTGTAGTGGTTATCA              194133         105234            ⋯
GTTTCCGTAGTGTAGTGGTTATC                82409          44170            ⋯
TCTGAGTTCGAGGCTAGCCTGGTCT             219499         211629            ⋯
GAGAAAGACATATAGGATATG                 162760          32505            ⋯
AAGAAAGATTGCAAGAACTGCTAATT            107034         134024            ⋯
CGACTCTTAGCGGTGGATCACTCGGCT            78676         153100            ⋯
GGGGGTGTAGCTCAGTGGTAGAG               121369          45644            ⋯
GTAGTCGTGGCCGAGTGGTTAAG               144790          35957            ⋯
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    77732          59004            ⋯
GGGGATGTAGCTCAGTGGTAGA                104259          30041            ⋯
ACCAGGATGGCCGAGTGGTTAAGG               38125          25048            ⋯
GACTCTTAGCGGTGGATCACTCGGCT             60744         104883            ⋯
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT    50938          48951            ⋯
TCACTCTGTAGACCAGGCTGGCCTCGA            24736          58523            ⋯
GTCAGGATGGCCGAGCGGTCTAAGGC             55979          48999            ⋯
TACAAAGTGAGTTCCAGGACAG                 31407          24848            ⋯
GAGAAAGGCATATAGGATATG                 108696          19552            ⋯
GGCCGTGATCGTATAGTGGTTAGTACTC           57681         190095            ⋯
⋮                                    ⋮               ⋮                 ⋱
GGGTTCGTTTCCCGGTCAGGGAACCA           51231           81870             ⋯
GTTTCCGTAGTGTAGTGGTTATCACGTTCGCC     18324           25861             ⋯
TCACTCTGTAGACCAGGCTGGCCTCGAA         11228           28918             ⋯
TCTTTGTGTAGCCCTGAAGACCATACC          10176            9398             ⋯
GCATGTGGTTCAATGGTAGAATTCTCGCCTCCCA     457           12639             ⋯
GAATTGCAGGACACATTGATCATCGAC          17390           19198             ⋯
GGCCGTGATCGTATAGTGGTTAGTACTCTG       15105           45936             ⋯
AGAAGACCCTGTTGAGCTTGACTCTAGT         19120           25394             ⋯
TTCCAATGCTGTAAGAACTGAGGCAC           13785           22169             ⋯
TACAGAGTGAGTTCCAGGACAGCCAATG         16891           21500             ⋯
GACGAGGTGGCCGAGTGGTTAAGG             42447           17271             ⋯

In [ ]:
hist(nchar(rownames(mircounts)))

In [69]:
#filter pirna from size 25 to 33

mircounts <- mircounts[nchar(rownames(mircounts)) == 27 | nchar(rownames(mircounts)) == 30,]
dim(mircounts)

[1] 38574039       48

In [ ]:
hist(nchar(rownames(mircounts)))

In [ ]:
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/analysis/seqCount/raw")
write.table(mircounts, file = "raw_count_matrix.txt", sep = "\t",
            row.names = TRUE, col.names = TRUE)

In [70]:
df$samples

                      files
129S1_SvImJ-12.5dpp.1 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.1.raw.count.gz
129S1_SvImJ-12.5dpp.2 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.2.raw.count.gz
129S1_SvImJ-12.5dpp.3 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-12.5dpp.3.raw.count.gz
A_J-12.5dpp.1         /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.1.raw.count.gz
A_J-12.5dpp.2         /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.2.raw.count.gz
A_J-12.5dpp.3         /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-12.5dpp.3.raw.count.gz
AKR_J-12.5dpp.1       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.1.raw.count.gz
AKR_J-12.5dpp.2       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.2.raw.count.gz
AKR_J-12.5dpp.3       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-12.5dpp.3.raw.count.gz
BALB_cJ-12.5dpp.1     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.1.raw.count.gz
BALB_cJ-12.5dpp.2     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.2.raw.count.gz
BALB_cJ-12.5dpp.3     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-12.5dpp.3.raw.count.gz
C3H_HeJ-12.5dpp.1     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.1.raw.count.gz
C3H_HeJ-12.5dpp.2     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.2.raw.count.gz
C3H_HeJ-12.5dpp.3     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-12.5dpp.3.raw.count.gz
C57BL_6NJ-12.5dpp.1   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.1.raw.count.gz
C57BL_6NJ-12.5dpp.2   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.2.raw.count.gz
C57BL_6NJ-12.5dpp.3   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-12.5dpp.3.raw.count.gz
CAST_EiJ-12.5dpp.1    /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.1.raw.count.gz
CAST_EiJ-12.5dpp.2    /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.2.raw.count.gz
CAST_EiJ-12.5dpp.3    /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-12.5dpp.3.raw.count.gz
CBA_J-12.5dpp.1       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.1.raw.count.gz
CBA_J-12.5dpp.2       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.2.raw.count.gz
CBA_J-12.5dpp.3       /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-12.5dpp.3.raw.count.gz
DBA_2J-12.5dpp.1      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.1.raw.count.gz
DBA_2J-12.5dpp.2      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.2.raw.count.gz
DBA_2J-12.5dpp.3      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-12.5dpp.3.raw.count.gz
FVB_NJ-12.5dpp.1      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.1.raw.count.gz
FVB_NJ-12.5dpp.2      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.2.raw.count.gz
FVB_NJ-12.5dpp.3      /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-12.5dpp.3.raw.count.gz
LP_J-12.5dpp.1        /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.1.raw.count.gz
LP_J-12.5dpp.2        /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.2.raw.count.gz
LP_J-12.5dpp.3        /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-12.5dpp.3.raw.count.gz
NOD_ShiLtJ-12.5dpp.1  /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.1.raw.count.gz
NOD_ShiLtJ-12.5dpp.2  /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.2.raw.count.gz
NOD_ShiLtJ-12.5dpp.3  /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-12.5dpp.3.raw.count.gz
NZO_HlLtJ-12.5dpp.1   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.1.raw.count.gz
NZO_HlLtJ-12.5dpp.2   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.2.raw.count.gz
NZO_HlLtJ-12.5dpp.3   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-12.5dpp.3.raw.count.gz
PWK_PhJ-12.5dpp.1     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.1.raw.count.gz
PWK_PhJ-12.5dpp.2     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.2.raw.count.gz
PWK_PhJ-12.5dpp.3     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-12.5dpp.3.raw.count.gz
SPRET_EiJ-12.5dpp.1   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.1.raw.count.gz
SPRET_EiJ-12.5dpp.2   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.2.raw.count.gz
SPRET_EiJ-12.5dpp.3   /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-12.5dpp.3.raw.count.gz
WSB_EiJ-12.5dpp.1     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.1.raw.count.gz
WSB_EiJ-12.5dpp.2     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.2.raw.count.gz
WSB_EiJ-12.5dpp.3     /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-12.5dpp.3.raw.count.gz
                      group               lib.size  norm.factors
129S1_SvImJ-12.5dpp.1 129S1_SvImJ-12.5dpp  35665240 1
129S1_SvImJ-12.5dpp.2 129S1_SvImJ-12.5dpp  56344296 1
129S1_SvImJ-12.5dpp.3 129S1_SvImJ-12.5dpp  35739075 1
A_J-12.5dpp.1         A_J-12.5dpp          37456350 1
A_J-12.5dpp.2         A_J-12.5dpp          60394672 1
A_J-12.5dpp.3         A_J-12.5dpp          38718616 1
AKR_J-12.5dpp.1       AKR_J-12.5dpp        70159879 1
AKR_J-12.5dpp.2       AKR_J-12.5dpp        64444294 1
AKR_J-12.5dpp.3       AKR_J-12.5dpp        63558038 1
BALB_cJ-12.5dpp.1     BALB_cJ-12.5dpp      91437968 1
BALB_cJ-12.5dpp.2     BALB_cJ-12.5dpp      80766214 1
BALB_cJ-12.5dpp.3     BALB_cJ-12.5dpp     122827334 1
C3H_HeJ-12.5dpp.1     C3H_HeJ-12.5dpp      50208529 1
C3H_HeJ-12.5dpp.2     C3H_HeJ-12.5dpp      53972572 1
C3H_HeJ-12.5dpp.3     C3H_HeJ-12.5dpp      40090969 1
C57BL_6NJ-12.5dpp.1   C57BL_6NJ-12.5dpp    83482982 1
C57BL_6NJ-12.5dpp.2   C57BL_6NJ-12.5dpp    79870214 1
C57BL_6NJ-12.5dpp.3   C57BL_6NJ-12.5dpp    76236710 1
CAST_EiJ-12.5dpp.1    CAST_EiJ-12.5dpp     89290372 1
CAST_EiJ-12.5dpp.2    CAST_EiJ-12.5dpp     98924906 1
CAST_EiJ-12.5dpp.3    CAST_EiJ-12.5dpp    131148193 1
CBA_J-12.5dpp.1       CBA_J-12.5dpp        84709448 1
CBA_J-12.5dpp.2       CBA_J-12.5dpp        68134589 1
CBA_J-12.5dpp.3       CBA_J-12.5dpp        89595427 1
DBA_2J-12.5dpp.1      DBA_2J-12.5dpp       36790306 1
DBA_2J-12.5dpp.2      DBA_2J-12.5dpp       40075958 1
DBA_2J-12.5dpp.3      DBA_2J-12.5dpp       63744599 1
FVB_NJ-12.5dpp.1      FVB_NJ-12.5dpp       66678626 1
FVB_NJ-12.5dpp.2      FVB_NJ-12.5dpp       39330182 1
FVB_NJ-12.5dpp.3      FVB_NJ-12.5dpp       64521075 1
LP_J-12.5dpp.1        LP_J-12.5dpp         94062439 1
LP_J-12.5dpp.2        LP_J-12.5dpp         48312453 1
LP_J-12.5dpp.3        LP_J-12.5dpp         74363404 1
NOD_ShiLtJ-12.5dpp.1  NOD_ShiLtJ-12.5dpp   31332424 1
NOD_ShiLtJ-12.5dpp.2  NOD_ShiLtJ-12.5dpp  112895345 1
NOD_ShiLtJ-12.5dpp.3  NOD_ShiLtJ-12.5dpp   64503531 1
NZO_HlLtJ-12.5dpp.1   NZO_HlLtJ-12.5dpp    62630378 1
NZO_HlLtJ-12.5dpp.2   NZO_HlLtJ-12.5dpp    45386012 1
NZO_HlLtJ-12.5dpp.3   NZO_HlLtJ-12.5dpp   103986735 1
PWK_PhJ-12.5dpp.1     PWK_PhJ-12.5dpp      92769856 1
PWK_PhJ-12.5dpp.2     PWK_PhJ-12.5dpp      70657297 1
PWK_PhJ-12.5dpp.3     PWK_PhJ-12.5dpp      61944265 1
SPRET_EiJ-12.5dpp.1   SPRET_EiJ-12.5dpp    92600046 1
SPRET_EiJ-12.5dpp.2   SPRET_EiJ-12.5dpp    81747208 1
SPRET_EiJ-12.5dpp.3   SPRET_EiJ-12.5dpp    81708228 1
WSB_EiJ-12.5dpp.1     WSB_EiJ-12.5dpp     104590907 1
WSB_EiJ-12.5dpp.2     WSB_EiJ-12.5dpp     128428242 1
WSB_EiJ-12.5dpp.3     WSB_EiJ-12.5dpp     112193526 1

In [71]:
#DESeq and PCA and Dandogram 


library("DESeq2")
library("gplots")
library("RColorBrewer")
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

#save results in this folder 
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/analysis/seqCount/raw")

In [72]:
# Make a color scheme for heatmaps
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)

In [73]:
# First we tell DESeq which samples correspond to which tissues.

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"
samplenames

 [1] "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp" "129S1_SvImJ-12.5dpp"
 [4] "A_J-12.5dpp"         "A_J-12.5dpp"         "A_J-12.5dpp"
 [7] "AKR_J-12.5dpp"       "AKR_J-12.5dpp"       "AKR_J-12.5dpp"
[10] "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"     "BALB_cJ-12.5dpp"
[13] "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"     "C3H_HeJ-12.5dpp"
[16] "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"   "C57BL_6NJ-12.5dpp"
[19] "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"    "CAST_EiJ-12.5dpp"
[22] "CBA_J-12.5dpp"       "CBA_J-12.5dpp"       "CBA_J-12.5dpp"
[25] "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"      "DBA_2J-12.5dpp"
[28] "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"      "FVB_NJ-12.5dpp"
[31] "LP_J-12.5dpp"        "LP_J-12.5dpp"        "LP_J-12.5dpp"
[34] "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"  "NOD_ShiLtJ-12.5dpp"
[37] "NZO_HlLtJ-12.5dpp"   "NZO_HlLtJ-12.5dpp"   "NZO_HlLtJ-12.5dpp"
[40] "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"     "PWK_PhJ-12.5dpp"
[43] "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"   "SPRET_EiJ-12.5dpp"
[46] "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"     "WSB_EiJ-12.5dpp"

In [ ]:
# Now we build a DESeq2 Count dataset and normalize it.
library(BiocParallel)
register(MulticoreParam(3))
cds <- DESeqDataSetFromMatrix(countData = mircounts, colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

gene-wise dispersion estimates

In [ ]:
#rlog normalisations
#rlog() may take a long time with 50 or more samples,
#vst() is a much faster transformation
#rl=rlog(cds)

rl = vst(cds)

In [ ]:

pdf("BarGraphBeforeAfter_all.pdf",paper="a4")
par(mfrow=c(2,1))

par(mar=c(10,4,0,2)) # increase y-axis margin.
prenorm=apply(mircounts,2,sum)
barplot(prenorm,col=as.factor(samplenames),las=2,names=samplenames)
postnorm=apply(counts(cds,normalized=TRUE),2,sum)
barplot(postnorm,col=as.factor(samplenames),las=2,names=samplenames)
dev.off()

In [ ]:
prenorm

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) 
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("12.5","16.5","20.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_",timePoint,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw()+  theme(legend.text=element_text(size=5))
  
}

pdf("PCA_After_1vs2_Beginning_all.pdf",paper="a4")
plotPCA.san(rl, intgroup = "sample", ntop = nrow(counts(cds)))
dev.off()

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(strain) 
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (strain in strains) {
print(strain)
rl.sub <- rl[ , rl$sample %in%  grep(paste0("^",strain), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_",strain,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

In [ ]:

##To plot PC2 versus 3
library(genefilter)
library(ggplot2)
library(ggrepel)

plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[2:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() 
  
}

pdf("PCA_After_3.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

In [ ]:
##To plot PC1 versus 3
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() 
  
}

pdf("PCA_After_4.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

In [ ]:
####
# Margins area


pdf("InitialHeatMap_all.pdf",paper="special",width=25000, height=25000,title="Trinity Assemblies",fillOddEven=T)
heatmap.2(cor(mircounts),trace="none",col=hmcol,main="Sample Correlation",cexRow=800,cexCol=800,
    margins=c(9000,9000),na.rm=T,key=T,offsetRow=300,offsetCol=300,keysize=0.7,density.info='histogram')
dev.off()

In [ ]:
##And the Spearman Dendogram
foo_sub_1 = counts(cds, normalized = TRUE)

foo_cor_1 = cor(foo_sub_1, method = "spearman") #builds matrix of Spearman corrn and euclidean distances

foo_cor_dist_1 = dist(foo_cor_1, method = "euclidean")
pdf(file="dendrogram_all.pdf", height=100, width=30)
plot(hclust(foo_cor_dist_1))
dev.off()

In [ ]:

##NEXT IS THE TOP 15% VARIANT miRNA plot on the means. Then the subset more useful miRNA plot
library(pheatmap)

foo_sub_1 <- as.data.frame.matrix(foo_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate

colnames(foo_sub_1)

head(foo_sub_1[ , grepl( "^129S1_SvImJ-12.5dpp" , names( foo_sub_1 ) ) ])
foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(foo_sub_1), ncol = 0))
row.names(foo_sub1_mean) <- row.names(foo_sub_1)
for (sample in samplenames) {
foo_sub1_mean[sample] <- apply(foo_sub_1[ , grepl(paste0( "^",sample) , names( foo_sub_1 ) ) ], 1, mean)
}
head(foo_sub1_mean) 

foo_sub1_mean$sd_perGroup <- apply(foo_sub1_mean,1,sd)
hist(log1p(foo_sub1_mean$sd_perGroup),breaks = 200)


nrow(foo_sub1_mean)
3959
foo_sub1_mean_top15sd <- foo_sub1_mean[foo_sub1_mean$sd_perGroup>3959,1:48]
head(foo_sub1_mean_top15sd)
foo_sub1_mean_top15sd$ID<-rownames(foo_sub1_mean_top15sd)
head(foo_sub1_mean_top15sd)



save_pheatmap_pdf <- function(x, filename, width=15, height=25) {
    stopifnot(!missing(x))
    stopifnot(!missing(filename))
    pdf(filename, width=width, height=height,paper="special")
    grid::grid.newpage()
    grid::grid.draw(x$gtable)
    dev.off()
}

savePheatmap <- pheatmap(log1p(foo_sub1_mean_top15sd[,1:48]),width=30000,height=50000, border_color = NA,show_rownames = T, cluster_cols = T, labels_row = foo_sub1_mean_top15sd$ID,fontsize_row = 5, color = hmcol)
save_pheatmap_pdf(savePheatmap,"InitialPheatMap_all.pdf")

In [ ]:

##for z-score
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)

savePheatmapZScore <- pheatmap(foo_sub1_mean_top15sd[,1:48], border_color = NA,show_rownames = T,  cluster_cols = T, scale = "row",labels_row = foo_sub1_mean_top15sd$ID,fontsize_row = 5, color = myCol)
save_pheatmap_pdf(savePheatmapZScore,"InitialPheatMap_zScore_all.pdf")